### ISSUE TITLE
Free choise of camera position?

### ISSUE THREAD

**Issue by BlackPixxel** [opentrack/opentrack#1000]
Hi!

Does OpenTrack allow for the camera position to be somewhere else than in front of the tracker?
When the tracker is centered with the hotkey will it then do any movement relative to that centered position? Or will it be incorrect because the camera position is wrong?

**Comment by sthalik** [comment]
> Does OpenTrack allow for the camera position to be somewhere else than in front of the tracker?

That's too complicated. Otherwise we'd need to center twice.
