### ISSUE TITLE
Single point tracking for 5DOF VR

### ISSUE THREAD

**Issue by wbfrost** [opentrack/opentrack#1003]
Is there any plan to introduce single-point tracking?
Single-point tracker is very useful for VR helmets made using Vridge software, smartphone and 3D glasses. Single-point tracking makes it easy to get 5DOF-360 degrees of tracking. Vridge can receive head-turn tracking from a smartphone and three-way motion tracking from OpenTrack. But the OpenTrack three-point tracker does not work when the head rotates 360 degrees. In this case, tracking of one point (only in 2 directions) have works well. So we can get 5DOF 360 degrees. We can use it with VR games for the chair, but not only with them.
It seems to me that the introduction of single-point motion tracking is an interesting new feature of modern OpenTrack use.
And if you could implement the ability to track changes in the light spot diameter as a third axis, you could do a full 6DOF - 360 degrees tracking. It is sufficient to use a luminous ball of a sufficiently large size for this purpose.

Translated with DeepL/Translator

**Comment by sthalik** [comment]
No plans at all. Quality is too low to be worthwile.
