### ISSUE TITLE
v3.2.6 crashes on picking bluetooth in the settings

### ISSUE THREAD

**Issue by TheYang** [opentrack/opentrack#1004]
Crashlog:  
https://del.dog/waduqifugo

I'm trying to use a MiBand3 with Gadgetbridge as a Heart Rate Monitor on HavocOS 2.9

uninstall, installing 3.2.5, picking my MiBand and then updating does work though.  
Just since downgrading doesn't work, you lose your track history if you don't backup in some way.

In that case it does record heart rate in the graph, but doesn't show it in the stats while recording

**Comment by sthalik** [comment]
That's not part of the opentrack project. Please report that to the code's author.
