### ISSUE TITLE
Open Track with P3D V4 Issue

### ISSUE THREAD

**Issue by adslucas** [opentrack/opentrack#1005]
Hi,

I have downloaded Open Track and it starts up fine and detects the head tracking kit.  When I open P3D V4 it automatically starts up, however it displays 'Unknown Game' at the top of Open Track and there is no movement within the cockpit of P3D, even though Open Track is working fine.  I have tried all the troubleshooting I could find, but it seems that Open Track isn't communicating with P3D properly.

Am I missing something?

Thanks

**Comment by sthalik** [comment]
Choose "Microsoft FSX" in the output selection.
