### ISSUE TITLE
UDP over network output frequency

### ISSUE THREAD

**Issue by JimmyRaoUF** [opentrack/opentrack#1008]
Hi, I am having a delay problem using UDP to send filtered data into Unity (I wrote a receiver in it without limiting the frame rate (update frequency)), not sure why maybe because of buffer?
I am thinking because the Kinect/Camera runs at 30Hz, I can just limit everything to 30Hz.
So is there a set frequency/default frequency for UDP output in OpenTrack?

Thanks~

**Comment by sthalik** [comment]
> So is there a set frequency/default frequency for UDP output in OpenTrack?

It's 250 frames a second.

**Comment by JimmyRaoUF** [comment]
@sthalik Thank you sthalik! What will happen to the between frame data if the tracker is 30 Hz? Will it just repeat itself?

**Comment by sthalik** [comment]
Filter will be applied each time.
