### ISSUE TITLE
vjoy and opentrack

### ISSUE THREAD

**Issue by Verc0rs** [opentrack/opentrack#1013]
Hello,
After installing vJoy Device Driver, I alway have a message error from opentrack saying vjoy is not installed. The vjoy setup confirm me that it is well installed.
I have trying with opentrack version beta and 2.3.10 under windows 10.
Did I miss something ?
thanks

**Comment by sthalik** [comment]
See if prerelease from <<http://opentrack.misaki.pl>> works.

**Comment by Verc0rs** [comment]
It's working with the prerelease.
thanks
