### ISSUE TITLE
X-Plane 11 plugin fixes

### ISSUE THREAD

**Issue by maxume** [opentrack/opentrack#1014]
Hi !

I've tested opentrack on Linux (Ubuntu 18.04.3 LTS), also with Aruco tracker, and it works well.
I've just fixed the x-plane-plugin for the XPlane >11.40 version (tested only on Linux).
Here you are the patch file for that.
 
Best regards,
Marc

[xplane11_plugins.zip](https://github.com/opentrack/opentrack/files/3998016/xplane11_plugins.zip)

**Comment by sthalik** [comment]
Fixed as of b8e7865a, thanks!
