### ISSUE TITLE
opentrack 2.3.11 beta 3 fails to compile on linux

### ISSUE THREAD

**Issue by paju1986** [opentrack/opentrack#1015]
../compat/qhash.hpp:7:19: error: redefinición de ‘struct std::hash<QString>’
    7 | template<> struct hash<QString>
      |                   ^~~~~~~~~~~~~
In file included from /usr/include/qt/QtCore/qlist.h:47,
                 from /usr/include/qt/QtCore/qobject.h:49,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/QWidget:1,
                 from ../api/plugin-api.hpp:12,
                 from ../filter-ewma2/ftnoir_filter_ewma2.h:3,
                 from ../filter-ewma2/ftnoir_filter_ewma2.cpp:7:
/usr/include/qt/QtCore/qhashfunctions.h:204:1: nota: previous definition of ‘struct std::hash<QString>’
  204 | QT_SPECIALIZE_STD_HASH_TO_CALL_QHASH_BY_CREF(QString)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[24/264] Building CXX object filter-kalman/CMakeFiles/opentrack-filter-kalman.dir/moc_kalman.cpp.o
FAILED: filter-kalman/CMakeFiles/opentrack-filter-kalman.dir/moc_kalman.cpp.o 
/usr/bin/c++  -DBUILD_FILTER_KALMAN -DEIGEN_DEFAULT_DENSE_INDEX_TYPE=int -DEIGEN_DONT_PARALLELIZE=1 -DEIGEN_MAX_CPP_VER=17 -DEIGEN_MPL2_ONLY=1 -DEIGEN_NO_DEBUG=1 -DOPENTRACK_ORG=\"opentrack-2.3\" -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MESSAGELOGCONTEXT -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_WIDGETS_LIB -Ifilter-kalman -I../filter-kalman -I../ -I. -I../filter-kalman/SYSTEM -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtNetwork -isystem /usr/include/eigen3 -fuse-cxa-atexit  -O3 -DNDEBUG -fPIC -fvisibility=hidden   -fPIC -std=c++17 -w -Wno-error -MD -MT filter-kalman/CMakeFiles/opentrack-filter-kalman.dir/moc_kalman.cpp.o -MF filter-kalman/CMakeFiles/opentrack-filter-kalman.dir/moc_kalman.cpp.o.d -o filter-kalman/CMakeFiles/opentrack-filter-kalman.dir/moc_kalman.cpp.o -c filter-kalman/moc_kalman.cpp
In file included from ../options/group.hpp:8,
                 from ../options/bundle.hpp:11,
                 from ../options/options.hpp:10,
                 from filter-kalman/../../filter-kalman/kalman.h:11,
                 from filter-kalman/moc_kalman.cpp:10:
../compat/qhash.hpp:7:19: error: redefinición de ‘struct std::hash<QString>’
    7 | template<> struct hash<QString>
      |                   ^~~~~~~~~~~~~
In file included from /usr/include/qt/QtCore/qlist.h:47,
                 from /usr/include/qt/QtCore/qobject.h:49,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/QWidget:1,
                 from ../api/plugin-api.hpp:12,
                 from filter-kalman/../../filter-kalman/kalman.h:10,
                 from filter-kalman/moc_kalman.cpp:10:
/usr/include/qt/QtCore/qhashfunctions.h:204:1: nota: previous definition of ‘struct std::hash<QString>’
  204 | QT_SPECIALIZE_STD_HASH_TO_CALL_QHASH_BY_CREF(QString)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[25/264] Building CXX object filter-kalman/CMakeFiles/opentrack-filter-kalman.dir/kalman.cpp.o
FAILED: filter-kalman/CMakeFiles/opentrack-filter-kalman.dir/kalman.cpp.o 
/usr/bin/c++  -DBUILD_FILTER_KALMAN -DEIGEN_DEFAULT_DENSE_INDEX_TYPE=int -DEIGEN_DONT_PARALLELIZE=1 -DEIGEN_MAX_CPP_VER=17 -DEIGEN_MPL2_ONLY=1 -DEIGEN_NO_DEBUG=1 -DOPENTRACK_ORG=\"opentrack-2.3\" -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MESSAGELOGCONTEXT -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_WIDGETS_LIB -Ifilter-kalman -I../filter-kalman -I../ -I. -I../filter-kalman/SYSTEM -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtNetwork -isystem /usr/include/eigen3 -fuse-cxa-atexit  -O3 -DNDEBUG -fPIC -fvisibility=hidden   -fPIC -std=c++17 -MD -MT filter-kalman/CMakeFiles/opentrack-filter-kalman.dir/kalman.cpp.o -MF filter-kalman/CMakeFiles/opentrack-filter-kalman.dir/kalman.cpp.o.d -o filter-kalman/CMakeFiles/opentrack-filter-kalman.dir/kalman.cpp.o -c ../filter-kalman/kalman.cpp
In file included from ../options/group.hpp:8,
                 from ../options/bundle.hpp:11,
                 from ../options/options.hpp:10,
                 from ../filter-kalman/kalman.h:11,
                 from ../filter-kalman/kalman.cpp:7:
../compat/qhash.hpp:7:19: error: redefinición de ‘struct std::hash<QString>’
    7 | template<> struct hash<QString>
      |                   ^~~~~~~~~~~~~
In file included from /usr/include/qt/QtCore/qlist.h:47,
                 from /usr/include/qt/QtCore/qobject.h:49,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/QWidget:1,
                 from ../api/plugin-api.hpp:12,
                 from ../filter-kalman/kalman.h:10,
                 from ../filter-kalman/kalman.cpp:7:
/usr/include/qt/QtCore/qhashfunctions.h:204:1: nota: previous definition of ‘struct std::hash<QString>’
  204 | QT_SPECIALIZE_STD_HASH_TO_CALL_QHASH_BY_CREF(QString)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by sthalik** [comment]
Fixed, thanks.
