### ISSUE TITLE
Error opening PS Eye camera on Linux

### ISSUE THREAD

**Issue by paju1986** [opentrack/opentrack#1016]
Error log when traying to start the tracking on ps eye camera on pointracker.

WARN Icon theme "gnome" not found.
DEBUG [/home/alberto/proyectos/opentrack/qxt-mini/qxtglobalshortcut.cpp:58]: qxt-mini: adding event filter
DEBUG [/home/alberto/proyectos/opentrack/qxt-mini/qxtglobalshortcut_x11.cpp:359]: qxt-mini: fixed x11 autorepeat
Icon theme "gnome" not found.
DEBUG [/home/alberto/proyectos/opentrack/logic/runtime-libraries.cpp:25]: protocol dylib load failure
WARN QXcbConnection: XCB error: 3 (BadWindow), sequence: 2403, resource id: 35651807, major code: 40 (TranslateCoords), minor code: 0

**Comment by paju1986** [comment]
Close, i didnt choose a output library that was the error

**Comment by morse-bip-bip** [comment]
Hi ! i'm having the same issue but I don't understand how you fixed it. How do you choose an output library ? thanks
