### ISSUE TITLE
Preview image don`t show up when i hit start and freezes when i hit stop

### ISSUE THREAD

**Issue by Fe301** [opentrack/opentrack#1021]
Just got mine generic webcam that allowed me to easily remove the IR filter. When i hit start the preview wont show`s up, and when i press to stop the tracking, opentrack freezes.

**EDIT** Just found it that if i open multiple instances of the Opentrack, some instance will work, but if i stop the tracking the program will crash when i start again.
![Start](https://user-images.githubusercontent.com/59678397/72
![1-7](https://user-images.githubusercontent.com/59678397/72040367-1a36e380-3287-11ea-817d-b150fa7f184a.png)
039089-87944580-3282-11ea-8acc-64e3a2bdd23e.jpg)
![Config](https://user-images.githubusercontent.com/59678397/72039090-88c57280-3282-11ea-8e5e-eead2b0d228a.jpg)
![Freez](https://user-images.githubusercontent.com/59678397/72039096-89f69f80-3282-11ea-8386-7ce80b0d89fd.jpg)

**Comment by Laserclip** [comment]
I think your camera is bad - incompatible. What is this camera?
