### ISSUE TITLE
Buttons to axis

### ISSUE THREAD

**Issue by Ec0nomist** [opentrack/opentrack#1024]
There are unofficial versions opentrack, which allow you to control the displacement axes keyboard or joystick buttons. You plan to add this functionality officially?

**Comment by sthalik** [comment]
That falls outside of what opentrack is made for -- I could be persuaded otherwise.

**Comment by Ec0nomist** [comment]
This is true for some users of the inertial tracker. Now it looks like this:
https://i.ibb.co/tCgb7Cx/Readme.jpg
I can send you this version

**Comment by sthalik** [comment]
It's not mergeable in its current form. It should be made with a tracker. Trackers can already make their own keybindings. Fusion allows for combining trackers for rotation and translation.

**Comment by Gianpaolo79** [comment]
> There are unofficial versions opentrack, which allow you to control the displacement axes keyboard or joystick buttons. You plan to add this functionality officially?

Where can I find this version?

**Comment by Ec0nomist** [comment]
> 
> 
> > There are unofficial versions opentrack, which allow you to control the displacement axes keyboard or joystick buttons. You plan to add this functionality officially?
> 
> Where can I find this version?

https://drive.google.com/open?id=14huWP1AK_snoS9JITg13R2Qh5092M6ao

**Comment by Gianpaolo79** [comment]
Thank you! 
Do you know why it does not see my Ps3eye camere while the standard version does?

**Comment by Ec0nomist** [comment]
> 
> 
> Thank you!
> Do you know why it does not see my Ps3eye camere while the standard version does?

I use inertial tracker, sorry
