### ISSUE TITLE
Opentrack crashes when starting tracking with Pointtracker

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#1025]
I got a certain setup with Windows 10 and the latest CL-Eye driver, and on this computer the whole program crashes, the latest beta as well as the current stable.

PS3 Eye Tool, Skype, FaceTrackNoIR are all capable of showing the webcam input, but on Opentrack it seems to crash.

What do you need of me when I want to debug this properly? :)

Regards

(It also crashes with Aruco marker instead of Pointtracker, sounds like it's beyond the pointtracker)

**Comment by sthalik** [comment]
A long-standing driver bug.

**Comment by MathijsG** [comment]
Okay, can I somehow help with this?

**Comment by sthalik** [comment]
I'm afraid not, opentrack crashes in driver code.
