### ISSUE TITLE
vjoystick driver problem

### ISSUE THREAD

**Issue by KulaGGin** [opentrack/opentrack#1030]
When I press on the Start button, it shows this error: 
![](https://i.imgur.com/ciOYHSz.png)

And then this error right after it: 
![](https://i.imgur.com/3UekqiW.png)

I pressed on Download the driver button, restarted PC and tried again. Nothing changed. Reinstalled vjoy driver just few minutes ago: https://i.imgur.com/VVARHlW.png

Works in vJoy feeder just fine.

I'm on Windows 10 x64. Is there a fix to this?

**Comment by KulaGGin** [comment]
@sthalik Ok I cloned this repo and I'm on unstable build. How do I compile it?

**Comment by KulaGGin** [comment]
Looks like there are a lot of dependencies. Can you guy compile and post binaries of the last build on the unstable branch, so we can investigate further why vjoy doesn't want to work on my system?

I'll try to compile and try by myself but it can take me quite a while for the first time and I will just might get into other problems with compilation, so I'll have to create another issue for that...

**Comment by sthalik** [comment]
This isn't a fix -- yet.

**Comment by KulaGGin** [comment]
I understand. I thought it would help if it logged version numbers and you would see what version it shows in my case

**Comment by ForceLightning** [comment]
I am also facing this issue with vjoy 2.1.9.1 and opentrack experimental build 20191023.
![jnBiYF](https://user-images.githubusercontent.com/5515479/72950513-99b7cd00-3dc6-11ea-84b7-6b6be139f587.png)

**Comment by Demuth92** [comment]
Same issue, any solution yet ?

**Comment by sthalik** [comment]
See if today's build from <<http://opentrack.misaki.pl>> works.

**Comment by ForceLightning** [comment]
Today's build works. Thanks.
