### ISSUE TITLE
Linux: Wayland: Keyboard shortcuts don't work, alternatives?

### ISSUE THREAD

**Issue by fxkr** [opentrack/opentrack#1035]
Wayland doesn't allow applications to register global shortcuts anymore. On Xorg opentrack's shortcuts still work, but on Wayland shortcuts don't work and you get this error message:

```
WARN [.../opentrack/qxt-mini/qxtglobalshortcut.cpp:93]: QxtGlobalShortcut failed to register: QKeySequence("Print")
```

The generic way around this seems to be adding an "API" to the program (opentrack, in this case) that can be called from the command line, and asking users to configure a shortcut in their window manager (e.g. GNOME) that calls this API.

A github issue referenced by other programs with the same issue -> albertlauncher/albert#309

**Comment by sthalik** [comment]
> The generic way around this seems to be adding an "API" to the program (opentrack, in this case) that can be called from the command line

No way.

> Wayland doesn't allow applications to register global shortcuts anymore.

There was never any support for native Wayland. I assume this was done through XWayland. Try using x11 Qt QPA.

**Comment by fxkr** [comment]
> There was never any support for native Wayland. I assume this was done through XWayland. Try using x11 Qt QPA. I'd consider native support if there's any adoption. Probably not in several years.

fwiw Wayland is the default in Debian(-if-using-GNOME) and Fedora.

Anyway, now that I'm aware of what the issue is I'm fine; I can just run opentrack in Xorg. I created this issue mostly for the benefit of the next user. Maybe this should be in the common issues list in the wiki.

(I don't even disagree with your decision, "no way" is what I thought when I read about the global hotkeys situation in Wayland as well.)

**Comment by sthalik** [comment]
Does it help any if you use `opentrack -platform xcb` with Xwayland?

**Comment by fxkr** [comment]
With `opentrack -platform xcb`, the warning is gone, and the shortcut works while the opentrack window is focused, but not when another application is focused.

(fyi, with Xorg there also was another warning and that goes away too with `-platform xcb`:  `WARN Wayland does not support QWindow::requestActivate()`)

**Comment by XenoPL** [comment]
Bump on this matter, wayland becomes default for both gnome and kde in most of the popular distros in 2022. I'd love to have  working shortcuts,quite handy thing for neuralnet tracker which by default is not centered along z-axis by default.
How difficult/work intensive  would it be to make it work?

**Comment by sthalik** [comment]
I'm definitely not going to target each compositor separately. At this rate it might be easier to read the keyboard's raw USB events and demand that the user sets up permissions through udev.

**Comment by JT8D-17** [comment]
`opentrack -platform xcb` fixes the non-working shortcuts withn Wayland for me in KDE Plasma 5 on Arch Linux. Even when opentrack is not in focus.

There also is "Legacy X11 app support" in the Plasma settings menu ("Applications"), which enables keyboard shortcuts passthrough, but this did not seem to have any effect on opentrack for me.

**Comment by krims0n32** [comment]
Any updates on this? Makes Opentrack in Wayland cumbersome because keybinds do not work. -platform xcb works but X apps in Wayland are becoming a pain in the ass compatibility wise. Passthrough functions (KDE, Hyprland) do not work either so there isn't a workaround really when running Opentrack in native Wayland mode, is there?

**Comment by n-prat** [comment]
Facing the same setup issue: 

[pretty much copy-pasted from "Lug helper"'s Discord:

Putting that here in case that can help anyone: I had managed to get `OpenTrack` (and neuralnet tracker!) working under `Wayland (niri)` in the last couple of days, and I have finally added the last piece that I was missing: a keybind to recenter from in-game [below is for `niri` but I guess you can apply to anything]:

```
        // https://github.com/opentrack/opentrack/issues/1035
        // and indirectly b/c https://github.com/opentrack/opentrack/issues/1895 we can't bind joystick buttons
        // in OpenTrack
        // NOTE: this require the NON-WAYLAND version of OpenTrack to be used
        // Alt+9 { spawn "xdotool" "key" "alt+8"; } // NOTE 2: apparently can not use the same keymap else not detected?
        // According to a bunch of messages on Lug Helper's Discord: xdotool is not the way; and my tries seem to confirm that...
        // Wait for physical Alt+9 to release, then press and release F10 (keycode 68)
        // NOTE 3: not sure why sleep is needed; but it is
        // Alt+9 { spawn-sh "sleep 1 && ydotool key 68:1 68:0"; } // FAIL; or rather works only if opentrack is focused which defeats the purpose
        // WARN: DO NOT use the same keymap on Niri side vs xdotool else that will trigger in a loop!
        Alt+9 { spawn-sh "xdotool search --class 'opentrack' key --window %@ alt+F10"; }
```

[I am leaving the comment as-is; if someone wants to experiment]
I also tried `ydotool` but seems more complicated; and could not get it to work whilst `OpenTrack` was not focused so...

NOTE: running the `OpenTrack - Wayland` on `Arch` (btw) which is running `opentrack --platform xcb`; not sure if relevant

Some finessing may be needed like opening `OpenTrack` fully once after the game is started, then background/tray is fine; not really sure about that one 

﻿

**Comment by sthalik** [comment]
Now there's also #1813.
