### ISSUE TITLE
Support protocol selection for Wine

### ISSUE THREAD

**Issue by jp7677** [opentrack/opentrack#1042]
Hi there,

The FT output plugin supports protocol selection (TrackIr or Freetrack,  https://github.com/opentrack/opentrack/blob/unstable/proto-ft/ftnoir_protocol_ft.cpp#L136) whereas the Wine plugin always enables both (https://github.com/opentrack/opentrack/blob/unstable/proto-wine/opentrack-wrapper-wine-windows.cxx#L45). It would be cool if the Wine plugin would have the same ability to select one or the other or both.

Reasoning behind this is that at least DCS via Wine/Proton seems to support both protocols but prefers freetrack when both are available. Unfortunately DCS then needs a `HeadTracker.dll` that isn't part of the game and not that easy to find. Being able to disable freetrack would remove this dependency.
(The same applies to Elite Dangerous via Wine/Proton, though that has been resolved by now having a `freetrackclient64.dll` in opentrack itself.)

**Comment by sthalik** [comment]
> Reasoning behind this is that at least DCS via Wine/Proton seems to support both protocols but prefers freetrack when both are available

Did you get DCS to work on Wine?

**Comment by jp7677** [comment]
Thanks a lot for your very fast response! Your implementation seems to works, though I'm a bit confused how the three games I have respond:
Elite Dangerous: Only works with Freetrack (I would expect both to work)
DSC: Works with both, though requires the `headtracker.dl`l in bot cases (I would expect that `headtracker.dll` is only needed for freetrack)
ACC: Only works with NPClient (expected)

> Did you get DCS to work on Wine?

Yes, with SteamPlay/Proton in my case. Only thing needed was vcrun2017. In my case I could install it `withprotontricks 223750 vcrun2017`. Furthermore the F10 key crashes the game. I haven't tried wine without Steam.

**Comment by sthalik** [comment]
Did you launch opentrack prior to starting the game? The registry change takes effect only when tracking is started.

**Comment by jp7677** [comment]
Yes, I've also checked the registry settings, they were applied correctly. So dunno what else especially ED needs for NPClient. Would be interesting to know what happens on Windows.

Well, anyway, thanks for your work!
