### ISSUE TITLE
opentrack don't record camera setting

### ISSUE THREAD

**Issue by Verc0rs** [opentrack/opentrack#1048]
Hello,
In the camera setting, "Exposition" panel,  uncheck the box "auto" work but it's not recorded.
I'm using a "Logiteck QuickCam Pro 4000".
Trying with opentrack-2.3.11-beta3 to 2.3.11-20-g631c85c8.
Thanks

**Comment by sthalik** [comment]
What camera setting exactly?

**Comment by Verc0rs** [comment]
Maybe it's a misunderstanding on my part about how opentrack works.
In "input", I select "pointTracker", then "pointTracker setting". In the new windows, I click on "open" of the "camera setting (when available)" option. Is the new window that opens part of the "opentrack" software or does it use a Microsoft Windows 10 function?
In the second case the problem would be with the camera driver of windows 10.

**Comment by sthalik** [comment]
> Is the new window that opens part of the "opentrack" software or does it use a Microsoft Windows 10 function?

Camera settings are provided by the driver. Try switching webcam driver to UVC Video.

**Comment by Verc0rs** [comment]
Thanks for the answer, I was able to solve the problem.
Sorry for the inconvenience.
