### ISSUE TITLE
Windows Phone tracker created

### ISSUE THREAD

**Issue by ZanderAdam** [opentrack/opentrack#105]
Hello,

Inspired by the Android version, I have created a windows phone version for head tracking

https://github.com/ZanderAdam/OpenTrack.WindowsPhone

Hoping to have it added to the Wiki page for for those besides Android devices.

Also wanted to check if its alright using the pink octopus as windows store logo :smile: 

-Aleks

**Comment by sthalik** [comment]
@KyokushinPL don't bother with FreePIE UDP. It doesn't do anything useful, other than compatibility with FreePIE.
