### ISSUE TITLE
Adding FreeTrack/TrackIR/SimConnect to input

### ISSUE THREAD

**Issue by ELXLabUF** [opentrack/opentrack#1050]
Hi, thanks for the amazing software,
I am wondering if there's any possibilities for OpenTrack to read in other program's output besides using UDP?
For example, I now see the FreeTrack/TrackIR/SimConnect options in output, any possibilites to add them into input as well?
What kind of work is needed for that?

**Comment by sthalik** [comment]
What's the use-case for that?

**Comment by zanven42** [comment]
an example use case.

I would like to migrate off windows to linux and having my existing TrackIR hardware work would be more ideal instead of buying something new.

**Comment by memstat** [comment]
It would let you network stream any tracking systems not directly supported by opentrack, which can be useful if the original software becomes unmaintained and stops working (linuxtrack is already unmaintained). Someone could use a vm/pc with an old system to stream the protocol to another system, which is running the game. I don't know if that would be worth the trouble, though.

There may be other exotic scenarios where someone can't connect a tracking system not directly supported by opentrack to the computer running the game. Or simply to translate those systems to any of the outputs provided by opentrack, like mouse emulation.

**Comment by human890209** [comment]
> What's the use-case for that?

I want to convert TrackIR into Joystick for a normal game.

**Comment by sthalik** [comment]
Features for TrackIR hardware won't be supported. For more information, see https://naturalpointofview.blogspot.com/p/trackir-anticompetition.html.
