### ISSUE TITLE
Size of the window

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#1054]
Hi,
the appearance of the GUI in 2.3.11 stable version has a larger size. The working window and the squid are not centred. Has a new the appearance of some intention?

![2 3 11](https://user-images.githubusercontent.com/13926997/75603683-2003b500-5ad1-11ea-8f24-7d6fa484625c.JPG)

**Comment by sthalik** [comment]
It's not intentional. Editing the main window through Qt Designer running on a 4K screen caused that.
