### ISSUE TITLE
2.3.11 Window size difference

### ISSUE THREAD

**Issue by JarcherPL** [opentrack/opentrack#1059]
The newest version looks weird on my PC. Like this:

![shift+c](https://user-images.githubusercontent.com/47431816/75922526-72dbc480-5e63-11ea-9bac-bdd993b9d86c.jpg)
![sizedifference](https://user-images.githubusercontent.com/47431816/75922528-73745b00-5e63-11ea-9ed6-c42b99b481d7.jpg)

**Comment by MathijsG** [comment]
That is by design. Although I understand the confusion.

**Comment by sthalik** [comment]
That's not by design. Can you see whether the build from <<http://opentrack.misaki.pl>> works?

**Comment by MathijsG** [comment]
Well I have the exact same thing then. With a fresh build.

**Comment by MathijsG** [comment]
Still looking different than the earlier versions. It looks like this with the build you linked:
![image](https://user-images.githubusercontent.com/529552/78044091-80a63c00-7374-11ea-9a4e-3ea98114c5a4.png)

**Comment by sthalik** [comment]
Can you confirm this with [opentrack 2022.3.0](https://github.com/opentrack/opentrack/releases/tag/opentrack-2022.3.0)?
