### ISSUE TITLE
2.3.11 Shift+C hotkey problem

### ISSUE THREAD

**Issue by JarcherPL** [opentrack/opentrack#1060]
For older versions I used Shift + C for centering.
Shift + Z = start/stop
Shift + X = pause

In 2.3.11 Shift + C stops "game data", but "raw tracker data" works. To make it work again tracking needs to be restarted.
Rarely it crashes the program.

**Comment by sthalik** [comment]
You're saying that center functionality causes the data to stay at zero?

**Comment by JarcherPL** [comment]
Not exactly, only "Shift + C". When I change centering for some other hotkey it works normally.
It happens only in 2.3.11, so im using 2.3.10

**Comment by marccreal** [comment]
I also experienced this problem. Had it binded to CTRL+\.
If I bind it to a single key, I did not experience the bug. So it seems to be connected to a two-key-binding.

**Comment by sthalik** [comment]
Can you confirm if it works in 2.3.12?

**Comment by marccreal** [comment]
Yes, I can confirm!

**Comment by JarcherPL** [comment]
I confirm it is working good now. Error is not present in 2021.1.2
Sorry for late response.
