### ISSUE TITLE
AI based tracker

### ISSUE THREAD

**Issue by gavazquez** [opentrack/opentrack#1066]
Hi. I made a tracker based on [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace) and it uses artificial intelligence to track the head and orientation. This tracker is much more precise than the old "FaceApi" tracker that FaceTrackNoIR uses and should allow you to track your head without the use of IR emitters (as long as your face is recognized by the AI model :) )

I managed to send the parameters trough UDP to opentrack but I coudn't find any documentation about the range or the order of the parameters.

~~Currently it "works" but the values are probably out of range or I may need to change the order of the values in the array that is sent... Also, I only receive position (X,Y,Z) values but not the tilt angles.~~

~~Can you tell me what's the order of the parameters that must be sent in the array and what's the accepted range in them?~~

Here is how I send my data trough UDP:
https://github.com/gavazquez/GazeTracker/blob/master/GazeTracker/MainWindow.xaml.cs#L256

Also I tried to look at this code of the opentrack but I'm still not sure of what I'm doing wrong as I don't know C++
https://github.com/opentrack/opentrack/blob/unstable/tracker-udp/ftnoir_tracker_udp.cpp

Here is the repo in case you want to have a look and try it, it should be easy to port to C++ aswell:
https://github.com/gavazquez/GazeTracker

---

Nevermind, I made it work :) Feel free to implement it in C++ if you want and close the issue, in my computer it works quite fine with a cheap webcam (logitech C270)

**Comment by bjensie** [comment]
I DL'ed it and as it doesn't seem to need any installation I just unpacked, ran the EXE and
got the message that it was searching for CAMs, then it crashed! Why? Do I need some
additional support files or what?

**Comment by gavazquez** [comment]
There must be a problem with your USB cam. Anyway, try to put an issue in the gazetracker repo and we can follow it there. I'm closing this one
