### ISSUE TITLE
View gets inverted at certain yaw value

### ISSUE THREAD

**Issue by ChrisTheAviator** [opentrack/opentrack#1072]
Hello there!

When I am using opentrack (2.3.11), I experience at a certain yaw value a 180 degree pitch, so when I was at first just looking to one side (it does not matter if left or right) and I pass a certain value, the view gets inverted. As for tracking model I use a selfmade cap model.

Now what I have noticed so far is that when the center (upper) LED and one of the outer LEDs build a vertical line with the center/upper LED, the view gets suddenly inverted, as the program would not be able to recognize the cap model anymore.

I have searched this and other forums about this issue but none of them seem to fit the exact issue as I have it here. As soon as im turning my head back to center a bit so the outer LED is again "outside" of the center/upper LED the octopus is again in normal view and just turning in the direction is it was before.

![opentrack_issue](https://user-images.githubusercontent.com/63561646/79079968-86a40180-7d12-11ea-88aa-2fa67cf5160e.png)

![opentrack_issue2](https://user-images.githubusercontent.com/63561646/79079418-44c58c00-7d0f-11ea-9bfc-dc2f093c8e8d.png)

I have also read through an entire setup forum thread on how to configure the certain options and values which i striclty adhered to. 

I tried also freetrack again, which I have been using before, but since it had issues during startup and getting not updated anymore, stopped using it. There this certain behaviour is not appearing, as I can turn my head further aside until the camera loses one of the LEDs at some point, but without any flipping view.

**Comment by sthalik** [comment]
Use the dynamic pose setting for caps.

**Comment by ChrisTheAviator** [comment]
Yep that worked, thank you a lot! Now I feel really stupid, for overlooking this little line, everytime, I was checking through all the different menus.... *facepalm*
