### ISSUE TITLE
Opentrack Feedback, Bug?, and Suggestions for improvement.

### ISSUE THREAD

**Issue by Atomiser** [opentrack/opentrack#108]
Hi, 

I'm not over familiar with the relationship between Freetrack -> FacetrackNoIR -> Opentrack, but I assume they're pretty closely related?

Anyway, I'm finding both Freetrack and Opentrack pretty much unusable which is very disappointing.

My hardware, is a PS3 Eye Cam (IR filter removed) and a 3 LED clip very close to the default model dimensions. I've found no significant difference between 320x240 and 640x480 in my tests. I've been using IL-2 Sturmovik 1946 (GOG) v 12.12 for visual testing.

My problem with Freetrack is easy to explain. Please see this post I made on the Freetrack forums which explains it in detail:

http://forum.free-track.net/index.php?showtopic=569&page=2#20534

Basically, the output values are 'drifting' even though the input values are constant!

The only reason I mention that here, is because Opentrack might still be using the same (or similar) algorithms? If so, then there is quite clearly a bug in the output calculation algorithm.

My problems with Opentrack are more difficult to explain. 

It seems that, the 'drifting' output values is not the problem, but filtering is. However, the overall effect is similar making it unusable too.

First of all, I should say, that I'm now testing with the 3 LED clip mounted on a tripod, so any yaw movement applied will be by default very smooth - I got sick (literally almost) of:

a) pretending to be a statue
b) the view wandering all over the shop.

In Opentrack 2.2, yawing without any filter is like a car riding over speedbumps. Not very nice at all. However, the output values are calculated very quickly and they don't slowly settle.

In Opentrack 2.3RC6 and with 2.2, using the Accela filter, the problem seems to be the reponse curve. There is about a 3 second delay before Yaw / Pitch and other movements settle to their final calculated values, which is way too much to be usable. So, you 'look', then the view sloooowly settles to its final resting place. This doesn't happen in real life and it doesn't happen with TrackIR 4/5 either from the (many) videos I've seen on YouTube.

The only effect of 'smoothing' in RC6 seems to be to to create a small deadzone before calculations are made, so that solves nothing at all with respect to the above problem.

The response curve of the filter reminds me of the typical RC integration curve, or possibly triangular in shape, i.e the output values are still being calculated after your head has 'already arrived' at its final position, which is totally redundant!

IMHO, the shape needs a quite slow attack response (adjustable), but needs a VERY fast decay curve, otherwise the visual feedback is just 'wrong'. Nobody 'looks' then has the view catching up with them!

What this should achieve would be pretty smooth movement and when your head is at its final position, the view should just STOP moving.

Why you get the 'car over the speedbumps' effect even while yawing on a tripod with no filter is a bit of a mystery too though? Are calculations not made fast enough, or what is causing that?

Further issues. Live updates of the sliders etc. in the point tracker no longer works i.e. you have to click 'Apply' to see updates (differs from 2.2).

Hope this feedback is useful?

**Comment by sthalik** [comment]
There are no valid issues raised here. Closing issue.
