### ISSUE TITLE
Only 30Hz with Webcam and Aruco?

### ISSUE THREAD

**Issue by BenGohan** [opentrack/opentrack#1083]
I am using opentrack with Aruco. It works great but the camera window in the program shows 30Hz no matter what actual frame rate the webcam is set to or is specified in the open track settings. I am trying various cams but still I only see 30Hz. I would be very happy to hear whether higher poll rates from the cam could be achieved, since it would increase the overall tracking smoothness within games. Thanks a lot.

**Comment by sthalik** [comment]
What webcams are you using?

**Comment by BenGohan** [comment]
Thanks for the questions, it made me recheck the cameras: The Creative HD 720 is only 30Hz and I think the same goes for the "DroidCamClient" I use for using mobile phones as webcam under W10. The phones support higher framerates and resolution but I guess the "DroidCamClient" is limiting factor.  I guess I will have to buy a decent (and recent) one. Thanks again.
