### ISSUE TITLE
UI suggestions for 2.3

### ISSUE THREAD

**Issue by denilsonsa** [opentrack/opentrack#109]
Hey, I just tried 2.3 RC6, and I have a couple of suggestions:

* That octopus image rotates following the head tracking. That is great, but also a bit confusing, because it has zero depth. Adding some extrusion (so that it looks like a thin box, instead of a piece of paper) would help. Alternatively, adding some perspective would also help.
* (minor) That octopus image could be rendered with anti-alias, but that is probably not worth implementing.
* (minor, but should be relatively easy) That octopus image should not be rendered with a black border. Removing that black border would look a lot better, and make it look less aliased.
* The webcam video should be mirrored, in my opinion.
* The placeholder picture for the webcam is a TV/monitor picture. Instead, it should be a webcam picture (because it makes more sense).
* Optionally, a second image could be shown. The first one shows the input rotation, the second one shows the output (after applying the curves).

**Comment by sthalik** [comment]
It doesn't look well in the UI unfortunately. It stands out compared to the rest of the interface.

**Comment by MathijsG** [comment]
Can't you just make a greyscale image if the tracker isn't active?

**Comment by FlyingCircus-** [comment]
That could be an easy solution. I'm kind of an amateur with photoshop but if you make good suggestions I can try my best.
Happy new year you all, btw!

**Comment by MathijsG** [comment]
Here you can download the original vector (unlimited resizable) image of the octopus: https://www.vectoropenstock.com/download-vector/598/free-vector-art-octopod if you need some help with making a greyscale version just ask me.

**Comment by sthalik** [comment]
Is it better with the "no video" text or with the frame completely blank?

**Comment by MathijsG** [comment]
The no video text makes it very clear in my opinion.

Groeten,

Mathijs Groothuis
Op 14 mrt. 2015 00:09 schreef "Stanisław Halik" <notifications@github.com>:

**Comment by sthalik** [comment]
Thanks for your involvement.
