### ISSUE TITLE
Opentrack GUI

### ISSUE THREAD

**Issue by K3NART** [opentrack/opentrack#1092]
Whilst setting up opentrack I got as far as setting up the curves when the user interface disappeared from  my screen. Closed the software in task manager and re-opened but no user interface appears although task manager states it is running. Uninstalled and re-installed but still the same problem.
I cannot get the user interface to appear on screen so I am unable to make any changes.
Windows 10 OS. 

Opentrack running but no interface on screen
![Opentrack](https://user-images.githubusercontent.com/66216872/83358577-756b8e80-a36c-11ea-8d0e-93deebec4d0b.jpg)

**Comment by sthalik** [comment]
Do you have tray support enabled?

**Comment by K3NART** [comment]
Do you mean system tray.
If not can you give me more details/instructions please
I'm a 62 yr old male and know very little about windows 10 :(

**Comment by K3NART** [comment]
All sorted thankyou.
It was in the system tray.

**Comment by sthalik** [comment]
Glad it works for you now.
