### ISSUE TITLE
Bug with CENTER shortcut and some crashes!

### ISSUE THREAD

**Issue by Shadoware** [opentrack/opentrack#1105]
Im using OpenTrack 2.3.11 With Windows 10 64bit 1909 and a PS3eye, and this software is great but Im having some bugs:

1 - Sometimes it starts minimized even with this option disabled; The tick box seems inverted.

2 - When I use the center shortcut, either in game or not, the raw tracker data continues but game data stills in zero, so the game view becomes immovable. Im using "restart tracking" as a workaround.

**Comment by Shadoware** [comment]
I found that if I use "restart tracking" many times the OpenTrack crashes!

**Comment by sthalik** [comment]
This is a PS3 Eye driver bug.

**Comment by sthalik** [comment]
> Sometimes it starts minimized even with this option disabled; The tick box seems inverted.

This was fixed in unstable.

> When I use the center shortcut, either in game or not, the raw tracker data continues but game data stills in zero

This was fixed as well. As a workaround, don't use a modifier (e..g shift+C), only the key.

**Comment by Shadoware** [comment]
The unstable version is already compiled? Can I just download it and use it?
Im using the version without installation.

**Comment by sthalik** [comment]
I've released 2.3.12.

**Comment by Shadoware** [comment]
Awesome man!

**Comment by Shadoware** [comment]
The related problem about crash dont seem to happen if I dont use restart tracking shortcut even with ps3 eye but perhaps I try this new open driver support another time.
Many thanks, your software helps a lot all the flight sim world!
