### ISSUE TITLE
Pitch jumping on yaw

### ISSUE THREAD

**Issue by streppa** [opentrack/opentrack#112]
Tracker: PointTracker 1.1
Protocal: freetrack 2.0 Enhanced
Filter: Accela
Model: Cap

First time user on opentrack so I apologize if this isn't actually an issue, but it doesn't seem like correct behavior. I couldn't find a solution to the issue I'm having.

When I yaw to the left or to the right and a reach a certain threshold the position of the "head" changes and causes the pitch to jump. The threshold seems to be when the either of the two lower points align to the top point along the 'x' axis.

The distance the head point moves down is the same as the distance from the top point to wither of the bottom points. 

Here's a video of what I'm experiencing.

http://youtu.be/GDE_FjjfBuk

**Comment by sthalik** [comment]
Thanks. I need the model coordinates too.

Curious, does it work in freetrack?

**Comment by alowva** [comment]
I'm having the same problems, noticed the other user hasn't replied. heres a video with cap coords

raw video capture: http://youtu.be/MG_7ln7kvww   https://www.dropbox.com/s/8rohpicrd0f4d95/3.cap_capture.mp4?dl=0

CAP calibration http://i.imgur.com/89c3Dd4.png

can't test on freetrack as it crashes on me, however it works fine win facetracknoir with the point tracker plugin and freetrack game protocol

**Comment by FlyingCircus-** [comment]
Dynamic pose resolution will be back according to sthalik and it should fix this issue. Be patient folks

**Comment by alowva** [comment]
Thanks for the info. Just trying to help any way I can :)

**Comment by clawhammer64** [comment]
Same issue here. Freetrack working perfect with same model. Is it mean that point track plugin 1.1 need to be fixed?

**Comment by sthalik** [comment]
Closing, notify if dynamic pose resolution doesn't work.

**Comment by clawhammer64** [comment]
It doesnt work. Already checked RC9

**Comment by sthalik** [comment]
Did you enable dynamic pose resolution in PT settings?

**Comment by streppa** [comment]
Just tried it after enabling dynamic pose resolution. Worked a treat! Awesome work!
