### ISSUE TITLE
Is there a way to bind modifier keys (alt/shift/ctrl) to global shortcut?

### ISSUE THREAD

**Issue by cpeng03d** [opentrack/opentrack#1122]
Hi community:
I would assume this is a common problem that selection of hotkeys (center/toggle/...) is limited, like it cannot accept alt key for example.
Why is it so? In Arma 3 I would love to use "hold alt" to enable tracking.
Is there a way around?
Thanks.

**Comment by sthalik** [comment]
No, sorry.
