### ISSUE TITLE
Joystick Input mapping - Yaw

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#1131]
Hi,
strange behavior Joystick Input mapping Yaw axis and Output Freetarack.
Shifting to outer situation, function will change suddenly direction on the contrary.

Makes this only of the function Yaw, tested on three different equipment from the version beta/stable 2.3.11 - 2.3.12. 
Old version 2.3.10 function correctly.

Thank you for the support.

**Comment by sthalik** [comment]
Are you using a filter? What happens if you disable (or enable) Accela?

**Comment by sthalik** [comment]
It should work now with switch to quaternions.
