### ISSUE TITLE
the "center" shortcut will keep centering if held down

### ISSUE THREAD

**Issue by cpeng03d** [opentrack/opentrack#1133]
Hi dear developer:
Right now the "center" shortcut key will keep centering if held down.
Can you make it so that even hold it down it will center ONLY once?
The goal is to map center and held toggle to one key so that every time I hold down that key to start tracking, I will have a centered fresh start.

**Comment by sthalik** [comment]
It used to be that way. People requested it to keep centering while it's held down. I found it more accurate that way myself. It's not worth adding yet another keybinding.
