### ISSUE TITLE
LibUSB install

### ISSUE THREAD

**Issue by Len62** [opentrack/opentrack#1135]
@sthalik  I should know how to install this, but I'm not sure how to. Would like to try this out.

**Comment by sthalik** [comment]
There are 3 different drivers in zadig -- libusbk, libusb, and winusb. See if the others work. Try not to use winusb unless all others fail. It's slow.

**Comment by Len62** [comment]
@sthalik Ok, it works fine with libusbk, however, the red recording light on the cam does not turn off when tracking is stopped. A trivial matter but, I prefer it to go out. Funny though, I re-installed the cl-eye driver and now the red light stays on using that driver. I tried unplugging the camera and rebooting my system but it now stays on once tracking is started.
