### ISSUE TITLE
2.3-rc7: axis remapping appears to be non-functional

### ISSUE THREAD

**Issue by LuCiPh33R** [opentrack/opentrack#114]
Firstly, great software!

Using freePIE-UDP with my Nexus 4 and 2.3-rc7, I have no problems getting it to work in Elite:Dangerous.  While I can invert and un-invert axes on the fly, and the raw game data updates as appropriate (confirmed in-game), the axis re-mapping settings appear to currently be ignored.

**Comment by sthalik** [comment]
Fixed, thanks for the report!
