### ISSUE TITLE
Easy Tracker Vertices

### ISSUE THREAD

**Issue by whiskeygreg** [opentrack/opentrack#1141]
Hello,

Very cool program. The basic Kinect Facetrack is awesome. I was so shocked at how much of a game changer head tracking is in DCS World. After looking into it a bit more, I decided to use Easy Tracker. I can't seem to get it working properly, though. I believe my main issue is being confused about the settings. First, when I click on the settings under Input: Easy Tracker 1.0, they are labeled as PointTracker Settings. Second, the model tab. I have three vertices selected, but I am confused about the measurements. 

Using the ones I've found in these forums before has not yielded good results, despite me using a hat very similar to the picture floating around here (A small ball wrapped in reflective tape on the top middle of the hat, and two more on the bill, one on each side, looks like Splinter Cell haha). Are you able to explain it a bit better? I am able to figure out the mapping, for the most part, but there is also a bit of roll input when I give yaw, and the X axis moves me in and out instead of side to side.

Any help would be appreciated. This is a sweet program and has been fun to tinker with over the last week, but I admit that I may need some help!

Cheers

**Comment by Slion** [comment]
Can you share your settings, vertices, hat, solver? Make sure the vertices are matching your hat tracking points dimensions. Make sure you are far enough from you Kinect. I think it's at least 70cm but maybe 100cm is better.

**Comment by whiskeygreg** [comment]
I'm using P3P, 

![image](https://user-images.githubusercontent.com/70292323/91623427-131d2c80-e961-11ea-8049-2e3980a933ef.png)
![image](https://user-images.githubusercontent.com/70292323/91623465-38aa3600-e961-11ea-91e2-7ef8d4a306ae.png)
![image](https://user-images.githubusercontent.com/70292323/91623561-86bf3980-e961-11ea-9bd3-4be1e8582c85.png)

**Comment by Slion** [comment]
Maybe around 70cm from sensor is best.
I just tested an older dev build on my machine and it was working great with the following settings.
Could be the size of your vertices are causing problems somehow.

![image](https://user-images.githubusercontent.com/6508892/91630986-4cdc4a80-e9d6-11ea-8250-5e27287cd1a8.png)

**Comment by Slion** [comment]
Are you sure your model definition is actually matching the position of your trackers on your hat? Looking at your screenshot it looks like they are closer together than on mine and you have the exact same vertices definition which looks rather suspicious.

You need to measure the distances between the centre of each trackers.

![image](https://user-images.githubusercontent.com/6508892/91631787-97f95c00-e9dc-11ea-8b03-549a38d7add7.png)
![image](https://user-images.githubusercontent.com/6508892/91631910-7c428580-e9dd-11ea-8685-3e9954d6e3eb.png)

**Comment by whiskeygreg** [comment]
I have adjusted my hat to be more in line with yours. My vertices are definitely bigger, but they are now spaced further apart. This did help, however my side to side movement is still interpreted as forward and backward.

**Comment by Slion** [comment]
> my side to side movement is still interpreted as forward and backward.
> a bit of roll input when I give yaw, and the X axis moves me in and out instead of side to side.

I see what you mean now. I do believe I have the same issues. No idea why, possibly a failure in OpenCV solver. The most obvious one is indeed Z acting up if you are off to the left or to the right.

I really ought to try and deploy other solvers:
https://github.com/opentrack/opentrack/issues/1020#issuecomment-573602447

**Comment by whiskeygreg** [comment]
I'll wait with bated breath. Thanks for your help! This is such a cool project, even if my wife says I look silly with the hat on.

Cheers!

**Comment by Slion** [comment]
> No idea why, possibly a failure in OpenCV solver or our inputs.

Though to be honest it is hard to think OpenCV solver would be that bad so I'm pretty sure we are doing something wrong.

**Comment by whiskeygreg** [comment]
If you end up figuring it out, please let me know. I think I'm almost getting the hang of this, but it's all a bit above my level.

Cheers

**Comment by Slion** [comment]
I just tried with 5 markers and the UPNP solver and that's the same issue. Stride left and right screws our Z position.

**Comment by whiskeygreg** [comment]
I really appreciate you taking your time to mess around with it.

**Comment by Slion** [comment]
I found the problem, it has to do with the way we feed the distortion coefficients to OpenCV solver.
Just disabling distortion coefficient usage makes it work great. Ideally we should fix them but disabling is fair enough for now. You should only get noticeable problems when moving to the far edges of the frame which is hardly a use case for us.

**Comment by Slion** [comment]
> I really appreciate you taking your time to mess around with it.

Thanks for taking the time to report that issue in the first place and challenge us to come up with a solution.

**Comment by whiskeygreg** [comment]
> Moreover it could take me some time to contribute this back to the main branch has I've not been keeping with the project for a while. I just patched it on an old locale checkout I had on my machine.

I am always happy to wait for improvements. Is there a workaround that I could do in the meantime? Otherwise I am happy to go back to plain face tracking for now.

Thanks again! You've been so helpful!

**Comment by Slion** [comment]
You should be able to download it from there:
https://slions.net/threads/open-track-for-kinect-v2.67/

**Comment by whiskeygreg** [comment]
Thank you! I don't think I'm relying on anything, I'm just winging all of it. Should I uninstall what I've got and reinstall this one? Or is this a matter of dropping files in folders?

Cheers

**Comment by Slion** [comment]
I'm actually shocked at how well it works now, that thing always bugged me but could never quite put my finger on the issue. I'm off to try it in MWO.

For reference the fix involve disabling the following lines in function `Tracker::CreateCameraIntrinsicsMatrices`:

    //for (unsigned k = 0; k < 8; k++)
    //    iDistCoeffsMatrix(k) = (double)iCameraInfo.dist_c[k];

**Comment by Slion** [comment]
> Should I uninstall what I've got and reinstall this one? Or is this a matter of dropping files in folders?

Just unzip it somewhere and run it from there, it's not an installer, just the binaries. Copying the files over your current installation may or may not work so I don't think you should bother. Just run it from wherever you want until the fix makes it into an official release.

**Comment by whiskeygreg** [comment]
Copy that, thank you!

**Comment by Slion** [comment]
Hope the download works though. I never published files that large on my web site before.

**Comment by whiskeygreg** [comment]
I am getting these errors when trying to run from your binaries.

![image](https://user-images.githubusercontent.com/70292323/91641804-8324c480-e9ec-11ea-8e6b-919504cc600a.png)
![image](https://user-images.githubusercontent.com/70292323/91641809-87e97880-e9ec-11ea-9e90-88c0a18067b7.png)
![image](https://user-images.githubusercontent.com/70292323/91641817-8d46c300-e9ec-11ea-96cf-f5de564cfd47.png)
![image](https://user-images.githubusercontent.com/70292323/91641824-9172e080-e9ec-11ea-8940-cde5f1919b7d.png)

**Comment by whiskeygreg** [comment]
I can run the latest version. Perhaps I'd be able to copy a specific file over to enact the change you made?

**Comment by Slion** [comment]
I've added another zip file with the missing DLLs just unpack them next the the EXE.

**Comment by whiskeygreg** [comment]
Awesome!

New problem (naturally), it opens now but Easy Tracker is not listed! I can't win.

**Comment by Slion** [comment]
I guess some other dependencies are missing somehow.

**Comment by whiskeygreg** [comment]
Well, I've been messing around with it for the last hour or so and cannot seem to finagle a way to make it work, unfortunately.

**Comment by helmick43270** [comment]
Hello, Slion and whiskeygreg,

This is amazing to read a conversation between people trying to figure out the nitty-gritty details to make something work that, for me, has been cerebral reality for around 24 years. This is something I knew could be done, and could visualize the user experience in my imagination back in 1996. I haven't kept up with developments on all fronts very well, so I watched a YouTube video of Kinect face track on a flight simulator. It seems that the effect is still fairly short of what it could be if there were different images presented to each eye, using glasses that alternately flicker. Are frame rates high enough yet to prevent headaches in that configuration? Anyway, I apologize that I can't contribute any technical details to help, but I just wanted to say that it's encouraging to me to see details being hammered out in the formation of the state of the art, and of today's inspired reality.

**Comment by whiskeygreg** [comment]
Helmick, I'm not even almost qualified to answer your question, but thank you for the kind words!

Cheers

**Comment by Slion** [comment]
@whiskeygreg Try installing various [Visual Studio runtimes](https://www.microsoft.com/en-us/download/details.aspx?id=30679) until it works.

**Comment by whiskeygreg** [comment]
No joy :(

**Comment by Slion** [comment]
> No joy :(

You tried all those redistributable and Easy Tracker is still not loading?

**Comment by whiskeygreg** [comment]
Correct. I even went through and uninstalled them all to reinstall them fresh, one at a time.

**Comment by Slion** [comment]
> I apologize for taking up so much of your time!

I'm sorry you could not get it to work on your machine. I'm giving up trying to solve that deployment issue for now. I've pushed that fix so hopefully you will get a new release soon. Maybe @sthalik can help us with that.

**Comment by whiskeygreg** [comment]
You have done more than enough for me! Something to note, while I still had issues with Z and X axis movement, adjusting the curves to a pretty significant level did help some. Still, it was tough to fly and track people in DCS when I started moving more freely. 

I appreciate you pushing the fix. Cheers to @sthalik as well.

**Comment by Slion** [comment]
@helmick43270 
> It seems that the effect is still fairly short of what it could be if there were different images presented to each eye, using glasses that alternately flicker. Are frame rates high enough yet to prevent headaches in that configuration?

Well that's what active 3D TV, monitors and projectors are doing. So yes frame rates are high enough. However this days people usually go for HMD and virtual reality instead.

**Comment by helmick43270** [comment]
Ok, wow, thanks very much! @Slion

**Comment by Slion** [comment]
@whiskeygreg I've published a brand new ZIP on that same web page. Try it out and see if it works this time.

**Comment by whiskeygreg** [comment]
Thanks, @Slion. I'll check that out when I get home from work today! You rock!

**Comment by whiskeygreg** [comment]
@Slion It seems to not be tracking at all, unless I'm missing a step. It's all there, and I can start it, but the octopus won't move. I'll keep troubleshooting.

**Comment by whiskeygreg** [comment]
@Slion Alright, after resetting my curves, it seems to be tracking now. I'll adjust from there and let you know. Thanks again! This is very cool!

Cheers!

**Comment by whiskeygreg** [comment]
I do have one more question @Slion : Can you define the vertices a bit better? On the model page, under the X Y Z where we have the Top, Right, Left rows. How exactly am I to interpret that? I gather that it is a measurement for my hat, but I am not fully understanding.

Thanks!

**Comment by Slion** [comment]
Each marker is matched to a vertex in the model the camera is tracking. To be able to compute the model pose and thus the pose of the head it is attached to, Easy Tracker needs to understand the model geometry.

Therefore you need to tell Easy Tracker the arrangement of your markers. This is done by giving your markers coordinates in the proper coordinates system of arbitrary origin. I recommend you use the top marker as your origin and therefore set it's coordinates to (x:0,y:0,z:0), then work out the coordinates of the two other markers. Units are in millimetres.

Think of it like this:
* X axis is horizontal and parallel to your Kinect, left is negative and right is positive.
* Y axis is vertical and parallel to your Kinect, up is negative down and down is positive.
* Z axis is horizontal and perpendicular to your Kinect, forward is negative and backward is positive.

The hat picture I posted above was supposed to illustrate that and matching the vertices coordinates you posted further up but confusingly I swapped the 10cm and 9cm labels  :)
Hope it helps.
