### ISSUE TITLE
Easy Tracker - Add clip support

### ISSUE THREAD

**Issue by NoX321** [opentrack/opentrack#1145]
Hi,

I'm trying to get a Kinect V2 working with OpenTrack. 
I made a clip which is perfectly detected in easytracker, but i'm unable to get the correct configuration.

Referring to the Easy Tracker wiki page, clip don't seems to be supported (unless someone "feels free to ask").

Signal seems clear enought to be used as input, but neither I wasn't smart enough to find the good setting nor it's simply not designed to work.

P.S. I wasn't able to find any mocap markers anywhere on the web. Any clues to where find some ?

Thanks for your help

**Comment by Slion** [comment]
Show me what your clip looks like. I believe easy tracker three vertices model is expecting them aranged as a triangle.

**Comment by Slion** [comment]
> wasn't able to find any mocap markers anywhere on the web. Any clues to where find some ?

https://optitrack.com/products/motion-capture-markers/
https://www.qualisys.com/hardware/accessories/passive-markers/

Looks like most people are building their owns using small balls, reflective tape and velcro stickers.

**Comment by NoX321** [comment]
Here is what it look like : https://www.thingiverse.com/thing:1431730 
Slightly tweaked in my case, but shown dimensions are correct.

**Comment by Slion** [comment]
> Here is what it look like

Can you show me what it looks like in the easy tracker preview? I guess I should build myself one of those and try it out.
If I recall well it would need a new algorithm for matching the vertices. The current one assumes arangement for hats, we need one that would work for clips.

**Comment by NoX321** [comment]
What do yo need ? Video or just a picture ?

If you're in France (or in Europe), I can send you the printed part if needed.

**Comment by Slion** [comment]
> What do yo need ? Video or just a picture ?

Screenshot would do.

> If you're in France (or in Europe), I can send you the printed part if needed

Thanks, I guess I could first try without it.

**Comment by Slion** [comment]
I've implemented clip support and published a demo version [there](https://slions.net/threads/open-track-for-kinect-v2.67/). Make sure you [define your vertices properly](https://github.com/opentrack/opentrack/issues/1141#issuecomment-685762072).

![image](https://user-images.githubusercontent.com/6508892/91994803-51d32e00-ed37-11ea-9c3a-5a0fef1a6230.png)

**Comment by NoX321** [comment]
Woaw, that was quick. I even hadn't time to send you what the clip look like. Here I go ...
![image](https://user-images.githubusercontent.com/46931966/92022041-f5820580-ed5a-11ea-97ab-e8ddb00bfa75.png)

Just downloaded and tried to launch : everything seems OK. Going to test it tommorrow and to make any feedback needed !

**Comment by NoX321** [comment]
Hi,

Just took some time to play with this build. 
Sadly, the tracker is pretty unusable.

I took a live capture of the behavior : the spots seems to jump to one led to another randomly : 
https://drive.google.com/file/d/17mBYC-UwPOOJFRe3nlcML1ma3JSNn7sq/view?usp=sharing

You'll also find my settings below : 
![image](https://user-images.githubusercontent.com/46931966/92310295-4ab55580-efad-11ea-9524-9a68769e182d.png)
![image](https://user-images.githubusercontent.com/46931966/92310304-5739ae00-efad-11ea-9d29-b2d2cea63689.png)

I took measurments and i think i'm OK with clip dimensions.

**Comment by Slion** [comment]
Could it be that you swapped X and Y axis?

**Comment by Slion** [comment]
I just gave it another try myself using the model below and it looks indeed like the solver does not like those kind of models. Most likely because it is just a two dimensions model. It is not as stable as the hat model. However after trying harder, adjusting models dimensions and adding some tracker deadzone it feels usable. Roll is being funny though but I reckon that could be compensated to satisfactory levels using mappings.   
![image](https://user-images.githubusercontent.com/6508892/92333142-976b6000-f083-11ea-914b-a02641fb5aab.png)
