### ISSUE TITLE
Binary compatibility with official Windows releases

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#1147]
Can developer achieve binary compatibility with official Windows releases?
 * How are releases built?
 * Using which compiler?
 * Which OpenCV version?
 * Which Qt version? 

I was doing an x86 Release build from Visual Studio 2017 hoping I could just take the binary from a tracker and replace it in the installation folder of our 2.3.12 release but that didn't work.

I also could not avoid noticing that Easy Tracker binary from 2.3.12 is 2.36 MB whereas the one from my build is 161 KB.

**Comment by sthalik** [comment]
Visual Studio 2019. Use `msvc.cmake` and `sdk-paths` for Windows-MSVC.

**Comment by Slion** [comment]
> Visual Studio 2019. Use `msvc.cmake` and `sdk-paths` for Windows-MSVC.

I keep forgetting about those. I always use our root CMakeLists.txt.
