### ISSUE TITLE
No connection between phone and opentrack

### ISSUE THREAD

**Issue by WilltheNinja** [opentrack/opentrack#116]
using the android phone tracking guide I tried to set up freetrack with a HTC desire X. they are both on the same wifi network (PC is ethernet) and I have done something similar using an IP webcam. the phone doesnt seem to send any information at all as no raw tracker data or game data comes through

any help?

**Comment by sthalik** [comment]
Other than checking that right tracking source is used -- should be "FreePIE IMU", that port is right, and IP/port are right on the sending side, there's no simple answer. You might want to grab Wireshark and see if there's data coming but that's overkill for a simple issue.
