### ISSUE TITLE
Idea: Advertise over mDNS if 'UDP over network' enabled

### ISSUE THREAD

**Issue by onionhammer** [opentrack/opentrack#1165]
This would enable UDP tracking publishers to automatically find opentrack running on the network without having to manually configure the device to a specific IP & port combination.

This is how other services like Chromecast etc work on your local network.

**Comment by sthalik** [comment]
No. opentrack purposefully does very little network or system activity. There should be silence on the wire unless absolutely necessary.

**Comment by onionhammer** [comment]
@sthalik then you should remove udp protocol support maybe
