### ISSUE TITLE
Not compatible with 64bit games?

### ISSUE THREAD

**Issue by Sk1dmarks** [opentrack/opentrack#117]
I hoped this software would work with the 64 bit version of rFactor 2, but it looks like it does not. Will it be compatible in the future?

**Comment by sthalik** [comment]
There's no freetrack version for 64-bit executables. We could compile it for 64-bit if only some apps used it.

**Comment by lcambia** [comment]
Assetto Corsa 1.3 64 bit example.. opentrack not work

**Comment by sthalik** [comment]
It should work. Use Process Explorer to see if npclient64.dll is used by the game process.

**Comment by lcambia** [comment]
Ti ringrazio, ma non saprei come verificarlo. come posso forzare l'uso di npclient64.dll ?

**Comment by sthalik** [comment]
@lcambia you can't. The game process is expected t load it basing on values from registry.

**Comment by lcambia** [comment]
We could compile it for 64-bit

**Comment by sthalik** [comment]
We don't need to. The game only loads npclient64 and nothing else.

**Comment by lcambia** [comment]
ok thanks...I will ask about the AC forum to add to the game a DLL

**Comment by sthalik** [comment]
They don't have to. If they support freetrack it's already taken care of. What do they support exactly?
