### ISSUE TITLE
Ps3 eye camera init failed

### ISSUE THREAD

**Issue by ProrokC2** [opentrack/opentrack#1176]
Hello
I used zadig and installed libusb onto interface 0 for my ps3eye
When i try to use it, it says PS3 Eye driver error : camera init failed : Access denied (insufficient permissions)
Im running it as administrator, it's installed on disc C.
Any help?

**Comment by m4ti140** [comment]
Same issue, why is this closed?

**Comment by sthalik** [comment]
See if libusb0 works, if libusbK won't. WinUSB is the worst choice by far.
