### ISSUE TITLE
Joystick freezes the camera (edited title)

### ISSUE THREAD

**Issue by ProrokC2** [opentrack/opentrack#1177]
Whenever I try to have a fun time , I plug in my ps3 eye and get my aruco. It works fine but then it stops tracking, sooner or later it will. Then I have to unplug my camera, stop tracking, plug it in and start again. And it just goes and goes like that forever. I have no idea why, and I have no clue on how to fix it. Sometimes after pluggin it back in again and starting tracking it gets a pipe error, or a camera not detected error

And whenever I want to use it, i have to go into zadig and install a proper driver, every single time i boot up.

**Comment by ProrokC2** [comment]
I FINALLY MADE IT WORK.
The camera used to freeze constantly, it was completely unusable.
I uninstalled the CL driver, I stopped craping around with zadig and driver changes. 
I uninstalled all the previous software, including CLeye and downloaded a different driver called iPi. And now it works out of the box! No problems what so ever. Leaving it here, maybe someone will need it someday, just like I did.

**Comment by ProrokC2** [comment]
Ok I figured some stuff out. Cleaned the drivers, the camera works and zandig driver is permament. The camera freezes when I plug my joystick in. And I have no idea why. I left it tracking aruco for 10 minutes and works flawlessly, i plug my joystick in and it freezes in an instant. My joystick is t.flight hotas x, windows 10 home 64 bit, camera installed via libusbK, joystick has standard drivers.

**Comment by ProrokC2** [comment]
switching the usb port fixed the issue

**Comment by sthalik** [comment]
How's your user experience? Is the CPU usage lower? Do you get any freezes or crashes?

**Comment by ProrokC2** [comment]
No freezes, no crashes. User experience is stellar, works as intended
