### ISSUE TITLE
PS3Eye Camera glitchy, artifacts and lines with framerate over 82hz

### ISSUE THREAD

**Issue by Diddo17** [opentrack/opentrack#1179]
Hey,
I updated opentrack and I saw that it added support for the "PS3Eye open driver".
Well as I have been using the CodeLaboratory Driver I wanted to switch to libusb anyway so I though yeah, why not.
So I downloaded Zadig and changed the driver to libusb and it worked without any error.

But now the camerafeed is like this if the framerate in the PointTracker settings is over 82hz:
![opentrack issue](https://user-images.githubusercontent.com/61393374/95264584-e0076c00-082f-11eb-9fb6-af25a3bc619c.PNG)

It was fine with the codelaboratory driver, no glitches whatsoever, but since the change to libusb it looks like that.
I also tried Zadig again to switch to libusbk but that looks exactly the same.

I have a three-point homemade tracking hat, if thats relevant in any way.
Can someone help me?

Thanks :)

**Comment by Diddo17** [comment]
Nevermind. 
My old .ini was totally fucked with fucked everything with it.
If you have this issue too, change to a different .ini and you should be fine.

I'll close this myself.

**Comment by Diddo17** [comment]
Sorry for this nightmare of a thread, never really used the github issues function before.

**Comment by sthalik** [comment]
That's normal. Above 75 Hz the image is partially corrupted

**Comment by Diddo17** [comment]
Ah, alright then I'm relieved to hear that I didnt screw something up.

**Comment by sthalik** [comment]
Can you compare the CL-Eye and open driver full system CPU usage? Thanks.

**Comment by Diddo17** [comment]
This is the CPU usage over 60 seconds for the CL-Driver:
![CPU_UsageCLDriver](https://user-images.githubusercontent.com/61393374/96788739-407fd700-13f4-11eb-97dd-3971079d9f5a.png)

This is the CPU usage over 60 seconds for the Open Driver:
![CPU_UsageOpenDriver](https://user-images.githubusercontent.com/61393374/96788741-41186d80-13f4-11eb-9468-f8ed4c41ccf4.png)

In both tests I moved my head more than usual but everything worked just fine.
I didnt have the artifacts on the CL-Driver if I went over 83hz though, something that I still have with the Open Driver (although it doesnt bother me because the tracking works fine).

I would've attached the .blg files but they arent supported and I dont know how to reach you privately.

**Comment by sthalik** [comment]
Thank you, this is important feedback. It's good that you can reproduce the reduced CPU usage.

> I didnt have the artifacts on the CL-Driver if I went over 83hz though, something that I still have with the Open Driver

The CL-Eye driver doesn't allow for the 83 Hz mode. 75 Hz has mild artifacts as normal, while 60 Hz has none.
