### ISSUE TITLE
Windows Phone

### ISSUE THREAD

**Issue by ZanderAdam** [opentrack/opentrack#119]
Finally got down to submitting Windows Phone Open Track to windows store:

http://www.windowsphone.com/en-us/store/app/opentrack-head-tracking/1c604f32-6d68-40ef-aa44-3163e30f547f

Please add to the tracking sources when you have a change.

Why it took so long? Was stuck in 34th century (WAY too much Elite Dangerous)

-Aleks

**Comment by KyokushinPL** [comment]
Good work man!

**Comment by sthalik** [comment]
Linked to from project README, thanks!
