### ISSUE TITLE
Double input for head tracking.

### ISSUE THREAD

**Issue by SweetBabyJezuz** [opentrack/opentrack#1225]
Is it possible to have the yawn, pitch and roll inputs from my phone AND the x, y and z inputs from my webcam?

**Comment by GO63-samara** [comment]
Try this:

Input -> Fusion -> ...
Rotations -> UDP over network
Positions -> PointTracker 1.1
Click Save

Good luck!

![image](https://user-images.githubusercontent.com/63638386/105989085-0b9db300-60ba-11eb-9c1c-521e777d893f.png)

**Comment by SweetBabyJezuz** [comment]
Thanks!
