### ISSUE TITLE
Opentrack should recenter everytime when hitting Start (or implement new button for it)

### ISSUE THREAD

**Issue by nabblschnur** [opentrack/opentrack#123]
This is just a small suggestion which resulted out of my own stupidity.

I honestly didn't know that you can "recenter" the Inputvalues again by just binding to it in the "Keys"-Tab. I tried to use opentrack a lot but came back to FacetrackNOIR instantly because I didn't know that you can recenter your view in Opentrack (what resulted in me trying to use the options in the mapping tab and manually adjust everything).

It would be a great help for absolute newbies like me to reset the inputvalues at the start of opentrack and/or hitting Start in the UI.
Maybe implement a simple Button so that you can recenter via the UI without needing to hit a keybinding.

**Comment by sthalik** [comment]
It's back in.
