### ISSUE TITLE
Wrong calculation of 3 Point Cap

### ISSUE THREAD

**Issue by clawhammer64** [opentrack/opentrack#126]
Every time i download new version and check how my 3 LED Cap model works.
But always i see same issue. The red line on the picture - thats the stuck for Opentrack, after which begins wrong calculation.

If the original Freetrack software continue YAW without any problems, the opentrack instead make some ROLL or etc. after crossing red line.

And the second question - why from version to version  i see different output results if the PointTracker Plugin remains the same?
![unnamed](https://cloud.githubusercontent.com/assets/10739782/5935985/4b277120-a6f1-11e4-9937-e51d8590e600.png)

**Comment by alowva** [comment]
duplicate issue, posted here a few weeks ago: https://github.com/opentrack/opentrack/issues/112

(not sure if theres a way I can report this as duplicate, so sorry if i have posted redundantly)

**Comment by clawhammer64** [comment]
Thanks! I'm just remind about it cause new versions have not any changes.

**Comment by sthalik** [comment]
Results are different since code now takes camera field of view into account. Due to this translating doesn't affect rotation.

**Comment by sthalik** [comment]
Closing, notify if dynamic pose resolution doesn't work.

**Comment by clawhammer64** [comment]
It doesnt work, already tested on RC9. Results are same.

**Comment by alowva** [comment]
works fine for me after the update

**Comment by clawhammer64** [comment]
Write me model dimensions please, i'll recheck.
