### ISSUE TITLE
Smartphone head tracking Suddenly stopped

### ISSUE THREAD

**Issue by Ronan6793** [opentrack/opentrack#129]
So I have been using this with my Samsung galaxy S5 for head tracking in Arma 2 and War thunder for some time now and all was well until today when I loaded it up and pressed start it doesn't work and I have tried everything from re install to trying my forwarding still nothing. All of my setting are the same as they were yesterday but today it just doesn't work, this is the screen I'm getting now http://gyazo.com/879bc6245f4f29e1dd2af58cec558593

**Comment by Stefan-deHoDev** [comment]
Show us a screenshot of your mapping settings (options).
I had a similar problem yesterday, where in "output remap" yaw, pitch, roll, x, y, z were all mapped to x.

**Comment by Ronan6793** [comment]
Here http://gyazo.com/63fbf2c60958224aa9e2ffe70869ab32

**Comment by sthalik** [comment]
On the screenshot the start button isn't pressed. Could it be the cause?

**Comment by Ronan6793** [comment]
"until today when I loaded it up and pressed start it doesn't work" I know it isn't pressed in the screenshot because I had already tryed

**Comment by Ronan6793** [comment]
Case closed dont know how it fixed but Its working now
