### ISSUE TITLE
when looking down, the octopus rises upwards

### ISSUE THREAD

**Issue by weczi** [opentrack/opentrack#1293]
when looking down (**pitch down**), the octopus rises upwards (Y-axis going up)
if i want to see "my feet" i am going up

version 2.3.13
older version 2.3.12 same profil is ok

**Comment by weczi** [comment]
version 2.3.13

**Comment by Slion** [comment]
You can invert the axis in your profile I think.

**Comment by weczi** [comment]
> You can invert the axis in your profile I think.

and what it could give me?
i think you dont understand

**Comment by GO63-samara** [comment]
In OT-2.3.12, the Octopus showed the Y-axis inverted.
In OT-2.3.13, the Octopus shows the Y-axis correctly, in accordance with the position of the pilot's head in the flight simulator. The Octopus display does not affect the Opentrack output coordinates.
@Slion correctly said that if the work of the Pitch or Y axes does not match the head, then you need to invert them in Options-Output.
It's not even a problem.

**Comment by weczi** [comment]
> In OT-2.3.12, the Octopus showed the Y-axis inverted.
> In OT-2.3.13, the Octopus shows the Y-axis correctly, in accordance with the position of the pilot's head in the flight simulator. The Octopus display does not affect the Opentrack output coordinates.
> @Slion correctly said that if the work of the Pitch or Y axes does not match the head, then you need to invert them in Options-Output.
> It's not even a problem.

sorry but it not a solution, problem is different:
when I invert Y-axis then: looking down (**pitch down**), the octopus rises looking down and crouch (**Y axis**) so its wrong Y-axis should move at all!

**Comment by GO63-samara** [comment]
Nothing is clear from your description.
Show screenshots of your **Options-Output** and **Options-Relative translation** settings.
It is also helpful to show a video of your problem.

> Y-axis shouldn't move at all

> pitch down should move Y-axis

One task contradicts another, right?

**Comment by weczi** [comment]
YES!!!
When I want pitch down i ALSO move up (Y-axis) - together.

Options-Output  are blank - standard like in 2.3.12 and older versions.
What is a difference when I invert Y? why Y even move? I dont want go up or down (Y-axis) I want to pitch down (look my feet).
If I invert Y-axis I will go down - not up - so still the problem with moving Y-axis.
From begining I am wrote about problem with PITCH. Pitching should move Y-axis at all!
Its a different move - different axis. Y should move at all when I want pitch - what you dont understand?

Pitch its a different move
[https://photos.app.goo.gl/TN8nL38keLQS3P4h6](url)

**Comment by GO63-samara** [comment]
We still don't know which tracker you have.
We still haven't seen your Opentrack settings.
It is impossible to help.

**Comment by weczi** [comment]
i have my own tracker IRTrack 
[www.irtrack.pl](url)
thats my profile
[DCS vPRO2.txt](https://github.com/opentrack/opentrack/files/6780106/DCS.vPRO2.txt)

**Comment by GO63-samara** [comment]
Now I can see that you have PointTracker. Perhaps his settings give the effect of Pitch on the Y-axis.
Check the input to see if the **Y**-axis changes as you rotate to **Pitch** in the `Raw tracker data` panel.
If changes, you need to calibrate the offset in `PointTracker Settings`-`Model position`-`Start calibration`.

The rest of the Opentrack settings are normal. Maybe you still need to try disabling `Relative translation`-`Disabled`.

**Comment by weczi** [comment]
Thank you - and that is a big help! thank you
I will check the calibration - hope this help. 
I will let you know.

**Comment by weczi** [comment]
Thank you very much! it was about calibration.
Now everything working fine! Thx!
