### ISSUE TITLE
Is this possible to remove the 180 degress limit?

### ISSUE THREAD

**Issue by alonzam99** [opentrack/opentrack#1313]
Hello, I use opentrack for steering wheel using aruco marker that I connected to the wheel but the roll tracking is limited to 180 degrees for every direction(left and right), but I want it to be 900 degrees for every direction, so I want to ask if it is possible to remove this 180 degrees limit ?
thanks.

**Comment by sthalik** [comment]
It's limited because values don't exist outside these boundaries. You should scale the output ingame.
