### ISSUE TITLE
2021.1.0 Not creating TrackIR device?

### ISSUE THREAD

**Issue by dssrtfx** [opentrack/opentrack#1325]
I was having problems with the new PS3 Eye open driver, so decided to try the neuralnet tracker.
It's tracking my face with a C920 perfectly, so I tried it out with DCS World and BMS 4.35, merely copying the config I had working with the previous Opentrack and PS3 Eye open driver versions and changing the Input to "neuralnet tracker," again, just changing the camera.
Neither game detected a "TrackIR" device so headtracking will not work. How to fix or diagnose root cause?

Using the "freetrack 2.0 Enhanced" Output, tried all 3 of the Interface options in there ("Use Track IR, disable freetrack," etc.) but none were telling my games that I had a head tracking device like Opentrack did on previous versions.

Installing 2.3.13 in a separate place and using 2.3.13 works great.

**Comment by sthalik** [comment]
Verify registry key exists as string, `Path`, with location of `HKEY_CURRENT_USER\SOFTWARE\NaturalPoint\NATURALPOINT\NPClient Location`.

**Comment by els2** [comment]
Opentrack 2021.1.0 is not being recognized by the games, I tried it on Falcon BMS, and Strike Fighters 2. The previous version 2.3.13 is working and being recognized by the games correctly, so I went back to using it. I use AITRACK (UDP over network) and it worked correctly in the previous version.

**Comment by sthalik** [comment]
@els2 see whether the above registry paths exists, and whether the fake `trackir.exe` gets started as with previous version. The freetrack protocol settings dialog should look like this:

![image](https://user-images.githubusercontent.com/1896811/132064347-2a33822b-051b-4f60-bc1e-373ed4060dbb.png)

**Comment by els2** [comment]
> @els2 see whether the above registry paths exists, and whether the fake `trackir.exe` gets started as with previous version. The freetrack protocol settings dialog should look like this:
> 
> ![image](https://user-images.githubusercontent.com/1896811/132064347-2a33822b-051b-4f60-bc1e-373ed4060dbb.png)

I checked the registry path and it is found, and the freetrack protocol settings dialog is present. In the previous version, Opentrack 2.3.13, everything worked fine:
![reg](https://user-images.githubusercontent.com/90060312/132067201-79a3e900-fcfd-4b02-a5f4-0e98d50a1f33.jpg)

![open](https://user-images.githubusercontent.com/90060312/132067291-55b3d8b1-a2d1-446f-af6d-b4393d304dca.jpg)

**Comment by sthalik** [comment]
See if the build `opentrack-2021.1.1-test.7z` from <<http://opentrack.misaki.pl>> fixes the freetrack problem.

**Comment by GO63-samara** [comment]
@els2
So you have an empty path in the `NPClient Location` registry key. All you need to do is click **[Locate DLL]** and select **NPclient.dll** from the `modules` folder.
This will fix the `NPClient Location` registry key.

**Comment by sthalik** [comment]
@GO63-samara  That won't fix it. The path will get reset to an incorrect value again.

**Comment by els2** [comment]
> See if the build `opentrack-2021.1.1-test.7z` from <http://opentrack.misaki.pl> fixes the freetrack problem.

OK, thank you very much, with this fix you indicated now Opentrack 2021.1.0 is working correctly. Thank you all for your help.

**Comment by dssrtfx** [comment]
As for me, 2021.1.2 seems to work! Thank you for doing whatever it was!
