### ISSUE TITLE
antivirus hit

### ISSUE THREAD

**Issue by DarkWolf303** [opentrack/opentrack#1326]
got this after running a new install (2021.1.1) from the .exe installer. 

"The file C:\Program Files (x86)\opentrack\modules\opentrack-tracker-kinect-face.dll is infected with Gen:Variant.Razy.902046 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean."

**Comment by FreemanGER2021** [comment]
Me too

**Comment by freecodecampster** [comment]
Trojan:Script/Wacatac.B!ml detected! Could the authors submit to Microsoft  so it passes Windows Defender to get the all clear.

**Comment by makattack** [comment]
Looks like Windows Defender is no longer alarming on the standalone archive and its contents.

**Comment by tenevas666** [comment]
> Trojan:Script/Wacatac.B!ml détecté! Les auteurs pourraient-ils soumettre à Microsoft afin qu’il passe Windows Defender pour obtenir le tout clair.

Oui cela serait le minimum.....car j'ai sans cesse un positif trojan a chaque fois

**Comment by sthalik** [comment]
See #1371
