### ISSUE TITLE
Build from opentrack source with steamvr

### ISSUE THREAD

**Issue by Nobatgeldi** [opentrack/opentrack#1334]
Hi there,

I did everything right to build with MS Visual Studio 2019 and build completed successfully. But when I run opentrack there is no Steam VR inpurt selection. 
![image](https://user-images.githubusercontent.com/11710280/132954660-2e341e69-c1cd-4b67-bb34-cb59dbc7fa63.png)

When I download latest portable opentrack, I can select Steam VR input. 

![image](https://user-images.githubusercontent.com/11710280/132954697-495d5451-6f3b-4697-bdc9-e3d53c1b00e3.png)

I build for x64 system.

**Comment by Nobatgeldi** [comment]
When I check Cmake GUI log, there is no steamvr modul.

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
User settings file 'sdk-paths-COVISART@MSVC-windows.cmake' doesn't exist
module api
module compat
module csv
module dinput
module filter-accela
module filter-ewma
module filter-hamilton
module user-interface
module logic
module migration
module executable
module options
module pose-widget
module proto-fgfs
module proto-freetrack
module proto-win32-mouse
module proto-simconnect
module proto-udp
module spline
module tracker-freepie-udp
module tracker-fusion
module tracker-hatire
module tracker-joystick
module tracker-s2bot
module tracker-test
module tracker-udp
module video
Compile flags:
   CXX: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
   CXX_RELEASE: /MD /O2 /Ob2 /DNDEBUG
Link flags:
   LINK_SHARED: /machine:x64
   LINK_SHARED_RELEASE: /INCREMENTAL:NO
Static archive flags:
   STATIC: /machine:x64
   STATIC_RELEASE: 

Configuring done
Generating done

**Comment by GO63-samara** [comment]
You need to use `opentrack-depends`.

The complete build of Opentrack from source is described here (in Russian):
https://sites.google.com/site/diyheadtracking/устройства-обзора-для-авиасимуляторов/opentrack/opentrack-сборка-из-исходников
According to the replies of the thread https://github.com/opentrack/opentrack/issues/1228

Good luck!

**Comment by sthalik** [comment]
Run `git submodule update --init` on the opentrack-depends repo.

**Comment by Nobatgeldi** [comment]
After clonnig repo, I cloned  [opentrack-depends](https://github.com/opentrack/opentrack-depends) repo using `--recurse-submodules`. Problem solved
