### ISSUE TITLE
Mapping Scaling Factor

### ISSUE THREAD

**Issue by DaMichel** [opentrack/opentrack#134]
Hi Stanisław,

i have a little feature wish: i'd like to have numeric input fields to scale the output. 

At the moment i use the curves to boost the response way up. E.g. for yaw i have 180 deg for 60 deg raw data. I think i boosted it even further in the games settings. A numeric input field would be very convenient for such scaling. I think the "Output remap" group in the Options tab would be a good place to put it. 

These new input fields should determine the maximal output magnitude and the curves should be changed to be determining the respective percentage.

**Comment by sthalik** [comment]
We don't intend on accumulating features unless they're really necessary. This one can be done without.
