### ISSUE TITLE
ONNXRuntime Performance issues

### ISSUE THREAD

**Issue by DaWelter** [opentrack/opentrack#1359]
I guess I figured it out. The x64 version is about 2x faster than x86 ...

```
(ml) PS ... > .\Debug\speed_test.exe .\test.onnx
time 0 = 23
time 1 = 22
time 2 = 22
time 3 = 21
time 4 = 22
time 5 = 23
time 6 = 22
time 7 = 22
time 8 = 21
time 9 = 21
(ml) PS ... > x64\Debug\speed_test.exe .\test.onnx
time 0 = 11
time 1 = 10
time 2 = 10
time 3 = 10
time 4 = 10
time 5 = 11
time 6 = 10
time 7 = 10
time 8 = 10
time 9 = 10
```

So err @sthalik ... I will be building my OpenTrack as x64 version. ;-)

I did look around though. Found a case where someone could find compiler settings to make his little unrelated test program have roughly equal performance in both versions. https://stackoverflow.com/questions/10317932/x64-performance-compared-to-x86 So there is hope. Albeit neural nets are a bit more complex than that.

Might be easier to port OpenTrack to x64 than mess with ONNX. Could also have even more performance benefits. X64 programs do after all have access to more registers and instructions (?).

What do you think @sthalik ?

**Comment by DaWelter** [comment]
Yes. That's what I had in mind. But first I want to try new ideas for the neural net training. Eventually I will get back to the tracker plugin for sure.

**Comment by tapir** [comment]
Is there a technical reason behind not ahving 64 bit builds for opentrack by default?

**Comment by sthalik** [comment]
> Is there a technical reason behind not having 64 bit builds for opentrack by default?

There's no need to have them in the first place.

**Comment by tapir** [comment]
Well having neuralnet work twice as fast is a good enough reason no? Also who doesnt have a 64 bit cpu nowadays?

**Comment by sthalik** [comment]
Twice as fast? It's worth giving a try.

**Comment by tapir** [comment]
apoligies if I misunderstood, I tought that's what @DaWelter was talking about

**Comment by sthalik** [comment]
Only now I reread the conversation from 2021 in this issue. Your initial comment makes sense now, and my first reply doesn't.

The next release will be a 64-bit binary, and there has to be a test build before that.

**Comment by DaWelter** [comment]
Oh nice. IIRC you once said you had trouble with the 64 bit versions.

**Comment by sthalik** [comment]
@DaWelter, please see if performance has improved in 2022.3.1. Maybe simply enabling AVX for this one tracker will be enough.

**Comment by DaWelter** [comment]
@sthalik The thing is, I upgraded my cpu ... with what I have now, your version 2022.3.**2** is as fast as my win32 build. And I haven't changed the onnx libs. Both versions have an inference time of ca 10 ms now.

I'll check my 64 bit linux build ...

**Comment by DaWelter** [comment]
Now that you do x64 builds, I guess we can close this one.

**Comment by sthalik** [comment]
Releases have AVX enabled but remain 32-bit.
