### ISSUE TITLE
Arma 3 native support

### ISSUE THREAD

**Issue by MexxPex** [opentrack/opentrack#1388]
Would it be possible to add native Arma 3 support?

As of now it takes a really long time to set up all the different things needed in order for it all to work and it is largely completely undocumented how you actually make it work with Arma 3.

**Comment by sthalik** [comment]
What things? Enable TrackIR in Arma's controller settings and use freetrack output in opentrack. That's all you need to do.

**Comment by MexxPex** [comment]
I tried that and it doesn't work. Kinect and I have glasses
