### ISSUE TITLE
Aruco on Linux

### ISSUE THREAD

**Issue by franciscot** [opentrack/opentrack#1397]
Hi,
Is it Aruco tracker compatible with Linux?
I can't build with aruco on manjaro or ubuntu,

Thanks,

**Comment by sthalik** [comment]
Yes. Use the fork. https://github.com/opentrack/aruco

**Comment by franciscot** [comment]
Is there any complete building guide? I'm not a Linux developer. I'm a normal user and It is very difficult to try to understand how to build everything. 
I'm fighting to build against WINE, x-plane plugin or aruco. For example.

**Comment by franciscot** [comment]
I found this bash script and It' was very useful for arch/manjaro: https://github.com/JT8D-17/opentrack/blob/main/z_Build.sh
It was easy to adapt to debian/ubuntu.

I'm thinking to do a guide for normal Linux users. 

Sorry but I don't agree with the FAQ about "It's assumed Linux users are software developers", there are a lot not-dev users too. ;-)

**Comment by sthalik** [comment]
> Sorry but I don't agree with the FAQ about "It's assumed Linux users are software developers", there are a lot not-dev users too. ;-)

This is why it's an assumption. It's not falsifiable.

**Comment by franciscot** [comment]
Well, Linux users have a new script to install opentrack and plugins. It's not for beginners user yet.
Sorry, the instructions are in Spanish:
https://gitlab.com/jugandoenlinux/opentrack-script
