### ISSUE TITLE
Is it possible to adjust gain and exposure with ps3 eye open drive?

### ISSUE THREAD

**Issue by AlphabetGhost** [opentrack/opentrack#1400]

**Comment by AlphabetGhost** [comment]
Hi i'm using ps3eye camera with point track, for open drive i can't adjust gain and exposure value so ir tracker does not work at all as cl driver, is there a way to set the gain and exposure value?

**Comment by GO63-samara** [comment]
Yes it is possible.

`PointTracker Settings` - `Camera` - `Camera settings (when available)` - `Open`:

![image](https://user-images.githubusercontent.com/63638386/147860105-fc0a84ae-ec97-4429-a7a8-7978e9309151.png)

Don't forget to click `OK`

**Comment by AlphabetGhost** [comment]
> Yes it is possible.
> 
> `PointTracker Settings` - `Camera` - `Camera settings (when available)` - `Open`:
> 
> ![image](https://user-images.githubusercontent.com/63638386/147860105-fc0a84ae-ec97-4429-a7a8-7978e9309151.png)
> 
> Don't forget to click `OK`

grateful!
