### ISSUE TITLE
Error occurred while loading tracker UDP over network  Can't bind socket -- The bound address is already in use

### ISSUE THREAD

**Issue by Dung3on-Master** [opentrack/opentrack#1401]
I am using Open Track 2.3 with AiTrack 0.6.5 but when I try to run it it gives me this error:
Error occurred while loading tracker UDP over network

Can't bind socket -- The bound address is already in use

I have been using this setup for about a year and never encountered this issue until now.

**Comment by sthalik** [comment]
Run `netstat -ano` from the command line. There's something else listening on that port.

**Comment by josephkdaniels** [comment]
I had this issue. It turned out that I had several instances of opentrack running simultaneously, but hidden in the tray. Closing all instances except one fixed this for me.
