### ISSUE TITLE
The Options Window  is cut off and doesnt let you press OK on options

### ISSUE THREAD

**Issue by 00greena** [opentrack/opentrack#1407]
![image](https://user-images.githubusercontent.com/73893164/148683218-cb52e9e9-1a91-4b59-b56c-14c0c7867bb5.png)

when I open, the window at the bottom is cut off and there is no way to resize it. so i cant press OK on the options. How do you resize the window?

**Comment by sthalik** [comment]
What's your desktop resolution?

**Comment by sthalik** [comment]
Please see whether this build works for you.

https://www.dropbox.com/s/z9aneqmpfg1hsle/opentrack-master-20220111_01.7z.7z

**Comment by sthalik** [comment]
Closing. It's ready for the next release.
