### ISSUE TITLE
PT: Head center indicator

### ISSUE THREAD

**Issue by DaMichel** [opentrack/opentrack#142]
Hello Stanisław,

would you have a look at what i did there https://github.com/DaMichel/opentrack/commit/8f0a2ed30437adf5e384dc593e0fdc75764a0c27

The calculation of the head center indicator screen position seemed very odd to me because it does not respect the rotation of the model. Provided of course it is supposed to do what i think it is supposed to do. 

So i changed it, using code from a few lines below where the final pose is computed. Seems to make more sense.

**Comment by sthalik** [comment]
That makes sense, yes. Good catch! I've merged as db7acfc67eda47bf859f8b6bd13bdc0dc2827fd5 to save up on rebasing.
