### ISSUE TITLE
Stuttering problem after Windows 11 inovation

### ISSUE THREAD

**Issue by DonArosa1** [opentrack/opentrack#1420]
Hi,
Please help me. I have problem with stuttering and no smooth movement in MSFS 2020 after Windows 11 inovation. I use opentrack with aitrack for my MSFS 2020. In W10 all run without problem but in new Windows 11 this softwares run very bad. Its unusable for me. FPS in simulation is the same as in W10 about 45-50. But when I start tracking, movement view has very big lag (stuttering movement). I think that is something with cpu but I do not know what is it. I try switch off game mode and increase priority for this aplications but nothing help me. I try reinstall but without succes. I have lastes opentrack and AItrack install package. Thanks.

**Comment by sthalik** [comment]
Try setting CPU affinity for MSFS to all except 1 core.

**Comment by DonArosa1** [comment]
I try it but without succes. I buy facetracknoir that compare this two software. Facetracknoir run me very similar. Not smothly. I have some problem with cpu usage in windows, simconnect or drivers.

**Comment by sthalik** [comment]
What's the priority for MSFS while it's running? Is the original affinity value getting restored on its own? Are opentrack or aitrack processes marked as suspended in the Task Manager while the game is running?

**Comment by DonArosa1** [comment]
- Problem is solved: -

I feel embarrassed, but it looks like in the end it was enough to just remove and reinstall Visual C ++ Redistributable x64, which is on the AItrack page. It's running smoothly now. Thank you Stanislaw for your willingness to help.

**Comment by sthalik** [comment]
aitrack's author should build it with `-MT`. All libraries shipped with opentrack are built like that, and that's why opentrack doesn't need any VC++ redistributables.
