### ISSUE TITLE
Profile directory name contains (old) version number

### ISSUE THREAD

**Issue by dglava** [opentrack/opentrack#1425]
I have noticed that Opentrack is saving its profiles in `My Documents\opentrack-2.3`. Is this a deliberate choice or an oversight? It's just a minor cosmetic issue, but I reckon it would be nicer if there's either no version number or it did get updated (if people require different profiles for different versions?).

**Comment by sthalik** [comment]
It's only going to be changed when there's a justification for breaking compatibility. Right now, changes to .ini values are handled via the migration system.

**Comment by dglava** [comment]
Thanks for the clarification. I guess this can be closed.
