### ISSUE TITLE
Ubuntu: No values for input, output and filter

### ISSUE THREAD

**Issue by harsh0596** [opentrack/opentrack#1428]
I'm trying to run opentrack with aruco to play American Truck Simulator (on proton)

I followed the Debian/Ubuntu guide located at https://github.com/opentrack/opentrack/wiki/Building-on-Linux
one thing to note is that the output was placed in `opentrack/` folder instead of `install/` folder as written in the wiki.

after building and then running `./opentrack`, i got an error loading shared libraries:
```./opentrack: error while loading shared libraries: opentrack-user-interface.so: cannot open shared object file: No such file or directory```

I added whichever libraries were needed to `$LD_LIBRARY_PATH` using [this](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s)

After that, opentrack launches but there are no options for `input`, `output` or `filter`
also, when I hit start, i get `DEBUG [/home/<username>/Documents/opentrack/logic/runtime-libraries.cpp:25]: protocol dylib load failure` from a quick search this is because nothing was selected as the output

![image](https://user-images.githubusercontent.com/11883323/155040835-157ce375-84d0-488b-afe8-b8d78cabfb88.png)

appreciate any help!

**Comment by airimder** [comment]
my guy really asked the exact question i have and then closed the issue before anyone could document help for the next person

**Comment by sthalik** [comment]
Run `make install` and execute from the install prefix.

**Comment by airimder** [comment]
Thank you so much! Not sure how I missed that step, but that's exactly what I was somehow missing! Thank you.
