### ISSUE TITLE
[Q] bluetooth hid

### ISSUE THREAD

**Issue by birdspider** [opentrack/opentrack#143]
Hi, 

first: FreePie UDP and Android Phone via WLan works nicely :) 

but I just out of curioisity: has anyone looked into using Bluetooth (HID?) for rotational control ? 
I guess there may be power-saving benefits and maybe lower latency ?

Also: is there a forum/irc channel somewhere to ask without "issuing" it ?

**Comment by sthalik** [comment]
There seem to be no existing solutions for sending rotation data over bluetooth. We're not supporting new devices that way.

You can't notice the latency. At 60 FPS, it takes 16 ms to render a frame. Ping over wifi is far less than that.

There's no IRC or forum, but it's fine to discuss matters on the bug tracker like that.

**Comment by birdspider** [comment]
thx
