### ISSUE TITLE
missing MJPEG mode for Aruco

### ISSUE THREAD

**Issue by eexx1** [opentrack/opentrack#1431]
As the title says, the Logitech Streamcam is not doing 60hz on aruco instead it's capped at 30hz, I tried pointracker with the MJPEG compression option ticked and it works (Goes from 60hz dropping down to 50hz then up to 60hz in not even a second) is there any way to fix this issue?
I tried using Logi Capture as input but in-game I experience terrible stutters and latency.
Pointracker performance: 
![image](https://user-images.githubusercontent.com/100306872/155374547-d1c204c0-6cd8-46d3-b7c1-30bbfda9dd48.png)
Aruco settings and performance:
![image](https://user-images.githubusercontent.com/100306872/155374876-56ec5139-8553-4c6e-92b4-ad46314584bf.png)

**Comment by sthalik** [comment]
So here's a build so that you can start using it already:  https://www.dropbox.com/s/dl07kz4sga91iz2/opentrack-master-20220226_01.7z

**Comment by eexx1** [comment]
tried it for about 5 minutes and seems to be working perfectly fine, thank you!
should I close the issue?

**Comment by sthalik** [comment]
Good to know, thanks for the confirmation. You can close it.
