### ISSUE TITLE
X, Y and Z axis with smarphone headtracking

### ISSUE THREAD

**Issue by endermast3r** [opentrack/opentrack#146]
Hi guys,
so I finally got the opentrack working with my cellphone, and I find it awesome (much momre smoother than the freetrack I've been using). But my problem is that the X, Y and Z axis are not working. And I don't know if I'm missing something, or they just don't have to work with the smartphone headtracking.
I'm planing to use it for play Star Citizen, where I don't think is going to be a problem if these axis don't work, but they are very important with the flight simulators I'm currently playing.

**Comment by sthalik** [comment]
There's so little precision with translation it's better not to advertise the support.
