### ISSUE TITLE
MJPEG Compression support for neuralnet

### ISSUE THREAD

**Issue by TheSpartaPT** [opentrack/opentrack#1467]
My webcam (Logitech StreamCam) is stuck at 30hz when using neuralnet because I have no way to enable mjpeg compression, if I change to pointtracker and enable mjpeg compression, it seems like it does 60hz but I can't know for sure because it doesn't show it like neuralnet does.

I tried to build opentrack myself and see what I could do, I was able to build it but neuralnet was missing from the list... I even tried to follow a more in-depth Russian guide I found in a different issue, but it would throw errors when building.

**Comment by TheSpartaPT** [comment]
@sthalik yeah I did that and neuralnet started showing up in the list

one thing though, I had to go and manually download from https://github.com/microsoft/onnxruntime, the one that comes with opentrack-depends wasn't working, I think it's because I am building opentrack in x64 and the one on opentrack-depends has onnxruntime in x86, or it's was just the version, I downloaded 1.10.0 and opentrack-depends comes with 1.8.1.

either way, at least now I can change stuff and see if it has any effect 😅

**Comment by TheSpartaPT** [comment]
@sthalik i did it 😂
![image](https://user-images.githubusercontent.com/8343238/167917420-b3307e84-b951-4485-9714-77ed06e63160.png)

basically just a copy paste of how you're doing it already for aruco, I can PR it if you would like me to

**Comment by sthalik** [comment]
> basically just a copy paste of how you're doing it already for aruco, I can PR it if you would like me to

Please do so.

**Comment by TheSpartaPT** [comment]
done: #1468

**Comment by Cyrmano** [comment]
Hello! I have problems with opening Opentrack in windows 7. "0x000007b" could someone give me a hand? I would appreciate it!
