### ISSUE TITLE
2022.2.0 CPU usage

### ISSUE THREAD

**Issue by gufo2k20** [opentrack/opentrack#1498]
Latest version 2022.2.0 get a constant +12% CPU usage when tracking (PointTracker, freeTrack, PS3eyeopendriver).
Still using 2022.1.1 with no issue on CPU load (1~3%)

Great work anyway!!

**Comment by sthalik** [comment]
The CPU usage is probably related to your camera gain or thresholding setting. Try decreasing gain, or decreasing auto threshold/increasing manual threshold.

**Comment by gufo2k20** [comment]
i'll try asap and report feedback
thanks!

**Comment by gufo2k20** [comment]
Great!
Reducing threshold solved the issue.
Thanks!!
