### ISSUE TITLE
60 fps ps3 eye cam linux

### ISSUE THREAD

**Issue by runningman84** [opentrack/opentrack#15]
My framerate does not go above 30 even if I select 60 fps in the point tracker settings. Are 60 fps not supported on Linux?

**Comment by edwin-v** [comment]
Interesting to find this closed. I still can't get my ps3eye to do 60 fps at 640x480. It's not the driver or anything because linuxtrack does 60 fps just fine. Is there anything specific that causes this? Maybe it's specific to the point tracker?

**Comment by sthalik** [comment]
In OpenCV in cmake/OpenCVFindLibsVideo.cmake, find this block:

    # --- V4L ---
    ocv_clear_vars(HAVE_LIBV4L HAVE_CAMV4L HAVE_CAMV4L2 HAVE_VIDEOIO)
    if(WITH_V4L)
      if(WITH_LIBV4L)
        CHECK_MODULE(libv4l1 HAVE_LIBV4L1)
        CHECK_MODULE(libv4l2 HAVE_LIBV4L2)
        if(HAVE_LIBV4L1 AND HAVE_LIBV4L2)

change it to:

    # --- V4L ---
    ocv_clear_vars(HAVE_LIBV4L HAVE_CAMV4L HAVE_CAMV4L2 HAVE_VIDEOIO)
    if(WITH_V4L)
      if(WITH_LIBV4L)
        CHECK_MODULE(libv4l1 HAVE_LIBV4L1)
        CHECK_MODULE(libv4l2 HAVE_LIBV4L2)
        if(HAVE_LIBV4L2)

Modern distros don't ship libv4l1 anymore and failing this check makes it use inferior opencv capture module.

**Comment by edwin-v** [comment]
It doesn't appear to work.

I recompiled everything and I get the following error:

VIDEOIO ERROR: V4L: setting property #5 is not supported

Which is the FPS iirc.

**Comment by sthalik** [comment]
Then you don't have libv4l2-dev installed.

**Comment by edwin-v** [comment]
Good call, it works now.

A wiki page with a few of those build details would probably help a lot.

**Comment by sthalik** [comment]
Linux users are assumed to be familiar with programming. The software runs on Linux to use Linux development tools, like Valgrind, also to increase code quality by using portable calls. We don't support Linux as an OS for end-users with fully-blown instructions or binaries.

**Comment by sthalik** [comment]
Filed an issue at http://code.opencv.org/issues/4471
