### ISSUE TITLE
Opentrack + ai track moves randomly

### ISSUE THREAD

**Issue by alepron2002** [opentrack/opentrack#1509]
Hi I would like to setup opentrack with ai track for DCS (with droidcam) but this happens:

https://user-images.githubusercontent.com/11015009/178562489-f0360cdf-1552-4ca2-a14b-3f1ece0e7bdf.mp4
I've already tried to restart my pc + a bunch of other things... My head is still

**Comment by 0yu5e0h0r** [comment]
Hello,

I think that it's probably Droidcam that is sending fluactuating values. And you can know it by looking at the left part of opentrack, which display values received by Opentrack : the values send by Droidcam.
In your video, we see mainly right part but look at the left yaw value : yaw value send by Droidcam, and probably other values too, are fluctutating a lot so Mr Octopuss is dancing in the same way.
Try other disposition, other light, maybe to be nearest or farthest from your camera. But your problem probably comes from Droidcam and not Opentrack.

**Comment by alepron2002** [comment]
Hi and thanks for your reply. This issue happens also when using my webcam, so I guess it's not droidcam... There must be other causes to that

**Comment by EconomicSacks** [comment]
It's an ai track problem, however neuralnet is now built into the opentrack build 2022.3.0, select it from the input options. Works like aitrack but better

**Comment by alepron2002** [comment]
Thank you it worked! My issue is now solved
