### ISSUE TITLE
HT doesn't work in 2.3RC9

### ISSUE THREAD

**Issue by njc** [opentrack/opentrack#152]
I'm using an unmodified PS3 Eye and face tracking doesn't work for me.
The device is configured correctly (640x480@60fps) and I get a feed from the camera in Opentrack, but no movement is registered. Using FreeTrack protocol and Accela filter.

**Comment by sthalik** [comment]
Are you wearing glasses or looking at a weird angle? Can you submit an image?

**Comment by njc** [comment]
Neither. The webcam image shows up alright, but no tracking is performed
(no raw or game coordinates). Are there any log files I should include or
is it just a screenshot?

man. 4. maj 2015 11.00 skrev Stanisław Halik <notifications@github.com>:

**Comment by njc** [comment]
Here's a screenshot. Webcam seems to be connected ok (works with
facetracknoir).


man. 4. maj 2015 kl. 18.57 skrev Nils Jakob Clemmensen <
nj.clemmensen@gmail.com>:

**Comment by sthalik** [comment]
There's no screenshot. Attaching via main doesn't work, please use github feature.

**Comment by njc** [comment]
Oh, here you go.
![screenshot](https://cloud.githubusercontent.com/assets/786703/7765823/dfdcad38-0062-11e5-8dd4-715e4b999b24.jpg)

**Comment by sthalik** [comment]
@njc cropping your face off the image and putting it through a virtual webcam source, it detects your face just fine. I'd like to give it further debugging but for now I can't reproduce the problem.

**Comment by sthalik** [comment]
Response timeout
