### ISSUE TITLE
Can't select Kinect IR camera for Easy Tracker or Point Tracker

### ISSUE THREAD

**Issue by PrimeEpilogue** [opentrack/opentrack#1527]
Hey,
I have my Kinect for Xbox One (I believe this is the V2, Model 1520?) hooked up to my pc and have installed SDK browser v2.0, all seems to be working in the browser.
When I try to set up OpenTrack to use Easytracker or PointTracker I have no option to select a camera. I'm not sure what I am doing wrong. I have tried the latest release as well as 2022.2.0 and 2.3.13( saw that someone else stated this release was working for them)
![image](https://user-images.githubusercontent.com/5026383/184524685-b22d88aa-3692-4258-ad68-21f2231f1298.png)

Any ideas on how I can fix or troubleshoot this?
Kinect face 0.1 works but id really like to try out IR tracking

**Comment by Slion** [comment]
That's weird, see that [post](https://github.com/opentrack/opentrack/issues/1461#issuecomment-1109950744).

**Comment by sthalik** [comment]
That's one old opentrack version.

**Comment by sthalik** [comment]
@Slion, the Kinect patch has already been included in 2022.2.0, so it should work just fine in 2022.3.0.

**Comment by Slion** [comment]
Just tried 2022.3.0 and it works just fine it seems:
![image](https://user-images.githubusercontent.com/6508892/185338428-8e9111c3-ea20-4cde-a992-0b1b9372afef.png)
![image](https://user-images.githubusercontent.com/6508892/185338647-168d78f8-e8ee-4f52-b4b2-01c999472545.png)

**Comment by sthalik** [comment]
Try running opentrack from within a console window to get some debug info. To do this easily, drag the executable or the shortcut onto an empty `cmd.exe` window and press Return.

**Comment by PrimeEpilogue** [comment]
looks like it is now working, only change I made was I opened it via the CMD window and now it appears to be finding my Kinect even when launching normally.
