### ISSUE TITLE
Aruco Tracker settings button crashes program

### ISSUE THREAD

**Issue by Inhaltsangabe** [opentrack/opentrack#1542]
![Screenshot 2022-10-01 201716](https://user-images.githubusercontent.com/79662341/193422834-122026d6-5d24-43c4-8508-8ea1c7780dec.png)
If I click this button Opentrack freezes and just doesnt answer and i get the no response message from Windows

**Comment by uuozz** [comment]
happening to me too , cant click on any button but start

**Comment by sthalik** [comment]
Make me a minidump (with opentrack 2022.3.1):

![image](https://user-images.githubusercontent.com/1896811/196055460-d1949600-b963-4b55-9414-9ce59319c6bc.png)

**Comment by uuozz** [comment]
> 

done it , do i attach it there?
sorry kinda new to githud

**Comment by sthalik** [comment]
Pack it inside a .zip, then Ctrl+V into this text box.

**Comment by uuozz** [comment]
file is to big :c

**Comment by sthalik** [comment]
Did you use Ultra compression?

Or just put it on Dropbox or OneDrive.

**Comment by uuozz** [comment]
> Did you use Ultra compression?
> 
> Or just put it on Dropbox or OneDrive.

https://we.tl/t-65mWNCeXF6

**Comment by sthalik** [comment]
I updated libusb. See if this helps: https://www.dropbox.com/s/prlbigdqss1hrtp/opentrack-test-20221017_01.7z.

**Comment by uuozz** [comment]
btw it happen whit every tracking oprions , nothing seems to change

**Comment by sthalik** [comment]
Do you have a PS3 Eye camera connected to the PC?

**Comment by sthalik** [comment]
As a workaround, delete `opentrack-video-ps3eye.dll` from the `modules` directory.

**Comment by uuozz** [comment]
wow it worked , hope that works to everyone !!
thanks a lot for the patience
