### ISSUE TITLE
Send data

### ISSUE THREAD

**Issue by MarceloTomaz** [opentrack/opentrack#155]
Hello , is there a way to send Yaw , Pitch and Roll by UDP or API ?

**Comment by sthalik** [comment]
Yes, through the "UDP receiver" protocol.

**Comment by MarceloTomaz** [comment]
Thank you, there is documentation ?

**Comment by sthalik** [comment]
No, but it's really simple - 6 double precision values, X Y Z, yaw, pitch roll.

**Comment by MarceloTomaz** [comment]
THANK YOU !
