### ISSUE TITLE
Mouse Emulation still not functioning properly.

### ISSUE THREAD

**Issue by Sokonomi** [opentrack/opentrack#157]
I noticed in the new release candidate changelog that work has been done to mouse emulation.

Ive tested it in GTA5 and Farm Simulator 15, both still do not pick up the mouse emulation from opentrack while in game (oddly enough it does move the cursor when you open the in-game menu.

So the issue raised in my previous ticket unfortunately remains; https://github.com/opentrack/opentrack/issues/153

**Comment by Nakonzaid** [comment]
I'll try in Skyrim, GTA-IV and others today. Then i'll post the results.
Anyway, thank you very much for the hard work!

**Comment by Sokonomi** [comment]
I'll attempt a few more games as well.

I also have a small suggestion, dont know if its possible; A settable deadband zone where mouse emulation "lets go" so to speak. This has two major benefits; One is that the mouse wont keep creeping around after you toggle it off, the other would be the ability to navigate menus when you face the screen directly. The last part would help games that have of dialog menus where the mouse steals focus when you move it. (Fallout and skyrim)

**Comment by sthalik** [comment]
It doesn't work currently. I have some idea on how to try to fix it again. Stay tuned.

**Comment by Nakonzaid** [comment]
Thanks, sthalik!

**Comment by sthalik** [comment]
The feature's been implemented for next RC. Please provide feedback.

**Comment by MathijsG** [comment]
I tried in GTA V (with the previous build, RC10) and it is working perfectly. You need to change the settings in GTA V, the mouse settings should be on Windows instead of Raw. When on raw, the input is directly going to the game, instead of via Windows.

**Comment by HornetMaX** [comment]
Works in-game for me too ! Nice job !

**Comment by sthalik** [comment]
Thanks!

**Comment by Nakonzaid** [comment]
Thank you very much!
