### ISSUE TITLE
Opentrack receives data but for some reason it is not reaching the simulator.

### ISSUE THREAD

**Issue by passer3d** [opentrack/opentrack#1574]
I am using for Flight Simulator 2020 and DCS, AITrack + Opentrack. For some reason they have stopped working. Opentrack receives the data from AITrack and there is movement. But the camera in both simulators does not work. I have updated both programs and reinstalled. I have checked the ports and settings. I launch all apps with admin permissions. And yes, I have also restarted the PC. I'm out of ideas. Can you give me a hand? Thank you!

**Comment by sthalik** [comment]
What's the output method that you've selected?

**Comment by passer3d** [comment]
Freetrack 2.0
I've tried with mouse emulation, just for testing and it's not working.

![image](https://user-images.githubusercontent.com/118166785/201635661-07869187-2c93-47ee-ad98-048efdd5a97e.png)

**Comment by sthalik** [comment]
In "select interface", select "use both".

**Comment by passer3d** [comment]
> 
thanks Stanislaw,
I tried that before but still not working. 
Mouse emulation should be working as basic test but don't. It's like something is blocking Opentrack. (antivirus is disabled).

**Comment by passer3d** [comment]
I don't know why, but it's working.  Maybe a Javascript update I just done?
Thanks for your quick response!

**Comment by sthalik** [comment]
Changing 'use freetrack' to 'use both' only affects games that are started after opentrack has started tracking (not just starting opentrack).

Good to know it's fixed.
