### ISSUE TITLE
[Feature Request] Support command line options for autostart

### ISSUE THREAD

**Issue by fawick** [opentrack/opentrack#159]
As a user, I'd like to be able to autorun and start opentrack at system startup. It would be great to have a command line parameter `--autostart <profile>` available, which, if used, would automatically load a profile and call `MainWindow::startTracker`.

If I can find the time, I'll come up with a pull request based on [QCommandLineParser](http://doc.qt.io/qt-5/qcommandlineparser.html).

**Comment by sthalik** [comment]
Thanks! Merged.
