### ISSUE TITLE
Opentrack crashes when opening options or input options when using PointTracker

### ISSUE THREAD

**Issue by ericesminombre** [opentrack/opentrack#1595]
OpenTrack freezes when opening options or input options when using PointTracker. I've tried 2022.3.2, 2022.3.1 and 2.3.13, and the same thing happens, although in 2.3.13 it doesen't crash when entering options. I used opentrack 2022.3.2 the day before writting this and it worked normally. This issue also occurs when using other inputs such as EasyTracker or WiiPointTracker. Output or filter don't seam to matter.

**Comment by ericesminombre** [comment]
I found the problem. It seems that the usb drivers ¡(for samsung phones) I installed to use my phone as a webcam are incomaptible with opentrack.

**Comment by sthalik** [comment]
Is this still occuring if you delete `opentrack-video-ps3eye.dll` as a workaround?
