### ISSUE TITLE
Can't get past 15 Fps no matter what settings I use

### ISSUE THREAD

**Issue by ZipperKopf** [opentrack/opentrack#1617]
![opentrack](https://user-images.githubusercontent.com/126263261/221201680-451c4efe-5d3c-4216-89ec-b54558454002.png)

As I said no matter what settings I use I can't get the webcam to go over 15 fps and I don't understand why. The tracking is smooth but if I'm only getting 15fps I'm using half of the webcams 30 fps output. I have tried putting the res at 640x480 and that does nothing. 

Any explanation/ tips would be greatly appreciated.

**Comment by GO63-samara** [comment]
https://github.com/opentrack/opentrack/issues/1576

**Comment by ZipperKopf** [comment]
> 

This thread doesn't give me a solution at all.

**Comment by sthalik** [comment]
Exposure too high.

**Comment by ZipperKopf** [comment]
> Exposure too high or MJPEG not enabled.

I tried changing both and nothing happened, still 15fps

**Comment by sthalik** [comment]
I had the same camera model (Logitech C525) and it ran in 15 FPS when a setting called 'RightLight' was enabled.

**Comment by ZipperKopf** [comment]
> I had the same camera model (Logitech C525) and it ran in 15 FPS when a setting called 'RightLight' was enabled.

This fixed it! Thank you so much!
