### ISSUE TITLE
In-game output of headtracking not smooth

### ISSUE THREAD

**Issue by OpenFire78** [opentrack/opentrack#1659]
I'm using OT with AITracker for MSFS. When I click "start" in OT while AITracker is tracking, the octopus moves smoothly. However, when I go in-game and try to use it, the movements are quite jittery. I also seem to be getting unwanted, exaggerated movements even when I keep my head as still as possible.

My settings:
![Screenshot 2023-05-21 120756](https://github.com/opentrack/opentrack/assets/134224137/5b84bb0e-435c-42d8-9355-672b37336597)

**Comment by GO63-samara** [comment]
https://github.com/opentrack/opentrack/issues/1614
