### ISSUE TITLE
Tracking randomly stopping when using auto tracking based on executable

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#168]
I tried the new very nice feature of automatically starting tracking based on starting a specific executable.

In my case this was Il-2 Cliffs of Dover. When I started the game the auto tracking started perfectly, but after a while it randomly stops tracking for a few seconds and then starts again. When I disabled the auto tracking based on executable feature the tracking didn't stop, therefore I think the error must be somewhere in the executable tracking.

I will check this out more with other games within a few days.

**Comment by sthalik** [comment]
There was a bug making it run erratically. It's fixed in rc12p1 binary release.

**Comment by MathijsG** [comment]
Confirmed that this is perfectly working again indeed :).
