### ISSUE TITLE
Game is crashing when selecting EWMA filter, also no octopus with this filter

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#169]
I'm trying out some filtering and stuff the get a smoother experience, but when I try the EWMA filter the game (IL-2 Cliffs of Dover) just crashes, and I don't see a moving octopus. Is this just me or is this filter deprecated?

**Comment by sthalik** [comment]
I can't reproduce the issue. What "game output" values are you getting?

**Comment by MathijsG** [comment]
The game output stays zero, while the raw data does give numbers. But as soon as I click start the octopus also hides (that's supposed to work that way?)

And with Kallman I do get the Octopus, but when I want to calibrate any settings of Kalman I just get an empty popup window with no settings.

**Comment by sthalik** [comment]
My guess is that there's division by zero resulting in NaN values passed around. Try this build: <<https://www.dropbox.com/s/vhxgn4er967g3yr/libopentrack-filter-ewma.dll>>. If the octopus no longer disappears, it's a proper fix.

**Comment by sthalik** [comment]
The binary is larger because there's debug info in it. It's otherwise identical with NaN check applied.

**Comment by MathijsG** [comment]
When I put the DLL and run the software the filter isn't even selectable anymore:
![image](https://cloud.githubusercontent.com/assets/529552/8019382/63493256-0c4b-11e5-9cc5-b41d565a92d6.png)

**Comment by sthalik** [comment]
My bad, try this whole installation directory: <<https://www.dropbox.com/s/2rm8udnvd2l6qpw/opentrack-ewma-test-20150606.7z>>

**Comment by MathijsG** [comment]
Nice it's working again now :-). Kalman only still got no settings, but I think that is working as intended?

All those filters are a little confusing to me though, maybe we can provide some in-program info about which filter is best for which situation or something? I would help with documenting things.

**Comment by sthalik** [comment]
Kalman and EWMA are @dbaarda's turf. He works on them when he feels like it. It's mostly for academical purposes that they're in-tree.

I'm working on improving Accela before release and gathering feedback. Let's wait with filter performance evaluation until all that could be done, has been done.

**Comment by sthalik** [comment]
Thanks for bug report.
