### ISSUE TITLE
Joystick emulation config popup link to vjoystick (sp?) gives a 404 error + confusion about the different versions out there

### ISSUE THREAD

**Issue by ackalker** [opentrack/opentrack#1700]
I'm using opentrack version 2023.1.0 on Windows 11, trying to set it up with neuralnet camera tracking as input and joystick emulation output.

When I tried to configure the output (Joystick emulation -- vjoystick), I get the following popup:
![OpenTrack-vjoystick-popup](https://github.com/opentrack/opentrack/assets/429567/72c0fe3a-f605-481c-938b-3f91b096a8d0)
I didn't know I had to install additional software, so I clicked the link for vjoystick.
Then in my browser, I received a 404 error from this page: https://vjoystick.sourceforge.net/site/
I didn't try the direct download link.

By vjoystick does it mean vJoy?
Then perhaps the Sourceforge link should point to: https://sourceforge.net/projects/vjoystick/
Or perhaps a link to the GitHub repository (for Windows 7 upto Windows 10): https://github.com/shauleiz/vJoy
Or perhaps a link to a fork on GitHub (for Windows 11, mentioned on the GitHub page for shauleiz/vJoy): https://github.com/jshafer817/vJoy
Or perhaps a link to a newer fork on GitHub (mentioned on the GitHub page for jshafer817/vJoy): https://github.com/njz3/vJoy/

All in all a bit of a rabbit hole to fall into, perhaps it is better to point the vjoystick link in the opentrack popup to a webpage explaining the different names (vjoystick / vJoy), the various versions, which versions are compatible with opentrack, and when and how to use them.

**Comment by sthalik** [comment]
Can you confirm which of the fork works? Preferably starting with the newest one.

**Comment by ackalker** [comment]
Sure! I will post my findings in a follow-up comment.

**Comment by ackalker** [comment]
Here are the results of my tests on both Windows 11 and Windows 10. I haven't added Windows build info, but both computers were fully updated on their version. I also haven't tested joystick input in actual games yet, because I wanted to check basic functionality as quickly as possible.
Please feel free to use this for a Wiki page if you wish.

### Version compatibility matrix

| Repository | Version (Date) | OS | Installation | Input from vJoy Feeder | Input from opentrack (# of axes) | Output to game | Remarks |
|------------|----------------|----|--------------|------------------------|----------------------------------|----------------|---------|
| [ njz3/vJoy](https://github.com/njz3/vJoy/) | [v2.2.1.1](https://github.com/njz3/vJoy/releases/tag/v2.2.1.1) (Jul 18, 2020) | Win11 | ❌ | ❌ | ❌ | | |
| [ njz3/vJoy](https://github.com/njz3/vJoy/) | [v2.2.1.1](https://github.com/njz3/vJoy/releases/tag/v2.2.1.1) (Jul 18, 2020) | Win10 | ✔️ | ✔️ | ❌ | | |
| [jshafer817/vJoy](https://github.com/jshafer817/vJoy) | [v2.1.9.1](https://github.com/jshafer817/vJoy/releases/tag/v2.1.9.1) (Jul 14, 2019) | Win11 | ✔️ | ✔️ | ✔️ (6) | | |
| [jshafer817/vJoy](https://github.com/jshafer817/vJoy) | [v2.1.9.1](https://github.com/jshafer817/vJoy/releases/tag/v2.1.9.1) (Jul 14, 2019) | Win10 | ✔️ | ✔️ | ✔️ (6) | | |
| [shauleiz/vJoy](https://github.com/shauleiz/vJoy) | [v2.1.8 Build 39](https://github.com/shauleiz/vJoy/releases/tag/v2.1.8.39) (May 27, 2018) | Win11 | ❌ | ❌ | ❌ | | |
| [shauleiz/vJoy](https://github.com/shauleiz/vJoy) | [v2.1.8 Build 39](https://github.com/shauleiz/vJoy/releases/tag/v2.1.8.39) (May 27, 2018) | Win10 | ✔️ | ✔️ | ✔️ (6) | | |

**Comment by ackalker** [comment]
Great, thanks for the fix!
