### ISSUE TITLE
Privacy 

### ISSUE THREAD

**Issue by Guaziboi** [opentrack/opentrack#1708]
Wasn't sure where else to ask this. So I'm working with my university to build a driving simulator. My advisors have concerns about the privacy of the user. Does opentrack gather, store, and sell any biometric data? Kind of along the lines of Facebook selling their users' data.

Thank you

**Comment by sthalik** [comment]
> Does opentrack gather, store, and sell any biometric data? Kind of along the lines of Facebook selling their users' data.

No. It only writes to the config directory and several HKCU/Software keys. No network activity is done unless tracking input or output over the network is specifically requested. The camera images aren't saved or sent anywhere, or even kept in memory longer than necessary.

Telemetry would actually be useful for the project's development but too many people hate it.
