### ISSUE TITLE
[feature] make a meta-tracker for running multiple trackers

### ISSUE THREAD

**Issue by jochenschmich** [opentrack/opentrack#171]
Hi there,

in V2.2 it was possible to configure a secondary tracker. This way you could combine a Gyroscope Tracker (via Joystick for example) and a IR Clip.

In V2.3 this options seems to be gone.
Is there any way to reactivate it?

Cheers

**Comment by sthalik** [comment]
The exact functionality of "secondary tracker" won't come back. It was poorly designed.

A better idea is to make a new "Meta" or "Multi" tracker that allows for selecting arbitrary other trackers and assigning axes.

Any objections?

**Comment by jochenschmich** [comment]
OK, sounds quite good. Configuration of each individual tracker should not change, though - I mean interface-wise.

Cheers.

**Comment by jochenschmich** [comment]
Will this feature be part of v2.3?

**Comment by sthalik** [comment]
Yes.

**Comment by sthalik** [comment]
How important is running the same tracker twice? It can be done in options.hpp bundle support.

**Comment by jochenschmich** [comment]
Might be useful in a scenario where multiple virtual Joysticks are used for example... it's not especially important for me - might be important for other people, though.

**Comment by cutzmf** [comment]
Ummm... I'm waiting for this feature.
I appreciate your work =) Thank You.

**Comment by Ec0nomist** [comment]
When? :)
https://forum.il2sturmovik.ru/uploads/monthly_05_2017/post-38890-0-66333900-1495974689.png

**Comment by sthalik** [comment]
I think this is enough for now. Are there any other use-cases? I'm closing but keep me notified if you need something else.

**Comment by sthalik** [comment]
@Ec0nomist I need a second user confirming Vive works in the test build.
