### ISSUE TITLE
full range of motion

### ISSUE THREAD

**Issue by snakeoneone** [opentrack/opentrack#1711]
whatever i do, i can't look over my right shoulder in dcs. I can but never as much as left-
I have made several led models, tweaked every setting i can think of and i always get the same result. After calibrating i am always looking 90º degrees left and about 60º down. I then compensat for that in output but turning right only ever allows me to see my right sidewinders tip, looking left almost allows me 180º back.
I have used ps3 eye with IR leds, ad other cameras with 140º field of view  red leds always with the same problem

**Comment by Len62** [comment]
Once you finish calibrating your view should be centered and game data should be all zeros.

**Comment by snakeoneone** [comment]
> Once you finish calibrating your view should be centered and game data should be all zeros.

Never happens. If i get zeros they're not in the center. I always get a view of my seat and part of my left panel

**Comment by Len62** [comment]
I'm sure you checked the options screen for key-binds. It's the only thing I can think of at the moment. I use the same set-up, PS3 eye and IR clip.
![OT Options](https://github.com/opentrack/opentrack/assets/10486813/7c629b59-695b-4c87-bd5c-f7c766b64b27)

**Comment by snakeoneone** [comment]
> I'm sure you checked the options screen for key-binds. It's the only thing I can think of at the moment. I use the same set-up, PS3 eye and IR clip. ![OT Options](https://user-images.githubusercontent.com/10486813/265222264-7c629b59-695b-4c87-bd5c-f7c766b64b27.png)

doesn't matter. Centering aligns with hud only after compensating in the output fields and whatever i do i can't see my right wing. I don't even think if 1 or 2mm of difference in led alignment when viewed from the front could skew the tracker because i remade the tracker and the result is always 90º left and about 60º or  65º down

**Comment by Len62** [comment]
Do you experience this issue with running OT w/o dcs running?

**Comment by snakeoneone** [comment]
![2023-09-02 at 23-51-10](https://github.com/opentrack/opentrack/assets/143658788/3b62544f-45d8-4cd2-bca6-b7f8b8e9e228)
 that's zeros

**Comment by snakeoneone** [comment]
> Do you experience this issue with running OT w/o dcs running?

I have configured opentrack both with and without dcs running

**Comment by Len62** [comment]
Ok, try this for me. W/O any games running start OT and capture a screen that shows the tracker running. In the one above the tracker is not running.

**Comment by snakeoneone** [comment]
![2023-09-03 at 12-29-14](https://github.com/opentrack/opentrack/assets/143658788/474d1041-5717-4dbe-86c2-8df88bf1a1e5)

**Comment by snakeoneone** [comment]
if i change from the f/a-18 to the f15 i can look up much more but can't look left or right more than 10º to either side, give or take.
Is it possible that OT is getting confused by the monitor setup file? In the f18 dcs's config as a diferent monitor resolution

**Comment by Len62** [comment]
Forget about games for the time being. You need to get OT running correctly first. Try re-calibrating, here is a link, it's pretty old but it still applies.
https://youtu.be/ZDz-bholoMo

**Comment by snakeoneone** [comment]
> Forget about games for the time being. You need to get OT running correctly first. Try re-calibrating, here is a link, it's pretty old but it still applies. https://youtu.be/ZDz-bholoMo

i did it running those planes i mentioned that don't use helios virtual cockpit or a different monitor setup and it works well

**Comment by Len62** [comment]
Ok.

**Comment by snakeoneone** [comment]
Every new plane i bought worked well.
I deleted some file about the F15 and it now works weel too.
Unfortunately i can't find the one corrupting F18, i don't know which i deleted.
Anyway it's not opentrack. It's probaly Helios

**Comment by snakeoneone** [comment]
end

**Comment by Len62** [comment]
Ok, hope you can figure out the F-18. I don't fly in DCS very often and when I do it's always in a chopper.

**Comment by snakeoneone** [comment]
for anyone facing the same problem delete SnapViews.lua in C:\Users\*****\Saved Games\DCS\Config\View
