### ISSUE TITLE
Can't open Camera settings

### ISSUE THREAD

**Issue by Dan0rk** [opentrack/opentrack#1716]
Hello.
Nothing happens whenever I try to click the "Camera settings (when available)" button with the PS3 Eye Universal device selected.
![image](https://github.com/opentrack/opentrack/assets/59278774/35714971-6915-4383-9d31-a6c58f4d579a)
It works with other cameras selected but not with the PS3 Eye.
Whenever I press the button, the red light on the PS3 goes on for about half a second and then turns off.

Is there any known fix for this or do other people have the issue too?

**Comment by sthalik** [comment]
Why not use the driver bundled with opentrack?

**Comment by Dan0rk** [comment]
I just tried this but for some reason the picture gets way worse. 
![image](https://github.com/opentrack/opentrack/assets/59278774/449d90a1-1261-47b0-a2f8-8c348b9ea518)

**Comment by sthalik** [comment]
What framerate is this? Use 640x480@60Hz.

**Comment by Dan0rk** [comment]
I had the framerate on 120 and a 60 fixes it. I copied the settings from [this](https://www.youtube.com/watch?v=5Nimz4M-sxU) YouTube video. Do you have an Idea why it works with his Camera?

**Comment by sthalik** [comment]
He ran in 320x240.

**Comment by Dan0rk** [comment]
But on [this part](https://youtu.be/5Nimz4M-sxU?si=83ozbp7Gl73PQ6co&t=998) of the video for example he used 640x480.

**Comment by sthalik** [comment]
He's using CL-Eye driver. Effectively he's using 75 Hz. That driver doesn't support 83 Hz. The image corruption in modes over 60 Hz decreases if you turn down gain. So it's your choice whether you prefer 60 or 75 Hz. The former has no corruption at all.

Here's the full list of modes: https://github.com/opentrack/PS3EYEDriver/blob/master/ps3eye.cpp#L492-L519.

**Comment by Dan0rk** [comment]
Thanks for the fast answer. You really helped me.
