### ISSUE TITLE
Remove walware from the wiki

### ISSUE THREAD

**Issue by Eitz** [opentrack/opentrack#1717]
While browsing the [wiki](https://github.com/opentrack/opentrack/wiki) I've noticed some strange links in some pages; I've tried to remove them on my own but only approved editors can remove.

Please revert the following commits in the **wiki separate git**, they have added spurious, likely malware, links to the text quite some time ago:

- `git revert 6f11ac3`
- `git revert 204f111`

Thanks.

(maybe there's more there, but these were the ones I've noticed).

**Comment by sthalik** [comment]
I've removed vandalized URLs from the ones you listed and just one other page. They won't come back, as the wiki can't be edited by guests anymore.

Thank you for this report.

**Comment by Eitz** [comment]
Thanks!
