### ISSUE TITLE
It doesn't working in the background

### ISSUE THREAD

**Issue by stradalee** [opentrack/opentrack#1720]
If I minimize opentracker window after running it, it suddenly disappears from the taskbar.

So if I go into the task manager and search opentracker, it's running now, but it doesn't use hardware such as cpu, and it doesn't work normally when I run it again. So there is a hassle of having to force to shut it down and run it again.

There was no such problem in previous versions.

**Comment by sthalik** [comment]
I won't be able to fix it without additional information or a way to reproduce it. Worse, there haven't really been any changes in 2023.2.0 that could cause this. It might be difficult to diagnose and fix.

**Comment by sthalik** [comment]
Are you sure you haven't enabled tray support?

**Comment by stradalee** [comment]
Ahhh, I haven't checked that yet.

**Comment by stradalee** [comment]
Disabling tray support, all issues disappeared. 
But there is new question. Why doesn't opentrack work on dcs if I enable tray support?

**Comment by sthalik** [comment]
Tray support shouldn't change anything regarding freetrack output.

**Comment by stradalee** [comment]
I see. Thank you for your help.
