### ISSUE TITLE
[BUG] neuralNet roll is upside down

### ISSUE THREAD

**Issue by ddzzkunye** [opentrack/opentrack#1728]
neuralNet roll is upside down  
![example](https://github.com/opentrack/opentrack/assets/92249100/0f3309dd-61de-4266-b3ff-7c810c1a6bfa)

**Comment by DaWelter** [comment]
I noticed and created a PR with a fix now. 

The visualization is actually working as intended, but the roll value was indeed by 180 deg wrong.

**Comment by ddzzkunye** [comment]
Branches have been merged
