### ISSUE TITLE
Sometimes filters get reset by unknown cause

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#173]
I sometimes encounter that my filter settings are all back to zero, don't know the cause yet, will investigate this further. Using the latest RC binary.

**Comment by sthalik** [comment]
Can you confirm like this:

- start with empty config
- open filter settings, cancel
- open again

It's empty then for me.

**Comment by MathijsG** [comment]
Yeah then it's empty, but I mean profiles with filter settings where I didn't explicitly reset the filter are somehow reset to zero.

**Comment by sthalik** [comment]
@MathijsG try RC13.

**Comment by sthalik** [comment]
I'll reopen if still happens.
