### ISSUE TITLE
Aruco has a roll problem

### ISSUE THREAD

**Issue by ddzzkunye** [opentrack/opentrack#1734]
> Aruco has a similar problem  

_Originally posted by @ddzzkunye in https://github.com/opentrack/opentrack/issues/1731#issuecomment-1741886358_

**Comment by ddzzkunye** [comment]
![image](https://github.com/opentrack/opentrack/assets/92249100/4fbcec8c-81c8-4b34-915e-5662b90f9ea2)  
I _drew_ this ArUco.

**Comment by ddzzkunye** [comment]
![image](https://github.com/opentrack/opentrack/assets/92249100/f71a9f1d-9611-40c9-9174-d6143d24a089)
I drew this ArUco.

**Comment by sthalik** [comment]
The PT and Aruco trackers didn't have these problems back when they were being developed.  Maybe try it with a known good marker. Here are some [user-submitted videos](https://www.dropbox.com/sh/atyazm22wwuzxlf/AADOStjt0F-xIsmhOcbEKXyZa?dl=0).

If there's a global issue then it needs to be fixed properly. There shouldn't be a need to invert any output axes.

**Comment by ddzzkunye** [comment]
In all the videos I could find, the aruco is rotated 90 degrees.  
![example](https://github.com/opentrack/opentrack/assets/92249100/e08a8526-cf80-4dca-9391-59cb8c4214e7)
![example2](https://github.com/opentrack/opentrack/assets/92249100/d952584f-840d-4355-8125-d2622f27f713)

**Comment by sthalik** [comment]
> Maybe this historical problem shouldn't be fixed? It affects too many people.

You're right that the problem exists, but it's mostly of theoretical interest. Users are expected to wave it at the Aruco tracker before mounting the marker on their headsets.
