### ISSUE TITLE
Rotation of headset not updating (UDP)

### ISSUE THREAD

**Issue by vitek182009** [opentrack/opentrack#1744]
Hello,

I am currently working on my own VR headset. But opentrack doen't offer any tracking that's cheap and supports all 360°.
So, I came up with my own tracking python script that tracks Aruco and it works great. It sends position and rotation of my headset over UDP to OpenTrack and from OpenTrack to SteamVR using this: [https://github.com/r57zone/OpenVR-OpenTrack](url).

This is my raw code for sending position to OpenTrack:

```
import socket
import struct

openTrack_ip = '127.0.0.1' 
openTrack_port = 4242 

udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

position_x = 12
position_y = -10
position_z = 6
yaw = 5
pitch = 57
roll = 12

data = struct.pack('dddfff', position_x, position_y, position_z, yaw, pitch, roll)

udp_socket.sendto(data, (openTrack_ip, openTrack_port))

udp_socket.close()
```
I recommend you try it yourself. It works, when you run it, it updates headset position x y z, but for some reason yaw, pitch and roll is not changing at all. It could be in OpenTrack configuration or in the code, I don't really know.

**Comment by sthalik** [comment]
```python
data = struct.pack('dddfff', position_x, position_y, position_z, yaw, pitch, roll)
```

No, you want 6 d's.
