### ISSUE TITLE
Wiki page about AI face tracking

### ISSUE THREAD

**Issue by microraptor** [opentrack/opentrack#1753]
AI face tracking became very good and popular in recent years. However, there doesn't seem to be any information about these trackers on the wiki. I wrote a short summary as seen below, which can be posted on the wiki, but I don't have any editing rights. It might be better to split this into three separate articles. Any corrections and additions are very welcome.

---

Edit: There was the text about AI face tracking here, which was moved to the wiki. Future readers, please [see the wiki page](https://github.com/opentrack/opentrack/wiki/AI-Face-Tracking) for updated information.

**Comment by sthalik** [comment]
It's definitely better if you can edit the page by yourself. I sent you an invitation.

**Comment by microraptor** [comment]
Thank you, I joined the organization. However, I don't have permissions to create or edit wiki pages yet. I assume you have to assign them manually. Let me know if I should the webcam and settings section on separate wiki pages, instead of leaving them as one.

I will then link the face tracking page at the one [FAQ question](https://github.com/opentrack/opentrack/wiki/common-issues#i-dont-want-to-make-a-led-clip) and in the paragraph where the [Quick Start Guide](https://github.com/opentrack/opentrack/wiki/Quick-Start-Guide-(WIP)) talks about trackers.

**Comment by sthalik** [comment]
It seems the only way to grant you wiki edit rights is to grant you de facto repository write access. I trust you won't do anything bad with it.

As for clip manufacturers, there's also [TrackHat](https://www.trackhat.org/) in the UK.

**Comment by microraptor** [comment]
Thank you, I added trackhat, cleaned up the links and created [the wiki page](https://github.com/opentrack/opentrack/wiki/AI-Face-Tracking). I also added the links in the quick start guide and faq:
![image](https://github.com/opentrack/opentrack/assets/15663536/99fb7c8b-508d-4bf4-aa56-a327d9a230b4)
![image](https://github.com/opentrack/opentrack/assets/15663536/f267a4e9-2106-487e-92f1-c671de7d80a9)

**Comment by microraptor** [comment]
I saw the issue with people posting malware links when the wiki was public. In the long run it would probably best to keep the documentation/wiki as files on the main or a separate repository and have a github action/CI [update the github wiki](https://stackoverflow.com/a/58692638) or create a web page (like Docusaurus, MkDocs, GitBook or Read the Docs). Then people could submit PR requests for wiki changes.

**Comment by sthalik** [comment]
That's a good idea. A simple Github Action can execute a force-push into the hidden wiki repository.
