### ISSUE TITLE
Dynamic resolution bug or improvement

### ISSUE THREAD

**Issue by rizer1980** [opentrack/opentrack#176]
Hello.

When one of the points lost, the red dot moves to the wrong place.
Coordinates are no longer properly transmitted.
It does not help either reset or switching on / off via hotkey.
Just stop and start through the application.

Video:
http://youtu.be/YEWlZ01GALw

I have two suggestions:
Or do so would by pressing zero, dynamic resolution also stop start.
Or do as freetrackNoIR, with the setting the "reset time Dynamic resolution" when I put there instead of 1000ms, 100ms, it works well.

Thx.

**Comment by sthalik** [comment]
Right, dynamic pose resolution timer needs to return badly.

**Comment by sthalik** [comment]
Assumed fixed in 95218d013693e3af637fe4ea3333090b8eaa0500. If still broken I'll reopen.
