### ISSUE TITLE
[bug] Default dimensions for clips and caps are all zero'd in Pointtracker plugin

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#180]
Normally this plugin would have the default dimensions for clip and cap in the software. I think with this all zero'd it would make the software harder for users.

![image](https://cloud.githubusercontent.com/assets/529552/8498720/82fa9186-218a-11e5-8b0a-c2d6d3460bed.png)

![image](https://cloud.githubusercontent.com/assets/529552/8498721/862132ac-218a-11e5-8541-2bad296cca93.png)

**Comment by sthalik** [comment]
It can't be any better. If dimensions are half-right by default, users will leave them there and complain that tracking works erratically.

**Comment by MathijsG** [comment]
But before they were based on the defacto default which anyone uses. Why differ from that? The few people with different dimensions will change it, but the majority with a default clip now find their program not working unless they fill in these dimensions somewhere hidden in the program.

**Comment by sthalik** [comment]
What default? Please provide a reference and back up how "everyone uses it".

**Comment by MathijsG** [comment]
In the Freetrack Manual: http://forum.free-track.net/index.php?showtopic=413

Every program or software I saw which involved home made clip making defaulted to:

![image](https://cloud.githubusercontent.com/assets/529552/8499816/bba718cc-2196-11e5-8af9-2e5ab1fc409c.png)

I thought FaceTrackNoIR and even the previous versions of OpenTrack also had these dimensions pre-filled in. Or am I mistaken?

**Comment by sthalik** [comment]
Fixed in 7a98f8831efb6692241106e53af09e2385f02668, thanks!

**Comment by MathijsG** [comment]
Maybe also insert these 'default' hat dimensions?

![image](https://cloud.githubusercontent.com/assets/529552/8500074/18f6dfba-2199-11e5-8f9f-bef6777884a8.png)
