### ISSUE TITLE
Missing many input options

### ISSUE THREAD

**Issue by SkippTekk** [opentrack/opentrack#1807]
OS: EndeavorOS Arch
Version: 2023.3.0-26-g3fe74769

Installed from Wiki

Not sure what's going on but trying to get this working for DCS and other applications.

![Screenshot from 2024-02-17 20-21-04](https://github.com/opentrack/opentrack/assets/6195158/7e98ec44-5574-49b7-9218-23c0035cec6a)

**Comment by SkippTekk** [comment]
Seems that the email method had failed. I'm trying to get the face tracking method working.

**Comment by SkippTekk** [comment]
Ok, sorry the name of it is "neuralnet". that's the main one i would wish to get working.

**Comment by berarma** [comment]
These are the dependencies directly from the code:

```
OpenCV
OpenMP
ONNXRuntime
```

If `tracker-neuralnet` isn't listed when running cmake then some dependency is missing.

**Comment by SkippTekk** [comment]
Thank you! That's what i was missing :)

**Comment by NickDeBeenSAE** [comment]
OS: Nobara40

Installed from the Github page instructions

This means that openmv does not exist.

I recommend removing this dependency.

``No match for argument: openmv``

**Comment by sthalik** [comment]
`opencv` is missing, not openmp.

**Comment by NickDeBeenSAE** [comment]
Open CV is fine.

It was not a weak.

**Comment by sthalik** [comment]
`openmp` is needed so that `tracker/neuralnet` can set the amount of cores as per its settings.
