### ISSUE TITLE
SDK wine issue

### ISSUE THREAD

**Issue by domrnet** [opentrack/opentrack#1808]
Hello

I am meeting the current issue....
[ 68%] Generating opentrack-wrapper-wine.exe.so
/usr/bin/ld: relocatable linking with relocations from format elf32-i386 (/usr/lib32/wine/i386-unix/libadvapi32.a(advapi32-00000384.o)) to format elf64-x86-64 (tmp65d87cc6/opentrack-wrapper-wine-00000003-00000002.o) is not supported
winebuild: /usr/bin/ld failed with status 1
winegcc: /usr/lib/wine/winebuild failed
make[2]: *** [proto-wine/CMakeFiles/wine-wrapper.dir/build.make:75: proto-wine/opentrack-wrapper-wine.exe.so] Error 2
make[1]: *** [CMakeFiles/Makefile2:2443: proto-wine/CMakeFiles/wine-wrapper.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I have wine32 installed and wine32-tools. I tried changing -m32 to -m64 in the cmake lists, exactly the same error. Googled for 4 hours and I'm nowhere closer.  I just updated to ubuntu 23.10 to see what breaks before the next LTS release and the only issue I have is now with opentrack. Any advice please?

**Comment by sthalik** [comment]
Build Wine by yourself and install it into `/opt`.

**Comment by domrnet** [comment]
thanks. just done that so now will try to build opentrack

**Comment by domrnet** [comment]
ah no! this now is sending me into more issues. wineg++: not found I presume this was not part of the wine build. out of one fire into another

**Comment by sthalik** [comment]
`wineg++` is built together with Wine. You might be using the wrong `PATH`.

**Comment by domrnet** [comment]
I am getting out my comfort zone now so apologies for questions that may seem obvious. 
I ran configure withe the prefix like this...   --prefix=/opt/wine 
Wine is installed in opt/wine . If I look in the bin directory there I see wineg++ symlinked . At what point or where do I define the path?

**Comment by sthalik** [comment]
Then try:
```console
$ ln -s /opt/wine/bin/wine* /usr/bin
```
assuming that you've uninstalled Ubuntu's version.

**Comment by domrnet** [comment]
yep purged the ubuntu install I had originally. 
Path was some help soem links were not set it seems however I now come full circle back to my original error..

relocatable linking with relocations from format elf32-i386 (tmp65d89237/opentrack-wrapper-wine-00000003.spec-00000000.o) to format elf64-x86-64 (tmp65d89237/opentrack-wrapper-wine-00000003.spec-00000001.o) is not supported
winebuild: /usr/bin/ld failed with status 1
winegcc: /opt/wine/bin/winebuild failed
make[2]: *** [proto-wine/CMakeFiles/wine-wrapper.dir/build.make:75: proto-wine/opentrack-wrapper-wine.exe.so] Error 2
make[1]: *** [CMakeFiles/Makefile2:2443: proto-wine/CMakeFiles/wine-wrapper.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by domrnet** [comment]
seemed I had missed a few dependencies in the wine build. Went through the whole list on the win web page https://wiki.winehq.org/Building_Wine and after a loooong build. Opentrack built without issue.

thank you for your support.

**Comment by sthalik** [comment]
Yeah the wiki page you linked a separate tools build. Which is what you need.

**Comment by domrnet** [comment]
Thanks a lot!
