### ISSUE TITLE
Win 11 kill Opentrack!

### ISSUE THREAD

**Issue by kaiolavi** [opentrack/opentrack#1818]
I installed the last version of Opentrack on the Win 11 machine, and for a while it opened, but now it doesn't even open anymore, would using an older version help?

**Comment by kaiolavi** [comment]
Even the Opentrack window does not open on this Win 11 machine, would the old version help with Win 11?

**Comment by kaiolavi** [comment]
I got the Openrack program working, thanks for that.
Another question would be, why Opentrack does not open at all on a Win 11 machine.
I tried the latest version?

**Comment by sthalik** [comment]
Try this build first: https://github.com/opentrack/opentrack/issues/1394#issuecomment-1938864870. If it still won't work, downgrade to 2023.1.0.

**Comment by sthalik** [comment]
Answered in #1817.

**Comment by kaiolavi** [comment]
Thank you ,i must try!

ma 18. maalisk. 2024 klo 12.12 Stanislaw Halik ***@***.***)
kirjoitti:
