### ISSUE TITLE
[bug] clicking on settings of filter while selected no filter let's program crash

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#182]
![image](https://cloud.githubusercontent.com/assets/529552/8501275/4f44d788-21a4-11e5-9a13-c59942bd8512.png)

When I press the settings of the filter the program crashes. Maybe make this greyed out while having no filter selected?

**Comment by sthalik** [comment]
Fixed, thanks

**Comment by MathijsG** [comment]
The crashing is fixed, but would the button 'greyed out' not be a better option UX wise? Now it still implies that you can alter some settings now.

**Comment by sthalik** [comment]
Not worth adding more logic to the UI.
