### ISSUE TITLE
Game detection settings keep in program

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#183]
While I thought I started clean by removing every file of the previous version, I still have all the games attached to the Game detection window:

![image](https://cloud.githubusercontent.com/assets/529552/8501314/90f93052-21a4-11e5-9f4e-96ebb3be685d.png)

However they are now automatically attached to the only custom profile (besides the default profile) left.

Maybe this should also be gone while removing all settings? Where is this saved anyway?

**Comment by sthalik** [comment]
It's in registry, in same place as profile name. It finds that profile since there's no other with given name.

**Comment by sthalik** [comment]
Fixed in d682058, thanks
