### ISSUE TITLE
[Feature request] Make a button or a window for specific webcam settings

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#187]
With my PS3 camera I use a special software tool called CL-Eye Tool, but for many webcams you can't easily alter settings of the webcam without some program like skype or something which can start the webcam settings, which can trigger this window:
![image](https://cloud.githubusercontent.com/assets/529552/8512425/06d923f6-2342-11e5-8b04-e775f5db2853.png)

Maybe OpenTrack should also have some settings button, so you don't need external programs to tweak the webcam view. FreeTrack also had this in their program.

**Comment by sthalik** [comment]
I agree. OpenCV has an option to pop up the dialog, but in case of PS3 Eye it doesn't work, even though it works in Skype.

Working with DirectShow is overkill for me. Someone else has to write the code.

**Comment by sthalik** [comment]
Implemented. Won't work for PS3 Eye.

Doesn't work while tracking for HT at all. Either HT stops being a subprocess or it won't work.

**Comment by sthalik** [comment]
We could temporarily stop tracking for HT though.
