### ISSUE TITLE
Missing inputs and outputs on Linux

### ISSUE THREAD

**Issue by skoove** [opentrack/opentrack#1874]
I am missing a ton of inputs and outputs, most important to me are nuralnet tracker and free track output. I am on nixos, on nixpkgs unstable, are there dependencies i need to add manually?

**Comment by sthalik** [comment]
Yes.

If you're missing a particular module, look into its directory (such as `proto-wine`) for `CMakeLists.txt` to see the conditions for it to be built.

**Comment by skoove** [comment]
i realised that my actual issue was being on linux, freetrack does not work with native linux games, i just reinstalled windows to play flight sims on

**Comment by sthalik** [comment]
There's the Wine protocol that works with Windows games though.
