### ISSUE TITLE
Hatire Arduino plugin is disappeared in opentrack 2024.1.1

### ISSUE THREAD

**Issue by Attigliuzzo** [opentrack/opentrack#1878]
The Hatire Arduino plugin is available under Linux, i compiled the source code. 
The portable edition of Opentrack 2024.1.1 lacks the Hatire plugin.
Has it been removed??
Thanks for the continuing development, @sthalik  and  @other_devs_&_testers

**Comment by sthalik** [comment]
It's missing in the 32-bit build. It'll be fixed very soon.

**Comment by Attigliuzzo** [comment]
The 64bit version has the Hatire plugin, so it is solved.
