### ISSUE TITLE
[Feature Request]  Multi CPU friendly

### ISSUE THREAD

**Issue by Forsaken-Player** [opentrack/opentrack#188]
It only uses one of my 6 cores... AMD 1090T cpu by the way.

**Comment by sthalik** [comment]
The software uses three threads.

- tracker
- UI
- coordination from tracker, filter and protocol

The idea is to leave CPU power to games, and don't perform any costly operations that sabotage that goal. This isn't a freestanding application that can consume all it wants.

If you have that many cores I recommend enabling core parking to prevent processes from jumping cores too much.
