### ISSUE TITLE
Enhancing Mouse Emulation with Overlay Tracking and Toggle Control Features (by gpt)

### ISSUE THREAD

**Issue by TenderChen** [opentrack/opentrack#1881]
The mouse emulation is working properly; what remains is to adjust the mapping curve to match intuitive feelings. However, the output of this mouse seems too simplistic. Ideally, it should function like eye-tracking by adding an overlay layer that continuously tracks and displays the bias position. The pointer should track movements via a toggle button, jumping immediately to the target position and beginning to track movements when pressed. In most cases, head movements should not drive the mouse, and the current tracking start time is obviously too long. Moreover, activating it only to jump to an unknown point provides a very poor experience; an overlay indicating the position could greatly enhance the experience. For example, in FPS games, after moving the focus to a target, one could quickly activate mouse movement, rather than shaking one's head all the way there or waiting temporarily only to find the aim is too high. An overlay might introduce additional display issues in full-screen games, but I think most people would accept switching to a borderless window for this. Just add an extra function key to control whether the mouse continues moving, whether it's held down or toggled. I believe integrating this feature into the main software rather than relying on an external script based on the SDK would be more appropriate.

**Comment by TenderChen** [comment]
forget an optimization for Mouse Pointer Tracking in Games. In many games, the default position of the mouse pointer is locked at the center of the screen. In such cases, continuously inputting the target position is not quite appropriate. This operation should be triggered once at the start of tracking to capture the current mouse position. A MouseMove event is then input, but after that, it is assumed that this event has been completed, meaning the latest mouse position starts from the last sent position. Subsequent MouseMove target positions should no longer be the screen target position, but rather the current mouse position plus the movement of the screen target position. If there is no further movement of the head afterwards, then no more mouse movements are input after the initial tracking-triggered mouse move. If the head moves a vector afterwards, then the input mouse target position is the current mouse position plus the position of the head movement vector, which is more intuitive.

**Comment by TenderChen** [comment]
I checked the code and found that the mouse output is already based on dx and dy. However, the calculation of dx and dy is always from the current mouse position to the target position on the screen. We just need to add an additional calculation for the dx and dy offsets based on the target position on the screen. Then, use the existing algorithm when the mouse movement is first triggered, and use the relative displacement algorithm for continuous input. This should easily implement the idea of quick mouse positioning + holding to sweep/draw rectangles or curves when the pointer is locked. Maybe?

**Comment by sthalik** [comment]
Elaborate mouse tracking would be more useful to something serious like a version of opentrack for quadriplegic people. Otherwise, the head is a very inaccurate controller, compared to hands or even feet. It's never going to be useful enough for gaming.

If you wish to develop your own tracker and have trouble building or setting up the environment (opentrack uses cmake), help is available.

**Comment by GO63-samara** [comment]
In this case, it would be useful to control the mouse cursor in absolute coordinates. Like a graphics tablet.

**Comment by TenderChen** [comment]
I haven't used the C++ environment for a long time, the configuration requires a lot of space and time, and the tool versions are not up to date, I hope everything goes well

**Comment by TenderChen** [comment]
Thanks to the wiki.Thanks to gpt.In the process of studying the code, I found that the circle only needs to show the expected landing point during the toggle_held to meet the initial needs.
Legacy mode is simple, but There is strange scaling in dinput mode. GPT guessed that it may be caused by the dpi setting of the system's desktop or software and gave me a piece of code that didn't solve the problem.
When I downloaded CSGO and tested it, the legacy mode was completely ignored by the game, and the dinput mode happened to work just fine.
I recorded a video showing what to expect and the strange phenomenon in both modes. https://github.com/TenderChen/opentrack/blob/mouse/ignore/2024.06.30-15.52_clip_15.mp4

**Comment by TenderChen** [comment]
> Elaborate mouse tracking would be more useful to something serious like a version of opentrack for quadriplegic people. Otherwise, the head is a very inaccurate controller, compared to hands or even feet. It's never going to be useful enough for gaming.
> 
> If you wish to develop your own tracker and have trouble building or setting up the environment (opentrack uses cmake), help is available.

In the case of cod's comprehensive enhancement of the joystick's assisted aiming, I don't think it's surprising that the emergence of a full-scene assisted target selection tool based on general AI, just like the current AI programming plug-in. In scenarios other than text editing and mapping, there are very few high-value targets in the screen area, and it is not very difficult for AI to determine the target of human interaction.

**Comment by sthalik** [comment]
What scaling, are you talking about `get_delta`? It's so that moving from +180 to -181 doesn't go the longer way (it should only change by a degree, not by 179).

**Comment by TenderChen** [comment]
> What scaling, are you talking about `get_delta`? It's so that moving from +180 to -181 doesn't go the longer way (it should only change by a degree, not by 179).

No, after that. https://github.com/TenderChen/opentrack/blob/mouse/proto-mouse/ftnoir_protocol_mouse.cpp , line 61 use SendInput(dx, dy) in dinput mode, and the end position is not SetCursorPos(+dx,+dy). line 104-110 is the dpi scaling provided by gpt, it's right in csgo, but not in desktop.

**Comment by sthalik** [comment]
You're better off getting the DPI before scaling and multiplying `s.sensitivity_x` by it for the call to `get_value`. The code already truncates `dx` and now you're truncating twice.
