### ISSUE TITLE
opentrack floods the system log with messages during webcam tracking

### ISSUE THREAD

**Issue by kakra** [opentrack/opentrack#1899]
My log becomes spammed with thousands of messages while using the webcam for tracking:
```
Jul 15 20:41:49 jupiter opentrack[511638]: [ INFO:5@976,405] global cap_v4l.cpp:1973 controlInfo VIDEOIO(V4L2:/dev/video1): property unknown is not supported
```

There are 10-30 message per second. I'm not sure if this is directly logged by opentrack but rather a lib, and "info" logging of this lib should probably be disabled except for debug builds.

**Comment by sthalik** [comment]
Normally messages are sent to stdout or stderr. Maybe there's something that's configured on your system that causes them to get logged?

The message's originator: https://github.com/opencv/opencv/blob/4.x/modules/videoio/src/cap_v4l.cpp#L1851

To workaround, open this file: https://github.com/opentrack/opentrack/blob/master/video-opencv/impl-camera.cpp

As the very first line in the file, add:

```c++
#include <opencv2/core/utils/logger.hpp>
```

Now change around line 33:

```c++
bool cam::start(info& args)
{
    stop();
    cap.emplace(idx, video_capture_backend);
```

to:

```c++
bool cam::start(info& args)
{
    cv::utils::logging::setLogLevel(cv::utils::logging::LogLevel::LOG_LEVEL_SILENT); // this line is getting added
    stop();
    cap.emplace(idx, video_capture_backend);
```

Then recompile.

**Comment by kakra** [comment]
On systemd, it logs to the journal, on many other systems, it logs to `$HOME/.xsession.log` (if I remember right). In a desktop environment, stdout/stderr is usually not thrown away, it goes at least somewhere. If nothing sets up a log, it logs to the session manager. You'd need to explicitly log to `/dev/null` but I don't think any distribution does this because no errors could be found in the logs.

If I start `opentrack` from cmdline, all logs go there.

Hmm, I wonder if we could set the loglevel to notice or warning from within opentrack... It links to `libopencv_videoio.so` so it should be able to do it. I'll prepare some PRs if you don't mind.
