### ISSUE TITLE
[Bug] Title of profile not updating

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#191]
When I change a profile the title stays the same:

![image](https://cloud.githubusercontent.com/assets/529552/8700137/79612eee-2b0a-11e5-8cd9-0f9ebe49f75a.png)

![image](https://cloud.githubusercontent.com/assets/529552/8700149/807f9530-2b0a-11e5-8e08-a2c4acf6ff23.png)

![image](https://cloud.githubusercontent.com/assets/529552/8700153/85b70254-2b0a-11e5-8d59-3668cf3e8efd.png)

**Comment by sthalik** [comment]
Fixed, thanks
