### ISSUE TITLE
Steam AppID should not be part of the profile

### ISSUE THREAD

**Issue by kakra** [opentrack/opentrack#1912]
To be able to reuse profiles across multiple games, the Steam AppID should not be part of the profile - or at least it should not be exclusively.

I propose to add another option:

- add "use Steam app ID from game detection list"
- add a Steam app ID to the game detection list

If the first option is used but the latter option is empty, the profile should refuse to start.

**Comment by sthalik** [comment]
It's easier to implement #1879 and it's going to solve issues like that.
