### ISSUE TITLE
Can't find neuralnet

### ISSUE THREAD

**Issue by MrNoob025** [opentrack/opentrack#1914]
Hey guys, I was trying to find NeuralNet since i heard that it's good, I installed multiple OpenTrack versions but still can't seem to find it.

Can anyone help?
![Screenshot (86)](https://github.com/user-attachments/assets/4f0378bc-fd04-4f3b-ba95-37f40091dc50)

**Comment by kakra** [comment]
Probably duplicate of #1908 - did you install the 64 bit version?

**Comment by DaWelter** [comment]
I wonder, do you happen to have a really old CPU?

**Comment by sthalik** [comment]
Did you install the Visual C++ redistributable by any chance?

**Comment by MrNoob025** [comment]
Well I don't remember installing it, but I have this folder on my pc, it's empty though.
