### ISSUE TITLE
[bug] When manually loading a profile, it is diverting to the top profile in the list

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#194]
While I was moving my profiles to my documents folder, to have no hassle anymore with my profiles when installing OpenTrack in Program Files. I encountered this bug:

When you manually load up a profile:

![image](https://cloud.githubusercontent.com/assets/529552/8766126/e03eb82e-2e2b-11e5-9577-3b342867c1a7.png)

It is still only loading the top profile of the list:
![image](https://cloud.githubusercontent.com/assets/529552/8766129/ea2c4cc0-2e2b-11e5-865f-af7df42563cf.png)

Here my profile list:
![image](https://cloud.githubusercontent.com/assets/529552/8766131/f0b601da-2e2b-11e5-99a0-67efec77f278.png)

**Comment by sthalik** [comment]
Thanks
