### ISSUE TITLE
Doesn't compile from source on linux

### ISSUE THREAD

**Issue by DoomSlinger** [opentrack/opentrack#1970]
Get this error when trying to commpile from source on linux

~/opentrack/compat/process-list.hpp:153:29: error: ‘PIDS_VAL’ was not declared in this scope
  153 |         char  **p_cmdline = PIDS_VAL(rel_cmdline, strv,  stack, info);
      |                             ^~~~~~~~
make[2]: *** [gui/CMakeFiles/opentrack-user-interface.dir/build.make:210: gui/CMakeFiles/opentrack-user-interface.dir/process_detector.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2405: gui/CMakeFiles/opentrack-user-interface.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by sthalik** [comment]
There's something wrong with your `libproc2`. This is a public API function, see: https://gitlab.com/procps-ng/procps/-/blob/master/library/include/pids.h#L247

```c
#define PIDS_VAL( relative_enum, type, stack ) stack -> head [ relative_enum ] . result . type
```

Just add it as line 152.

By commenting out the feature check as below you can go back to libprocps if you're using an old distro that still has it.

```patch
diff --git gui/CMakeLists.txt gui/CMakeLists.txt
index 8c57221a..5db77c24 100644
--- gui/CMakeLists.txt
+++ gui/CMakeLists.txt
@@ -13,7 +13,7 @@ if(APPLE)
 elseif(LINUX)
     otr_pkgconfig_(has-libproc2 ${self} libproc2)
     if(has-libproc2)
-        target_compile_definitions(${self} PRIVATE -DOTR_HAS_LIBPROC2)
+        #target_compile_definitions(${self} PRIVATE -DOTR_HAS_LIBPROC2)
     else()
         otr_pkgconfig(${self} libprocps)
     endif()
```

**Comment by krims0n32** [comment]
Same issue here, happened after procps-ng upgraded (arch):

**Comment by DoomSlinger** [comment]
> Same issue here, happened after procps-ng upgraded (arch):
> 
> `procps-ng (4.0.4-3 -> 4.0.5-1)`

This was my problem too, I downgraded my packages to about a week ago and it compiled.

**Comment by McTom234** [comment]
I can confirm: downgrading makes the build successful

**Comment by thorger** [comment]
@sthalik, I have same issue, and as the API has changed as per 
https://gitlab.com/procps-ng/procps/-/blob/master/library/include/pids.h#L247, 
the code here is still calling the old signature:
`char  **p_cmdline = PIDS_VAL(rel_cmdline, strv,  stack, info);`
https://github.com/opentrack/opentrack/blob/master/compat/process-list.hpp#L153C23-L153C23
I get same error as the fn call is trying to pass info param which is not handled by the new libproc2, because the info param has been removed 7 months ago:
https://gitlab.com/procps-ng/procps/-/commit/967fdcfb06e20aad0f31073474cb94545c9bdea5
Is this something to be adjusted in the process-list.hpp?

**Comment by sthalik** [comment]
Should be fixed in the newest revision. Ping me otherwise.

**Comment by SHOTbyGUN** [comment]
history: https://github.com/opentrack/opentrack/commits/master/compat/process-list.hpp

Bug was fixed 2024 https://github.com/opentrack/opentrack/commit/1a40b793adbdd7c8718b9f383eadd1ab0bb02cf0
Bug was reintroduced 2025 https://github.com/opentrack/opentrack/commit/00beb1e9730198a5ad885e0cf940bfd4a2e02a6c 

Manual workaround is to remove info parameter from line 141 https://github.com/opentrack/opentrack/blob/master/compat/process-list.cpp#L141

*edit: ping @sthalik

**Comment by sthalik** [comment]
Thanks for spotting this @SHOTbyGUN. See if this patch works:

```diff
diff --git compat/process-list.cpp compat/process-list.cpp
index 34c83b06..1afb0e99 100644
--- compat/process-list.cpp
+++ compat/process-list.cpp
@@ -136,9 +136,22 @@ QStringList get_all_executable_names()
 
     procps_pids_new(&info, items, 3);
 
+    // procps-ng version 4.0.5 removed an unused argument in PIDS_VAL() macro.
+    // cf. https://gitlab.com/procps-ng/procps/-/commit/967fdcfb06e20aad0f3
+
+    // Although the emitted machine code is identical, backward API
+    // compatibility was silently broken in the patch with no upgrade path
+    // (e.g. deprecating PIDS_VAL() while introducing PIDS_VAL2()).
+
+    // Unfortunately, procps-ng doesn't include a #define for identifying its
+    // version.  For these reasons the code below depends on undocumented ABI
+    // compatibility between procps-ng versions.. -sh 20241226
+
+#define OPENTRACK_PIDS_VAL(i, type, stack) stack->head[i].result.type
+
     while ((stack = procps_pids_get(info, PIDS_FETCH_TASKS_ONLY)))
     {
-        char  **p_cmdline = PIDS_VAL(rel_cmdline, strv,  stack, info);
+        char  **p_cmdline = OPENTRACK_PIDS_VAL(rel_cmdline, strv,  stack, info);
 
         // note, wine sets argv[0] so no parsing like in OSX case
         if (p_cmdline && p_cmdline[0] && p_cmdline[0][0] &&
```

**Comment by JT8D-17** [comment]
> Thanks for spotting this [@SHOTbyGUN](https://github.com/SHOTbyGUN). See if this patch works:
> ...

Patching process_list.cpp with this produces "error: ‘OPENTRACK_PIDS_VAL’ was not declared in this scope" on compilation.

- Edit: Removing "info" the original file works.

**Comment by SHOTbyGUN** [comment]
> See if this patch works: _>> while patch itself did not work for the reason JT8D-17 mentioned_

`yay -S opentrack-git`

works now without issues since fix in master https://github.com/opentrack/opentrack/commit/a47cbd05214787640bbeffa289b4d932905d213f

**Comment by JT8D-17** [comment]
Yep, compiles fine again. Thanks, @sthalik !

**Comment by cyber199** [comment]
Unsure if this is related (I'm an idiot) but as the issue is still open I'll show what's happening to me
```
$ make
[...]
[ 29%] Building CXX object csv/CMakeFiles/opentrack-csv.dir/csv.cpp.o
/media/path/to/opentrack/csv/csv.cpp:24:15: error: ‘QLatin1StringView’ was not declared in this scope; did you mean ‘QLatin1String’?
   24 | auto do_scanf(QLatin1StringView s, unsigned(&tmp)[8])
      |               ^~~~~~~~~~~~~~~~~
      |               QLatin1String
/media/path/to/opentrack/csv/csv.cpp:24:46: error: ‘tmp’ was not declared in this scope; did you mean ‘tm’?
   24 | auto do_scanf(QLatin1StringView s, unsigned(&tmp)[8])
      |                                              ^~~
      |                                              tm
/media/path/to/opentrack/csv/csv.cpp:24:53: error: expression list treated as compound expression in initializer [-fpermissive]
   24 | auto do_scanf(QLatin1StringView s, unsigned(&tmp)[8])
      |                                                     ^
/media/path/to/opentrack/csv/csv.cpp:25:1: error: expected ‘,’ or ‘;’ before ‘{’ token
   25 | {
      | ^
/media/path/to/opentrack/csv/csv.cpp: In function ‘bool getGameData(int, unsigned char*, QString&)’:
/media/path/to/opentrack/csv/csv.cpp:95:61: error: ‘QLatin1StringView’ was not declared in this scope; did you mean ‘QLatin1String’?
   95 |                 else if (id_cstr.length() != 22 || do_scanf(QLatin1StringView(id_cstr), tmp) != 11)
      |                                                             ^~~~~~~~~~~~~~~~~
      |                                                             QLatin1String
make[2]: *** [csv/CMakeFiles/opentrack-csv.dir/build.make:80: csv/CMakeFiles/opentrack-csv.dir/csv.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1531: csv/CMakeFiles/opentrack-csv.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
Partially obfuscated, not that you knowing my username and drive name is a big issue, but eh.
I'll see if I can figure out and try the above fixes, it shouldn't be too hard to find the files,but that's where I am.
It's also worth mentioning that I'm on Mint, which seems to do some funny stuff with it's packages.  I didn't have anything to do with `libproc2` in my default repos, and I had to install `qt6-l10n-tools` and `qt6-tools-dev-tools` as additional dependencies.  Maybe it serves me right for straying off the beaten track that is Ubuntu, haha, but you'd think Noob-Friendly Mint wouldn't be too different.

**Comment by cyber199** [comment]
Poked around in the process-list file, unpatched, repatched, and removed the offending line, so in my unprofessional opinion it's not related.  Not sure what the griff is with the csv.cpp file, I'm barely literate in C++.  Would it be helpful to create a new issue, or keep my problem here?

**Comment by sthalik** [comment]
> csv.cpp:24:15: error: ‘QLatin1StringView’ was not declared in this scope

Add 

```
#include <QLatin1String>
```

as the first line of the file.

**Comment by cyber199** [comment]
Still getting `csv.cpp:25:15: error: ‘QLatin1StringView’ was not declared in this scope; did you mean ‘QLatin1String’?` as an error, even with `#include <QLatin1String>` as the very first line of the file `csv.cpp`

**Comment by sthalik** [comment]
What's your Qt version @cyber199?
