### ISSUE TITLE
Unknown game

### ISSUE THREAD

**Issue by enviksy** [opentrack/opentrack#1971]
So yesterday everything was working perfectly with freetrack 2.0 enhaced and today i went to fire up some ets2 and its not working and then i saw the Unknow game in the title so if anyone knows the solution please tell me ty in advance.

**Comment by sthalik** [comment]
Did you move opentrack's installation directory? Try starting opentrack first (in freetrack settings, with freetrack & npclient enabled), then ETS2.

**Comment by enviksy** [comment]
I solved it i need to launch beamng/farming sim 22 and then ets2 and it works
