### ISSUE TITLE
rc15 broke PT tracker

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#199]
I'm trying out the new RC.

Old program:

![image](https://cloud.githubusercontent.com/assets/529552/8850626/e392f9f6-3149-11e5-882f-986e7ff313e2.png)

![image](https://cloud.githubusercontent.com/assets/529552/8850630/e98bc752-3149-11e5-9ede-747f6f777974.png)

New program:

![image](https://cloud.githubusercontent.com/assets/529552/8850645/f996fc02-3149-11e5-8cfa-7954576b38f7.png)

![image](https://cloud.githubusercontent.com/assets/529552/8850647/fe410efa-3149-11e5-9464-a65515663004.png)

With the reference position of my head totally wrong in the new build, based on values which worked in the previous version, I'm unable to test headtracking because it's way off now and the rotation is all wrong. Calibrating it makes it only worse. Did something change with this?

**Comment by sthalik** [comment]
Please test it like so:

- put your model upside down
- wiggle it

Does it match what happened with old rc in the normal non-upside-down position?

**Comment by sthalik** [comment]
The issue is only for pitch. That's the part that changed in internal representation.

**Comment by sthalik** [comment]
Alternative you can switch 40 to -40 and 70 to -70 and it could help.

**Comment by MathijsG** [comment]
But the visual location of me (I think that's the purpose of that red cross?) is also totally different, and with rotation and translations it picks a wrong reference then.

I will try the above things asap.

**Comment by HMRMike** [comment]
Same here. I set up everything with the same values and curves as I used in RC14.
The new coordinates for calibrated model position seem very wrong, placing the point of origin somewhere on my throat. Large +TZ and +TY output when I pitch up. But barely any reaction (in any axis) when I pitch down.

Flipping the marker upside down and calibrating seemed to produce a more correct output, but I can't test the accuracy yet.

**Comment by MathijsG** [comment]
I can't test this properly upside down unfortunetaly, although it seems more correct upside down. The calibrating is just way off.

**Comment by MathijsG** [comment]
With the -70 and -40 trick it's working more okay. Will test further in-game.

**Comment by Daggett57** [comment]
This is happening to me too. I get yaw and roll interconnect and the auto calibrations gives wonky number like 820 mm for the y model offset. Inverting those two numbers seem to help a lot, if not fix it.

**Comment by sthalik** [comment]
I've reverted the change. In fact it was only needed for calibration, which was also removed, so it was reverted without a hassle.

Please confirm if rc15p1 works. Thanks!

**Comment by MathijsG** [comment]
Why did you kill calibrating by the way? How are people supposed to use Pointtracker without a form of calibration? It was working for me in previous builds?

**Comment by sthalik** [comment]
I didn't kill it. in rc15p1 it should work fine.

**Comment by sthalik** [comment]
Are you talking about camera calibration? The values in data files were all wrong. For instance focal length was too similar with 56/75. To do camera calibration I need more research and confirmation, rather than pushing the change on unsuspecting users.

**Comment by MathijsG** [comment]
Looks like it is working again. Calibration still puts the red crosshair on a different spot, but looks like it is working. Only problem with some yaw when I only move up and down. Will dive further into it. Overall very smooth.

**Comment by sthalik** [comment]
Calibration isn't absolute, i.e. it differs basing on exact sequence of data it receives.

Please report further issues if they arise.
