### ISSUE TITLE
keybindings aren't working on OSX

### ISSUE THREAD

**Issue by bodylinksystems** [opentrack/opentrack#203]
Bound the center and zero function to various keys and either they don't work or I cannot tell if they are working as there is no visual feedback there is anything happening.

Center key toggles the apple settings menu, but numbers do not reflect being centered and zeroed.

**Comment by sthalik** [comment]
Some keys may indeed not work. If you bind "Home" or "Page up" won't they not work either?

**Comment by sthalik** [comment]
We're working on this in #118

**Comment by sthalik** [comment]
That is, #118 will fix this issue implicitly.

**Comment by sthalik** [comment]
@bodylinksystems I have a working build for Mac, want to test before rc15?

**Comment by bodylinksystems** [comment]
happy to test, but this week is insanely busy.  might not be able to report back until the weekend.

**Comment by sthalik** [comment]
That's understanable. Here's a current build: https://www.dropbox.com/s/5iz6nfl0hhb97uv/opentrack-osx-2.3-rc15p1-44-g7c7f4d3.zip

**Comment by sthalik** [comment]
Arbitrary keys should work now also on OSX.
