### ISSUE TITLE
Trinus VR centering broken

### ISSUE THREAD

**Issue by Gpinchon** [opentrack/opentrack#206]
When using Trinus VR with Gamestream and Opentrack redirect, the axes keep interverting when attempting to center the view, pretty sure it's not Trinus VR's fault.
Tracker used : UDP Sender
Protocol used : freetrack 2.0 Enhanced
Filter : Accela

**Comment by sthalik** [comment]
I need more information.

**Comment by Gpinchon** [comment]
When inverting yaw and roll in output remap, setting pitch on roll and roll on pitch, then centering, the axes get messed up, pitch becomes roll and roll becomes a mix between pitch and yaw...

**Comment by sthalik** [comment]
What ranges of values for yaw pitch roll do you get before and after this happens?

**Comment by sthalik** [comment]
Closing abandoned
