### ISSUE TITLE
opening camera with PT tracker crashes

### ISSUE THREAD

**Issue by cazzoo** [opentrack/opentrack#207]
I recentrly installed RC15P1 and got issues while starting the tracking and having my PS3 eye cam set as default camera.
I get a popup windows that says me that the memory could not be read at instruction 0x6fcbd733 (If It could be usefull for you..).

I previously used RC9 with no issues.

**Comment by sthalik** [comment]
Is this the PT tracker? It had camera issues that were only fixed very recently. Confirm this build fixes the crash https://www.dropbox.com/s/6j9cegmujiqtlgp/opentrack-20150727_1.7z if it does, we need to release another public build.

**Comment by cazzoo** [comment]
Thanks for the feedback, I'll try this at lunch GMT+1 and will post results
on another message in this thread issue.

Le lun. 27 juil. 2015 04:12, Stanisław Halik <notifications@github.com> a
écrit :

**Comment by cazzoo** [comment]
Well I had some minutes to try this right now and unfortunately this recent build does not fix the issue.
The popup error is same with same memory address. :/

**Comment by sthalik** [comment]
Run this build https://www.dropbox.com/s/f7scrm5vfejuyry/opentrack-console-debug-20150728_1.7z

Get it to crash and send contents of the console window that pops up along with the UI. Paste the window image or paste the text.

**Comment by cazzoo** [comment]
Ok I finally get some time to spend on my PC, I downloaded the custom build you made and tried to run as I usually did.
Here is the ouput of the program : 
```
Loading "libopentrack-filter-accela.dll"
Loading "libopentrack-filter-ewma.dll"
Loading "libopentrack-filter-kalman.dll"
Loading "libopentrack-tracker-aruco.dll"
Loading "libopentrack-tracker-freepie-udp.dll"
Loading "libopentrack-tracker-hatire.dll"
Loading "libopentrack-tracker-ht.dll"
Loading "libopentrack-tracker-hydra.dll"
Loading "libopentrack-tracker-joystick.dll"
Loading "libopentrack-tracker-pt.dll"
Loading "libopentrack-tracker-rift.dll"
Loading "libopentrack-tracker-udp.dll"
Loading "libopentrack-proto-fgfs.dll"
Loading "libopentrack-proto-freetrack.dll"
Loading "libopentrack-proto-fsuipc.dll"
Loading "libopentrack-proto-simconnect.dll"
Loading "libopentrack-proto-udp.dll"
Loading "libopentrack-proto-vjoy.dll"
Loading "libopentrack-proto-win32-mouse.dll"
bundle + "opentrack-ui"
bundle + "proto-freetrack"
bundle + "HT-Tracker"
bundle + "Accela"
failed CoInitializeEx -2147417850
```

**Comment by sthalik** [comment]
You're using the HT tracker and not PT. HT has some issues at the moment that cause crashes for few people.

**Comment by sthalik** [comment]
HT fixed for rc16.

**Comment by cazzoo** [comment]
Nice! I'll check that out at the end of the day!
Thanks

2015-08-14 9:35 GMT+02:00 Stanisław Halik <notifications@github.com>:

> Closed #207 <https://github.com/opentrack/opentrack/issues/207>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentrack/opentrack/issues/207#event-382301509>.
>



-- 
Casimir BONNET.
Port. : +33 650 612 550
e-Mail : casimir.bonnet@gmail.com

**Comment by sthalik** [comment]
Note there hasn't been a binary release yet.

**Comment by sthalik** [comment]
Fix released.

**Comment by cazzoo** [comment]
Thanks for the feedback.
I'll test this out asap.
Thanks

Le ven. 21 août 2015 03:53, Stanisław Halik <notifications@github.com> a
écrit :
