### ISSUE TITLE
[Feature Request] Wiimote as tracking source

### ISSUE THREAD

**Issue by odivalq** [opentrack/opentrack#214]
It would be very handy if we could detect input from wiimote (and its motion+ gyro) and make use of it for headtracking, like in freePIE or GlovePIE, but with all the output options of Opentrack. Is it feasible?

**Comment by sthalik** [comment]
It is. Depends on how much usage it gets, though. It's not worth the time spent if there are just a few owners of the device.

**Comment by sthalik** [comment]
Response timeout, closing
