### ISSUE TITLE
Settings automatically saved and overwritten

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#219]
When you change a setting to your profile. And you quit the program, the changed setting is still in the profile, even if you reload the profile file manually. So it gets saved after quitting the program without a notice. This is unwanted behaviour in my opinion. Maybe adding a prompt to save or reject the settings?

While testing out the software I sometimes lose my specific settings this way.

**Comment by sthalik** [comment]
No, this is prelude to #179. The "save" button will go away, and profiles will be stored in a designated directory like "Documents/opentrack-2.3".

**Comment by MathijsG** [comment]
But how can you easily reject a change without manually undoing the change then?

**Comment by sthalik** [comment]
If you click "cancel" the change will be undone. As for the main software's UI, there's only tracker/filter/protocol selection there.

I don't think you need to keep a history of changes. I don't know of software that does that for its configuration. Maybe use git for your .ini files? Just a random suggestion.
