### ISSUE TITLE
64bit version

### ISSUE THREAD

**Issue by gigi137** [opentrack/opentrack#221]
Hi,
in a future there will be a 64bit version of this product?
X-plane 10 can run at 64 bit and it would be fantastic to make this plugin compatible.

Thanks
Luigi

**Comment by sthalik** [comment]
opentrack works with 64bit X-Plane.

**Comment by sthalik** [comment]
Just to be clear, the X-Plane plugin is used only on Linux and OSX. There a 64-bit version of opentrack is built. It's only Windows, but there's no X-Plane plugin needed there.

**Comment by bodylinksystems** [comment]
Sorry I haven't been able to test I have been very busy lately. I will try to run the latest and greatest this weekend (OSX and x-plane 64-bit) and report back here.
