### ISSUE TITLE
GNU GPL in opentrack project

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#228]
Blocked by #226.

**Comment by sthalik** [comment]
See 9322afafb94e4a0caffa9006ead6c19dd8f59848

Original commit at http://sourceforge.net/p/facetracknoir/codegit/commit_browser
The revision is 579d2f

@phOb what do you think?

**Comment by ph0b** [comment]
@sthalik that looks perfect to me. Thanks to you and Wim!

I'll be able to improve the RS tracker a bit.

We still need to ensure we're not combining GPL modules with other incompatible ones.

**Comment by sthalik** [comment]
No GPL modules remain though. Wim went over all of them.

**Comment by sthalik** [comment]
@ph0b maybe we can just disallow copyleft in-tree as policy or something.

**Comment by ph0b** [comment]
good. I've added [CONTRIBUTING.md](https://github.com/opentrack/opentrack/blob/unstable/CONTRIBUTING.md) to ensure this.

**Comment by sthalik** [comment]
:+1:

**Comment by sthalik** [comment]
@ph0b are you fine with potential LGPL dependencies in people's projects?

**Comment by ph0b** [comment]
@sthalik yes as long as there is no static builds including the LGPL software or modifications of the LGPL code.

**Comment by sthalik** [comment]
can you add the bit about lgpl static linking to docs? edit interface won't work on mobile.

**Comment by ph0b** [comment]
done.
