### ISSUE TITLE
[Feature] Make an official installer

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#229]
Now the program is evolving and becoming more and more polished with every release it may be is time for a regular installer so people can install this program officially the regular way like every other program.

**Comment by sthalik** [comment]
Definitely for 2.3 final we'll provide both an installer and an archive. We already have an app bundle for OSX though.

Personally I find bloated installers annoying, with updating metadata for a minute, installing MSVC CRT redist even though they're installed already, and so on. So this is a breath of fresh air, with stuff to extract wherever you want.

We're still kinda away from 2.3 point release, all blocker bugs need to be finished before that.

**Comment by sthalik** [comment]
We're good.
