### ISSUE TITLE
No input from XYZ

### ISSUE THREAD

**Issue by daltonv297** [opentrack/opentrack#232]
I'm using FreePIE on my android phone, and opentrack is only receiving yaw, pitch, and roll data.  Is this a problem, or does FreePIE not support XYZ output?

**Comment by sthalik** [comment]
There's no translation support in inertial trackers, sorry.

**Comment by AliDjango** [comment]
@sthalik is this still not possible?if it's not possible why i can see accelerometer and magnetic sensor info in debug?
can you explain?
