### ISSUE TITLE
Translation Compensation rotation offset

### ISSUE THREAD

**Issue by kissklas** [opentrack/opentrack#233]
Translation Compensation seem to use the wrong position as a pivot for rotation.It works when centered to zero. But moving again, and then rotating makes the issue reappear.

Could it be that it uses the zero position instead of the last known position, as pivot on one or more of the axes when compensation is enabled?

**Comment by sthalik** [comment]
It's meant to translate depending where rotation points to. I see no issue here, provide more details.

**Comment by kissklas** [comment]
Good evening, sthalik! 

Finally got around to making a recording with Translation compensation on and off. In these videos, I only rotate my head, and move back and forth.

Here is the one with compensation enabled. As you see when the head is moving away from centered position, the rotation pivot does not move with the head position, resulting in wide rotations around the centered position:
https://youtu.be/V_u099NOj_Y

Here is the same movements without translation compensation. All rotations seem correct, no matter where I move the head (The only problem of course, is that I don't have compensation when looking backwards.):
https://youtu.be/VMTh9E6Y9Gw

Hope this makes the issue clearer.

Best,
Klas

**Comment by kissklas** [comment]
Good evening, sthalik! 

Finally got around to making a recording with Translation compensation on and off. In these videos, I only rotate my head, and move back and forth.

Here is the one with compensation enabled. As you see when the head is moving away from centered position, the rotation pivot does not move with the head position, resulting in wide rotations around the centered position:
https://youtu.be/V_u099NOj_Y

Here is the same movements without translation compensation. All rotations seem correct, no matter where I move the head (The only problem of course, is that I don't have compensation when looking backwards.):
https://youtu.be/VMTh9E6Y9Gw

Hope this makes the issue clearer.
Best,

**Comment by MathijsG** [comment]
Same problem with Rise of Flight indeed.

**Comment by kissklas** [comment]
Looked into this a bit more, and I found this is only a problem using the config setup for older Track-IR models in IL-2: BoS.  This file is found here: "<GAME FOLDER>/data/startup.cfg": Due to problems with the newer trackers during beta, I set the "old_trackir =" to "1". Reverted it to "0" now, and Translation Compensation works like a charm.

And @MathijsG... 
I looked in the Rise of Flight folder as well (being based on the same engine). Found the file but no "old_trackir =". They have however updated RoF since IL-2: BoS came out, so you could try just adding it, like so:

[KEY = input]
	input_map = "input.map"
	mouse_plane_control = 0
	old_trackir = 0

I guess you could close this thread @sthalik, since it turned out to be a game issue.

Best,
Klas

**Comment by sthalik** [comment]
@kissklas thanks for the report. But if @MathijsG says Rise of Flight is broken too, we need to wait on this one.

**Comment by sthalik** [comment]
Is it that translation compensation is already applied with "old_trackir = 1"?

**Comment by kissklas** [comment]
I do not believe so. It was the lack of compensation that made me activate yours. If it is already applied from the games side with "old_trackir = 1", it does not seem to really work at all. I will double check this when I have time.

On a different note:
I did however notice a little bit of strange rotation this weekend while playing IL-2: BoS with "old_trackir = 0" and translation compensation on. There seemed to be a bit of offset, much like what I described with "old_trackir = 1". But on a very small scale. It seemed fine unless I looked over -90/+90 degrees in game and rotated my head vertically. Not sure if this is a result of bad calibration though.

I can do another video if I am able to replicate it after a calibration.

Best,
Klas

**Comment by kissklas** [comment]
There is definitively no Translation Compensation implemented in the old trackIR setting.

I was not able to replicate the issue I was having either. It was probably just the calibration then.

**Comment by sthalik** [comment]
@MathijsG are we fine?

**Comment by kissklas** [comment]
@sthalik unless he replies, I can probably check ROF later, if "old_trackir = 0" works.

**Comment by MathijsG** [comment]
I will check today. I didn't use the newest OpenTrack yet because it had some weird positioning, but I will try today.

Where do I need to put the old_trackir parameter? In settings of game or profile of Opentrack?

**Comment by kissklas** [comment]
Check RoF folder for "startup.cfg". Under "[KEY = input]" add the sentence like so:

[KEY = input]
input_map = "input.map"
mouse_plane_control = 0
old_trackir = 0

**Comment by MathijsG** [comment]
With that setting enabled I got no problems anymore. But it isn't very user friendly I think to let people alter settings? Why DOES it work without translation compensation and when you enable it (without editting the config) the rotation point is wrong.

**Comment by kissklas** [comment]
It is a setting that is standard in IL-2: Battle of Stalingrad, which is build from the same engine. Probably added updated trackIR support since that game came out a lot later than RoF. They have since pushed some of the changes made in IL-2 back to RoF and updated the engine. I guess this "hidden setting" is one of them. 

You could notify the developers, and ask them to set the old_trackir = 0 as default in RoF, as it fixes translation compensation issues.

**Comment by MathijsG** [comment]
I submitted a ticket to the Rise of Flight team. Will keep you guys updated.

**Comment by sthalik** [comment]
Don't, it breaks freetrack with = 0.

**Comment by MathijsG** [comment]
What do you mean? It is working perfectly now.

**Comment by kissklas** [comment]
On opentrack, yes. 

I think what sthalik means is that freetrack, another popular free headtracking software (which is no longer being developed I think?), does not play well with the "new" setting (old_trackir = 0).

**Comment by MathijsG** [comment]
But then the problem is in this software instead of in the game I think?

**Comment by kissklas** [comment]
There is no problem with Opentrack. I would say it is Freetrack and older TrackIR versions that are getting outdated, and that is creating compatibility issues. People are still using older software, and the game does not recognise what you use automatically. if they made the setting a tickbox in the UI, instead of hiding it in the config, that would probably be better. I wouldn't think that should be accommodated in Opentrack.

**Comment by sthalik** [comment]
@MathijsG freetrack's problem is in baseless legal threats against the software. Give them a break. Look up "natural point of view" in google.

Better for the game's authors to fix compensation than to default to obfuscated protocol. We support the obfuscated one because we have to, not because we want to.

**Comment by MathijsG** [comment]
I emailed the developers of Rise of Flight and they replied a bit annoyed. I don't think they will change anything.

**Comment by kissklas** [comment]
Oh dear. I did not know about any of this. Yes, better not go to tech support again, as certain people might be involved in this. The respect and gratitude I have for the work you do here just went up a few more notches. Keep it up.

**Comment by sthalik** [comment]
Thanks guys. Like @kissklas said let's leave implementors/game authors alone, too much heat is bad.

Since it seems to be all fine I'm marking resolved closed.

**Comment by MathijsG** [comment]
With RC19, which is working great though, I got this problem again. (I already editted the config of ROF to put in the line). Sometimes after centering it is gone. But it looks like something still is wrong.

**Comment by sthalik** [comment]
@MathijsG what is gone? Is opentrack forgetting settings?

**Comment by MathijsG** [comment]
I don't know, but I got the same rotation problem sometimes, while I already changed the config of RoF. Will investigate further when not ill.

**Comment by MathijsG** [comment]
This still is wrong here, even after changing the config. After I center again it's okay again.

Specs: PT headtracking,

![image](https://cloud.githubusercontent.com/assets/529552/10770769/5cac96e6-7ced-11e5-93ce-65c1d312c3b8.png)

**Comment by sthalik** [comment]
What's wrong? I don't have the game to check myself.

**Comment by MathijsG** [comment]
The same rotation problem as shown in the earlier video. You somehow rotate
around a point instead of rotating self.

Groeten,

Mathijs Groothuis
Op 28 okt. 2015 03:26 schreef "Stanisław Halik" <notifications@github.com>:
