### ISSUE TITLE
Center position 

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#235]
Probably the best build rc17P2 in the center position, but yet I feel as if after a long time will reduce the look of mine checking through the crossfire, the center is not effective helps only to again stop start.

**Comment by sthalik** [comment]
I don't understand. Please explain.

**Comment by petsild** [comment]
After some time 10min I don't have the opportunity to be centering the image of the hot keys properly on the center, effectively works only the new start-stop.
Head I try to still stick to the default location.
I can create a short video where it will be better explained.

Would it be possible to add a hot key on the function of the Start-Stop?

**Comment by sthalik** [comment]
You mean hotkeys don't work anymore?

**Comment by petsild** [comment]
The image of the octopus to stay slightly below even after pressing the centering.

**Comment by sthalik** [comment]
Adjust filter settings to lower deadzone.

**Comment by petsild** [comment]
I use this settings
http://img8.rajce.idnes.cz/d0801/4/4901/4901891_507dca2b7c43a1bacef8c830a77145ff/images/Accela.jpg

**Comment by MathijsG** [comment]
You are looking straight forward when pressing center?

**Comment by petsild** [comment]
After setting the deadzone to 0 with the centering behaves correctly thank you very much.

**Comment by sthalik** [comment]
@MathijsG it's not necessary.

**Comment by sthalik** [comment]
@petsild does the problem still exist? Are we done here?

**Comment by petsild** [comment]
Hi,
now I have tried the rc18 and centering responds quickly and accurately :D really great work.
