### ISSUE TITLE
implement two ways to center - relative and absolute

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#237]
Hi, I apologize in advance for the weird post. Friend on the rc18 has arisen the problem of the extreme positions, the movement of the octopus dodging into other positions. Has crookedly attached clip on the headset. The previous version rc14-17 functioned well without redoing the clip.
Rather I will add pictures.
![clip pozice](https://cloud.githubusercontent.com/assets/13926997/9832381/a34a0a62-5979-11e5-9d2b-bc58d4f4f2f0.JPG)
![lstrana](https://cloud.githubusercontent.com/assets/13926997/9832383/a7e9fd84-5979-11e5-845d-def37527856f.JPG)
![pstrana](https://cloud.githubusercontent.com/assets/13926997/9832401/00fedd54-597a-11e5-8b48-8d19ae5abdd6.JPG)

If there are leds on the clip positioned exactly there is no difference in the end positions between the rc17-18. Thank you for understanding and sorry for the post.

**Comment by sthalik** [comment]
This problem is related to centering only, right?

**Comment by petsild** [comment]
If looked left the picture went diagonally, look to the right of the good.

**Comment by sthalik** [comment]
Note to self: we need two centering methods, current as relative and previous as absolute.

**Comment by petsild** [comment]
The clip what was all the time diagonally and on the older OT the work, is now aligned exactly and there is no problem. The attached pictures are now history. Thank you very much for your support and I look forward to another OT. Pet
