### ISSUE TITLE
Unwanted bezier curve S-shape in mappings.

### ISSUE THREAD

**Issue by YellowOnion** [opentrack/opentrack#238]
I'm trying create a little dead zone, but there's a tiny "hump" near zero position, this is not just a visual bug, but easily seen while yawing/pitching in game as well.

I've repositioned a point to exagerate the effect in this picture: http://i.imgur.com/JQZJF0H.png

But even without any point near zero, it creates a 1-2px size hump like displayed here:

![image](https://cloud.githubusercontent.com/assets/364160/9958772/46787c0a-5e61-11e5-9d32-63fd86c38224.png)

**Comment by MathijsG** [comment]
Maybe something to change the curve strength between points? Now you can't make things lineair if you need.

**Comment by sthalik** [comment]
Add a fourth point, it interpolates better then.

**Comment by sthalik** [comment]
Actually, the bump is where your first point is. The function always passes the points exactly. I see no bug here.

**Comment by YellowOnion** [comment]
sthalik, I don't see it as a bug but I don't see this behaviour as intuitive and expected either, when x increases y should always increase, that's the expected behaviour for me.

for a comparison, Blender uses a selectable Linear, Bezier and Constant interpolation for its animation system, it also gives you access to the handles of the Bezier curves to further refine expected behaviour.

I've tried adding extra points but some way to control curve strength and adding hard corners would be nicer, actually I think having an alternative to this mapping UI where you just control 3 parameters deadzone, sensitivity curve would be a lot more intuitive and cover 99% of use cases.

**Comment by sthalik** [comment]
Monotonicity of the spline is one thing. Another is the derivative at given place between control points. For now there's not enough motivation to implement more interpolation method than Catmull-Rom that we're already using. But I'm leaving the issue open.

**Comment by sthalik** [comment]
I'm closing this until there are code contributions.
