### ISSUE TITLE
Shortcut keys don't work 2.3 rc18

### ISSUE THREAD

**Issue by mi-st** [opentrack/opentrack#244]
I bound some shortcuts to center and zero but when I press them  nothing happens.  Did I missed something ?  I tried different shortcuts without results.  The only way to center is stop/start tracking by clicking buttons in the UI. Running Opentrack as admin didn't help either.

**Comment by mi-st** [comment]
It is rc18 not rc13  sorry for mistake

**Comment by sthalik** [comment]
Confirm still broken in the test build - https://www.dropbox.com/s/avlzpywpx39o1r0/opentrack-test-20151002_1.7z

**Comment by sthalik** [comment]
@mi-st confirm in rc19

**Comment by mi-st** [comment]
it works thanks
