### ISSUE TITLE
Is there a magic trick to get OpenTrack to work in iRacing?

### ISSUE THREAD

**Issue by jasondilworth56** [opentrack/opentrack#246]
I hope someone can help. I installed OpenTrack today, and am using an IR clip and PS3 Eye. OpenTrack is registering perfectly well. I leave that running, open iracing.com and start a session from there. I then go to options to assign the 'look' commands, but the IR setup is seemingly not recognised. Is there something I'm doing wrong?

**Comment by ph0b** [comment]
you shouldn't have to do any configuration inside iRacing to get it to work.
Select the freetrack protocol and start opentrack, tracking will work while you're driving.

**Comment by sthalik** [comment]
I second that. If there are any problems with iracing and freetrack protocol, it needs investingating though.

**Comment by sthalik** [comment]
If it's still broken, try moving to "program files" or "c:/". Might be a filesystem permission issue.

**Comment by jasondilworth56** [comment]
Thanks for the replies guys. It turned out to be what I would call a bit of a bug. Within iRacing I had 'Look Left' and 'Look Right' bound to the left and right keys on my wheel. All the time that was the case, I couldn't use OpenTrack and I couldn't bind those actions to the yaw axis. 

To fix the problem, I had to bind both 'Look Left' and 'Look Right' to Space, which set them both to Unassigned instead. Once they were unassigned the tracking started working instantly.

**Comment by sthalik** [comment]
glad you sorted that out

**Comment by bodylinksystems** [comment]
this gives me hope for using this with ETS2

**Comment by sniperwolfpk5** [comment]
Well I played ETS2 with factracknoir. I think it should work with OpenTrack

**Comment by bodylinksystems** [comment]
I'll give it another shot
