### ISSUE TITLE
Mapping: Current value indicator goes beyond graph bounding rect on negative values

### ISSUE THREAD

**Issue by alterscape** [opentrack/opentrack#249]
In 2.3-rc18-42, when adjusting the mapping properties, if the value for the axis being mapped goes negative, the red "current value" indicator moves to the left and down below the (0,0) point of the graph. 
![2015-10-07 21_23_59-digital combat simulator](https://cloud.githubusercontent.com/assets/76178/10357686/c961757c-6d39-11e5-83f9-d0ad256bdd6b.png)

I think fixing this may be as simple to fix as taking the absolute value before updating the marker position in the MappingWidget. I couldn't find the relevant code, despite poking around in curve-config and friends.

**Comment by sthalik** [comment]
Thanks @alterscape fixed just in time for rc19.
