### ISSUE TITLE
Game Assetto corsa 1.3 64bit - opentrack not compatible

### ISSUE THREAD

**Issue by lcambia** [opentrack/opentrack#250]
I wanted to know if you have a 64-bit version for use with the game poretla Assetto Corsa (latest version 1.3 64-bit), I tested with version 2.3 of OpenTrack but unfortunately does not work

**Comment by sthalik** [comment]
@lcambia see https://github.com/opentrack/opentrack/issues/117#issuecomment-146772719

**Comment by sthalik** [comment]
@lcambia verify game supports the protocol you're using.

**Comment by frost555** [comment]
v1.3.4 works normally with opentrack.

**Comment by sthalik** [comment]
@lcambia use freetrack protocol most likely.
