### ISSUE TITLE
Hot key to Start/Stop

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#252]
Hi, great work, I commend the last rc Opentrack are great, the control works absolutely excellently in simulators such as Rise of Flight and DCS World. I asked if it was possible in the future to select the hot key to Start/stop completely independently on the choice of the set of profiles?
Thank you for the perfect product hi. Pet

**Comment by sthalik** [comment]
There's "game detection" in options, isn't that enough?

**Comment by sthalik** [comment]
Technically we could do that shortcut now, following recent changes shortcuts outside of tracking work. But what for?

**Comment by petsild** [comment]
Functions suitable to be a longer pause camera stop, without having to switch between windows and the crease so the mouse on the main screen of the OT.

**Comment by MathijsG** [comment]
Isn't this suitable to use a key for zero? Then you have the same as not tracking?

**Comment by sthalik** [comment]
I understand that tracking uses resources, and blocks the camera while in progress.

**Comment by Sovereign-Man** [comment]
I would welcome a start/stop key, OpenTrack stops working quite often in Elite:D.
It doesn't crash per se, it either stops reporting raw data or stops sending that data to Elite.
I'm using rc19p2 and an EDTracker2

**Comment by sthalik** [comment]
There was a tracking data freeze bug fixed in rc19p3

**Comment by Sovereign-Man** [comment]
That was a quick reply :) will try p3 now.

**Comment by sthalik** [comment]
How many of you guys want it, other than people already in the thread? Drop a "+1" or like that.

**Comment by petsild** [comment]
The other two friends of Leon and Joska thank you.

**Comment by severgun** [comment]
+1 
Why not? I think that this feature just copy and paste of code from zeroing hotkey to start/stop.
Isn't it?

**Comment by sthalik** [comment]
@severgun no, we have different subsystem listening for stuff during tracking. That subsystem doesn't exist when tracking's stopped. See latest changes.

Who's feeling adventurous? Build - https://db.tt/vVs03dfD

**Comment by petsild** [comment]
Such a function there was missing, great work thank you very much hello. Pet

**Comment by sthalik** [comment]
We're done with the functionality. Report regressions in #267.
