### ISSUE TITLE
Elite Dangerous crash when opentrack 2.3 rc 19 is runned

### ISSUE THREAD

**Issue by marfarin** [opentrack/opentrack#256]
Elite Dangerous 1.4 crashed when load world. I install opentrack using installer with default path.

**Comment by sthalik** [comment]
Can anyone else reproduce?

**Comment by Oakshios** [comment]
I can not reproduce this issue.  Playing Elite Dangerous 1.4 and opentrack 2.3 rc 19.  I have another issue I will search for or post.

**Comment by Oakshios** [comment]
MarFarina is it possible for you to verify game files, in Steam if you use it, and the launcher itself?

**Comment by sthalik** [comment]
Lack of response from submitter, closing
