### ISSUE TITLE
right-hand Ctrl, Alt, and Shift keys cannot be bound. v2.3-rc19

### ISSUE THREAD

**Issue by SgtGrumbles** [opentrack/opentrack#257]
When binding Global Shortcuts for Center, Toggle, or Zero, I cannot use the Control, Alt, or Shift keys on the right-hand side of the keyboard.  The left side versions work.

e.g. if I try to bind for Center, and hit (right) Ctrl + P, it'll be set to just "P".  Similarly, if I use the left Control + P, the bind will correctly read "Ctrl+P", but only the left Control + P will Center; hitting right Control + P will do nothing.

This is on a (fairly standard) keyboard with a US layout.

EDIT: not really related, but more just a note: I also cannot bind the "Print Screen," "Scroll Lock," or "Pause/Break" keys.

**Comment by SgtGrumbles** [comment]
Holy schnikes that was quick!  Thanks.

**Comment by sthalik** [comment]
@SgtGrumbles use https://www.dropbox.com/s/ptjxuqo5l6xfyvw/opentrack-2.3-rc19p1-12-g86418fa.zip?dl=0

**Comment by SgtGrumbles** [comment]
Tested and verified working.  Thanks again!
