### ISSUE TITLE
Center and toggle key binds not working in 2.3RC19p2

### ISSUE THREAD

**Issue by DerangedPineapple** [opentrack/opentrack#258]
Center and toggle key binds won't work at all if they both are bound to same key i.e. I had both Center and Toggle bound to Return (keyboard Enter) in 2.3RC18 and after updating to 2.3RC19p2 those key binds wont work anymore when bound to same key (doesn't matter which key).

EDIT: Zero seems to work just like Center and Toggle bound together to same key. Previously I couldn't get Zero to function like that though.

**Comment by DerangedPineapple** [comment]
Update as I Forgot to mention OS and tracker in use.

I have Windows 10 upgraded from Win7 and tracking device is EDTracker configured in opentrack as joystick input and outputting it TrackIR and Freetrack and running opentrack as administrator.

There is small difference how Zero works comparing to Center and Toggle functioning together. I would rather use Center+Toggle combination as after releasing Toggle tracker would be centered also, with Zero opentrack keeps tracking head movement and this can lead in my case to funny situations.

**Comment by sthalik** [comment]
This is an unusual use case but there you have it now.

**Comment by DerangedPineapple** [comment]
Thank you. It's very useful feature when you need to aim down to sight in DayZ/Arma2-3 and center  and toggle your head tracking at the same time so the view won't drift accidentally when turning head.
