### ISSUE TITLE
Can't bind the center command to my numeric pad...

### ISSUE THREAD

**Issue by Hardcard** [opentrack/opentrack#259]
Hi all.
I'm using Opentrack 2.3 rc19p1 and today I noticed that I can't bind the "center" command to any of my numeric pad keys...This is weird and unfortunate, I'm used to bind the "center" command to the "5" key of the numeric pad, it has always worked in Facetracknoir and Freetrack, but it doesn't seem to work in Opentrack, sadly. 
I'm guessing there is some kind of driver incompatibility...
Am I the only one having this issue?

**Comment by sthalik** [comment]
Qt has no constants for numpad numbers. I can alias them to normal numbers at best.

**Comment by sthalik** [comment]
Note: they aren't aliases, use a "Num" modifier that works similar to shift or ctrl.
