### ISSUE TITLE
UDP Protocol

### ISSUE THREAD

**Issue by hrobertson** [opentrack/opentrack#26]
I've written an Android app to send orientation data via UDP but Opentrack doesn't appear to receive/understand it. The raw value displays remain at 0.

This is one of the UDP packets:

```
bcee7b774d5b18e2c29b015208004500004c000040004011b6aac0a8016ac0a8013c891e15ae00389c5900000000000000000000000000000000000000000000000040600000000000003ff0000000000000c010000000000000
```

The data being the last 48 bytes:

```
00:00:00:00:00:00:00:00
00:00:00:00:00:00:00:00
00:00:00:00:00:00:00:00
40:60:00:00:00:00:00:00
3f:f0:00:00:00:00:00:00
c0:10:00:00:00:00:00:00
```

The first 3 are 0 as I'm not using translation, only rotation.
The three numbers should be 128, 1 and -4.
These are IEEE doubles.

Am I doing something wrong or is this a bug in Opentrack?
Thanks

**Comment by Su33ke** [comment]
use the reverse order of bytes

**Comment by sthalik** [comment]
@Su33ke I thought IEEE floats are always little-endian
