### ISSUE TITLE
opentrack 2.3 rc19p3 - Aruco Axis are broken!

### ISSUE THREAD

**Issue by JoeSchr** [opentrack/opentrack#262]
Just tried the aruco tracker, came upon this bug: 
- Pitch gets translated as yaw, yaw gets translated as pitch. 

If I just go into option and map yaw to pitch and vice versa, everything works as expect. Kinda weird though.

**Comment by sthalik** [comment]
What's your roll raw value?

**Comment by JoeSchr** [comment]
I don't quite understand your question. or what data you require. generally roll seem to act fine. 

settings are: 
- yaw -> pitch [X] invert
- pitch -> yaw [ ] invert

![options](https://cloud.githubusercontent.com/assets/8218910/10915016/3092f894-8255-11e5-8636-443d9310ffa5.png)

does this screenshot help? 
![roll](https://cloud.githubusercontent.com/assets/8218910/10914914/bc962bdc-8254-11e5-80e0-60616dd71f08.png)

this are the current settings:

**Comment by sthalik** [comment]
Yaw and pitch are swapped since your model is rotated by 90 degrees. It shouldn't say roll: 86 by any means.

**Comment by JoeSchr** [comment]
Thx, that really did the trick. Had to roate it 90° ccw. 

Maybe this should be advised in the wiki (because I printed it with the same orientation as linked here: https://raw.githubusercontent.com/opentrack/opentrack/unstable/contrib/aruco/test3.jpg )

**Comment by sthalik** [comment]
> Maybe this should be advised in the wiki

If it really isn't obvious that the marker has to be rotated -- wiki is editable by everyone.

**Comment by JoeSchr** [comment]
not obvious, edited wiki! :)
