### ISSUE TITLE
HT-FACETRACK Don't work

### ISSUE THREAD

**Issue by guajardo** [opentrack/opentrack#266]
Hello, i have a problem whit HT-FACETRACK when i click on start i get the this error:

Runtime error!
Program:c:/program files/opentrack/opentrack.exe
this application has requested the runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

Im using windows 10
and opentrack 2.3-rc20

I try to reinstall the program, reinstall Microsoft Visual C++ 2010 Redistributable  and don't work.

Other methods for track work :(

Thanks

**Comment by sthalik** [comment]
Duplicate. The issue is known, see https://github.com/opentrack/opentrack/issues/139#issuecomment-153550235 and https://github.com/opentrack/opentrack/issues/197
