### ISSUE TITLE
Qt5 needed?

### ISSUE THREAD

**Issue by flyingfisch** [opentrack/opentrack#27]
`$ cmake ./
CMake Error at CMakeLists.txt:117 (find_package):
  Could not find module FindQt5.cmake or a configuration file for package
  Qt5.

  Adjust CMAKE_MODULE_PATH to find FindQt5.cmake or set Qt5_DIR to the
  directory containing a CMake configuration file for Qt5.  The file will
  have one of the following names:

```
Qt5Config.cmake
qt5-config.cmake
```

CMake Error at CMakeLists.txt:118 (cmake_policy):
  Policy "CMP0020" is not known to this version of CMake.

CMake Error at CMakeLists.txt:197 (QT5_WRAP_UI):
  Unknown CMake command "QT5_WRAP_UI".
Call Stack (most recent call first):
  CMakeLists.txt:221 (opentrack_module)

-- Configuring incomplete, errors occurred!`

Do I really need Qt5? It's not even in the default ubuntu repos...

**Comment by cossacksman** [comment]
I just installed qt5-default and qt5-doc, available from the apt-get repositories.

**Comment by sthalik** [comment]
Not enough, need headers and .so as well.
