### ISSUE TITLE
OSX - EDTracker Integration

### ISSUE THREAD

**Issue by ElEsido** [opentrack/opentrack#270]
Hi!

Have been using opentrack on WIN for about a year now and with to thank you for all the work you have done!

In OSX I am unable to pull EDTracker input into opentrack - the Joystick option that is present in windows is not there. Whuat would be required to include this? Is there any way I can help? (I am not a programmer, but I could help testing). 

Best
ElEsido

**Comment by sthalik** [comment]
There's no joystick input tracker on OSX. It requires Objective C++ code.

**Comment by sthalik** [comment]
you can submit code or wait long for me to write it.

**Comment by sthalik** [comment]
It's a subset of #234. Closing this one. It's as simple as using QGamepad.
