### ISSUE TITLE
OT 2.3 RC21 Crippling System Interupts 

### ISSUE THREAD

**Issue by 0ddBall** [opentrack/opentrack#272]
I have revered back to RC20 and issue does not appear there. When tracking and playing war thunder, system interrupts run excessively and kill frame, ping and the system in general becomes unresponsive but does not crash.

[OpenTrackBugReport.txt](https://github.com/opentrack/opentrack/files/46289/OpenTrackBugReport.txt)

**Comment by sthalik** [comment]
What system interrupts? Are you talking about page faults?

What tracker are you using?

**Comment by 0ddBall** [comment]
System Interrupts in my brain, please disregard

**Comment by sthalik** [comment]
@0ddBall you might mean the multimedia timer. opentrack sets OS scheduler Hz to 1000 during tracking using timeBeginPeriod and restores it back to 100 once it's done. It shouldn't have any negative effects on modern PCs. My 486 Geode runs on 500 Hz permanently without issues.
