### ISSUE TITLE
Dynamic pose resolution??

### ISSUE THREAD

**Issue by watermanpc** [opentrack/opentrack#302]
Hi again guys...I cant find a definitive answer to what exactly this option does???...also the dynamic pose timeout is a mistery for me...I cant see any difference with it enabled nor with any value I set for the timeout...I have them enabled and timeout at 25ms right now...any help here??

**Comment by Len62** [comment]
I'm still in the dark on this one also. Try checking the closed issues, I seem to remember a post in there that discussed dynamic pose resolution.

**Comment by sthalik** [comment]
@watermanpc see https://github.com/opentrack/opentrack/issues/289#issuecomment-171885479
