### ISSUE TITLE
dedication of 2.3 branch 

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#304]
my beloved Cat died. from the next binary onward for the future releases, an about page will feature a dedication and photos of Him. 

I'll leave the issue open as a reminder until the dedication is included in a release.

**Comment by Len62** [comment]
So sorry for your loss.

**Comment by MathijsG** [comment]
I'm also sorry for you. It's always sad to lose a pet.

**Comment by sthalik** [comment]
Thanks you two.

It's done.
