### ISSUE TITLE
multiple protocols at once support

### ISSUE THREAD

**Issue by Pulstar85** [opentrack/opentrack#305]
First of all thank you for your effort into this great application, secondly I have been trying to see if I can play non-TrackIR/FT games using the UDP client, especially for walking simulators. Is there a semi-ideal way of configuring mouse emulation to enable effects similar to Arma and Sir You're Being Hunted? However hard I try there's a lot of camera compensation to do to make it an enjoyable experience... And to add further: Is it possible to consider mapping the roll function to keys (e.g. E and Q) in case said game supported linear leaning?

**Comment by sthalik** [comment]
We're already doing the best we can for mouse support. Maybe linear mapping can help you.

We could have a "snapview" protocol at some point that binds threshold values to keys. But we don't have multiple-protocol support yet. Once multi-tracker support is in-tree I'll see what can be done about that.

**Comment by Pulstar85** [comment]
That sounds encouraging, cheers. :)

**Comment by sthalik** [comment]
Actually we already have game detection support. Duplicate a single profile and assign it with different protocols, each connected to game detection.
