### ISSUE TITLE
Two tracking sources - 3LED + Phone Tracking

### ISSUE THREAD

**Issue by Coren4** [opentrack/opentrack#306]
Hello
Is there any chance to use two tracking sources?(some time ago there was function like that in facetracknoir) Currently i'm using 3led set on my headphones, for over a year.

But there is problem, when we lose track on one of the led's...saddly it happens to me quite often.
Today i read about phone tracking in opentrack and i thought that maybe there is any way to get combined tracking from 3LED set + phone tracking to prevent malfunctions(for example loosing LED fix), for better precision, and overal performance.

**Comment by sthalik** [comment]
We won't "fuse" two trackers for the foreseeable future. It's too niche an idea, also trackers return different values for the same pose.

It's already planned to merge rotation/translation data from different trackers' values, see #171.
