### ISSUE TITLE
Compiling on 64 bit Linux

### ISSUE THREAD

**Issue by Atrixium** [opentrack/opentrack#307]
Compiling this on my 64 bit system (Mint 17.1) is a nightmare, I'm going to give this a try in a 32 bit virtual, are you compiling this in a 32 bit environment, or have you setup a 64 bit system to compile this? If you have setup a 64 bit environment for compiling this, could post some pointers?

The core application doesn't seem to be too much trouble, I was able to get that to compile and run without too much trouble, but I need the Freetrack protocol for my application so as soon as I added my wine folder, things just got way out of hand, finally ending in an error stating "Relocatable linking with relocations from format elf64-x86-64 to format elf32-i386 is not supported"

**Comment by sthalik** [comment]
Wine games are supported through a separate 32-bit executable. You need multilib stuff, including libstdc++ for 32-bit. Compiler will spit out the library names you're missing for `-m32`.
