### ISSUE TITLE
Auto-recentering issue when holding position

### ISSUE THREAD

**Issue by libertosurf** [opentrack/opentrack#309]
Whenever I'm using OpenTrack with my smartphone (Lumia 920 ; using UDP receiver config on my PC, and using OpenTrack app on my smartphone with Gyroscope mode.), it auto-centers itself if I look at a particular direction for more than 1 second.
For instance: I turn my head 20° left, it will go 20° left. However, if I hold that position for more than a second, it will auto-center again (so now if I put my head straight forward again, I will be 20° RIGHT, since the new center is now 20° left, if that makes sense).

When I look at the octopuss, it drifts slowly from 20° left to 0° (= facing me).

How can I fix that?

**Comment by sthalik** [comment]
That's unfortunately a device issue. Nothing can be done on freepie's or opentrack's part.
