### ISSUE TITLE
Tobii EyeX eye tracking support

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#310]
There's an SDK at <http://developer.tobii.com/>

For eye tracking we need both "accumulative" and "fov extension" methods.

**Comment by sthalik** [comment]
Status update. I have the hardware. My asmedia usb 3.0 controller doesn't have enough bandwidth. A friend has a proper controller and is willing to help. It's going to take more time than I thought previously.

**Comment by sthalik** [comment]
Cancelled due to obsolete hardware and an API change.

**Comment by thor** [comment]
Would it be relevant or interesting to create a new issue for the Tobii EyeTracker 4C and 5?

**Comment by sthalik** [comment]
See #1037. There's no copyright information (illegal for me to include it), and it hasn't been tested by a third party.
