### ISSUE TITLE
The Z axis at the same time a Zoom function

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#313]
Hello,
colleagues come to such a super performance enhancer, implement on the end of the axis From the border for the zoom. All of the simulators to control the zoom but it goes only to the button or assign a physical axis. A lot of pilots would be such a specialty welcomed right in Opetrack. Because I am not a programmer I have no idea if it can be or how much modification of the code difficult. Please view at such a function, thank you very much I wish you a nice day hi. Pet

![zoom ot](https://cloud.githubusercontent.com/assets/13926997/13004181/478493ea-d17a-11e5-8c0f-5b19853241cd.jpg)

**Comment by sthalik** [comment]
Some simulators have assignable zoom and cockpit movement functionality. However from the freetrack protocol's side we can't affect that. Only the sim can do that.
