### ISSUE TITLE
can't open camera on some configurations

### ISSUE THREAD

**Issue by RoarGi** [opentrack/opentrack#314]
Hi everybody! I hope someone will help me with my issue.

Opentrack  running on Windows 7(without any service pack) doesn't start PS3 Eye when I push start button. In "Tracker" optoins PS3 Eye selected, but it just don't start.
Tried to fix this by using different combinations of versions.
PS3 Eye drivers was installed:
CL-Eye-Driver-4.0.2.1017
CL-Eye-Driver-5.0.1.0218
CL-Eye-Driver-5.3.0.0341
Opentrack versions:
opentrack-2.3-rc19p3-win32
opentrack-2.3-rc21p6-win32
opentrack-2.3-rc21p8-win32
opentrack-2.3-rc4
and maybe some of unstable versions.

CL-Test, Skype and FreeTrack 2.2 work well.

Thank you in advance for your response.

**Comment by Len62** [comment]
Are you running Opentrack as an Administrator ? If not, try that. I don't have any problems with my PS3 eye and Opentrack. I'm on windows 10 but that should not matter.

**Comment by RoarGi** [comment]
Len62, thank you for your answer. I tried that. No result.
Looks like it's very rare bug and may be related to my system because i cannot find any problems like mine in the internet.

**Comment by sthalik** [comment]
Try replug the camera into a different USB port. The current port is fine, just that changing the port makes windows do some things.

**Comment by RoarGi** [comment]
Changed some ports USB 2.0 and USB 3.0. No effect.
Also, when I try to open Camera settings dialog in Tracker options nothing happens. Looks like opentrack cannot access camera driver or something.

**Comment by MathijsG** [comment]
Maybe try to upgrade to service pack 1? Any particular reason why you stayed with 7 without service pack 1 anyway?

**Comment by alterscape** [comment]
Do you have a driver for the PS3 Eye camera installed? I know it's a basic thing, but in case you aren't aware: the PS3 Eye camera doesn't work out of the box with Windows, you need a driver (Code Labs' is the one most people use -- he's charging $5 or some other nominal amount now).

**Comment by RoarGi** [comment]
MathijsG, maybe I should. I'll write here in any case when I get updated.
alterscape, sure. In OP I wrote 3 versions of driver I tried.

Thanks for your attention to my problem. I'll inform you if something change.

**Comment by sthalik** [comment]
Are you using any antivirus software? Try disabling it completely entirely.

**Comment by Archibas** [comment]
I have Opentrack does not work with PS3 Eye , too.

**Comment by sthalik** [comment]
Do you have any antivirus software running?

**Comment by sthalik** [comment]
@Archibas  Do you have any antivirus software running? Also what Windows version?

**Comment by Archibas** [comment]
Yes , I turned off anti-virus. Windows 7 64 
maximum. It did not help.

**Comment by Archibas** [comment]
I tried to connect to FreeTrack camera works .

**Comment by RoarGi** [comment]
@Archibas , I have same problem. Tried switching off antivirus software but no effect.
FreeTrack and FaceTrackNoIR works fine.
Interesting thing that when I try to capture video with Sony Vegas it cannot connect PS3 Eye too.

**Comment by Archibas** [comment]
Yes, the only problem with opentrask. It's a shame.

**Comment by Archibas** [comment]
Да   у меня Sony Vegas it cannot connect PS3 Eye too.

**Comment by Archibas** [comment]
With only two people with the same problem ?

**Comment by Len62** [comment]
Since Sony Vegas cannot connect either I would assume it has to be some other issue then with Opentrack itself. This is a stumper for sure. Maybe an issue with Windows 7?

**Comment by Archibas** [comment]
Maybe. Even likely . But that hinders normal operation.

**Comment by clovenlife** [comment]
I am also have this issue. Opentrack appears to connect to camera but raw data is black. I have no access to camera settings sliders. It opens other cameras and reads fine. PS3 camera works with other software such as skype.

**Comment by sthalik** [comment]
Change USB port.

**Comment by clovenlife** [comment]
changed usb port, uninstalled drivers, reinstalled drivers, updated opentrack, tried previous versions of opentrack. Opentrack had worked flawlessly for months before this new issue.

**Comment by Archibas** [comment]
Again it began. Installed WIN 10 Opentrask worked yesterday. Today, I stopped working. No black window capture. All porvtorilos as in windows 7. No public program is not installed.

**Comment by sthalik** [comment]
Is it broken with the exact same opentrack version you used, or did the problem start occuring in a new version only?

**Comment by clovenlife** [comment]
I should add, I've worked around this issue by using accessing the ps eye camera indirectly through manycam software's virtual webcam

**Comment by Archibas** [comment]
I confirm that after installing ManyCam opentrack started working .

**Comment by sthalik** [comment]
I can't help you guys. It works for thousands of users. Furthermore, details such as DirectShow and codecs are brittle things just asking to break at any time.

If you can provide a real solution, please do. I'll keep the issue open for the time being.

**Comment by Archibas** [comment]
The problem observed in the new and old versions . opentrack-2.3-rc21p11, opentrack-2.3-rc21p10-win32. But I start with opentrack-2.3-rc21p11. It is strange but the problem persists as the windows 7 and the windows 10 .

**Comment by sthalik** [comment]
Can you reproduce with opentrack 2.2?

There are some changes to the build environment back-and-forth between rc's but shouldn't be the cause.

**Comment by Archibas** [comment]
Yes, but I try for the evening . Maybe you can collect logs of work?

**Comment by Archibas** [comment]
opentrack I started working after installing ManyCam . ManyCam run but do not just install it all worked.

**Comment by Archibas** [comment]
I try to remove ManyCam. Let's see what happens.

**Comment by Archibas** [comment]
Yes, after the removal of ManyCam opentrack stopped working .

**Comment by sthalik** [comment]
It can be a bug in opentrack, but the way we open the camera is very common.

This bit of code in the external library is very complex, due to innate complexity of video input handling in Windows in general.

It's most probable that it's a problem with your system configuration, e.g. codecs. I've been unable to reproduce that on a fresh install of Windows 10, 8.1 and so forth. Only K-Lite codec pack Mega was installed.

**Comment by sthalik** [comment]
I can only help given technical basis of what we're doing wrong. Code is always welcome.

**Comment by clovenlife** [comment]
Thank you for mentioning codecs. I had installed the SAF codec pack to fix an issue with my PVR system. I uninstalled the codec pack and opentrack now functions as intended.

**Comment by sthalik** [comment]
@clovenlife this is important information, thanks for sharing that.

My personal recommendation: install K-Lite codec pack biggest version on fresh Windows and don't touch codecs ever again at all. Then they won't break.

**Comment by RoarGi** [comment]
Hi everyone! My problem was solved by installing ManyCam! Thank you!

**Comment by sthalik** [comment]
That's most likely a codec problem, but it's good that it works with for you with a workaround at least.
