### ISSUE TITLE
vJoy 2 (from sourceforge) support?

### ISSUE THREAD

**Issue by kromit** [opentrack/opentrack#319]
I've seen #40 so I guess it can work but was dismissed... why?

vJoy 2.x from sourceforge has much wider support and active development than Headsofts VJoy 1.2

Widely used tools like [UJR](http://evilc.com/joomla/articles/9-code/autohotkey/1-ujr-universal-joystick-remapper)  and [UCR](https://github.com/evilC/UCR) rely on vJoy 2.x.

The problem is that VJoy 1.2 and vJoy 2.x can not be installed on the same machine so the users have to choose between opentrack and UCR/UJR.

Since controls are much more important than head tracking, it makes opentrack support for VJoy 1.2 completelly unusable.

**Comment by sthalik** [comment]
I'd like to replace the proprietary vJoy protocol support with this opensource project with the same functionality <<https://github.com/shauleiz/vJoy>>. Any objections?

**Comment by kromit** [comment]
Is this a fork of the SF version or a working copy? I would be happy to see the project moving from SF to GitHub

**Comment by mirh** [comment]
They are indeed developing on github (just try to press code [here](https://sourceforge.net/projects/vjoystick/)). 
They still use SF to provide binaries, forums and website then.

**Comment by sthalik** [comment]
A module's been implemented and replaces headsoft vjoy.
