### ISSUE TITLE
PT tracker crashes on tracking start

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#320]
Happens rarely but consistently.

First noticed on trackhat opentrack but regular opentrack has reports too.

@soulmaril says it depends on gain/exposure settings so the problem could be in the point extractor component.

**Comment by SoulMaril** [comment]
Could be a windows security issue accesing the cl-eye driver from pointtracker. A better practice will be  to run OpenTrack as administrator.

**Comment by sthalik** [comment]
See if opentrack-2.3 rc21p9 fixes.

**Comment by sthalik** [comment]
We're good.
