### ISSUE TITLE
Latest P9 interrupts the movement of

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#321]
Hi,
when testing the latest p9 after a while interrupts the movement and the view will remain on the basic screen, while the squid responds all the time. Opentrack as that will lose the link with the controlled program. The previous p8 worked still well. I have no idea why this is happening. Thank you for the response hi. Pet

**Comment by sthalik** [comment]
Provide more info, I need some context.

If this is related to PT, does p10 fix it?

**Comment by petsild** [comment]
In p10 is fine thank you.
