### ISSUE TITLE
QtStandardPaths, QtPluginLoader and GNUInstallDirs support

### ISSUE THREAD

**Issue by reavertm** [opentrack/opentrack#322]
Please consider switching to QtStandardPaths: http://doc.qt.io/qt-5/qstandardpaths.html as it handles all kinds of OSes nicely.

Also QtPluginLoader: http://doc.qt.io/qt-5/qpluginloader.html could be used to replace now custom dlopen/QLibrary code to support standard plugin directories.

After that, Apple/Linux opentrack would be as easy-to-set-up-and-run as Windows.

Using GNUInstallDirs:https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html is also recommended (so that distro packagers like myself don't need to get out of the way to package opentrack) and I could submit patches for that once standard paths are supported by binary itself (as now it expects specific directory layout, namely hardcoded QCoreApplication::applicationDirPath() which makes it a deal-breaker for packaging).

**Comment by sthalik** [comment]
Change the install prefix to `/opt/opentrack/libexec/opentrack` or `/usr/local/libexec/opentrack`.

Then, create a shell script in `bin/` with the equivalent of `exec "$(dirname "$0")/../libexec/opentrack/opentrack.bin "$@"`

Also note that Linux isn't officially supported. Support exists only for developer convenience and to increase portability.

**Comment by sthalik** [comment]
Furthermore, using Qt library wrappers rather than `dlopen(3)` causes symbol conflicts between plugins and we have plenty of these. For a long time this was the reason opentrack wouldn't work on Unix sytems with don't have implicit equivalent of `RTLD_DEEPBIND` as on Windows.

**Comment by sthalik** [comment]
Closing WONTFIX

**Comment by reavertm** [comment]
Using QtStandardPaths would increase portability all around, but hey...

**Comment by sthalik** [comment]
You can conditionalize `cmake` install() to use libexec/opentrack and copy a shell script with `@CMAKE_INSTALL_DIR@/libexec/opentrack`. I'll review any patch like that.
