### ISSUE TITLE
can't auto save camera settings 

### ISSUE THREAD

**Issue by liuxyc** [opentrack/opentrack#324]
i need to adjust the camera settings every time when start the software.

version: opentrack-2.3-rc21p9

**Comment by MathijsG** [comment]
Can you provide some more details?

What Camera, what driver version? Which operating system?

**Comment by liuxyc** [comment]
i'm using win10-x64, my camera/driver info:
![image](https://cloud.githubusercontent.com/assets/3349675/13657354/a3f7ba5a-e6a9-11e5-8b4c-0e54b2f4b646.png)

**Comment by sthalik** [comment]
opentrack only pops up the camera dialog. Saving is the system's business. There's nothing the opentrack project can do about the problem.

**Comment by sthalik** [comment]
Edit I have to do the same with a generic camera driver. Camera functions are delegated to opencv which has other problems like not opening the PS3 Eye dialog properly.

I'd like to help but DirectShow graph is a complex thing to construct and I've never had any experience with it.

For now please use other program like Skype to open camera settings, it's known to do it the right way.

**Comment by liuxyc** [comment]
thanks sthalik for analyzing this issue, i use freetrack setup the camera and the settings saved.

**Comment by sthalik** [comment]
@liuxyc We've now made changes to opencv in order to invoke the dialog properly.

You can retry using newest rc49, maybe it'll work.

**Comment by sthalik** [comment]
There's nothing I can do unless someone else contributes working code.
