### ISSUE TITLE
TX + Yaw - weird output

### ISSUE THREAD

**Issue by Coren4** [opentrack/opentrack#326]
I have some kind of problem, where i can't identify reason in Arma3.

When i move on X axis to left everything is fine.
When i yaw left everything is fine.

When i move on X(to left side) and Yaw to left(moving head out of helicopter and looking back) - X output get inverted - it is like i yaw to left, but lean to center of helicpoter.

Any idea what could be a reason?

**Comment by Len62** [comment]
Try playing with these options.
![options](https://cloud.githubusercontent.com/assets/10486813/13728726/c51ce250-e8f7-11e5-8ea9-a375b889145d.PNG)

**Comment by Coren4** [comment]
You are my hero, thank you:)
