### ISSUE TITLE
Support SUU-7 cluster bombs

### ISSUE THREAD

**Issue by gyrovague** [opentrack/opentrack#330]
From Discord chat:
> Gos - March 27  at 8:05 PM
> #coding need to figure out how to setup a munitions dispenser like the SUU-7.  bomblets fall out the back, but the dispenser stays on the wing.
> Level - March 27 at 8:08 PM
> could you set the SUU-7 as an adapter? That way it won't fall off?
> just a thought
> Gos - March 27 at 8:09 PM
> the SUU-7 model is likely tied to the adapter
> but then, how do you get the bomblets to dispense properly
> cluster munitions in-game all assume the cluster bomb is dropped from the wing
> there's no example to copy
> i'm saying, maybe our coders can experiment to find something that works
> March 30, 2016
> gyrovague - March 30 at 8:43 AM
> Gos, I wonder whether the SUU-7 can't perhaps be handled similar to the SUU-25 on A-10C, or any of the rocket/flare pods for that matter.. but instead of firing rockets/flares, it fires the cluster bombs. Somehow... but point is, those pods also aren't released themselves, and also fire multiple munitions.
> Farlander - March 30 at 10:07 AM
> Correct

**Comment by sthalik** [comment]
Too bad - cluster munitions work well in civilian, crowded areas.
