### ISSUE TITLE
missing support for joystick tracker on Linux

### ISSUE THREAD

**Issue by rgh2** [opentrack/opentrack#335]
I've built and installed the latest (unstable) version of opentrack on my ubuntu system. The problem is that when I call opentrack.bin the only trackers that can be selected are the FreePie and UDP sender trackers. I want to use a joystick tracker so that I can use opentrack with the EDtracker.

**Comment by sthalik** [comment]
There are dependencies required. For the joystick tracker, install the development package of `libevdev` and `pkg-config`.

**Comment by rgh2** [comment]
It seems that Cmake is not building all of the trackers. I have installed libevdev and have pkg-config installed but it seems that all of the trackers except FreePie and UDP are not being built. One thing that I have seen is that you have to manually set the CMAKE_BUILD_TYPE property (I just set to release). How do you have cmake build all the trackers ?

**Comment by sthalik** [comment]
Hold on apparently we have no joystick *tracker*. We have joystick *protocol* for output. Let's mark this as a blocker.

**Comment by rgh2** [comment]
I see a project in the source tree tracker-joystick.

**Comment by rgh2** [comment]
Really what I want is to use joystick as input like seen with EDTracker here -> http://edtracker.org.uk/index.php/using/opentrack.

**Comment by sthalik** [comment]
@rgh2 it's missing for both Linux and OSX currently. The `tracker/joystick` module is only for Windows.

**Comment by sthalik** [comment]
See #234
