### ISSUE TITLE
Is it possible to interface with OpusFSI with FSX?

### ISSUE THREAD

**Issue by popwebz** [opentrack/opentrack#336]
OpusFSI is a third party addon for Microsoft Flight Simulator X that adds live weather and camera effects such as dynamic head movements (DHM) e.g. vibrations in turbulent areas. It has a setting where TrackIR can connect to OpusFSI, so that the DHM is combined with the tracking data before being sent to FSX through simconnect. The OpusFSI documentation suggests renaming the simconnect manifest file in TrackIR but such a file doesn't seem to exist with opentrack.

**Comment by sthalik** [comment]
Send the new manifest file content.
