### ISSUE TITLE
Oculus runtime 1.4+

### ISSUE THREAD

**Issue by ahobel1995** [opentrack/opentrack#339]
Are you planning to update this to Oculus runtime 1.3 anytime soon? I love this program l, but its more or less useless to the oculus consumer base at this point!

**Comment by Kianoni** [comment]
I really would like to see this implemented, so here's my vote for runtime 1.3

**Comment by sthalik** [comment]
I'm going to update, but not soon. I'm busy with other work.

**Comment by kkotowick** [comment]
Any update on 1.3 support? I have a feeling you're about to get a flood of requests for it, what with the CV1 shipping to all pre-orders now.

**Comment by sthalik** [comment]
You just create noise by bumping an issue marked `blocker`. They're the highest priority new features.

**Comment by bizzclaw** [comment]
Would Opentrack need to be updated with every new version of the oculus runtime?The assumption is that as long as it would work with earlier versions of the runtime that the CV-1 uses, it should still work even after the runtime is updated, right?

**Comment by sthalik** [comment]
Older SDK versions support older devices. opentrack can support several SDKs at once, just like right now.

**Comment by Piffx1** [comment]
Hi :)
Is there an approximate period for version 2.3.1 ? 
Greetings piff

**Comment by Karlomat** [comment]
Hey nice ! Just what i need ! Cant wait until its finnished . Keep up the good work .

**Comment by deliciousniko** [comment]
I hope it´ll be finished soon!

**Comment by Narfvader** [comment]
Can't wait for this to be released - keep it up!

**Comment by ColBurton** [comment]
Keep up the great work, cant wait to get my hands on !

**Comment by Soren1793** [comment]
Really great job ! When will it be updated ?

**Comment by sthalik** [comment]
I thought it was 1.4.0 now. I'd rather not support 1.3.0 separately unless there's a reason.

**Comment by sthalik** [comment]
Please see issue #464 and my last comment. I need it fixed before rc13.

**Comment by sthalik** [comment]
Does the Rift build work?

https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa

**Comment by sthalik** [comment]
Position and rotation must both work.

**Comment by Piffx1** [comment]
wuhu :)  yes it works! great! my weekend is save XD

**Comment by sthalik** [comment]
Confirm both position and rotation work, please.

**Comment by sthalik** [comment]
I also need to know whether SDK 1.9.0 needs to get implemented.

**Comment by Piffx1** [comment]
Yes. It has tested briefly everything runs fine. No problems until now. Could tonight test more must now go to work

**Comment by sthalik** [comment]
There's no need to test any more. The code doesn't perform differently with time. Thank you for confirmation.

**Comment by kkotowick** [comment]
So to confirm, the Rift CV1 should be fully supported in 2.3.0-rc15 now, even with the newest Rift update?

**Comment by sthalik** [comment]
Yes. You can grab the build from dropbox. The dropbox URL is always in `wiki -> experimental builds` also.

**Comment by sthalik** [comment]
And to be precise -- the changes are already in the branch that becomes release candidates.
