### ISSUE TITLE
No Icon at system taskbar opentrack-2.3 rc21p11

### ISSUE THREAD

**Issue by severgun** [opentrack/opentrack#342]
There is blank white sheet of paper instead of icon at taskbar.
Windows 10 x64

**Comment by sthalik** [comment]
I have a pink octopus in tray on a fresh build.

The only issue I see here is that the window becomes visible but not raised when clicked from tray.

Try clearing your icon cache (plenty of instructions on Google), restarting explorer.exe and see if it helps.

**Comment by sthalik** [comment]
@severgun reopen if you have additional information. From my testing it works just fine.

**Comment by severgun** [comment]
![no_icon](https://cloud.githubusercontent.com/assets/1197314/14921202/a2800454-0e39-11e6-916f-2610cdd19fe4.png)

**Comment by sthalik** [comment]
It was probably the icon cache.
