### ISSUE TITLE
Need ability to turn off axis in UDP protocol

### ISSUE THREAD

**Issue by zakamik** [opentrack/opentrack#345]
Hello,
I am working on wireless UDP head tracker and stumbled upon common issue when I need to switch or disable axis the same way as in hatire plugin.
Also, there it would be great to be able to assign angle output to the movement axis.

**Comment by sthalik** [comment]
It should be enough to mark axis as disabled in a generic way, without protocol-specific settings.

If not, why?

**Comment by zakamik** [comment]
Sorry, I just did not know mappings and control were moved to generic configuration area.

**Comment by sthalik** [comment]
No problem.
