### ISSUE TITLE
shortkey's for disabling axis

### ISSUE THREAD

**Issue by WFL1969** [opentrack/opentrack#348]
Hi everyone,
I use opentrack for my Ed-tracker.This Ed-tracker is only 3dof,but by combining yaw with the x-axis and pitch with the z-axis I get the movements I need.
Is it possible to ad shortkey's to opentrack for disabling  axis?
With combining pitch with the z-axis Iam able to look up and move my view a little forward to see what is hidden by the metal parts of the canopy.But sometimes I don't want to move forward, I just want to look up.

Regards Willem

**Comment by sthalik** [comment]
That's unfortunately too specialized to include as a program option.
