### ISSUE TITLE
random 360 on mouse emulater

### ISSUE THREAD

**Issue by littlewolfpaint** [opentrack/opentrack#350]
a lot of the time when i play any game it randomly does a 360 on the mouse emulator, if anybody know how to stop it please help

**Comment by sthalik** [comment]
@littlewolfpaint probably bad tracker input. The code is simple and looks fine. Try a joystick/gamepad tracker or press "zero" to disable mouse tracking for a duration.

**Comment by sthalik** [comment]
See #370
