### ISSUE TITLE
Octopus having artifacts at specific settings

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#356]
On specific settings here, being 90 degrees pitch in-game, and the last position before 20 degrees in physical, my octopus is tripping all over.

I've made a video of it: https://www.youtube.com/watch?v=9y9I5DdqR9s

As far as I see it doesn't affect the output, however this effect seems weird to me.

**Comment by sthalik** [comment]
Good catch on reproducing it. I'll take a look.

**Comment by sthalik** [comment]
@MathijsG please confirm fixed https://www.dropbox.com/s/rsj78idet70clqt/opentrack-pt-v15.7z

**Comment by MathijsG** [comment]
Still having the issue? is your upload the correct one? It's not stating some like V15.

![image](https://cloud.githubusercontent.com/assets/529552/15267184/d8b040ca-19ba-11e6-8d3c-3fb8be68df6a.png)

**Comment by sthalik** [comment]
@MathijsG please try https://www.dropbox.com/s/krt76r4zp2owkc5/opentrack-pt-v16.7z

It works for me with yaw, pitch, and raw all enabled. The archive naming is arbitrary.

**Comment by MathijsG** [comment]
Working here now! Great work man!

Was this problem introduced by something recently? I can't remember having this weirdness earlier on.

**Comment by sthalik** [comment]
@MathijsG probably not. But even if, the numerical code has to remain stable in light of recent changes. There's a new flag for vectorization now but the thing I fear here is crashes on just some CPUs.

**Comment by sthalik** [comment]
@MathijsG and thanks for the amount of work you put into submitting and discussing issues during the whole 2.3 development process.
