### ISSUE TITLE
[UX] Clarify which is rotation and which is translation

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#359]
When I see the filter options
![image](https://cloud.githubusercontent.com/assets/529552/15426798/3554f994-1e91-11e6-9dc9-b2cf014f2286.png)

I always need to google for which was which again. Maybe clarify the axes instead of using the abstract terms 'translation' and 'rotation'?

For foreigners they may be less common.

**Comment by sthalik** [comment]
Hey,

Even for native speakers "translation" is hard to understand. The term is too technical. For example NASA calls avoiding debris by the ISS "translating", i.e. moving the ISS by thrusters. So it's inappropriate especially for the already opaque filter options.

Looks like that right now, are we good?

![image](https://cloud.githubusercontent.com/assets/1896811/15427444/772e3f70-1e95-11e6-8c7d-8c39bb4aa007.png)

**Comment by MathijsG** [comment]
Maybe add this for the sake of simplicity, something like this?

Rotation filtering (axes: pitch yaw, roll)

Position filtering (axes: X, Y, Z)

**Comment by sthalik** [comment]
Are we good?

![image](https://cloud.githubusercontent.com/assets/1896811/15427550/334fb350-1e96-11e6-990b-65cc7a99a14d.png)

**Comment by MathijsG** [comment]
Yeah I think that will clear some things up! :)

**Comment by sthalik** [comment]
Thanks.
