### ISSUE TITLE
Just a quick question, not an issue.

### ISSUE THREAD

**Issue by Len62** [opentrack/opentrack#360]
In the mapping window the scale represents degrees for rotation, what does the scale represent for translations? I want to do a video for the mapping. Also, thanks for all your work. Latest RC49p0 is working great!

**Comment by sthalik** [comment]
@Len62 it represents an arbitrary unit used for input translation. Note, if the FOV is set right and model coords are in millimeters, you'd get millimeters as input translation.

**Comment by Len62** [comment]
Thanks for the info. For some reason I had almost assumed millimeters. Will close this.
