### ISSUE TITLE
Option for translation compensation

### ISSUE THREAD

**Issue by Emton** [opentrack/opentrack#362]
Hey I like to use translation compensation as it's more natural but there's one issue that might be improved. As an example, if I turn left and lean right (so I'm looking to my back left) and then I turn to the right (while still leaning) then the X gets detranslated (starts going back the other way) Would it be possible to hold the X translation until X physically returns to the middle? So that I could turn left, lean right and then turn right without the X going to the other side (inverting)? Well I'm not sure if it's possible how I'm saying but I just wanted to give the suggestion, if you want me to make a video showing what I'm talking about just let me know. Thanks for your work on opentrack it's amazing.

**Comment by sthalik** [comment]
I understand. However - the implementation here is very simple, only rotating the translation by rotation. There's hardly any room for more complex logic to be involved.
