### ISSUE TITLE
oculus rift cv1 

### ISSUE THREAD

**Issue by Piffx1** [opentrack/opentrack#363]
Hi all,
does actually opentrack works with oculus rift cv1?
 greetings
Piff

**Comment by sthalik** [comment]
Not yet. I've got my hands full with work, opentrack, and personal.

Kitten just turned six weeks and it's one hell of a time investment.

**Comment by sthalik** [comment]
Some progress. Soon-ish ovr SDK 1.4.0 for testing.

**Comment by Piffx1** [comment]
oh great ! thx for the info

**Comment by bizzclaw** [comment]
If you need help with testing, just let me know. Just got my CV-1 in yesterday.

**Comment by sthalik** [comment]
Some stuff is done for cv1 but it's still not certain it'll work.

**Comment by Piffx1** [comment]
That would be great! what's your nickname in oculus

**Comment by sthalik** [comment]
see #339

**Comment by Tbsc74** [comment]
Just wondering what the progress is for opentrack being compatible with Oculus Rift CV-1. Really want to play Arma 3.

**Comment by Piffx1** [comment]
i buying only for arma 3 the oculus rift and a gtx1080 XD
