### ISSUE TITLE
Tracking the raw, pitch, and roll, but nothing is happening in-game

### ISSUE THREAD

**Issue by PokerulerPlayz** [opentrack/opentrack#365]
When I use start OpenTrack, load an app on my iPhone called VR Streamer, and connect to it, I open up my game(Portal 2) and nothing is happening when I move around my phone. But when I look back at the opentrack window, the little octopus moves around with the phone's movement and the yaw, pitch, and roll are all tracked. What am I doing wrong?

The Tracker is set to UDP Sender, the Protocol is freetrack 2.0(though, I've tested it on mouse emulator too), and the Filter is Accela. I haven't done anything with the Mapping, because I really don't know what it is. I don't think it's the app on my phone, because the only settings on it are IP and tracker data settings.

**Comment by sthalik** [comment]
Portal 2 doesn't support any other tracking device than mouse control. Most software supporting the protocols are flight, race, tank, infantry sims.
