### ISSUE TITLE
Main LED in PointTracker 1.1 switching around

### ISSUE THREAD

**Issue by archeria1** [opentrack/opentrack#366]
When I move my head up the red main LED always switches around. I made sure to enter the exact positions of the 3 LEDs on my clip on, every LED is always visible and there are never more than 3 dots visible. How can I force him to keep the main LED the main LED? It's not like it disappears.

**Comment by MathijsG** [comment]
Can you make a screenshot? Did you calibrate your clip or hat?

**Comment by Len62** [comment]
Sounds like you did not do the calibration steps. Here's a link to a video on calibrating. Once done you should have 3 green and 1 red dots visible.
https://github.com/opentrack/opentrack/wiki/Quick-Start-Guide-(WIP)

**Comment by sthalik** [comment]
@archeria1 enable dynamic pose resolution.

**Comment by archeria1** [comment]
@sthalik Thanks, that seems to have done the trick. It still bugged out sometimes but I just adjusted the curves so I don't have to turn until that critical point.
