### ISSUE TITLE
RFC: rename standard tracker/protocol terminology

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#371]
It's not immediately apparent what "tracker" and "protocol" are. I'd like to rename them "input" and "output", respectively.

Please comment on that.

@MathijsG what do you think?

**Comment by MathijsG** [comment]
Yeah they are quite abstract indeed. Maybe input and output are better.

And maybe rename the fieldset around the start stop buttons to 'Tracking' instead of 'Controls'?

**Comment by sthalik** [comment]
I'll rename it.

Is there anything else that stands out as too non-informative?

**Comment by Len62** [comment]
Both sound good to me. I didn't notice anything else that would benefit from a name change.

**Comment by sthalik** [comment]
Thanks
