### ISSUE TITLE
not support normal usb webcam ?

### ISSUE THREAD

**Issue by adrianmak** [opentrack/opentrack#377]
I have a logitech C720 usb webcam.
opentrack could not find in camera list.

**Comment by sthalik** [comment]
Is this some antivirus software feature? There were never any problems like that.

**Comment by Len62** [comment]
I used to use a C720 so I pulled it out, plugged it in, did not install any drivers, and OT found it w/o any problems. It came up as "USB Video Device" on the OT camera menu. This is on Win10.

**Comment by sthalik** [comment]
Replug it into a different port definitely.
