### ISSUE TITLE
Bug in point_tracker.cpp

### ISSUE THREAD

**Issue by DaMichel** [opentrack/opentrack#380]
I just found a little issue here https://github.com/opentrack/opentrack/blob/unstable/tracker-pt/point_tracker.cpp#L49

In this part
```
for (unsigned i = 0; i<points.size(); ++i)
    d_order[i] = d_vals[i].second;
```
`points.size()` can be more than the size of d_order which amounts to `PointModel::N_POINTS=3 `. It happened to me and it resulted in a stack corruption warning in the debugger. I guess the warning was legit ...

**Comment by sthalik** [comment]
Thanks, great catch!

**Comment by DaMichel** [comment]
Wait a sec. `points.size()` can be less that 3, can't it? So I think it might be better to take `min(points.size(), PointModel::N_POINTS)`.

**Comment by sthalik** [comment]
@DaMichel no. See that `PointTracker::track(...)` is called only if `success` is true in the thread.

<pre>
const bool success = points.size() >= PointModel::N_POINTS;

if (success)
{
    point_tracker.track(points, PointModel(s), fx, s.dynamic_pose, s.init_phase_timeout);
    ever_success = true;
}
</pre>

There are no other code paths that go there.

**Comment by sthalik** [comment]
Also see `std::sort` usage in `PointExtractor::extract_points(...)`. We're using the three most circular points.

**Comment by DaMichel** [comment]
Ok. Great. Nevermind then.
