### ISSUE TITLE
Support for PlanetSide2?

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#382]
Hi,
is there any way to Opentrack could work in the future in PlanetSide2?
https://www.planetside2.com/home/youtube
I tried to emulate the mouse and in the menu I am successful, but in the plane there is no reaction. Here are the complicated instructions on how it could work.

https://www.youtube.com/watch?v=WlMF5LkvUK4

or

https://www.youtube.com/watch?v=9RhehulgnkQ

Does anybody have any experience that would help under this game to work OT?
Thank you all very much for your reply. Pet

**Comment by sthalik** [comment]
@petsild vjoy would work.

**Comment by petsild** [comment]
I tried Vjoy version:

https://sourceforge.net/projects/vjoystick/files/latest/download?source=files

and

http://www.headsoft.com.au/index.php?category=vjoy

In system it is added a virtual device, but OT does not work vjoy ends the message.

![vjoy](https://cloud.githubusercontent.com/assets/13926997/16679477/2774aedc-44e8-11e6-9bf2-f3d3c1fb6fbf.JPG)

**Comment by sthalik** [comment]
Headsoft should work.

**Comment by sthalik** [comment]
See device manager if there's a reboot required. Try running as administrator or as non-administrator.

**Comment by petsild** [comment]
Vjoy works well... unfortunately the administrator didn't help.

![vjoy2](https://cloud.githubusercontent.com/assets/13926997/16680052/7ad32e9c-44ec-11e6-8360-eaf225822991.JPG)

**Comment by sthalik** [comment]
Try rebooting. Try both devices. Windows might sort them incorrectly. vjoy exposes two joysticks. Also see if all is fine in device manager.

I haven't used vjoy in a while but it always worked and there were no changes.

**Comment by sthalik** [comment]
Just to be clear, if it's really broken I'll fix it.

**Comment by petsild** [comment]
Device manager is error free.
Thought I paste installed files vjoy to the OT path: E:\opentrack\contrib\vjoy it didn't help.

**Comment by sthalik** [comment]
Okay.

Don't copy-paste the .dll. Just in case if you pasted any stuff into VJoy install dir then reinstall it.

The vjoy SDK and runtime were updated and that's probably it. Try this build: https://www.dropbox.com/s/fw80gm178v2nddl/opentrack-vjoy-20160708.7z

**Comment by sthalik** [comment]
Also if you're using an older vjoy version, update from headsoft's site.

**Comment by sthalik** [comment]
If the protocol won't load, rename to "vjoy.dll".

**Comment by petsild** [comment]
Now in the menu is missing completely.
- the renaming of the VJoy on vjoy.dll menu doesn't help.

**Comment by sthalik** [comment]
This one works for me right now, with the driver: https://www.dropbox.com/s/wio1mhsyg2507w0/opentrack-vjoy-20160708_2.7z

**Comment by petsild** [comment]
Still it behaves the same as the p7.
He has to show some settings after confirming OK?

**Comment by sthalik** [comment]
Confirming what? Select the protocol and it'll transmit.

Reinstall the driver. The options dialog has the URL.

If it doesn't help, go to device manager, select "uninstall" on vjoy and tick the "remove driver" checkbox. The latter part is important. Then reboot and reinstall the driver from the dialog's site.

**Comment by petsild** [comment]
With the driver in the link I'm working from the beginning of the experiments. Has to open some new window after the OK confirmation?

![vjoy4](https://cloud.githubusercontent.com/assets/13926997/16684228/41eaa4da-4504-11e6-8c7f-156a21f0c113.jpg)

When you start OT in the background and an attempt to map in the menu Vjoy no reaction to the movement of the octopus.

![vjoy3](https://cloud.githubusercontent.com/assets/13926997/16684233/48760042-4504-11e6-8f9f-3a4c0a8319aa.JPG)

**Comment by sthalik** [comment]
The dialog buttons aren't functional. In fact I'll change them to a single button saying "ok".

Restart opentrack after driver install just to be sure.

**Comment by petsild** [comment]
I manually uninstalled vjoy in the device manager. After rebooting and re-installing no change.

![vjoy5](https://cloud.githubusercontent.com/assets/13926997/16684656/948cf56a-4506-11e6-8f7b-6881217662f1.JPG)

**Comment by sthalik** [comment]
What's your Windows version?

**Comment by petsild** [comment]
Windows 7 64bit

**Comment by sthalik** [comment]
@petsild  can you see it if it works in a pristine Windows VM? There's the test tracker that generates nonsensical data.

**Comment by sthalik** [comment]
@petsild alternatively try some other software doing output to vjoy.

**Comment by petsild** [comment]
After countless restarts I gave up.
In addition, I found that the PS2 is so sensitive to the periférii after adding the virtual joystick ignores all the actual device, then you cannot map the analog axis.
I really appreciate your support :-D OpenTrack belongs to the most popular programs that I use.
Where to send some money for your great work?

**Comment by sthalik** [comment]
@petsild It's a hobby, I don't intend to take any money. But I appreciate that you like the software.
