### ISSUE TITLE
GRID Autosport don't work anymore since: opentrack 2.3.0 release candidate 8

### ISSUE THREAD

**Issue by andregm3** [opentrack/opentrack#385]
Please check why GRID Autosport headtracking stopped work on this release.

Freetrack.

**Comment by Len62** [comment]
Did you re-select the input/output filters as mentioned in the release notes?

**Comment by andregm3** [comment]
How to do that ?

**Comment by Len62** [comment]
In #1 and #2, note they are labled input and output in the current versions.
https://camo.githubusercontent.com/caa19afd3574a8409badbf55f0353c5fb8b39f4c/68747470733a2f2f7777772e64726f70626f782e636f6d2f732f366f653870377a637679747532356a2f6d61696e73637265656e2e706e673f646c3d31

**Comment by andregm3** [comment]
lol sure yes i did, i use UDP Receive and Freetrack, but Trinus VR dont work with that anymore, just head tracker app from playstore and p8 don't work with GRID p7 works

**Comment by Len62** [comment]
It was just a guess on my part. Not familiar with the game or UDP. Maybe someone else will chime in.

**Comment by andregm3** [comment]
thanks for your attention

**Comment by sthalik** [comment]
I'll check with the actual game.

**Comment by vikingsail** [comment]
I second this. RC8 doesn't work on UDP+Freetrack 2.0 with ARMA 3 anymore. 
Interestingly, if I put the protocol on "FreeTrack" mode it works even thou everything is messed up. But on "TrackIR" mode nothing happens in ARMA, while Mr.PinkyOctopus shows movement in OpenTrack.
I guess something is broken with the TrackIR protocol on this RC.

**Comment by sthalik** [comment]
I see the bug. Installation directory was repeated so it was like `/program files/program files/...`. I'm recalling rc8.

**Comment by sthalik** [comment]
@vikingsail @Len62 @andregm3 any issues anymore in rc9? I tested all involved modules.

**Comment by andregm3** [comment]
Trimus VR os not working too, Free-Track output from Trinus to UDP input in Open-Track

**Comment by sthalik** [comment]
rc9?

**Comment by andregm3** [comment]
oh new release, will try right now

**Comment by sthalik** [comment]
Oh and start tracking just once before starting the game since it has to update the path in registry.

**Comment by andregm3** [comment]
trinus is not moving the octupus

**Comment by sthalik** [comment]
This is different. The issue was freetrack protocol not reading the .csv.

**Comment by andregm3** [comment]
GRID is back !

**Comment by sthalik** [comment]
@andregm3 please be more specific.

**Comment by andregm3** [comment]
GRID and Project Cars are working now ! on RC9

but Trinus VR still don't make Octopos move on Open Track anymore.

**Comment by sthalik** [comment]
The UDP tracker had no changes really. It can be a firewall or network issue.

**Comment by andregm3** [comment]
i have https://play.google.com/store/apps/details?id=com.frozenbacon.headtracker
and that app work, would it be a Trinus VR issue ?

**Comment by sthalik** [comment]
Temporarily disable Windows firewall and see if it works. It's really outside the scope of the project to help with issues like that.

**Comment by andregm3** [comment]
thanks mate, but i never use windows firewall, the mouse emulation on Trinus VR works, just the sensor to Open Track that don't, i tested in 2 PC one here and other at my job.

**Comment by vikingsail** [comment]
RC9 works perfect! Thanks for the good work!
