### ISSUE TITLE
Trinus VR not working with Open Track anymore

### ISSUE THREAD

**Issue by andregm3** [opentrack/opentrack#387]
Trinus VR is not working, i've tryied all sensors modes and it lost its connection with UDP from Open Track, i don't know if this is a Trinus VR Side issue or Open Track.

I've already disabled firewall

There is another android sensor UDP sender in Android called Head Tracker, that still works: https://play.google.com/store/apps/details?id=com.frozenbacon.headtracker

**Comment by sthalik** [comment]
@andregm3 the UDP protocol format hasn't changed at all.

**Comment by khan213** [comment]
Hi I had this problem too and I just delete  documents>opentrack-2.3 folder. I start opentrack and set mapping again. 
I hope to help. 
Cheers.

**Comment by sthalik** [comment]
rc11 got totally broken UDP input by accident. rc12 is unbroken again. I've tested it before release and opentrack receives data from a Python program that uses the right format.
