### ISSUE TITLE
interconnect between axis when centered

### ISSUE THREAD

**Issue by Cybotive** [opentrack/opentrack#394]
I'm having problems with my roll affecting pitch and vice versa. It's very annoying and I'm using this in a VR setting, so I can't have that at all. I usually have my phone tethered over USB and point my phone to the right IP that my phone gave it, but I've also debugged with a wireless connection.

Speaking of debugging, when I turn on debugging and watch the orientation values while i pitch the phone only one of the three numbers separated by a comma moves but according to OpenTrack on the PC side, all three "Raw" values change significantly (mostly roll and pitch).

Just did some more number watching under debug in the app and when i roll all three orientation numbers change.

Also I tried out a FreePie example sketch for emulating mouse and whichever direction i turned it would stay drawing a u shape (probably something to do with the deprecated code in the example, but still...)

I am trying to use OpenTrack to take in my phone's orientation, output it as FreeTrack and then I'm using RiftCat which can be pointed to the FreeTrack orientation data. I had some problems with drift when just using the Cardboard API Vridge uses by default and OpenTrack completely got rid of the drift with the filters, but this whole axis tied thing is frustrating.

The tracking acts the same way whether it is right above my computer or whether it's on the other side of the room (checking for magnetometer interference)

Okay, so it seems I'm having troubles with gimbal lock on the gyroscope. Does FreePie IMU (and HeadTracker on Google Play) use Euler angles? If so... why? Is there anyway to get around this?

**Comment by sthalik** [comment]
The freepie side uses Android framework functions to compute the actual pose. It doesn't perform centering.

freepie transmits euler angles. This is in accordance with the freepie cell phone API so that you can use a pristine freepie apk. The apk is maintained as part of the freepie project.

If you're having gimbal lock then use the "angle offset" function in our freepie tracker settings. It should help with the typical cases.

**Comment by Cybotive** [comment]
Nope. Doesn't help at all. just rotates the octopus by the offset as expected, but the axes are still tied. I have confirmed it is opentrack by turning off "center at startup" and watching raw data. when it's flat on a table and i pitch up it only affects roll, and roll affects pitch, (so I swap them) but they're not tied in raw data, only calculated data no matter what filter i use.

**Comment by sthalik** [comment]
There are two centering modes in the options window. Are you using the one for inertial trackers?

**Comment by Cybotive** [comment]
Yes, I tried both. I also recently tried unchecking "center at startup" and it behaves the same way. Vridge and every app I have using the Cardboard API or Google VR SDK works, besides when using it with this.

**Comment by sthalik** [comment]
Can you also check rc10's correct matrix -> euler formula?

**Comment by sthalik** [comment]
If this fails, give me starting and ending raw values that give this bad behavior.

**Comment by Cybotive** [comment]
Where/what is the correct matrix? I am not able to test immediately as it is 2:32am, but I will soon.

**Comment by Cybotive** [comment]
It's still very wonky.

**Comment by sthalik** [comment]
Give me the zero value of raw rotation and the rotated value that doesn't work for you.

**Comment by Cybotive** [comment]
I figured I would just show it in action, the first half of the video, the values are just swapped so roll is affecting yaw (although settings are all good, no swapping) but that's easy to remedy. But the real problem is moving around in other directions.

https://www.youtube.com/watch?v=8xdr5QDANQQ
Wait a bit for 1080 to process if you see this right away.

**Comment by thiagokrieck** [comment]
I am having the same issue while using pointracker. There seems to be some bleed of one axis into another.

**Comment by sthalik** [comment]
This is harder than it seems. If someone can provide a geometrical solution, be my guest.

**Comment by sthalik** [comment]
In rc12 we're using a different formula for euler -> matrix and matrix -> euler conversions. Also there's a third centering option that centers each axis ignoring all the others. Please confirm whether either of this solves the problem.

**Comment by thiagokrieck** [comment]
For me the problem is completely gone.

**Comment by sthalik** [comment]
This is consistent with other reports. Thanks for the confirmation.

**Comment by Cybotive** [comment]
I'll have to try it out. I'll see if this is better in terms of drift than RiftCat alone.

**Comment by sthalik** [comment]
@Cybotive report back if this is fixed please.

**Comment by Cybotive** [comment]
Sorry for not testing. For me it hasn't changed, or maybe got worse.

**Comment by Cybotive** [comment]
using 2.3-rc99p13

**Comment by sthalik** [comment]
@Cybotive do raw values change for you when roll affects pitch, or is it only output values?

**Comment by Cybotive** [comment]
it seems the raw values don't suffer from this, at least as much (shown on the left in OpenTrack).

**Comment by Cybotive** [comment]
laying it landscape, flat on a table and leaning it forward and back, the only raw value that changes is roll (the others are +-2-ish). But with the calculated values, roll and pitch move quite a lot, and very minimally does yaw move, but still more than raw.

**Comment by Cybotive** [comment]
but even in raw, when in portrait and leaning it around, the numbers skip at a certain point.

**Comment by sthalik** [comment]
The IMU app that I've co-written uses Android internal functions for pose estimation. It's gyro+mag+acc integration.

You may want to try out other camera centering modes -- "experimental camerra" for instance.

**Comment by Cybotive** [comment]
hmmmmmmm.

**Comment by sthalik** [comment]
Magnetometers are in general total crap if anywhere near speaker or headphone magnets. Try moving them out of the room for testing to eliminate possibility of interference. Merely plugging them off won't work of course here.

**Comment by sthalik** [comment]
If there are any more bugs related to that please send a message in this issue and I'll reopen it.
