### ISSUE TITLE
OpenTrack not stop correctly tracking with an output TrackIr

### ISSUE THREAD

**Issue by SharkNoir** [opentrack/opentrack#401]
Hello. 
I don't know if you know this pb. 
I use Opentrack with EDTracker to simulate an TrackIr for some planes's simulator. 
The pb is when i stop Opentrack with a keybind. The simulator not see that Opentrack is stop and we can't move the head with keyboard. If we restart the tracking. All work. 
With the software of an TrackIr. When the track is stop, we can move the view with the keyboard. 
If you can set Opentrack same as TrackIr. You have the best software for me.

**Comment by sthalik** [comment]
I won't change our .dll because it's whitelisted by anti-cheat software for the time being. This is a known problem. The injected .dll doesn't know there's no more data no matter what happens.
