### ISSUE TITLE
Trackir 5 camera not detected by opentrack

### ISSUE THREAD

**Issue by MigLeader** [opentrack/opentrack#402]
hello opentrack developers , i have an issue as the title says , opentrack cant detect trackir 5 camera , even though i have disabled my internal camera , my specs are as follows:

win 8.1 64bit
MSI GS60 2QE (I7 4700 , GTX970m , 16GBram)
Trackir 5

i don't know what other info i must provide , but i will be gladly provide anything

thanks for any help i get.

![untitled-4](https://cloud.githubusercontent.com/assets/20781698/17310266/f43660e8-584b-11e6-9cb6-731fd7381be7.jpg)
.

**Comment by Len62** [comment]
Could be that the camera is not identified as a camera in windows. Since it was designed to work with their software it may be hidden to other apps. It should be listed under the "imaging devices" in order for windows to see it?

**Comment by sthalik** [comment]
opentrack only supports directshow cameras, not proprietary camera protocols. Take a look at linuxtrack.
