### ISSUE TITLE
P10  automatic threshold

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#405]
Hi,
the last P10 when a friend Leon turns on automatic threshold green crosses are turned off and are only white points. 
The range of the size of the points has no influence at all.
The manual works well. 

HW:
Model Cap 
Camera PS3 640x480@75
System Win 10

**Comment by Len62** [comment]
Interesting. Automatic threshold is working fine here w/P10. I have the same specs except I use a clip. What kind of pixel sizes does your friend get using manual?

**Comment by sthalik** [comment]
@petsild what's your point area size?

**Comment by petsild** [comment]
shows 15px

**Comment by sthalik** [comment]
@petsild max value is 10 px. Can you try if lowering exposure makes it work, just to make sure? If it does then I'll put the max value at 16 px.

**Comment by Len62** [comment]
Even with auto threshold selected the threshold slider may need to be adjusted.

**Comment by sthalik** [comment]
@Len62 what I meant is that the slider's value most to the right needs to get changed from 10 to 16. I'd like to know how it works with lowered exposure (hence smaller points), first.

**Comment by sthalik** [comment]
By the way I have a really dumb way to fix gimbal lock once and for all for all devices.

**Comment by sthalik** [comment]
Max radius is 15 now.

**Comment by petsild** [comment]
If I have a point in the neutral position of 15px, and then I zoom in on the camera? For sure will 20 value better?

**Comment by sthalik** [comment]
No, it makes small values hard to adjust.

**Comment by sthalik** [comment]
Test build(s): https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa

**Comment by petsild** [comment]
When you try to run it show error.

![qt](https://cloud.githubusercontent.com/assets/13926997/18234225/8a1f198a-72fd-11e6-85b9-c5b00625c20b.JPG)

**Comment by Len62** [comment]
Strange, running fine so far here. Have yet to really try it out.

**Comment by sthalik** [comment]
@petsild do you have the "platforms" directory and qwindows.dll when unzipped?

**Comment by petsild** [comment]
Friends it also does not start. Always OT worked now error.
The whole time running f:\opentrack
I need something else to install?
Thank you for the support.  Pet

**Comment by sthalik** [comment]
I see the problem.

Get today's second build. http://goo.gl/Fq8CT7

**Comment by sthalik** [comment]
Can someone try start opentrack on Windows XP, please?

**Comment by petsild** [comment]
I tested the latest build for download:
![build](https://cloud.githubusercontent.com/assets/13926997/18262016/fb697530-73fd-11e6-937d-f86f8d57e432.JPG)
I can run but all the curves in the profiles are lost! The new version will require setting the new curves?

**Comment by Len62** [comment]
Yes, probably due to changes in how mapping works.

**Comment by sthalik** [comment]
Import function's not yet written.

**Comment by sthalik** [comment]
For the record, rc12 will import splines as long as no new one have been set.

**Comment by petsild** [comment]
Automatic threshold still doesn't work.

**Comment by sthalik** [comment]
Decrease exposure so points aren't larger than 15 px.

**Comment by petsild** [comment]
Tested on the size of 12px the actual size of the point. The change of scope has no effect.

![12px](https://cloud.githubusercontent.com/assets/13926997/18410301/7c29eb60-775e-11e6-9b44-77ac922df145.JPG)

**Comment by Len62** [comment]
Why is the video window so bright and noisy? You may want to play around with the CLeye driver to get your picture darker and less noisy. Are you using IR leds, and if so have you removed the IR filter from the camera?

**Comment by petsild** [comment]
AT the verse P9 all work on the same light configuration as in the picture.

**Comment by Len62** [comment]
Ok. Just a thought. You do know that with automatic checked you can still adjust the slider right? The slider works with auto on or off, it just functions differently.

**Comment by sthalik** [comment]
@petsild it works when I set exposure and gain as high as this. What happens when you set min size to 0 and max size as 999?

**Comment by sthalik** [comment]
@petsild it makes more sense to use very low exposure and gain values so the light's center area is brighter than the edges. Then PT gives more weight to the brighter parts but doesn't discard the rest.

What I did was lower color balance a lot, set lowest exposure and slightly adjust gain. Then barely anything is visible and the LED is visible as different shades of gray, not a single white flash. But I also have several unexposed film layers on the sensor so even IR could be darker than normal.

**Comment by sthalik** [comment]
My single LED, zoomed in. Auto threshold shows 6 px.

![image](https://cloud.githubusercontent.com/assets/1896811/18721168/8840eadc-802f-11e6-9ae9-9d78539e2db7.png)

**Comment by sthalik** [comment]
@petsild run the experimental build. I forgot to multiply by `pi` for point area.

https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa

**Comment by petsild** [comment]
Features AT again works flawlessly :) to all my friends. 
Thank you very much for the patch, great work hey. Pet
