### ISSUE TITLE
Vjoy Demo Expired error

### ISSUE THREAD

**Issue by Pure-Awesomeness** [opentrack/opentrack#407]
Latest version of opentrack causes vjoy output to display a message box "Demo expired" after a couple minutes of use. Drivers were downloaded from the headsoft website linked when clicking on the options button. Is this a bug? How can I fix it?

Edit: Previous version 2.3 (prerealese 4) I was using for opentrack worked fine with vjoy.

**Comment by sthalik** [comment]
I'm going to replace vjoy with an open-source joystick driver. This is a problem definitely.

**Comment by Pure-Awesomeness** [comment]
So is there a temporary fix for this?

PS: Sorry for your cat's loss, Keep up the great work sir!

**Comment by sthalik** [comment]
Temporary, no. The vjoy protocol needs to be replaced with another driver.

**Comment by sthalik** [comment]
See if https://www.dropbox.com/s/3ygvghboe7kk2p2/opentrack-vjoystick-20160808.7z works. You'll get instructions on how to install the driver.

**Comment by Pure-Awesomeness** [comment]
Works very well. Thanks

**Comment by sthalik** [comment]
Thanks for the confirmation.
