### ISSUE TITLE
When viewed at 90 degrees, the offset is displayed incorrectly

### ISSUE THREAD

**Issue by olegiy** [opentrack/opentrack#408]
Hi all. 
Previous version opentrack-2.3-rc49p7 --> https://youtu.be/gY9XFM_E5RY
Latest version --> https://youtu.be/P54s4nAS2Ig
The settings are not changed.

**Comment by sthalik** [comment]
What offset?

**Comment by olegiy** [comment]
displacement of the head to the left and right

**Comment by sthalik** [comment]
If you move 90 degrees to the right, moving left should move you toward the front of the aircraft. Is it working correctly?

**Comment by olegiy** [comment]
https://youtu.be/uFjrXqIGlnc

**Comment by sthalik** [comment]
I cannot reproduce. See if https://www.dropbox.com/s/z1f6u5voc0lz1af/opentrack-tcomp-20160808.7z works for you, it's the latest dev version.

**Comment by sthalik** [comment]
And don't enable "use center as translation offset" since it works badly with compensation.

**Comment by olegiy** [comment]
Thanks for patience. I will test program tomorrow. And than I will write you.

**Comment by olegiy** [comment]
The latest version better, but not as rc49p7. The range of movement is less.. 
"use center as translation offset"  - disabled. 
(translate.google) © )))

**Comment by sthalik** [comment]
Are you referring to translation max value being 50? What max value do you need for War Thunder?

**Comment by sthalik** [comment]
If that's the case, do you need the input and output to be more?

**Comment by olegiy** [comment]
65-70

**Comment by sthalik** [comment]
But output or input?

**Comment by olegiy** [comment]
output

**Comment by sthalik** [comment]
@olegiy confirm it works. https://www.dropbox.com/s/mj1lsd3604c3npa/opentrack-tmax-20160809.7z

If you still have doubts regarding translation compensation, please take your time until you're sure.

**Comment by sthalik** [comment]
@olegiy is it working now?

**Comment by olegiy** [comment]
I will check only tomorrow.

**Comment by olegiy** [comment]
All is well. Thank you.

**Comment by sthalik** [comment]
@olegiy thank you for the confirmation.
