### ISSUE TITLE
rc49-p11 curves are broken

### ISSUE THREAD

**Issue by albertolg** [opentrack/opentrack#415]
the asymmetric mapping are ignored, worked with p7

**Comment by sthalik** [comment]
It works for me except you need to select the checkboxes again.

The reason for that is that options window and mapping window saved each other. Now they are separate in the .ini file.

**Comment by sthalik** [comment]
@albertolg can you confirm what's happening, please?

**Comment by albertolg** [comment]
@sthalik the problem is in the output remap... I use edtracker and need to remap the axis like in the picture, but with the p11 the remap is not saved, you remap, works.. change profile and open the previous where you changed the output remap and is not there

![immagine](https://cloud.githubusercontent.com/assets/7831332/17670882/499819a0-6314-11e6-9d66-10b614fdbb54.jpg)

**Comment by sthalik** [comment]
Test build(s): https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa

**Comment by sthalik** [comment]
rc12 has migration support for options changing representation. Also remap is now saved like it should.
