### ISSUE TITLE
Toggle calibration error

### ISSUE THREAD

**Issue by olegiy** [opentrack/opentrack#416]
invert values
https://youtu.be/ZTR1XrmKPjw

**Comment by sthalik** [comment]
It's not an error. It uses a statistical method. There's a link how to make the method detect the center properly in this dialog, in blue.

**Comment by sthalik** [comment]
I'm sorry you are right.

**Comment by sthalik** [comment]
@olegiy since when was it broken?

**Comment by olegiy** [comment]
I discovered today. In previous versions did not check. ((

**Comment by sthalik** [comment]
@olegiy build for you https://www.dropbox.com/s/vs2k93qlsg7q38s/opentrack-pt-tcalib-20160815.7z

Please report crashes since I changed the compiler from GNU 5.4.1 to 6.1.1 again.

**Comment by olegiy** [comment]
https://www.dropbox.com --> "This file is no longer here"

**Comment by Len62** [comment]
I'm getting the same issue in RC11. If I manually invert the numbers all is fine. As olegiy stated the test version is no longer there. Only happens when performing a new calibration. Previously saved ini files work fine.

**Comment by sthalik** [comment]
Test build(s): https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa

**Comment by Len62** [comment]
No issues with calibration in this build.

**Comment by sthalik** [comment]
Thank you for the report.
