### ISSUE TITLE
Hatire, FPS

### ISSUE THREAD

**Issue by rizer1980** [opentrack/opentrack#417]
Hello.

Thanks for your great work.
I use GY-85 vs arduino nano, Razor AHRS firmware.
Little modified firmware to 100 count per second data output. 115200 baud rate.
Checked, in text mode, it is really 100 data per second.

But in opentrack, with hatire arduino protocol, in status window, i see fps about 56.
It's some some limitation of opentrack?

Sorry of my awuful English )

**Comment by sthalik** [comment]
Make sure the "workaround" checkbox in the dialog is off.

**Comment by rizer1980** [comment]
My mistake.
Found my error in AHRS Firmware.
Now all works fine.

Thanks.
