### ISSUE TITLE
 Error release rc99 p11.

### ISSUE THREAD

**Issue by Alex7272** [opentrack/opentrack#424]
Sorry for the English, I write through a translator. When you open the tab camera setting dialog is exited with an error. Camera A4 techPK-336mb.

**Comment by Alex7272** [comment]
opentrack 2.3.0 release candidate 7 version works!

**Comment by sthalik** [comment]
The button is broken. I'm removing it for rc12 since there were so many reports.

**Comment by sthalik** [comment]
For the record, I don't know how to fix it and it's complex to make it work.
