### ISSUE TITLE
RC11 weird Pitch coupling with yaw/roll - Aruco

### ISSUE THREAD

**Issue by 503Kento** [opentrack/opentrack#426]
I'm getting pitch coupling in RC11.  When I first tried it out if I yawed to the right I was suddenly inverted, yawing to the left was fine.  I tinkered a bunch with settings to no avail then tried again with the default.ini.  The yaw coupling was replaced with roll coupling.  rolling my head right gets me inverted; rolling left works as expected.

RC7 and RC10 (with simconnect fix) worked just fine for me.

**Comment by sthalik** [comment]
See the warning in aruco article <https://github.com/opentrack/opentrack/wiki/Aruco-tracker>, the last paragraph.

**Comment by 503Kento** [comment]
@sthalik Thanks, assuming I understand the paragraph correctly I have that in place already as I have the bottom edge of the marker closer to the camera than the top (oblique angle).  I'll play with the angle and see if I can make a change.  As I said, previous releases work just fine with the same hat/marker angle.

**Comment by sthalik** [comment]
To have pitch not confuse itself you need as much as 15-20 degrees pitch up or down at all times. That is, +- 15 to 20 degrees is the closest to the center the marker can get.

I'm thinking of a design to alleviate this - rather than putting it as an axis-aligned rectangle, or as top-bottom left-right "diamond-like" corner positions, put it halfway in between. The slant should prevent the breakage and allow for pitch with no restrictions.

**Comment by 503Kento** [comment]
I have about that amount of angle normally.   Perhaps when I roll that gets fouled up.  

I'll try to rotate the marker a bit and see what happens.

**Comment by 503Kento** [comment]
Well, I tried all manner of angles for the marker with no success.  I even tried tilting my head forward to make sure I had positive pitch at all times but rotation to the right still flipped the octopus inverted.  All of the same marker tests work as expected in RC7.

**Comment by sthalik** [comment]
What's the raw pitch value just before it breaks?

**Comment by sthalik** [comment]
@503Kento we had no changes to aruco since rc7. This may have to do with the compiler. See if #454 does anything for you. If not, send a raw camera video that I can replay to see the bug. Just please compress it.

**Comment by 503Kento** [comment]
Still same Issue with experimental build.

By raw camera video you mean just capture from CL-Eye test?

**Comment by sthalik** [comment]
@503Kento yes, but compress it.

**Comment by 503Kento** [comment]
@sthalik hopefully this is what you need.

https://drive.google.com/open?id=0BxmLU5HrJBobc25QU1BRMjBkS2s
