### ISSUE TITLE
blob::brightness Member?

### ISSUE THREAD

**Issue by DaMichel** [opentrack/opentrack#429]
This is just a programming question.
In
https://github.com/opentrack/opentrack/blob/unstable/tracker-pt/point_extractor.cpp#L139
, I saw that `blob::brighness` is set to `vals/sqrt(double(cnt))`. I am wondering about the square root. Is it meant to be this way?
I mean, it is not the average nor the sum of the pixel values.

**Comment by sthalik** [comment]
Hey,

It needs to take size into account at all, but linear scaling gave bad results with false blobs. This is a crude ad-hoc formula.

**Comment by DaMichel** [comment]
I see, thanks.
