### ISSUE TITLE
Hatire Arduino translation (X, Y) - very slow.

### ISSUE THREAD

**Issue by Ec0nomist** [opentrack/opentrack#431]
I'm using Arduino inertial tracker. Translations X and Y are linked with head rotation (Yaw and Pitch). In version opentrack -2.3 rc49p7 everything works quickly , the new version rotations (Yaw and Pitch) - fast, translations (X and Y) - slow . Where it is possible to adjust their speed \ smoothing ?
https://www.youtube.com/watch?v=UFKYD1pagcE&feature=youtu.be

**Comment by sthalik** [comment]
What happens if you disable Accela?

**Comment by rizer1980** [comment]
Same problem.
If i set all bars in accela, nothing changed.
If disable accela - problem is gone

**Comment by rizer1980** [comment]
EWMA and Kalman work fine too.

**Comment by sthalik** [comment]
@rizer1980 @Ec0nomist see the build in #454. The cap is the same as previously now.
