### ISSUE TITLE
A simple Ball Tracker....

### ISSUE THREAD

**Issue by Tux0Topo** [opentrack/opentrack#433]
So... i've seen this blog:
http://www.robot-home.it/blog/en/software/ball-tracker-con-filtro-di-kalman/

Seems to be the same idea behind psmove controllers...
Can be made something like that to work with opentrack? I'm planing to use it with riftcat, so yaw, pitch and roll will be received from cellphone...

**Comment by sthalik** [comment]
Not unless someone contributes.
