### ISSUE TITLE
[bug] Toggle while held also works when just pressing that button.

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#434]
The toggle button also works when just pressing it once. Then the tracking stays in the stopped state. You can only undo this again by pressing the button for a longer time, then the tracking is starting again.

**Comment by sthalik** [comment]
Build: https://www.dropbox.com/s/2nlk6r5jtkqcrao/opentrack-2.3.0-test-20160831.7z

**Comment by sthalik** [comment]
Test build(s): https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa
