### ISSUE TITLE
The axes X, Y, Z. Manual tuning curves very rough. Too big step.

### ISSUE THREAD

**Issue by olegiy** [opentrack/opentrack#436]
Opentrack-2.3.0-rc11.  Mapping --> Mapping propeties --> The axes X, Y, Z
Manual tuning curves very rough. Snap -  big step.

**Comment by sthalik** [comment]
Mapping window translation smap got changed for rc12, X axis is now snapped to 1. Is Y snap of 5 too big for you?

**Comment by olegiy** [comment]
I do not have RC12 ((
To fine-tune want to disable the SNAP.

**Comment by olegiy** [comment]
Specifically near zero.

**Comment by sthalik** [comment]
Having at snap of at least 1 is good since games break if e.g. pitch is more than 90.

Build: https://www.dropbox.com/s/259fio91i97e0dm/opentrack-2.3.0-test-20160901.7z

Are you from the Russian Sturmovik community? I saw the thread via Google Translate. You can share bugs rather than using old builds. 

cheers

**Comment by sthalik** [comment]
@olegiy also check the third way to center, called experimental for cameras.

**Comment by olegiy** [comment]
Ок. 
Version opentrack-2.3.0-test-20160901. 
1. All old values "Mapping propeties" returned  to default
2. Manual tuning curves very rough. Big Snap step.
https://yadi.sk/d/QiWZxwF4ufrwj
3. Alignment settings - error not found.

**Comment by sthalik** [comment]
I haven't yet written a mapping migration function. it'll come later before rc12. 

The video doesn't open on this wifi but I'll fix it once i get home. 

What isn't found?

**Comment by olegiy** [comment]
> @olegiy also check the third way to center, called experimental for cameras.

How does it work?  No anomalies have found.

**Comment by sthalik** [comment]
Is it better or the same as the regular method?

It centers each axis separately.

**Comment by sthalik** [comment]
Tag relates to original snap issue. Snap now set to 1 for both X and Y.

**Comment by sthalik** [comment]
Test build(s) - https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa

**Comment by olegiy** [comment]
The axes X, Y, Z . Сan you make a snap step even less?

**Comment by sthalik** [comment]
They snap by merely one degree now.

**Comment by olegiy** [comment]
Only axes X, Y, Z
https://youtu.be/0NaTFYWGCb0

**Comment by sthalik** [comment]
Is half of that fine?

With 1 pixel Y on ypr it's too hard to get e.g. exactly 90 pitch.

**Comment by olegiy** [comment]
Interested area around zero.

**Comment by sthalik** [comment]
@olegiy is this good now? https://github.com/opentrack/opentrack/wiki/experimental-builds

**Comment by olegiy** [comment]
Nice!!! Thanks )

**Comment by sthalik** [comment]
:)
