### ISSUE TITLE
import opencv's aruco version

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#437]
It has better code quality than original aruco.

See: https://github.com/opencv/opencv_contrib/tree/master/modules/aruco

**Comment by Tux0Topo** [comment]
Can't wait to try this!!!

**Comment by NobleWizard** [comment]
How do I put it into OpenTrack?

**Comment by sthalik** [comment]
That version is worse. I already had it running.

**Comment by Tux0Topo** [comment]
What happen?

**Comment by sthalik** [comment]
It doesn't improve on aruco.
