### ISSUE TITLE
[RFC] tracker, filter, protocol in scripting langs

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#438]
Do you want the ability to write aforementioned stuff in other languages? I know @DaMichel prototypes math stuff in Python.

Less of a "it'd be good if", more of a "I want to write one".

**Comment by DaMichel** [comment]
I'm fine with how it is. The nice thing about writing self-contained prototype programs is that one can easily generate test-cases and do all sorts of analysis. 
I think, once one is satisfied, it is relatively easy to port something to C++.

**Comment by sthalik** [comment]
Agreed.
