### ISSUE TITLE
Output remap not saved (2.0.3. rc11)

### ISSUE THREAD

**Issue by nosefish** [opentrack/opentrack#439]
I swapped pitch and yaw source and inverted yaw on the Output tab of the Options dialog. None of these were saved in the configuration file.
I edited configuration file to the expected values and the change was loaded correctly.

**Comment by sthalik** [comment]
See if it works in the dev build - https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa

**Comment by nosefish** [comment]
Works, thanks.
