### ISSUE TITLE
Question about multiple cameras...

### ISSUE THREAD

**Issue by Tux0Topo** [opentrack/opentrack#451]
So... is there any chance to make it happen?

**Comment by Forsaken-Player** [comment]
Would be great!!!

**Comment by Emton** [comment]
Do you mean like multiple cameras to increase the FOV?

**Comment by Tux0Topo** [comment]
Increase the fov? Didn't think about it, but could be an interesting idea... but no.
I'm talking about using 2 or 3 cams (or more), so the tracker can be identified when we turn more than 90 degrees.

**Comment by sthalik** [comment]
Not unless someone sends code for review.

**Comment by SkeleCrafter** [comment]
That's going to require some complex code with all this paralax shiz and comparing values and mapping 3d spaces. I don't even know how to code but it already sounds quite like a huge deal although, PSMoveservice does do this.

**Comment by sthalik** [comment]
@SkeleCrafter there are multiple state-of-the-art perspective solvers. We use one already in Aruco.

**Comment by SkeleCrafter** [comment]
Aruco is the AR code looking thing right? We could use that for having multiple cameras in that case correct? Open source positional tracking sounds awesome.
