### ISSUE TITLE
Lag/smoothing in Accela

### ISSUE THREAD

**Issue by H-Bear-22** [opentrack/opentrack#452]
G'day, 

I am using 2.3-rc99p11 and seem to have a problem with excessive lag/smoothing.

I am using Joystick Input/Freetrack2.0 Enhanced/Accela and it takes ~2 seconds for an axis to pan from full left to full right. There is no noticeable lag in the joystick properties display.

If I adjust the smoothing slider in the Accela properties it appears to have no effect on the amount of lag/smoothing.

Thank you for your help,

Bear

**Comment by sthalik** [comment]
The maximum absolute value in degrees is capped. Can you use Kalman or no filter at all for the joystick device?

**Comment by sthalik** [comment]
Maybe we can rescale the input in the joystick tracker. But Accela needs a sensibly capped max value.

**Comment by sthalik** [comment]
> If I adjust the smoothing slider in the Accela properties it appears to have no effect on the amount of lag/smoothing.

It's controlled by the sensitivity slider.

**Comment by sthalik** [comment]
@H-Bear-22 see #454. The cap is now the same.
