### ISSUE TITLE
translation compensation needs a better name

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#461]
The name for "translate after rotate" is `"translation compensation"`. This name sucks. Please help me and find a better name.

**Comment by sthalik** [comment]
@MathijsG @DaMichel @dbaarda  ideas?

**Comment by MathijsG** [comment]
Let me think aloud. Something like 'Tracking order' and instead of on off you talk about Pitch,yaw, roll axes first, or X, Y, Z first.

Will keep this in mind when I know something even better :-P

**Comment by Sone989** [comment]
Do you want it to be more understandable for an average user (straightforward, even if not exactly precise)?

**Comment by MathijsG** [comment]
I never really understand the functionality in-depth. Is it mostly just for looking backward AND zooming? Maybe we then can focus on that functionality in the naming.

Like some kind of option button with a question: "When looking behind, you will zoom-in with fysically moving:

- Away from camera
- Closer to camera

**Comment by Sone989** [comment]
Not only.
Notice, that whenever you move your head to the left (raw) in X axis, your avatar will close his head to the left wing. Now let's first rotate backward (180 deg output) - your left wing is now on the right side of your head. This means that X rotation got reversed (simplyfying here) in relation to looking forward.
So, whenever you're looking backwards, moving your head over the left side of the headrest will require you, to translate X to the right. At least that's what your brain will tell you to do. Without compensation your avatar will be "locked" to understanding translation as always looking forward.

With option on, no matter where you look, thetranslation output will get dynamically recalculated to ensure the in-game movement takes into account the direction you are facing. That's how dynamic translation came to my mind. While not that precise, it's for sure a more straightforward name.

I'll keep thinking ;)

**Comment by MathijsG** [comment]
So something like "relative left and right" and "absolute left and right"?

**Comment by Sone989** [comment]
Yes, exactly. And of course it also corresponds othe translation axes.

**Comment by Sone989** [comment]
Actually, relative translation sounds good as well ;)

**Comment by sthalik** [comment]
That makes sense, thanks. Relative/absolute translation it is.

**Comment by MathijsG** [comment]
#nitpick but can you also change the name in Options -> Shortcuts the bottom one.
