### ISSUE TITLE
Opentrack freeze when i try start in game 2

### ISSUE THREAD

**Issue by kzfr** [opentrack/opentrack#472]
"I fix random crashes by clear registry, now i can run everytime opentrack and start without freezes, when i close opentrack a dummytrack in taskmanager is close too. But now i must find way to work with games
I found the fix, i use on game and opentrack a "Run as Administrator" now my DCS was detect "Black Shark" on opentrack!"

Today when i start pc a problem come back. Again opentrack get freezes after click start. 
Any idea? Dont work start"Run as Administrator" Dummytrack again stay in task after closing opentrack.

Maybe problem is here? http://imgur.com/a/gogTe

**Comment by sthalik** [comment]
comment on the same thread, it's not locked or anything.
