### ISSUE TITLE
Aruco pose solver broken in rc13

### ISSUE THREAD

**Issue by Emton** [opentrack/opentrack#474]
Pitching up seems to make the octopus go crazy on several axis, but especially pitch (jumping to negative, won't go past a certain amount) Yawing right has similar issue but yawing left doesn't seem to have the problem. RC12 seems to work ok, let me know if you want some data or if someone else has noticed the same thing?

**Comment by 503Kento** [comment]
I've been having the same issue since RC11 See #426 

I have not had a chance to try RC13 yet.

**Comment by sthalik** [comment]
@503Kento your marker's mounted upside down as per roll value. Also recommend you add more pitch since you pitch down up to -8. Don't go below 22 pitch when looking down.

**Comment by Emton** [comment]
Well I'm keeping positive pitch, the marker should be mounted the correct direction (last time you told me to flip it which I did) RC12 works ok.

**Comment by sthalik** [comment]
@Emton I was referring to his marker. As for yours, send me another video please. Use heavy lossy compression.

**Comment by Emton** [comment]
I can send a small video file of raw data that is 7.8mb or I can send some extra videos that show the opentrack window and compares between RC12 and RC13 so you can see what I mean, the total for that is 29mb do you want all the videos or just the small one?

**Comment by sthalik** [comment]
Send the raw file please.

**Comment by Emton** [comment]
http://www.filedropper.com/rawdata let me know if you don't see the issue I can send these views of the opentrack window that show the problem

**Comment by sthalik** [comment]
@Emton read the aruco wiki page and especially the last paragraph. I'll add a link to this wiki page to prevent further confusion like this.

**Comment by Emton** [comment]
Buddy I've read the last paragraph of the aruco page over and over I've used open track for months, I used it for months, why does it work in RC12 and not in RC13?

**Comment by Emton** [comment]
Do you want to see the video of my open track window? I'm using the EXACT same settings from RC12, in RC13 it simply doesn't work at all...

**Comment by sthalik** [comment]
@Emton now I do. Fixing.

**Comment by sthalik** [comment]
Unsurprisingly it works now, as per the commit. Get the build. Thank you for finding this before 2.3.0 got released. Now quite a few people use Aruco.

https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa

Just confirm it and we're good to go.

**Comment by sthalik** [comment]
Good news is that now our opencv changes are easy to rebase. They'll persist with little to no work on my side.

**Comment by Emton** [comment]
It works now

**Comment by 503Kento** [comment]
Works not for me as well
