### ISSUE TITLE
Problem with camera offset.

### ISSUE THREAD

**Issue by xAK3Dx** [opentrack/opentrack#478]
So here's the problem. I used facetrack no IR with point tracker and accela filter about year, and now i want to try out new accela filter, as many ppl sayed it's much better than mk1 version i got in payed ftrack v200... i got cap and ps3 eye camera. In ftrack in pointtracker settings i set camera pitch to 20 degrees and everything was good. In opentrack i can't find solution to camera angle. Angle in otpions menu doesnt give same effect as pitch in ftrack... Example - when i set pitch in Otrack - and move on z axis to tv - i move up, not forward... When i set pitch to -20 , z axis work good , all translations are good, but when i use yaw axis - there is roll coming , just as if camera pitch was on 0... thats pretty much unusable... there is no camera angle in pointtracker setup , and setup from main options doesn't work... what should i try?

**Comment by sthalik** [comment]
I get up to 5 degrees roll difference when yawing left to right. Are you sure you have the camera centering mode set in options?

**Comment by xAK3Dx** [comment]
i got -40 to +40 roll from left to right ((( Well do you mean ' Centering method'? it is default value , but i tried all 3 of them.. In other options only thing i changed in camera - is pitch angle with no results for roll... It works for transition though - my z axis work good with camera pitch , but it doesn't affect roll on yaw... Or i miss something?

**Comment by sthalik** [comment]
What's your neutral rotation? That is, when looking forward at your display.

Compare with an older release, in particular rc7.

**Comment by xAK3Dx** [comment]
Neutral roll u mean? it's 0... Where i can find older release? seen here only code, but no installer:

https://github.com/opentrack/opentrack/releases/tag/opentrack-2.3-rc7

**Comment by sthalik** [comment]
https://github.com/opentrack/opentrack/releases/tag/opentrack-2.3-rc49p7

**Comment by xAK3Dx** [comment]
ok i'll check that evening!

**Comment by xAK3Dx** [comment]
Just tested build u gave... same problems occur...

**Comment by xAK3Dx** [comment]
okay, tested one more time and got these results: with centering method "relative" i occur no roll with yaw, but now z transition got parasite y transition... see here:
https://www.youtube.com/watch?v=DNnkOHdqf44&feature=youtu.be

**Comment by sthalik** [comment]
@xAK3Dx you need to fine-tune the pitch value so that moving forward is treated as moving more-or-less perfectly forward. It's not a bug.

**Comment by xAK3Dx** [comment]
I would agree, but 1st - i haven't ghot this issue in freetracknoir, and 2nd - how it could be not error if camera doesn't at 0 angle to clip and moving front to it should give y and z transition without camera transition setup? as i see it - seems that transitions aren't connected with camera offset setting. So when i correct yaw/roll problem - transition problem pops up...

**Comment by xAK3Dx** [comment]
At my video at 1:00 u can notice that Y transition doesn't work at all also...

**Comment by sthalik** [comment]
The camera angle may not have the same effect in relative mode. All movements are, relative -- to the model's center position and not camera's up, down.

**Comment by xAK3Dx** [comment]
So than i should use not relative , but absolute centering method?

**Comment by sthalik** [comment]
Yeah.

**Comment by sthalik** [comment]
Is it any different if you position the camera on the display?

**Comment by sthalik** [comment]
Also does roll change on raw data or only on tracker output?

**Comment by xAK3Dx** [comment]
ill try to set camera on tv... but that will be tough... i ll check and reply than.. I use 52" tv as monitor... so canera will be or very low as it is now , or very high , but i 'll try anyway.

**Comment by sthalik** [comment]
Please answer the raw data question also.

At the very least it's interesting how moving the camera will affect the data.
