### ISSUE TITLE
move to xinput from dinput

### ISSUE THREAD

**Issue by jojom4n** [opentrack/opentrack#479]
On Windows 10, if you press CTRL+ALT+CANC and then you select "Cancel" in the screen that appears or any other entry (like "Task Manager"), the "Center" shortcut in Opentrack does not work anymore (2.3p11 release).

**Comment by Len62** [comment]
Just tested and same thing happens in RC13. Ctl-alt-del then hit cancel and OT center shortcut (shift+joy button on my setup) stops working.

**Comment by sthalik** [comment]
I can confirm that. After ctrl+alt+delete the ctrl and alt keys get stuck from opentrack's perspective.

We should be using xinput anyway since dinput is deprecated for a time now.

A workaround is to tap ctrl, alt, shift, having it return back to not held state.

**Comment by Len62** [comment]
Ah, did not know about the ctrl-alt-shift! Thanks.

**Comment by sthalik** [comment]
I'm leaving the issue open and hijacking it as "use xinput rather than dinput".

**Comment by sthalik** [comment]
xinput can't be used. There's no benefit and it doesn't even support keyboards...

**Comment by sthalik** [comment]
See: https://en.wikipedia.org/wiki/DirectInput#DirectInput_vs_XInput
