### ISSUE TITLE
freetrack 2.0 Enhanced refuses to work with Elite: Dangerous

### ISSUE THREAD

**Issue by amadeus1171** [opentrack/opentrack#483]
It was working one day and the next, nothing.

I'm using EDtracker as the joystick input with the correct axes mapped.
Output is freetrack 2.0 Enhanced.

I've tried uninstalling/reinstalling.
I've tried choosing from the LocateDLL option, both the 64 and 32 bit versions.
I've tried all the variations of Use/Hide FreeTrack/TrackIR
I've tried changing permissions.
I've tried turning off the MCaffee Virus checker and firewall.
I've tried opening up ports.
I've tried running as administrator.
I've tried the calibrated elbow.

Nothing seems to fix the problem.

I've run freetracktest.exe, and it does show that it's receiving vectors.  But Elite: Dangerous simply does not want to work with it anymore.  It's driving me nuts!  Other than the above mentioned, I hadn't changed a thing before it mysteriously stopped working.

What am I doing wrong?

**Comment by MathijsG** [comment]
Do any of the builds here: https://github.com/opentrack/opentrack/releases work or won't they all?

**Comment by sthalik** [comment]
Install opentrack on the same partition as ED.

**Comment by amadeus1171** [comment]
I only have one partition for the OS and everything else.  I will try previous builds.  But as I said, it worked previously but then suddenly stopped.  And I have tried previous builds at one point or another as they're released.

**Comment by sthalik** [comment]
Use the installer in case you used the archive.

**Comment by amadeus1171** [comment]
I used the installer.
I didn't use a previous version.  I remembered something that I did before that made it work.  I created an empty profile and didn't modify it, and it worked!  I then switched back to my Elite: Dangerous profile and it continued to work.  What the heck?!

**Comment by amadeus1171** [comment]
I'm going to include two profiles.  One is test.ini and the other is elite dangerous.ini

test.ini works when I start Elite: Dangerous with opentrack already running.
elite dangerous.ini does not work with opentrack already running, not running, w/e.

I have to start Elite: Dangerous with the test.ini profile, and once Elite: Dangerous starts, I switch over to the elite dangerous.ini profile and it continues to work.  Can anyone figure out what's going on here?

test.ini
`[migrations]
last-migration-at=20160917_00~

[modules]
tracker-dll=Joystick input

[tracker-joystick]
axis-map-1=0
axis-map-2=0
axis-map-3=0
axis-map-4=2
axis-map-5=3
axis-map-6=4
joy-guid={ACC24E70-A80B-11E5-8002-444553540000}

[opentrack-ui]
center-at-startup=true
compensate-translation=true
use-camera-offset-from-centering=false
x-source-index=0
y-source-index=1
z-source-index=2
`

elite dangerous.ini
`[Curves-tx]
point-count=1
point-0-x=100
point-0-y=45

[HT-Tracker]
camera-name=Logitech HD Pro Webcam C910
fov=56
fps=0
resolution=1

[keyboard-shortcuts]
keycode-center=Alt+F12
keycode-toggle=Ctrl+F12
keycode-zero=Shift+F12

[opentrack-ui]
camera-pitch=0
camera-roll=0
camera-yaw=0
center-at-startup=false
compensate-translation=false
compensate-translation-disable-z-axis=false
filter-dll=Accela
pitch-alt-axis-sign=false
pitch-invert-sign=false
pitch-source-index=4
pitch-zero-pos=0
protocol-dll=freetrack 2.0 Enhanced
roll-alt-axis-sign=false
roll-invert-sign=false
roll-source-index=5
roll-zero-pos=0
tracker-dll=Joystick input
use-system-tray=false
x-alt-axis-sign=false
x-invert-sign=false
x-source-index=3
x-zero-pos=0
y-alt-axis-sign=false
y-invert-sign=false
y-source-index=3
y-zero-pos=0
yaw-alt-axis-sign=false
yaw-invert-sign=false
yaw-source-index=3
yaw-zero-pos=0
z-alt-axis-sign=false
z-invert-sign=false
z-source-index=4
z-zero-pos=0
button-center=-1
button-start-tracking=-1
button-stop-tracking=-1
button-toggle=-1
button-toggle-tracking=-1
button-zero=-1
centering-method=1
guid-center=
guid-start-tracking=
guid-stop-tracking=
guid-toggle=
guid-toggle-tracking=
guid-zero=
keycode-center=Ctrl+F12
keycode-start-tracking=
keycode-stop-tracking=
keycode-toggle=Ctrl+Shift+F12
keycode-toggle-tracking=
keycode-zero=
button-restart-tracking=-1
button-toggle-press=-1
button-zero-press=-1
guid-restart-tracking=
guid-toggle-press=
guid-zero-press=
keycode-restart-tracking=
keycode-toggle-press=
keycode-zero-press=
use-camera-offset-from-centering=true

[proto-freetrack]
use-memory-hacks=false
used-interfaces=1
close-protocols-on-exit=false

[udp-tracker]
add-pitch=0
add-roll=0
add-yaw=0
port=5550

[Curves-tx_alt]
point-count=1
point-0-x=100
point-0-y=100

[Curves-ty]
point-count=1
point-0-x=100
point-0-y=100

[Curves-ty_alt]
point-count=1
point-0-x=100
point-0-y=100

[Curves-tz]
point-count=1
point-0-x=100
point-0-y=100

[Curves-tz_alt]
point-count=1
point-0-x=100
point-0-y=100

[Curves-rx]
point-count=1
point-0-x=36
point-0-y=180

[Curves-rx_alt]
point-count=1
point-0-x=23.76578645235362
point-0-y=180

[Curves-ry]
point-count=1
point-0-x=28
point-0-y=180

[Curves-ry_alt]
point-count=1
point-0-x=180
point-0-y=180

[Curves-rz]
point-count=1
point-0-x=100
point-0-y=180

[Curves-rz_alt]
point-count=1
point-0-x=180
point-0-y=180

[tracker-joystick]
axis-map-1=0
axis-map-2=0
axis-map-3=0
axis-map-4=2
axis-map-5=3
axis-map-6=4
joy-guid={ACC24E70-A80B-11E5-8002-444553540000}
joy-id=EDTracker Pro

[Accela]
ewma=20
rotation-deadzone=25
rotation-threshold=5
translation-deadzone=0
translation-threshold=50

[mouse-proto]
mouse-x=4
mouse-y=5

[udp-proto]
ip1=127
ip2=0
ip3=0
ip4=1
port=5550

[accela-sliders]
ewma=@Variant(\0\0\0\x7f\0\0\0\x16options::slider_value\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0@>\0\0\0\0\0\0)
rotation-deadzone=@Variant(\0\0\0\x7f\0\0\0\x16options::slider_value\0?\x9e\xb8Q\xeb\x85\x1e\xb8\0\0\0\0\0\0\0\0@\0\0\0\0\0\0\0)
rotation-nonlinearity=@Variant(\0\0\0\x7f\0\0\0\x16options::slider_value\0?\xf0\xcc\xcc\xcc\xcc\xcc\xcd?\xf0\0\0\0\0\0\0?\xf8\0\0\0\0\0\0)
rotation-sensitivity=@Variant(\0\0\0\x7f\0\0\0\x16options::slider_value\0?\xe0\0\0\0\0\0\0?\xa9\x99\x99\x99\x99\x99\x9a@\x14\0\0\0\0\0\0)
translation-sensitivity=@Variant(\0\0\0\x7f\0\0\0\x16options::slider_value\0?\xa9\x99\x99\x99\x99\x99\x9a?\xa9\x99\x99\x99\x99\x99\x9a?\xf8\0\0\0\0\0\0)
translation-deadzone=@Variant(\0\0\0\x7f\0\0\0\x16options::slider_value\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0?\xf0\0\0\0\0\0\0)

[migrations]
last-migration-at=20160917_00~

[modules]
filter-dll=Accela
protocol-dll=freetrack 2.0 Enhanced
tracker-dll=Joystick input

[opentrack-mappings]
pitch-alt-axis-sign=false
roll-alt-axis-sign=false
x-alt-axis-sign=false
y-alt-axis-sign=false
yaw-alt-axis-sign=false
z-alt-axis-sign=false

[spline-X]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x1@>\0\0\0\0\0\0@>\0\0\0\0\0\0)

[alt-spline-X]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x1@>\0\0\0\0\0\0@R\xc0\0\0\0\0\0)

[spline-Y]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x1@>\0\0\0\0\0\0@$\0\0\0\0\0\0)

[alt-spline-Y]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x1@>\0\0\0\0\0\0@R\xc0\0\0\0\0\0)

[spline-Z]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x1@>\0\0\0\0\0\0@>\0\0\0\0\0\0)

[alt-spline-Z]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x1@>\0\0\0\0\0\0@R\xc0\0\0\0\0\0)

[spline-yaw]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x3@(\0\0\0\0\0\0@[\xc0\0\0\0\0\0@.\0\0\0\0\0\0@d\0\0\0\0\0\0@1\0\0\0\0\0\0@f\x80\0\0\0\0\0)

[alt-spline-yaw]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x1@7\xc4\n\x94\xb8\x94#@f\x80\0\0\0\0\0)

[spline-pitch]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x2@*\0\0\0\0\0\0@U\x80\0\0\0\0\0@0\0\0\0\0\0\0@f`\0\0\0\0\0)

[alt-spline-pitch]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x1@f\x80\0\0\0\0\0@f\x80\0\0\0\0\0)

[spline-roll]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x1@Y\0\0\0\0\0\0@f\x80\0\0\0\0\0)

[alt-spline-roll]
points=@Variant(\0\0\0\x7f\0\0\0\xfQList<QPointF>\0\0\0\0\x1@f\x80\0\0\0\0\0@f\x80\0\0\0\0\0)
`

**Comment by sthalik** [comment]
`used-interfaces=1`

Either 2 or 0

**Comment by amadeus1171** [comment]
What?  Opentrack configured this.

**Comment by sthalik** [comment]
This isn't the default value. As you can see, empty config defaults to a value of 0.

**Comment by amadeus1171** [comment]
My question, though, is why did Opentrack configure an invalid value?

**Comment by sthalik** [comment]
You selected it in freetrack protocol options -- protocol visibility list.

**Comment by amadeus1171** [comment]
...
...
...
Why does it offer an invalid value in the first place?  Forgive me, but that doesn't seem to make any sense.

**Comment by sthalik** [comment]
It makes sense for other games.
