### ISSUE TITLE
Configure OpenTrack with a phone

### ISSUE THREAD

**Issue by amadeus1171** [opentrack/opentrack#485]
This isn't a bug, but a feature request.

Is there an app that allows me to configure OpenTrack remotely using a phone?

The most annoying part of OpenTrack (I love it, btw) is when I have to configure mapping (yaw, pitch, roll, x, y, z).  I have to look around in the game and guess adjustments that need to be made, then switch back to OpenTrack, make the corrections, and back to the game again to see if the changes I made were what I wanted.  It would be so much easier to have an interface open in a phone and do the adjustment realtime while the game is up so I can immediately see what effect the change has had.

Is it possible to create something like this?  Not just for the mappings, but the filter settings and other things too.  Heck, make everything available.

**Comment by sthalik** [comment]
It's possible. But that's a lot of effort. No user interface code could be reused.
