### ISSUE TITLE
Request +-180 degree normalisation as an option.

### ISSUE THREAD

**Issue by H-Bear-22** [opentrack/opentrack#487]
G'day @sthalik 

I was wondering if the "Trackers submitting rotation over +-180 will have it normalized" mentioned in the release points for rc13 could be made a user-selected option?

I have checked the output csv and found that my joystick input device provides a raw maximum input of 180.003 which is 'normalized' to -1

85.635, effectively switching my view from full right to full left when my head is turned fully to the right.

I just have a 'normal' setup with one monitor in front of me.

Thanks for your time,

 - Bear

[test.zip](https://github.com/opentrack/opentrack/files/568214/test.zip)

**Comment by sthalik** [comment]
This is a rounding bug.

Please see if the joystick build fixes. https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa

**Comment by sthalik** [comment]
In this build

- joystick is clamped to -180->180
- overall, trackers need to be over +-180.01 to break

**Comment by sthalik** [comment]
There's a rounding error in dinput code. Fixed.

**Comment by sthalik** [comment]
I confirmed it works with my own joystick.

**Comment by H-Bear-22** [comment]
Perfect!

Thank you very much for your work @sthalik 

 - Bear

**Comment by sthalik** [comment]
Thanks for confirmation.
