### ISSUE TITLE
Using mapping profiels from older releases

### ISSUE THREAD

**Issue by IvanDolvich** [opentrack/opentrack#490]
For a long time I was using Opentrack 2.3 rc21p11. One reason for doing that and not using a later release was that I could not use my mappings for the axis from my older version. The profile is shown and can be selected but it has no influence on the mapping properties. They are still the preset defaults. Did anyone run into the same problems and can help me solving this?

**Comment by Len62** [comment]
I thought that RC12 implemented migration of settings, however, I think the mapping has been updated since RC12, so maybe that broke the migration?

**Comment by IvanDolvich** [comment]
The settings for camera resolution, camera offset etc. are ported to the new version...

**Comment by Len62** [comment]
Right, but possibly, due the changes in the mapping, the migration does not work on the mappings. I'm sure @sthalik  will chime in soon.

**Comment by sthalik** [comment]
Remove the rc11 mapping sections before updating to rc12. Otherwise rc12 won't migrate cause it'll consider new mappings to exists.

**Comment by sthalik** [comment]
I'll add a warning to the rc11 page.

**Comment by sthalik** [comment]
That is -- the new sections are binary data as `Variant`. You'll find six of them.
