### ISSUE TITLE
[X-Plane] OpenTrack and dual monitors 

### ISSUE THREAD

**Issue by Denco96** [opentrack/opentrack#493]
I'm using dual monitors setup for X-Plane and I've noticed that when using TrackIR the view doesn't move in sync which causes eye strain. One monitor moves faster that the other. The issue is not present if I use my mouse to view around the cockpit. I'm using Delan Clip with Open Tracker Input. I use my two monitors in the extended mode using a custom resolution of 4480x1080.
http://i.imgur.com/MtA4PfW.jpg

Can anyone lend any advice on this problem?

**Comment by Denco96** [comment]
I think this happens because of the FOV distortion. Will report back once I find out more.

**Comment by sthalik** [comment]
Are you using PilotView? You should.

**Comment by Denco96** [comment]
I'll give it a go. Otherwise I'm using X-Camera.

**Comment by sthalik** [comment]
How is it?

**Comment by Denco96** [comment]
After some searching online I think I've discovered a possible reason why this is happening and it's entirely unrelated to Open Track. Because the monitors are run using the extended mode, instead of the surround mode, it is possible that the fps are not the same on both monitors which could cause the anomalies I'm experiencing.

**Comment by sthalik** [comment]
I hope it works for you in the end. I'm closing the issue since it's unrelated to opentrack.
