### ISSUE TITLE
Unable to start Rift tracker: Unknown reason   Oculus CV1

### ISSUE THREAD

**Issue by Jinchok** [opentrack/opentrack#498]
Hy i have this problem with my Occulus CV1 cant find the issue ... : Unable to start Rift tracker: Unknown reason

**Comment by Piffx1** [comment]
The latest runtime is currently not compatible. From the next version, it will probably be implemented.
Greeting Piff

**Comment by sthalik** [comment]
Doesn't it work with 0.8.0?

**Comment by Jinchok** [comment]
Not at all

Le 29 nov. 2016 12:24 PM, "Stanisław Halik" <notifications@github.com> a
écrit :

**Comment by sthalik** [comment]
What is the SDK version for CV1?

**Comment by Piffx1** [comment]
Oculus SDK for Windows V1.10.1

**Comment by sthalik** [comment]
It was verified our 1.10 works.
