### ISSUE TITLE
source files for translation

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#500]
Hi,
I'd like to do Czech location for Opentrack. I have to use some special sw? Pet

**Comment by MathijsG** [comment]
I just forked this repo and grabbed the Russian file from here: https://github.com/opentrack/opentrack/tree/unstable/gui/lang and editted it with a text editor (like Notepad++) and then did a pull request.

**Comment by sthalik** [comment]
See https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa for translation stubs.

**Comment by petsild** [comment]
Hi,
i have translated the Gui into the Czech language. Probably will want to, where appropriate correction of the text. Like it before the release of the big test. Write please what can I do thank you. Pet
[cz_CZ.txt](https://github.com/opentrack/opentrack/files/673211/cz_CZ.txt)

**Comment by sthalik** [comment]
@petsild @MathijsG you now have .ts files in all releases in the `source-code/` subdirectory.

**Comment by sthalik** [comment]
@petsild please send as pull request.
