### ISSUE TITLE
missing robust cap point ordering code

### ISSUE THREAD

**Issue by peterek1983** [opentrack/opentrack#504]
Why when I invert my cap out of camera view for a moment and back then program lost calibration and everything is mess all axes are bad inverted ?

How to fix that ?

In Freetrack program there is no problem like this, I can go away from computer and get back and everything is fine.

So this is very big bug in opentrack, and should be fixed as fast as possible.

Also what I noticed, for example when I move out of view of my camera opertrack should keep last view when all points was.
Also Freetrack in this situation work as should.

**Comment by sthalik** [comment]
It's the "dynamic pose resolution" option. A fix for the situation is to cover a single LED from the camera for its timeout's duration.

A solution for this would be code able to differentiate the points without having known where they were previously. I have thought about this but I'm not entirely sure it's possible. I'll give it a try in the indeterminate future but don't wait on it.

**Comment by peterek1983** [comment]
Cover one single LED it's not a solution for me :) 
Why in Freetrack there is no problem like this, this should be first on list to fix, with this bug opentrack it's no useable for me, sorry :(

In Polish - Proszę zajmij sie tym ;) byłoby super jakby to się udało poprawić bo to jest nie do przyjęcia żeby takie cuda sie działy jak sie odejdzie od monitora i wróci. Pozdrawiam

**Comment by sthalik** [comment]
Nie, zakryć aż się zresetuje i puścić.

Po pierwsze primo, ja nie mam z tego kasy. Po drugie primo, nie zawsze jestem w stanie pisać. Po trzecie primo, kto inny może napisać i wysłać pull request.

**Comment by sthalik** [comment]
Po czwarte primo, to nie jest bug tylko nieprzyjemne ograniczenie.

**Comment by sthalik** [comment]
No i jeszcze dodam, że to nie jest trywialne rozróżnić punkty - jak spojrzysz w górę czapką to środkowy jest na górze a nie na dole. Jak spojrzysz w bok to środkowy nie jest na środku, etc.

**Comment by sthalik** [comment]
freetrack miał też takie samo rozróżnianie punktów. Miał też szukanie środkowego na podstawie jego wysokości w ramce od kamery ale to nie zawsze jest poprawne. Ciężko się czyta tego Pascala ale tak jest.

Ustawisz sobie stabilność ruchu parametrami Acceli. Daj "rot nonlinearity" na 1.1, sensitivity na mniej, deadzone na 0.03, smoothing na 2-5 ms. Nawet przy bardzo zaszumionych danych wejściowych zadziała jak dobrze pokręcisz gałkami.

Oczywiście najważniejsze jest żeby model miał wymiary zgodne z klipsem.

**Comment by peterek1983** [comment]
Super wielkie dzięki za sugestie odnośnie ustawień, czapkę mam zrobioną z odblaskami myślę wzorowo, czyli odległości domyślnie jak dla Capa 3 punktowego w programach + A4Tech PK333E. Testuje obecnie w American Truck Simulator :)

**Comment by peterek1983** [comment]
Kombinuje na rózne sposoby i nie moge uzyskać płynności Freetracka, tzn ogólnie nie jest zle, ale Opentrack ma pewną tendencje do przeskakiwania minimalnego w ruchu niezależnie co by sie nie ustawiło w ustawieniach Acceli.

Tutaj mozesz zobaczyć o co mi chodzi ustawiony minimalny łagodny deadzone na początku na dole osi i kulka w programie na krzywej chodzi po tych idealnie gładko jednak w grze jest mały skok na przejściu jakby schodek
https://youtu.be/g4Kyk18VnFE

We Freetracku podobna krzywa i nie ma takiego przeskoku jest tylko jakby w tym miejscu łagodne zwolnienie 

Nawet jak ustawie liniowość całkowitą na krzywej to podczas ruchu dostrzegam mikroskopijne przeskoki jakby przyspieszanie i zwalnianie na osi, oczywiście mozliwe ze mój ruch głową wtedy nie jest idealnie równy ale nie moge tego skorygować ustawieniami Acceli aby było ultra łagodnie i płynnie jak we Freetracku.

Nie orientujesz sie co brakuje Freetrackowi ze nie chce w niektórych grach działać, od taki Dirt 3, w OpenTracku działa we Freetracku juz nie, pomimo ze mam dograny plik NPClient64.dll.

**Comment by sthalik** [comment]
To może być co innego. Prześlę builda niedługo.

**Comment by peterek1983** [comment]
OK super dzieki! czekam na builda...

**Comment by sthalik** [comment]
Builda z dzisiaj - https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa?dl=0

W facetracknoir do dzisiaj nie naprawili, że protokół, filtr etc. działają jedynie 66 razy na sekundę.

**Comment by peterek1983** [comment]
Dzieki piekne, zaraz biore sie za testowanie

**Comment by peterek1983** [comment]
Po szybkim porównaniu obu wersji powiem szczerze ze nie dostrzegam jakis różnic w ruchu, niestety nadal patrząc np. w kokpicie samolotu na zoomie na instrumenty rozgladając sie po ukosie prowadzenie nie jest równe po ukosie odczuwam takie jakby schodki w ruchu jakby coś przyciągało osie w ruchu ukośnym raz albo dla osi Yaw raz dla Pitch, mam nadzieje ze wiesz o co mi chodzi. Sprawdzam Freetracka i tam jest łagodniej nie ma czegoś takiego.
Bede jeszcze testował.

**Comment by sthalik** [comment]
Daj screena z ustawieniami acceli.

**Comment by peterek1983** [comment]
[https://s13.postimg.org/brqt65klz/Bez_tytu_u.png](url)

**Comment by sthalik** [comment]
Nonlinearity na 1.15 do 1.2. Deadzone na 0.03 do 0.06.

**Comment by peterek1983** [comment]
OK :) tak tez ustawie zaraz i potestuje
