### ISSUE TITLE
Open Track  headtracking with phone not working anymore

### ISSUE THREAD

**Issue by ErikGroen** [opentrack/opentrack#505]
Hello,

I am using opentrack now for a week and realy enjoyed playing with it but since today the software isn't getting any infomation from my phone anymore yesterday it was working fine i haven't changed anything please help me

Erik

**Comment by sthalik** [comment]
Disable the firewall temporarily and check ip address.

**Comment by ErikGroen** [comment]
ip address is right and i do not see the port 5555 in the firewall list

**Comment by ErikGroen** [comment]
please help me

**Comment by ErikGroen** [comment]
anyone???

**Comment by sthalik** [comment]
See if you can ping your phone's IP address.

**Comment by sthalik** [comment]
Also actually disable the entire firewall for a minute for testing.

**Comment by sthalik** [comment]
Finally, please don't make spammy posts like the last two of yours, please.
