### ISSUE TITLE
How to save data to RAM

### ISSUE THREAD

**Issue by PintsizedSix40** [opentrack/opentrack#506]
Hi, I'm wondering if it is possible to save the Yaw Pitch and Roll values to the RAM so I could access them using another program.
Thanks.

**Comment by sthalik** [comment]
Use the freetrack protocol as it is right now.

**Comment by PintsizedSix40** [comment]
But than how would I get the values?

**Comment by sthalik** [comment]
See https://github.com/opentrack/opentrack/tree/unstable/freetrackclient

**Comment by PintsizedSix40** [comment]
sthalik:
> See https://github.com/opentrack/opentrack/tree/unstable/freetrackclient

What do you mean?
I'm trying to get RAM addresses for the tracking values.

**Comment by sthalik** [comment]
See the linked directory for mapping name and data layout.

**Comment by PintsizedSix40** [comment]
Where?

**Comment by sthalik** [comment]
The link I gave you.

**Comment by PintsizedSix40** [comment]
> sthalik:
 See the linked directory for mapping name and data layout.
 


> PintsizedSix40:
Where?

I mean where in https://github.com/opentrack/opentrack/tree/unstable/freetrackclient where do I find the mapping name and data layout?

**Comment by sthalik** [comment]
In the source file and the header file, respectively.

**Comment by PintsizedSix40** [comment]
Lol sorry for being this stupid.
