### ISSUE TITLE
Point Tracker with camera above

### ISSUE THREAD

**Issue by cutzmf** [opentrack/opentrack#510]
To be clear:
I have DIY HMD and camera mounted above me - I want 360 degrees yaw. I remapped axis Roll -> Yaw

Now I have an issue with new yaw axis(orig Roll) - it has error at (and above) 90 degrees.
Is it possible/hard to make a camera mount switch position (front/upper)?

**Comment by sthalik** [comment]
Do you have "dynamic pose resolution" set?

Does the model center, the red cross, jump abruptly at roll +- 90 deg?

**Comment by cutzmf** [comment]
1. "dynamic pose resolution" - i'll update later (but seems to be off)
2. model center really jumps abruptly at roll +- 90 deg

**Comment by sthalik** [comment]
Set dynamic pose to on with a sensible timeout -- no less than 500 ms.

**Comment by cutzmf** [comment]
I've switched on dynamic pose resolution.
With 500ms timer - i've got errors above 120 degrees.
Tried 700ms - got better angle (up to 150).
It seems to me I need to set  timer at 1000ms to get rid of errors at 180 degrees motion =)

Thank you!
I appreciate your work! =)

**Comment by sthalik** [comment]
I don't think this the correct solution but glad it at least works for you now.

If dynamic pose confuses itself, remember to cover one LED for the dynamic pose timeout's duration. It'll reset itself after you uncover it.

**Comment by cutzmf** [comment]
By the way, would it be too hard to implement feature "vertical mounted camera"?

**Comment by sthalik** [comment]
What for?
