### ISSUE TITLE
Oculus Rift runtime 1.10.1 HMD

### ISSUE THREAD

**Issue by huliqan** [opentrack/opentrack#512]
can You add the last 1.10.1 runtime oculus rift to opentrack 2.3?
**Oculus Rift runtime 1.10.1 HMD** needed

**Comment by sthalik** [comment]
Sure just give it some time.

**Comment by sthalik** [comment]
I'm gonna make a single Rift tracker with selectable SDK.

**Comment by huliqan** [comment]
it"s very cool!!!

**Comment by huliqan** [comment]
oops...
in opentrack 2.3 > input > Oculus Rift runtime 1.4.0 - HMD 
all works to last runtime 1.10.1!!!
everything is working !!! just my antivirus blocked the process :)))

**Comment by sthalik** [comment]
@huliqan stated that it works now using the 1.10 SDK. No need to make any changes.

"Persistence" is for older models with gyro drift.

**Comment by abhinaynatti** [comment]
it says" error occured while loading tracker Oculus Rift runtime 1.4.0 -- HMD" when I put it as input.Can you tell me what I missed here .Thank you.

**Comment by sthalik** [comment]
What's your API version?

**Comment by abhinaynatti** [comment]
2.3.10

**Comment by sthalik** [comment]
No, Rift SDK version. It was said that it works with 1.10 SDK, is there a new version?

**Comment by abhinaynatti** [comment]
Actually what I need is I need to analyze the  data of head movements(pitch etc. ). The values are getting stored in the csv file.  I don't actually know how it is tracking .

**Comment by abhinaynatti** [comment]
So I don't know how it takes into consideration of the oculus.

**Comment by sthalik** [comment]
It's `libopentrack-tracker-rift-140.dll` or another API version you chose. See the `tracker-rift-140/` subdirectory for the source code.

**Comment by abhinaynatti** [comment]
Hey can I ask from the start?This is more like a doubt than an issue. What I basically want is to analyze the  data of head movements when I'm using my VR headset . So what input should I be using and what software should I download. Sorry for the trouble.

**Comment by sthalik** [comment]
Read the "raw" column. You can draw a plot with libreoffice.
