### ISSUE TITLE
ArmA 3 64Bit Issue Question

### ISSUE THREAD

**Issue by Suppresed** [opentrack/opentrack#513]
Arma 3's Dev Branch had an update that made the game 64 bit. Headtracking is said to not work, can anybody confirm this?

**Comment by sthalik** [comment]
We support headtracking for 64-bit games.

See if it works without BattlEye. If it does, please send our NPClient64.dll to BattlEye.

**Comment by Emton** [comment]
I tried it with Battleye disabled but it still didn't work.

**Comment by sthalik** [comment]
Does it work for anyone at all, with trackir or something else?

**Comment by sthalik** [comment]
You can tell bohemia to look for "NPClient64" and use the same head tracking API as they did before.

**Comment by petsild** [comment]
ArmA 3 64Bit with OT work without problem.

**Comment by sthalik** [comment]
@petsild does it work with BE?

**Comment by petsild** [comment]
Tested on DB 1.67.139743

**Comment by sthalik** [comment]
:+1:

**Comment by okaryna** [comment]
I confirm after x64 patch of Arma3 opentrack stops work in version 3.4.1.
I am not sure it is Arma problem or opentrack settings.
Solution: in "FreeTrack 2.0 Enchanced "options set "User TrackIR, hide FreeTrack".

**Comment by sthalik** [comment]
Works for me also. BattlEye enabled.
