### ISSUE TITLE
Open track stopped working on games

### ISSUE THREAD

**Issue by Tafkaa** [opentrack/opentrack#514]
I've been using opentrack (with aruca paper tracking) for a while now and up until this morning it worked fine. Now, all of a sudden, none of my games seem to recognize that opentrack is running.  I have no idea what changed or how to fix it. Already tried reinstalling but that didn't help. To clarify; the tracking itself works fine (the octopus moves as expected) but in game there is no movement at all anymore.

Any ideas how to fix this?

**Comment by sthalik** [comment]
Use the freetrack protocol. Drop me a screenshot with the protocol settings.

**Comment by Tafkaa** [comment]
thanks for the reply. I am using the freetrack protocol (i think; this is all new to me). I hope this is the screenshot you are asked for:

![ftproto](https://cloud.githubusercontent.com/assets/24613263/21277940/e5be3e8e-c3d8-11e6-9594-273164d1483a.png)

**Comment by sthalik** [comment]
Set the first checkbox to "use both".

**Comment by Tafkaa** [comment]
I just tried it. Still nothing. Any other suggestions?

**Comment by Tafkaa** [comment]
Nevermind. I fixed it by removing opentrack (and every registry entry i could find that has anything to do with it), rebooting and reinstalling. Everything works again now. Thanks again for the help and time !

**Comment by sthalik** [comment]
For what it's worth, it started working because you started opentrack before running a game, after changing that particular protocol preference. Glad it works for you.
