### ISSUE TITLE
PS3 eye only runs at 30 FPS on Windows 8.1 

### ISSUE THREAD

**Issue by ajpoinsatte** [opentrack/opentrack#515]
Hi, Im having trouble getting the ps3 eye to run at more then 30 FPS with the acuro paper tracker, (i tested this issue and it seems to occur in point tracker as well ), However, with CL eye test I can get it running at 75 FPS no problem. Its only in opentrack. Anyone have any idea why? I even installed K-Lite mega codec pack and im still having the same issue. Thanks.

**Comment by Len62** [comment]
Have you tried adjusting the Aruco tracker settings?

**Comment by ajpoinsatte** [comment]
Yes, and it even says 60FPS in the top left corner but the video feed is definitely not 60 FPS.

**Comment by sthalik** [comment]
Video feed is always 20 Hz to reduce CPU load.

**Comment by ajpoinsatte** [comment]
Then why is there an option to select more then 20 FPS? its a little misleading.

**Comment by sthalik** [comment]
The software logic works on full Hz. The display on the software's main window doesn't update more often than 20 Hz.

**Comment by SkeleCrafter** [comment]
I agree. This is kind of misleading.

**Comment by sthalik** [comment]
Even if it is, there are other priorities regarding the video feed. The CPU usage on The Octopus and video feed both takes a large part of all the CPU usage.

On the other hand, in the not-yet-released hotfix, I changed the code to perform resizing in tracker's thread, not the user interface thread. Now even with lowered preview framerate it looks more responsive. Freeing the UI thread is mostly theoretical but actually the reason for more responsive interface.
