### ISSUE TITLE
Suggestion: switch from absolute to relative mode in-game

### ISSUE THREAD

**Issue by nicolaschaufette** [opentrack/opentrack#521]
by relative I mean the camera only moves when your head moves
some "mouse emulation" in early version of Track IR worked this way, where the cursor only moves when your head moves
why ? to improve precision when precision matters more than speed, for example when checking the gauges in the cockpit view and activate switches (EZdock does not exist for all games)
I could be implemented as an option in the filter, but a key should be available to activate/deactivate it in-game
what do you think ?

**Comment by sthalik** [comment]
Not without scripting. See #492. These kinds of requests are too specialized to implement in the core program.
