### ISSUE TITLE
No UI or activity after main .exe launch

### ISSUE THREAD

**Issue by Ounicron** [opentrack/opentrack#522]
I currently get no response from this program when executing under Windows 10.   Currently using the portable version (2.3.0-win32-portable) on a separate logical drive from the OS. The program starts, and there is a process listed in the Task manager, but no UI launches at any point and the process shows no CPU usage at all.  I've attempted all the standard procedures, run as Admin, Win 8/7 compatibility ect. and get the same response every time.

**Comment by Tux0Topo** [comment]
Check if the SmartScreen process is running in backgroun. If it's working, close it and wait a few second. If the app show, search about how to disable SmartScreen (it's easy, but don't remember how :p). If nothing happens, don't know....
Any change, please, comment.

**Comment by Ounicron** [comment]
Smartscreen has been long disabled on this box.  Unless it is requisite to Opentrack somehow, I don't believe it's the issue.

**Comment by sthalik** [comment]
Drop a backtrace of all threads please.

**Comment by MathijsG** [comment]
Isn't it hidden in the system tray?

**Comment by Ounicron** [comment]
Bizzaro occurrence: I ran it.  Same behavior as reported priorly.  I opened process explorer to get a backtrace of it, and when I fired up the process explorer it launched perfectly.  It now launches regularly every time.  I'll try to catch it in the act if it does it again, but for now I have nothing to chase down.  My apologies for the apparently false alarm.

**Comment by ouoertheo** [comment]
I had this issue and I use Moonlight/Geforce Experience. When I had moonlight connected, I ran into this behavior. Going to open a new bug for that, but thought I would post here in case it helps.

**Comment by sthalik** [comment]
Please do the following:

- download Sysinternals Process Explorer
- enable "lower pane view" in "view" menu
- select "dlls" in lower pane view type, "view" menu
- select the opentrack process
- locate the offending injected library

Detecting the offending library will allow for placing a warning on opentrack startup.

**Comment by sthalik** [comment]
If you can't find the particular library, send screenshots with the entire .dll list. Thanks.

**Comment by ouoertheo** [comment]
I've been having a bit of trouble reproducing this on demand. Seems there are some other variable in play that I'm working on figuring out. Sorry for the delay in getting back to you on this

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by sthalik** [comment]
opentrack deals badly with injected .dll's. This isn't something other software should do to opentrack to begin with. We already have two failure cases with "GIGABYTE OC GURU" and another similar app that make it crash on tracking start.

I'll look into refusing to load particular .dll's.

**Comment by sthalik** [comment]
Please send me the Moonlight .dll name, thanks.

**Comment by ouoertheo** [comment]
Here’s the dlls that load up with opentrack before I launch moonlight (works) and after (fails).

**Comment by sthalik** [comment]
It's now in FAQ, see wiki.
