### ISSUE TITLE
Android: Raw Data keeps on turning although my head/phone doesn't move at all

### ISSUE THREAD

**Issue by SevenSiSix** [opentrack/opentrack#525]
Good day, thanks for making this possible, it is amazing! I only have this little problem where the yaw keeps on increasing/decreasing even when I already stopped my head from moving. I don't know if this is a problem with my phone or something else. I am using a OnePlus 3.

Thanks in advance!

**Comment by sthalik** [comment]
Move away from any magnets. Eliminate the possibility of magnetometer error influence by putting headphones and speakers out of the room temporarily and see if it's still broken like that.

Also how many degrees are we talking about? 60? 30? 5? 2?

**Comment by SevenSiSix** [comment]
Thanks for your response, I've tested it with my speakers close by, or completely removed from my room. And that doesn't change it. It could be because it had a good day, it's right now about 2 to 5 degrees at the max. But I've had it happen with up to 30 degrees of rotation.

Is there an easy way of changing the source on my phone. I think most phones have multiple ways of tracking the direction of the phone. Maybe we could then choose the source we think works the best.

**Comment by sthalik** [comment]
@SevenSiSix android has one API to get rotation from phones with a gyro. We're using that one API.

**Comment by sthalik** [comment]
We COULD be using gyro+acc AHRS but Java is slow.

**Comment by SevenSiSix** [comment]
I understand, thanks for your help!
