### ISSUE TITLE
Issue: Samsung S2 FreePie IMU bug ?

### ISSUE THREAD

**Issue by MopheusDG** [opentrack/opentrack#527]
Hi, on my Samsung S2 I have a problem. When I selec SEND ORIENTATION and not SEND RAW DATA, I can see in debug that GYRO info stays static in 0 (actually -0.00; -0.01;0.01), now if I select SEND ORIENTATION and SEND RAW DATA, the gyro information moves fine.

Is there anyway to force GYRO use ? Cause I'm not sure what info is opentrack using (accelerometers ? gyro ? other ??) to move and I think that's why I'm not having much movement precision.

To be honest, I'm pretty sure it's not using gyro cause even when gyro is in 0 under debug, the Raw Tracker Data showing 20.

Any ideas ? Thanks.

**Comment by sthalik** [comment]
Yes, see #475. It's only a display bug and the gyro is actually used. You'd get totally broken tracking if the phone was lacking a gyro.

I'm closing this as a duplicate.
