### ISSUE TITLE
opentrack with Dota 2 like game ??

### ISSUE THREAD

**Issue by Madoogun** [opentrack/opentrack#531]
i kinda new here. anyways, it would be nice if opentrack could work with Dota 2.  like having a direction key emulator..so that when user pitch up, the camera pan up... just  an idea..i don' have any knowledge about programming though.

**Comment by sthalik** [comment]
It won't work well. Especially since dota won't allow to scroll with differing speeds depending on opentrack's estimated rotation.

**Comment by Madoogun** [comment]
okay , thank you for answering
