### ISSUE TITLE
check permissions for your .ini directory   ??

### ISSUE THREAD

**Issue by t1rta** [opentrack/opentrack#537]
I used to run this program with no error.
However when I try to run it now I get this "check permissions for your .ini directory" error instead.

![opentrack error](https://cloud.githubusercontent.com/assets/25360969/22322081/069b1574-e3cc-11e6-959c-57a6b67bf99c.jpg)

how do I fix it?
please help.

ps I have tried to uninstall and reinstall opentrack but the problem remains.

**Comment by sthalik** [comment]
opentrack asks Windows for the user's "My Documents" path. Does it exist and is Windows aware of it?

**Comment by t1rta** [comment]
thanks for the reply.
can you tell me what is the exact address for the directory?
and is it possible to move this directory somewhere else?

**Comment by Emton** [comment]
C:\Users\YOURUSERNAME\Documents\opentrack-2.3

**Comment by sthalik** [comment]
Windows holds the path in registry so you can specify an alternate path. But this is heavily outside the scope of the opentrack project. I won't provide support wrt broken user profiles.

Other than that, a "Documents" directory is a standard Windows feature and we won't jump through hoops if it's missing.

**Comment by t1rta** [comment]
thanks sthalik and Emton for all the replies.

yes I have found the culprit.
that directory is in external hdd, when I forget to connect it, then I
get the error.

however, I am still confused how to move it to my internal hdd,
but as you said that this is a window issue not yours,
so I guess I have to google it.

thanks again for all the help.
I really appreciate it very much.

**Comment by sthalik** [comment]
@t1rta see what kind of object "My documents" is on the primary hard drive. Try recreating the directory with the external disk unplugged.

**Comment by t1rta** [comment]
I am sorry I do not really understand "what kind of object".
can you explain it a bit more?

**Comment by sthalik** [comment]
@t1rta delete the shortcut to the external drive. Having such basic directory missing will break many programs.

**Comment by fuzzy17** [comment]
I created c:\users\myuser\Documents\opentrack-2.3 and now get "check permissions for your .ini directory "c:/users/myusers/documents/operntrack-2.3." exiting now".  I treid running both as admin and non-admin and got same error both times.

**Comment by sthalik** [comment]
Are you able to access `My Documents` as Windows recognizes it through File Explorer?

**Comment by fuzzy17** [comment]
No I did not have.  So I created  c:\users\myusers\My Documents and still get same error.  I checked permission and it shows full control for my user that I am logged in as. Yet I am in admin mode.

**Comment by sthalik** [comment]
opentrack doesn't look up for a hardcoded "Documents" name or anything of the sort. opentrack asks Windows to designate the "Documents" directory for the current user. That you had to create it is by itself a red flag.
