### ISSUE TITLE
How to debug Opentrack source code in Visual Studio 2015

### ISSUE THREAD

**Issue by yuanchang200** [opentrack/opentrack#543]
I compile the source code in Visual Studio successfully, after building INSTALL there is a opentrack.exe file. But now if I want to add some new code to the source code, how can I compile and run the new code? And how can I debug the code using breakpoints?

**Comment by sthalik** [comment]
If you set msvc++ to generate .pdb files, you can put breakpoints and get readable stack traces as well.

**Comment by sthalik** [comment]
As for new files, rerun cmake and they'll get automatically added to their modules by virtue of the file resolution.
