### ISSUE TITLE
Can't select camera device on mac os build

### ISSUE THREAD

**Issue by HansMono** [opentrack/opentrack#548]
Hello, im new to opentrack on mac but have used it on windows with great success.
Since Arma3 got mac support i thought i'd give it a try but since i'm a fanatic helo-pilot nothing goes without head tracking. 
I tried the mac os build of opentrack, that i could find, but it wouldn't let me select a camera-device (not even the native i-mac cam) in the input tab. Just shows a blank selection field, unable to click it. It also wont open the camera-settings dialog. Upon just start tracking anyways the cam light is lit up (native i-mac cam) and after 1 or 2 secs opentrack always crashes.
I'm using an i-mac and os sierra and want to use it with my webcam to point-track a clip with 3 LED's on my headset, using the freetrack-solution, as it worked really well on windows and the 'trackir-support' for arma is perfect. 
Do i have to set some specific settings in mac-settings to get opentrack running or am i missing something..?! 
Any help would be greatly appreciated, cheers.

**Comment by HansMono** [comment]
checked linuxtrack and there the camera-device selection works and it functions, more or less.. but i'd rather use opentrack because of features and usefullness.. in linuxtrack a detailed camera settings window isnt there, only a 'treshold' slider.. and that not really helps with finetuning the picture to only cap your 3 point s from the clip

**Comment by sthalik** [comment]
We don't have any support to list camera devices and their names on OSX presently.

**Comment by sthalik** [comment]
Unless someone steps up and works on the OSX port it's gonna stay as it is sadly.
