### ISSUE TITLE
Issue or not ? Samsung J7

### ISSUE THREAD

**Issue by MopheusDG** [opentrack/opentrack#550]
Hi, I have a Samsung J7 and I've been trying to use OpenTrack with FreePie UDP and it's not working at all. My phone (J7 original) only shows Accelerometer when you select debug. Is that the problem why it doesn't work ? The rest of the sensors stay in 0, probably because I think it does not have any of the others (Gyro, Mag, Etc). Is there any way to make it work only with accelerometers ? I've check the debug data on the phone and only with accelerometers seems good enough to handle some head tracking, but I may be wrong of course.

Thanks !

**Comment by sthalik** [comment]
No, there's absolutely no way to make it work right without both gyro and an accelerometer.
