### ISSUE TITLE
Suggestion/Request - Minimize to Task Bar

### ISSUE THREAD

**Issue by Len62** [opentrack/opentrack#551]
2.3.1 is working beautifully for my setup. One little request, would it be possible to provide an option to minimize OT to the task bar vice the tray? Much what like you would get if you click on the minimize button. Thanks also for your work, constantly updating and improving OT!

**Comment by sthalik** [comment]
When would it minimize? On startup, when tracking is started or when?

**Comment by sthalik** [comment]
If you want it to minimize on startup, create a shortcut with "start minimized" selected. It actually works.

**Comment by Len62** [comment]
It would minimize on start-up. Forgot about the shortcut method, which works fine. Thanks.

**Comment by sthalik** [comment]
👍
