### ISSUE TITLE
Auto-centre not giving full 180 degrees in both directions

### ISSUE THREAD

**Issue by akamustang** [opentrack/opentrack#554]
You only get full tracking left (0 to -180) and right (0 to 180) if you start the raw axis value at zero, at any other position you lose the full range.

I made a short video demonstrating the issue: https://www.youtube.com/watch?v=iZn3xSJYOxc

**Comment by sthalik** [comment]
The reason for the issue occuring is `scaled_rotation` and in particular <<https://github.com/opentrack/opentrack/blob/unstable/logic/tracker.cpp#L235>>.

We do that to get a "canonical" Euler representation in face of the gimbal lock issues. The method actually works except for that singularity you get.

We should do something at <<https://github.com/opentrack/opentrack/blob/unstable/logic/tracker.cpp#L164>> taking into account c_div and c_mult. I'll look into it after the 2.3.1 hotfix.

**Comment by akamustang** [comment]
Thanks for responding, I tried to build the source to have a bash at fixing it myself, but wasn't able to get it to compile, that's a topic for another day though.

**Comment by sthalik** [comment]
It should work with recent GNU and MSVC 2015+.

**Comment by akamustang** [comment]
Just read in the 2.3.1.6 release notes that hopefully this should be fixed.

Not sure what the related commit was, [9958d78](https://github.com/opentrack/opentrack/commit/9958d784532c43e46df19e67c6f4513e332b7acd) maybe?

**Comment by sthalik** [comment]
@akamustang apologies, I meant to refer to #600 rather than this issue. There's no rescaling being done in the filter, no.

**Comment by akamustang** [comment]
Ah okay, no worries.

**Comment by sthalik** [comment]
It should be fine in the development build at <<http://opentrack.misaki.pl>>. It's gonna be part of 2.3.11.

**Comment by LeoPazEs** [comment]
Its working GREAT but Arma 3 Dont Recognize The program you can help me?

**Comment by mustanggb** [comment]
@sthalik To let you know I tested in 2.3.11 beta3, and the bug still exists, so this is not fixed yet.

**Comment by sthalik** [comment]
@mustanggb can you confirm that you tested on the newest development build from the said address?

**Comment by mustanggb** [comment]
Okay you were right, the dev build seems to work fine, my mistake, thought it was in the beta release already. Thanks a lot!
