### ISSUE TITLE
settings wont save.

### ISSUE THREAD

**Issue by hollywood156** [opentrack/opentrack#557]
i have been trying to get arma 3 working with open track, for some reason i cannot get the settings to save. please help. btw, i have no programming knowledge.

**Comment by sthalik** [comment]
Are you pressing the "OK" button in the settings dialogs?

**Comment by hollywood156** [comment]
yes

**Comment by sthalik** [comment]
Which settings are you unable to save?

**Comment by hollywood156** [comment]
i cannot save anything in the options menu. i tried using portable software and installed software. im using windows 10 as OS.

**Comment by sthalik** [comment]
Are you able to create another profile and see it on the profile list?

**Comment by hollywood156** [comment]
Yes

**Comment by sthalik** [comment]
What's the content of the profile directory? Use the profile dropdown to the left of the profile list to get to the directory.

**Comment by sthalik** [comment]
Damn I can reproduce it myself. What a disaster...

**Comment by sthalik** [comment]
@hollywood156 released hotfix2. Thank you for a quick report.
