### ISSUE TITLE
will not load when arma starts

### ISSUE THREAD

**Issue by hollywood156** [opentrack/opentrack#558]
thanx for the fast response with my last issue. after you fixed the last issue, now it tells me "opentrack is taking too long to open, if the problem persist check app". any idea what this could be?

**Comment by sthalik** [comment]
when does it happen?

**Comment by hollywood156** [comment]
when i start the game. it only shows the message on the rift.

**Comment by hollywood156** [comment]
i open the open track software first. then i open steam in vr mode. hit start on open track then i hit the play button for arma. that's how i was doing it on the first fix with no issues.

**Comment by sthalik** [comment]
Which SDK version is it?

**Comment by hollywood156** [comment]
1.4.0 I see there is a recent update. i will give it a try.

**Comment by sthalik** [comment]
What message is it? The health warning?

**Comment by sthalik** [comment]
No reply too long. :(
