### ISSUE TITLE
Adding Vjoy to protocols 

### ISSUE THREAD

**Issue by gsg94490** [opentrack/opentrack#560]
Hey!
I have been having an Issue adding Vjoy (not vjoy - according to the star citizen forums there is a difference please correct if that is wrong) as an output protocol for opentrack. how do i go about doing this?

Im just trying to get Opentrack to work with star citizen so if you know how do to that, then any info would be appreciated.

gsg

**Comment by sthalik** [comment]
Use the "vjoystick" protocol. "VJoy" is apparently a trial version given multiple users got a "trial expired" message.

**Comment by sthalik** [comment]
"vjoystick" has a direct URL to the download. It's in its options I think
