### ISSUE TITLE
Unwanted pitch

### ISSUE THREAD

**Issue by blueeagle69** [opentrack/opentrack#561]
Hi.
I am using Opentrack 2.3.0 with a PS3 Eye and DelanClip.
Every time I move yaw right, I getting unwanted pitch.
When turning my head right, I get pitch in one direction, then when turning back to centre and turning my head right again, I get pitch in another direction.
If I turn my head left, no pitch happens.
The yaw right is working fine of course, I just keep getting pitch thrown in.
I tried the latest version too with the same result.
I have also tried Dynamic Pose Resolution enabled & disabled.

Apart from this the head tracking works nice and responsive, and easily rivals the stupidly expensive commercial version.
It clearly something that is not quite right in my setup?
Never noticed the issue in FTNoIR.
Is my head on an angle or something :)

**Comment by Len62** [comment]
I'll assume you have calibrated your set-up. You can try and add some deadspace in the pitch mapping. I needed to do this to prevent the same issue. OT is very sensitive to movement, as you have discovered.

**Comment by blueeagle69** [comment]
Hi, yes I have calibrated a few times. The red crosshair is over the centre point.
I think that's correct.
I was thinking of adding a small dead zone to the pitch, but not a huge fan of dead zones in head tracking.
But it looks like I may have to.

Cheers.

**Comment by Len62** [comment]
Are you using the Accela filter? You can play with the rotation filtering options there, it can be of some help.

**Comment by blueeagle69** [comment]
Hi.
Yes I am.
I will have a play around with it and see later before Elite Dangerous calls me 😀

**Comment by Len62** [comment]
See my edit to previous comment.

**Comment by blueeagle69** [comment]
Thank you, in regards to the red point.
I will calibrate again and ensure the centre point is not obstructing the three points.
Oh well, that's one thing I had wrong 😉

**Comment by blueeagle69** [comment]
Thanks Len62.

I looked at my calibration again. I looked at a video on YouTube.
I then re-calibrated again , but must have some how did the yaw left/right bit wrong because the red centre point appeared to the right of my head. So I simply added a negative value of the X axis to move it to the correct spot. Tried it in Elite Dangerous and this time I cannot spot any degree of pitch whilst yawing.
Thanks for all your help.
I knew there was something my 50yo brain had missed. LOL

**Comment by blueeagle69** [comment]
The clip is on the right hand side of my head when facing the camera. So I take it the centre point should be where the head is 😊

**Comment by Len62** [comment]
The OT display is not a mirror image. My clip is on the left side of my head, so the red cross appears to the left of the green crosses. Glad you got it sorted out.
![ot points](https://cloud.githubusercontent.com/assets/10486813/23506446/5674e09c-ff16-11e6-8382-37475b05b171.JPG)

**Comment by blueeagle69** [comment]
Cheers Len.
My mistake.
I thought the red point was where the head was. 
I will correct it later.

Thanks again.

**Comment by sthalik** [comment]
Thanks @Len62 :+1: 

@blueeagle69 the red cross (aka the pivot) is in the horizontal center of your head, like your neck.

**Comment by blueeagle69** [comment]
Thanks.
The clip is on the right side of my head, and after calibration, the pivot point is on the right.
No more unwanted pitch though.

**Comment by Len62** [comment]
That is where it should be.

**Comment by blueeagle69** [comment]
Yeah, thanks again @Len62. 
I gathered that now.
Couldn't believe I have been using Opentrack this long with what I thought was a correctly calibrated   point tracker.
The only niggle I had was the pitch during yaw,  and you mentioning calibration fixed it.
Cheers.
