### ISSUE TITLE
Не компилируется на Debian 8 x86_64, gcc 4.9.2

### ISSUE THREAD

**Issue by ljgdasfhk** [opentrack/opentrack#569]
1. Ошибка в строке 2 в файле ndebug-guard.hpp

2. Ошибка в строке 108 в файле ftnoir_tracker_pt.cpp

/opentrack/tracker-pt/ftnoir_tracker_pt.cpp: In member function ‘virtual void impl::Tracker_PT::run()’: /home/someone/opentrack/tracker-pt/ftnoir_tracker_pt.cpp:108:17: error: expected primary-expression before ‘static’ static const cv::Scalar(0, 0, 255); ^ make[2]: *** [tracker-pt/CMakeFiles/opentrack-tracker-pt.dir/ftnoir_tracker_pt.cpp.o] Ошибка 1 make[1]: *** [tracker-pt/CMakeFiles/opentrack-tracker-pt.dir/all] Ошибка 2 make: *** [all] Ошибка 2

**Comment by sthalik** [comment]
Please report bugs in English next time. I see the compile-time error but next time I probably won't.

Strange it works on modern GCC/LLVM, it shouldn't.
