### ISSUE TITLE
Names of UDP Receiver and UDP Sender are wrong and need to be switched [main exe]

### ISSUE THREAD

**Issue by adeldex** [opentrack/opentrack#571]
So on some old rig I have my PS3 eye set up with opetrack 2.3.0 to take the load of my main processor and at first it was confusing to me because I wanted output to be UDP sender but couldn't select it. Now I have input as PointTracker 1.1 as usual and output as UDP receiver with my main pc's LAN address.
Then on my main pc on opentrack 2.3.1.4 its also reversed and now I have as input UDP sender and as output I have freetrack 2.0 as usual.
And it all works*. The main point is that the receiver sends to the sender. Only the labels are wrong.

*the x y z translations are weird but that's another issue

**Comment by sthalik** [comment]
What's with the translation?

**Comment by babbott1000** [comment]
Yes, I noticed this too.  I was really confused that the sender was in the input slot.  The free pie receiver or whatever was also in the input slot, so that is right but there is a sender in the input slot.  Would be nice if this would be fixed.

**Comment by sthalik** [comment]
It's a matter of which side you're looking from. But I can appreciate your perspective, and that it's the more common one.

**Comment by sthalik** [comment]
Done!

**Comment by fuxingyang** [comment]
![image](https://user-images.githubusercontent.com/20569009/35429539-72a0f600-02af-11e8-88fe-29a68d33cf0e.png)
Hello,I have a similar problem with opentrack output setting.Can you help me? Thank you!Best wishes to you!

**Comment by sthalik** [comment]
Responding in #736.
