### ISSUE TITLE
Centered position sent to games.

### ISSUE THREAD

**Issue by olegiy** [opentrack/opentrack#572]
Thus it must be?
[https://youtu.be/aC_BJE2RFiQ](url)

**Comment by sthalik** [comment]
@olegiy turn off all relative translation options, including dynamic head and see if it still happens.

**Comment by olegiy** [comment]
[https://youtu.be/bXaE_QZfZ4Q](url)

**Comment by olegiy** [comment]
with Yaw, Pitch, Roll all good

**Comment by sthalik** [comment]
Let's consider moving custom zero pose after all mapping and filtering. Having it done before relative translation is definitely incorrect here.

See the test build.

**Comment by petsild** [comment]
Hi,
the shift of the center position of the pilot works fine, no motion to each other does not affect. Again great job thank you very much for adjustment. Pet

**Comment by sthalik** [comment]
Thanks for confirmation. Fixed in 949d847ed9df6d2d2a7931f3f69014aa56a5ab7c.
