### ISSUE TITLE
jumping view

### ISSUE THREAD

**Issue by phantomwraith** [opentrack/opentrack#574]
I have an persistent issue with my opentrack. With my head perfectly steady the view will suddenly jump, left then back for example. I tried another version of opentrack called trackhat opentrack and it has the same issue. Through the program it looks like all 3 dots jump together to a different point on the screen then jump back. I have videos showing this but i'm not sure how to share. I tried reinstalling and clearing regedit and it solved the issue for a couple months, but it's back now.

**Comment by sthalik** [comment]
How far do they jump? A few pixels or more than 10% of the screen? If the latter, not enough USB bandwidth.

**Comment by phantomwraith** [comment]
I think it's less than 10% of screen, if you give me your email I can send you the videos i have of the issue. Also i tried plugging my tracker to a powerbank, still get the same issue.

**Comment by phantomwraith** [comment]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/26469956/24026105/3ca712ae-0a95-11e7-980f-115e1e9cf1ae.gif)

**Comment by phantomwraith** [comment]
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/26469956/24026263/32dee048-0a96-11e7-97d7-2fb88b3fd2a7.gif)

**Comment by sthalik** [comment]
Make the camera gain show your room, for testing. Then see what happens. You'll probably get the left side wrap around to the right side.

It's not the clip. Plug your _camera_ to a different USB hub.

**Comment by sthalik** [comment]
You can also reduce framerate but that's a crap solution. This is a hardware problem.

**Comment by phantomwraith** [comment]
just to clarify i have a ps3 camera, and when running cl-eye test this jump NEVER occurs on it.

**Comment by sthalik** [comment]
Change the framerate in cl-eye test.

**Comment by phantomwraith** [comment]
Changed frame-rate to 60 and it's still occuring, should i still try a different usb port?

**Comment by sthalik** [comment]
Yes. You probably have 2 controllers, one with blue and one with black slots. Choose the other one.

**Comment by phantomwraith** [comment]
it's working PERFECTLY so far!!!!! it's late for me now so i cant really try it for long, but i think it's solved. thank you so much! i really appreciate the quick responses too :D

**Comment by sthalik** [comment]
:1

**Comment by sthalik** [comment]
Kropek woke me up at 5am. Kitty's so impatient. :cat2:
