### ISSUE TITLE
No Russian interface ( Debian 8 x64 gcc 4.9.2 Qt 5.8 )

### ISSUE THREAD

**Issue by ljgdasfhk** [opentrack/opentrack#580]
The interface did not switch to Russian
But in 2.3.1.4 switched

**Comment by sthalik** [comment]
Probably your i18n files are empty. That sometimes happens on heavy changes to a file or two.

checkout unstable. `make i18n`. Then `git checkout -f */lang/*.ts`. Then `make install`.

**Comment by sthalik** [comment]
![image](https://cloud.githubusercontent.com/assets/1896811/24179575/362e5eb8-0eb0-11e7-8f99-2b35154a8aac.png)
> ananke /home/sthalik/dev/opentrack/build % DISPLAY=:0 env {LANGUAGE,LANG}=ru_RU.UTF-8 install/bin/opentrack

**Comment by sthalik** [comment]
```
ananke /home/sthalik/dev/opentrack/build % DISPLAY=:0 env {LANGUAGE,LANG}=ru_RU.UTF-8 install/bin/opentrack
libEGL warning: DRI2: failed to authenticate
qxt-mini: adding event filter
^C
```

![image](https://cloud.githubusercontent.com/assets/1896811/24179750/4de4cf5a-0eb1-11e7-8b57-f654cb120ba3.png)

**Comment by sthalik** [comment]
I confirmed i18n `lupdate` and `lrelease` work on Linux.

**Comment by sthalik** [comment]
@ljgdasfhk I simplified the translation generation code. Also try running `make i18n` manually.
