### ISSUE TITLE
create your own game up load to opentrack

### ISSUE THREAD

**Issue by daviddb1951** [opentrack/opentrack#585]
Hi,
I want to up load my game to opentrack.
I create a video game and built the 3D virtual character using Blender.org.
I reduce the polys and compressed it on save as to file.
I converted the obj file to a text file and using notepad to a ini file.
Questions
What is the maximum data that can be used?
How can I reduce the size to meet the requirement?
Am I missing a step to get this working with success?
Any suggestions are welcome.
Thank You

**Comment by sthalik** [comment]
Are you asking for head tracking support?

Implement either freetrack (source code is in `freetrackclient/`) or npclient (in `contrib/trackir-client`). The latter's the actual client part, already implemented.

**Comment by daviddb1951** [comment]
April 5,2017
 
Hi Stanislaw,
 
Thank you for responding to my email.
Yes,that is correct on the head tracking support to implement a game I programmed myself.
Installed it on open track.
I will use the information you have sent me.
Thank You,
David Brown
--------- Original Message --------- Subject: Re: [opentrack/opentrack] create your own game up load to opentrack (#585)
