### ISSUE TITLE
 [Feature] Add head tracking output for GoPro VR Player

### ISSUE THREAD

**Issue by r57zone** [opentrack/opentrack#591]
GoPro VR Player 2.2 - [32bit](http://cdn-download.kolor.com/ked/2.2.0.400_2017-02-13/GoProVRPlayer_win32_220_2017-02-13.exe) or [64bit](http://cdn-download.kolor.com/ked/2.2.0.400_2017-02-13/GoProVRPlayer_x64_220_2017-02-13.exe)

In the settings need to change this:

1. In the Master / Slave settings -> Slave.
2. URL Decoding -> Absolute.
3. Camera Orientation -> Absolute.

After that you can send the json package (only head orientation) to 7755 UDP Port:

_{"fov": 90, "id": "ked", "pitch": MyPitch, "position": 0, "roll": MyRoll, 
"state": 0, "url": "", "yaw": MyYaw}_

Where "MyPitch", "MyYaw" and "MyRoll" are yaw, pitch and roll degrees from OpenTrack are 
converted into radians.

MyPitch = DegToRad ( OpenTrack->Pitch )
MyYaw = DegToRad ( OpenTrack->Yaw )
MyRoll = DegToRad ( OpenTrack->Roll )

**Comment by r57zone** [comment]
![](https://user-images.githubusercontent.com/9499881/27303862-36a5bb14-554d-11e7-8c49-3fa516788866.png)
FOV slider (min - 80, max - 120).

It is enough to copy the plug-in Output - UDP over Network, change the port to 7755, add slider fov and change the type of sending from package (float x, y, z, yaw, pitch, roll) to {"fov": MyFov, "id": "ked", "pitch": MyPitch, "position": 0, "roll": MyRoll, "state": 0, "url": "", "yaw": MyYaw}

**Comment by sthalik** [comment]
Is it JSON text or binary data?

**Comment by r57zone** [comment]
JSON text

**Comment by r57zone** [comment]
[Proxy app](https://github.com/r57zone/VR-tracking-apps) if someone else needs it.

**Comment by sthalik** [comment]
Sorry it's taking so long. Nowadays my time and energy are limited...

**Comment by r57zone** [comment]
I think can close, if anyone needs it, there is a proxy app.
