### ISSUE TITLE
[Bug] Setup Path

### ISSUE THREAD

**Issue by SoulMaril** [opentrack/opentrack#596]
After installation opentrack setup asks to start the executable right away. If you have changed the setup path samething different than the default path then it cant launch and throws an error. "Can't find". Setup path seems to be hardcoded.

**Comment by Len62** [comment]
Probably set that way for a reason. You can always d/l the manual install version and unzip it to any folder you like.

**Comment by SoulMaril** [comment]
I just report. I am already using in a different path without any problems.

**Comment by sthalik** [comment]
No, it's not meant to be like that.

**Comment by SoulMaril** [comment]
It is not a big deal. It is working anyway. But everytime I use the installer and update it gives this error at first complimentary launch which will never be needed again. Once and all.
