### ISSUE TITLE
Filter Accela. Changed the max values?

### ISSUE THREAD

**Issue by olegiy** [opentrack/opentrack#601]
Changed the max values?
[https://yadi.sk/i/cj1nl4kQ3H8Euz](url)

**Comment by sthalik** [comment]
I did. The previous max values were too high.

**Comment by sthalik** [comment]
The limited range has a nice side effect that users will probably feel less lost in the settings. It's easier to find a good slider combination if the range isn't overly broad.

**Comment by olegiy** [comment]
My settings did not fit in the new range. :-(  15-20%

**Comment by sthalik** [comment]
Why would you need that high settings?

**Comment by olegiy** [comment]
I like very smooth )))

**Comment by sthalik** [comment]
At 30 ms it's very laggy as if i took too many drugs mixed with alcohol. But you can use the nonlinearity slider to get it smooth also.

**Comment by olegiy** [comment]
I agree!

**Comment by sthalik** [comment]
Is that OK for you? If not, how much additional smoothing would you need?

**Comment by olegiy** [comment]
+15%. Thanks!

**Comment by sthalik** [comment]
#605 makes smoothing work on a different scale. It also seems to perform with less lag and more comfort. It involves heavier changes to Accela. See if it works for you.

**Comment by sthalik** [comment]
I'm closing this issue since the 6 * 1DOF Accela behavior is hopefully gone forever.
