### ISSUE TITLE
opentrack 2.3.1.6 release process

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#605]
Hey,

I'm soon going to release opentrack `2.3.1.6`. I'd like the dedicated users, and perhaps others, to submit feedback. As you know this hobby project has no QA team.

@mrsanchos has officially joined the development team. Welcome! :cat2: 

Some of the changes you might like:

- **fix Vive rotation order and enable this tracker.** fixes provided by @subnet- and @antcodd, thanks!
- **accela: now filters 3 DOF for rotation and position rather than each separately**; please report new issues!
- accela: reduce sudden jumps on minimal movement (reported by and discussed with @mrsanchos)
- remove camera angle option that wasn't doing anything
- accela: reduce acceptable value range; this makes it easier to configure
- reduce CPU usage while tracking, spent in program's core functionality
- fixed the path to Intel RealSense camera driver installer, by @ph0b 
- flightgear: some output DOFs were inverted
- allow for roll calibration; it mostly works from my testing
- some operations in the PT and Aruco trackers are now faster thanks to the Intel IPP library
- fix PT point size display; make calibrated center a yellow cross

Grab builds at <<http://opentrack.misaki.pl>>.
The current build filename is `opentrack-test-20170503-2.3.1.6-pre1.7z`.

**Comment by sthalik** [comment]
Paging @MathijsG @Len62 @mrsanchos @olegiy @petsild. Cheers!

**Comment by mrsanchos** [comment]
@sthalik thx Stas! :)

**Comment by sthalik** [comment]
That was fast :)

**Comment by Len62** [comment]
A quick test looked good. Will test some more tomorrow.

**Comment by ph0b** [comment]
I've encountered an issue while testing so I had to do a small fix, sorry! https://github.com/opentrack/opentrack/commit/ff3f20bf50ccae00937732673bbb12f1b6be7afe

@sthalik did you change anything regarding unicode support in plugin names or the build itself?
I had no such issue when building with msvc2015 or with previous releases, but in your test build I get:

<img width="326" alt="opentrack-unicode" src="https://cloud.githubusercontent.com/assets/827051/25619921/e2153f32-2f4c-11e7-9b4e-22814f975303.PNG">

**Comment by sthalik** [comment]
@ph0b previously it was random whether utf-8 literals worked. Now they should always work, provided they're in form `u8"foo"`. The type is `const char*` of course.

**Comment by sthalik** [comment]
The regression is 36540c773f6833696bae3364c39217847fc5f96b.

**Comment by sthalik** [comment]
@ph0b I was actually confused by a comment in `kalman.cpp` to that extent. It appears we don't actually have issues of this sort. Carry on please, no changes to string literals are necessary at all.

**Comment by sthalik** [comment]
I updated the test build in the first post. It's `opentrack-test-20170503-2.3.1.6-pre1.7z`. The changes are:

- fix realsense driver installer path -- by @ph0b 
- undo the Unicode mess -- me

With regard to the Unicode change, there shouldn't be any user-facing changes.

**Comment by ph0b** [comment]
@sthalik perfect! your build is working well for me now, thanks.

**Comment by sthalik** [comment]
@ph0b please see if my cmake changes broke anything, thanks. It now unconditionally generates and installs `.pdb`s. The rationale is that users can't debug unless they have the files, and by the time a build's released, the files are long gone.

If this should be conditionalized let me know.

**Comment by Len62** [comment]
Newest build is working great! No issues from my end.

**Comment by MathijsG** [comment]
Will try soon. Quite busy with some other work unfortunately. One minor question, are we diverting from semantic versioning already? :-P hence the extra digit. Shouldn't this be 2.3.2?

**Comment by sthalik** [comment]
@MathijsG I will drop the penultimate digit.

**Comment by sdysj** [comment]
Is it just me can't get it work on DCS World latest version? 
It worked before. The options page shows up TrackIR correctly but just don't work.
BTW using the dll from https://github.com/MaximeMorel/DCS-headtracker works.

**Comment by sthalik** [comment]
There were no changes to that module. Same dll, same logic sharing with the dll, same game list.

**Comment by sthalik** [comment]
Do you get a game name on opentrack's titlebar?

**Comment by sdysj** [comment]
@sthalik No, the titlebar just show profile name.

**Comment by Len62** [comment]
Hmm, just loaded up DCS World here and OT works fine. Are you running OT as administrator? You could also try doing a repair of DCS World. When running OT the titlebar shows the profile, and then Black Shark.

**Comment by sthalik** [comment]
Disable "stop tracking on program exit".

See if the registry path exists -- `HKCU\NATURALPOINT\NPClient Location`. It must point to where `NPClient64.dll` is stored.

Some people also said it suddenly starts working after rebooting.

**Comment by sdysj** [comment]
Solved. Reset the profile got it work.

**Comment by PH-LCS** [comment]
Hi,

Opentrack 2.3.1.6 is not working for Prepar3D v4.
See head moving in Opentrack but no tracking in Prepar3D v4.
All programs running as administrator.
