### ISSUE TITLE
OT and antivirus issues

### ISSUE THREAD

**Issue by Len62** [opentrack/opentrack#606]
Not a problem for me but a couple of OT users on other forums have run into issues with OT and AVG/Avast. Only way they could get OT to work properly was to uninstall the AVG/Avast programs. Just wanted to pass this along.

**Comment by sthalik** [comment]
The antivirus software blocks camera use by default apparently. Good from their point of view but nothing opentrack can do about it.

**Comment by petsild** [comment]
If anyone has a problem just add OT to the list of exceptions.
![vyjimky](https://cloud.githubusercontent.com/assets/13926997/25592999/4a950778-2ebb-11e7-8676-193674578f36.JPG)

**Comment by Len62** [comment]
@sthalik The users reported no other issues using their cameras. 
@petsild The users reported that just excluding OT did not help.

Never had this problem myself, of course I don't use AVG or Avast.

**Comment by sthalik** [comment]
@Len62 there's nothing that can be done from programming perspective.
