### ISSUE TITLE
allow for switching profiles on a hotkey

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#609]
In Arma, people want different profiles depending on whether they pilot a heli or run as infantry.

It's been requested multiple times, now by @mrsanchos.

It's time The Octopus learned a few more tricks :octopus: :cat2:

**Comment by Xon2** [comment]
Not sure how to interpret the accepted and closed markers here, but is this something already implemented as of version 2.3.11 beta3? I did not find any mention of this in the changelogs of the last couple of versions, so i guess not. Any news on this? As mentioned in the OP, this would come in really handy. Arma 3 and Star Citizen for instance would greatly benefit from being able to switch on the fly from a cockpit to an infantry/fps profile.
