### ISSUE TITLE
Logitech C615

### ISSUE THREAD

**Issue by raviv** [opentrack/opentrack#616]
Hi,

I'm trying to use opentrack point tracker with a Logitech C615 webcam and unlike what i see in tutorials, the video input looks normal (as in not black) and it picks up many points in the picture, not just me LEDs.
What am I doing wrong?

Thanks,
Raviv

**Comment by Len62** [comment]
Open the Point Tracker settings and adjust the "Point Extraction" settings so only the LEDs get picked-up. Are you using IR or regular LEDs?

**Comment by MathijsG** [comment]
Did you remove the IR filter and blocked light by using some kind of filter? For example a piece of film or a floppy diskette piece? By default a regular webcam picks up a lot of daylight and blocks the IR.
