### ISSUE TITLE
does not work on Debian 8 x64

### ISSUE THREAD

**Issue by ljgdasfhk** [opentrack/opentrack#618]
http://s019.radikal.ru/i632/1705/9a/93b411198be6.png

Can not select modules

> Process 22258 - opentrack

> Summary
> 
> The process opentrack (with pid 22258) is using approximately 30.4 MB of memory.
> It is using 27.3 MB privately, and a further 15.3 MB that is, or could be, shared with other programs.
> Dividing up the shared memory between all the processes sharing that memory we get a reduced shared memory usage of 3.1 MB. Adding that to the private usage, we get the above mentioned total memory footprint of 30.4 MB.
> Library Usage
> 
> The memory usage of a process is found by adding up the memory usage of each of its libraries, plus the process's own heap, stack and any other mappings, plus the stack of its 3 threads. 

> Private
> 6688 KB	[heap]
> 4400 KB	/programms/Qt5/5.8/gcc_64/lib/libQt5Gui.so.5.8.0
> 4240 KB	/programms/Qt5/5.8/gcc_64/lib/libQt5Widgets.so.5.8.0
> 3436 KB	/programms/Qt5/5.8/gcc_64/lib/libQt5Core.so.5.8.0
> 2024 KB	/usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.375.39
> 1144 KB	/programms/Qt5/5.8/gcc_64/lib/libQt5XcbQpa.so.5.8.0
> 888 KB	/programms/Qt5/5.8/gcc_64/lib/libicui18n.so.56.1
> 856 KB	/programms/Qt5/5.8/gcc_64/lib/libicuuc.so.56.1
> 500 KB	/programms/Qt5/5.8/gcc_64/lib/libQt5DBus.so.5.8.0
> 432 KB	/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.375.39
> 376 KB	/programms/Opentrack/bin/opentrack
> 312 KB	[stack:22260]
> 192 KB	/programms/Qt5/5.8/gcc_64/lib/libicudata.so.56.1
> 164 KB	/programms/Qt5/5.8/gcc_64/lib/libQt5Svg.so.5.8.0
> 140 KB	/programms/Qt5/5.8/gcc_64/plugins/imageformats/libqtiff.so
> 140 KB	/programms/Opentrack/libexec/opentrack/libopentrack-options.so
> 136 KB	/programms/Qt5/5.8/gcc_64/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
> 132 KB	/programms/Qt5/5.8/gcc_64/plugins/imageformats/libqwebp.so
> 128 KB	/programms/Qt5/5.8/gcc_64/plugins/imageformats/libqjpeg.so
> 116 KB	/programms/Opentrack/libexec/opentrack/libopentrack-logic.so
> 104 KB	/usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
> 96 KB	/programms/Opentrack/libexec/opentrack/libopentrack-spline.so
> 92 KB	/programms/Opentrack/libexec/opentrack/libopentrack-pose-widget.so
> 80 KB	/programms/Opentrack/libexec/opentrack/libopentrack-migration.so
> 72 KB	/lib/x86_64-linux-gnu/libprocps.so.3.0.0
> 64 KB	/programms/Qt5/5.8/gcc_64/plugins/xcbglintegrations/libqxcb-glx-integration.so
> 64 KB	/usr/share/mime/mime.cache
> 60 KB	/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0
> 60 KB	[stack]
> 44 KB	/programms/Qt5/5.8/gcc_64/plugins/imageformats/libqicns.so
> 40 KB	/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20
> 36 KB	/programms/Qt5/5.8/gcc_64/plugins/imageformats/libqjp2.so
> 36 KB	/programms/Opentrack/libexec/opentrack/libopentrack-qxt-mini.so
> 32 KB	/programms/Qt5/5.8/gcc_64/plugins/imageformats/libqico.so
> 32 KB	/programms/Qt5/5.8/gcc_64/plugins/imageformats/libqgif.so
> 28 KB	/usr/lib/x86_64-linux-gnu/libfreetype.so.6.11.1
> 28 KB	/usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
> 28 KB	/programms/Opentrack/libexec/opentrack/libopentrack-api.so
> 28 KB	/programms/Opentrack/libexec/opentrack/i18n/ru_RU.qm
> 24 KB	/programms/Qt5/5.8/gcc_64/plugins/imageformats/libqwbmp.so
> 24 KB	/programms/Qt5/5.8/gcc_64/plugins/imageformats/libqtga.so
> 24 KB	/programms/Qt5/5.8/gcc_64/plugins/imageformats/libqsvg.so
> 24 KB	/lib/x86_64-linux-gnu/libc-2.19.so
> 20 KB	/usr/lib/x86_64-linux-gnu/libjasper.so.1.0.0
> 20 KB	/programms/Opentrack/libexec/opentrack/libopentrack-compat.so
> 16 KB	/lib/x86_64-linux-gnu/libexpat.so.1.6.0
> 16 KB	/programms/Qt5/5.8/gcc_64/plugins/platforms/libqxcb.so
> 12 KB	[stack:22261]
> 12 KB	/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.8.0
> 8 KB	/lib/x86_64-linux-gnu/libnss_files-2.19.so
> 8 KB	/lib/x86_64-linux-gnu/libnss_nis-2.19.so
> 8 KB	/lib/x86_64-linux-gnu/libnsl-2.19.so
> 8 KB	/lib/x86_64-linux-gnu/libnss_compat-2.19.so
> 8 KB	/usr/lib/x86_64-linux-gnu/libjpeg.so.62.1.0
> 8 KB	/usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
> 8 KB	/usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
> 8 KB	/usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
> 8 KB	[stack:22259]
> 8 KB	/lib/x86_64-linux-gnu/libpng12.so.0.50.0
> 8 KB	/lib/x86_64-linux-gnu/libuuid.so.1.3.0
> 8 KB	/lib/x86_64-linux-gnu/libdbus-1.so.3.8.14
> 8 KB	/usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
> 8 KB	/usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
> 8 KB	/usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
> 8 KB	/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
> 8 KB	/usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
> 8 KB	/usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
> 8 KB	/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
> 8 KB	/lib/x86_64-linux-gnu/libpcre.so.3.13.1
> 8 KB	/lib/x86_64-linux-gnu/libglib-2.0.so.0.4200.1
> 8 KB	/usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4200.1
> 8 KB	/lib/x86_64-linux-gnu/librt-2.19.so
> 8 KB	/lib/x86_64-linux-gnu/libz.so.1.2.8
> 8 KB	/lib/x86_64-linux-gnu/libpthread-2.19.so
> 8 KB	/lib/x86_64-linux-gnu/libdl-2.19.so
> 8 KB	/lib/x86_64-linux-gnu/libm-2.19.so
> 8 KB	/lib/x86_64-linux-gnu/ld-2.19.so
> 4 KB	/usr/lib/x86_64-linux-gnu/tls/libnvidia-tls.so.375.39
> 4 KB	/usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
> 4 KB	/usr/lib/x86_64-linux-gnu/libGLX.so.0
> 4 KB	/usr/lib/x86_64-linux-gnu/libGL.so.1.0.0
> 4 KB	/lib/x86_64-linux-gnu/libgcc_s.so.1
> 4 KB	/home/someone/.local/share/mime/mime.cache

> Shared
> 5196 KB	/usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.375.39
> 1404 KB	/lib/x86_64-linux-gnu/libc-2.19.so
> 1300 KB	/SYSV00000000 (deleted)
> 784 KB	/usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
> 752 KB	/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20
> 716 KB	/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.375.39
> 536 KB	/usr/lib/x86_64-linux-gnu/libfreetype.so.6.11.1
> 524 KB	/lib/x86_64-linux-gnu/libglib-2.0.so.0.4200.1
> 400 KB	/usr/lib/locale/locale-archive
> 364 KB	/lib/x86_64-linux-gnu/libm-2.19.so
> 332 KB	/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> 320 KB	/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0
> 312 KB	/usr/lib/x86_64-linux-gnu/libGL.so.1.0.0
> 268 KB	/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
> 260 KB	/lib/x86_64-linux-gnu/libdbus-1.so.3.8.14
> 236 KB	/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.8.0
> 152 KB	/lib/x86_64-linux-gnu/libexpat.so.1.6.0
> 128 KB	/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
> 128 KB	/lib/x86_64-linux-gnu/ld-2.19.so
> 104 KB	/lib/x86_64-linux-gnu/libz.so.1.2.8
> 96 KB	/usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
> 96 KB	/lib/x86_64-linux-gnu/libpthread-2.19.so
> 76 KB	/lib/x86_64-linux-gnu/libgcc_s.so.1
> 76 KB	/var/cache/fontconfig/d52a8644073d54c13679302ca1180695-le64.cache-4
> 64 KB	/usr/share/mime/mime.cache
> 64 KB	/usr/lib/x86_64-linux-gnu/libjasper.so.1.0.0
> 64 KB	/lib/x86_64-linux-gnu/libnsl-2.19.so
> 64 KB	/lib/x86_64-linux-gnu/libpng12.so.0.50.0
> 64 KB	/usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
> 64 KB	/lib/x86_64-linux-gnu/libpcre.so.3.13.1
> 60 KB	/usr/lib/x86_64-linux-gnu/libjpeg.so.62.1.0
> 60 KB	/usr/lib/x86_64-linux-gnu/libGLX.so.0
> 52 KB	/usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
> 44 KB	/lib/x86_64-linux-gnu/libnss_files-2.19.so
> 44 KB	/var/cache/fontconfig/945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-4
> 44 KB	/var/cache/fontconfig/d589a48862398ed80a3d6066f4f56f4c-le64.cache-4
> 40 KB	/lib/x86_64-linux-gnu/libnss_nis-2.19.so
> 40 KB	/usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
> 40 KB	/var/cache/fontconfig/3f7329c5293ffd510edef78f73874cfd-le64.cache-4
> 36 KB	/usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
> 36 KB	/var/cache/fontconfig/d0972c3d32f097851eb916381fc38920-le64.cache-4
> 28 KB	/lib/x86_64-linux-gnu/libnss_compat-2.19.so
> 28 KB	/usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
> 28 KB	/lib/x86_64-linux-gnu/librt-2.19.so
> 28 KB	/var/cache/fontconfig/3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-4
> 20 KB	/usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
> 20 KB	/usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
> 16 KB	/lib/x86_64-linux-gnu/libuuid.so.1.3.0
> 12 KB	/usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
> 12 KB	/lib/x86_64-linux-gnu/libdl-2.19.so
> 12 KB	/var/cache/fontconfig/e49e89034d371f0f9de17aab02136486-le64.cache-4
> 12 KB	/var/cache/fontconfig/e13b20fdb08344e0e664864cc2ede53d-le64.cache-4
> 8 KB	/usr/lib/x86_64-linux-gnu/tls/libnvidia-tls.so.375.39
> 8 KB	/var/cache/fontconfig/4b14b093aebc79c320de5e86ae1d3314-le64.cache-4
> 8 KB	[vdso]
> 4 KB	/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
> 4 KB	/usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4200.1
> 4 KB	/var/cache/fontconfig/1bb779988dd113829cac3881d8b6fc0e-le64.cache-4

v. 2.3.1.4 works

**Comment by sthalik** [comment]
![image](https://cloud.githubusercontent.com/assets/1896811/26036562/12eba122-38e0-11e7-9a1e-214fe92d4238.png)

The Octopus over X11.

cheers
