### ISSUE TITLE
Feature request: DayDream controller for input 

### ISSUE THREAD

**Issue by r57zone** [opentrack/opentrack#619]
DayDream controller for input data (bluetooth pc [[1]](https://github.com/xabuloes/daydream-controller-ts/blob/master/example/dist/js/main.js)[[2]](http://stackoverflow.com/questions/40730809/use-daydream-controller-on-hololens-or-outside-daydream/40753551#40753551).

**Comment by sthalik** [comment]
If someone contributes an implementation then sure.
