### ISSUE TITLE
second tracker support to be removed

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#62]
Users of two trackers at once please step up.

Describe your use case.

Second tracker support was always a kludge.

**Comment by KydDynoMyte** [comment]
Looks like I am late to the vote. The "second tracker" was great for the DK1. It would be great for the OSVR HDK since its positional tracking seems to jump all over the place.

**Comment by sthalik** [comment]
@KydDynoMyte I've already planned an arbitary amount of trackers with axis remap. See #171. But see the amount of priority issues <<https://github.com/opentrack/opentrack/issues?q=is%3Aissue+is%3Aopen+label%3Apriority>> and that all work is done in my own free time.

Programmers can submit code at any time and either me or someone else will review it. Otherwise it's the sheer amount of work to do faster than new priority issues arise. This isn't working. I'm a single person doing the software as a hobby. Another developer takes care of the RealSense tracker but the rest of it is a one-person hobby.

I understand this is an issue for DK1 with no camera and gyro drift.

OSVR support is already planned as a priority issue. See #294.
