### ISSUE TITLE
Acella

### ISSUE THREAD

**Issue by ljgdasfhk** [opentrack/opentrack#620]
Akella does not work
The image jerks even at maximum settings
https://www.youtube.com/watch?v=BfBlrzSNqjk

**Comment by sthalik** [comment]
Increase nonlinearity, remove smoothing. Smoothing doesn't remove noise.

Are your model dimensions accurate?

**Comment by ljgdasfhk** [comment]
The dimensions of the model have not changed since the previous version 2.3.1.4
Something does not work as before
[https://www.youtube.com/watch?v=Zk9Czvx5fwk](url)

**Comment by sthalik** [comment]
in `filter-accela/accela-settings.hpp`, change:

`rot_sensitivity(b, "rotation-sensitivity", slider_value(1.5, .1, 2)),`

to

`rot_sensitivity(b, "rotation-sensitivity", slider_value(1.5, .1, 4)),`

The last value is rotation sensitivity. The same you can do for `pos_sensitivity`.

**Comment by ljgdasfhk** [comment]
In my opinion, the filter Akella does not work.
Watch my video
https://www.youtube.com/watch?v=9yPdR5GI2vE
No filter or selected achele - no difference.

**Comment by sthalik** [comment]
I'll do some tests on Linux. It might be related to time delta but this is a long shot.

**Comment by sthalik** [comment]
Wow, it's really like that!

See line 157 here: <<https://github.com/opentrack/opentrack/blob/632cd5bf7778cb9062633f8d27ecd6aadcaa5d28/filter-accela/ftnoir_filter_accela.cpp#L157>>.

Replace `< 0` with `>= 0` and it should start working. Tell me if it helps.

**Comment by ljgdasfhk** [comment]
Now everything works fine.

**Comment by sthalik** [comment]
@ljgdasfhk correct fix is to remove these 4 lines. The if/else and fmax/fmin lines.
