### ISSUE TITLE
Combination of Vjoy 

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#621]
Hi,
when 2.3.1.5-6 setting  a combination of input – PT and output - Vjoy, occurs accidental falls application. The same problem have friends with different running W7,10 and other hw, thank you. Pet

edit:
He sent me a friend yet a similar mistake to what he does Vjoy.
![vjoy](https://cloud.githubusercontent.com/assets/13926997/26037580/3848fda0-38f6-11e7-83fc-e1ba39b5879f.png)

**Comment by sthalik** [comment]
What exactly do you do with PT and vjoystick?

**Comment by petsild** [comment]
I use vJoy device 1 to control the virtual axis X,Y,Z for the game PlanetSide 2. It works but sometimes it randomly falls off, someone 2x per day others more often.
But running the game the error does not affect, thanks for any resolve.  Pet

**Comment by sthalik** [comment]
Please install Visual Studio 2017 Preview or even 2015 Update 3. We'll have to see where it crashes.

cheers

**Comment by petsild** [comment]
What all do I install a summary of the dozens of components?
![vs](https://cloud.githubusercontent.com/assets/13926997/26062553/719b7ba6-398b-11e7-8426-5466aff845ee.JPG)

**Comment by sthalik** [comment]
Desktopowych aplikacji pomocy C++

_Nie_ instaluj uniwersalnej platformy. Potrzeba tylko środowiska i obsługi C++.

:laughing:

**Comment by petsild** [comment]
I installed the Community 2017, what do I do next?

**Comment by sthalik** [comment]
Start the software. Wait for it to crash. Now start Visual Studio without closing the "program has crashed" window.

- connect to crashed process <<https://msdn.microsoft.com/en-us/library/3s68z0b3.aspx?f=255&MSPPError=-2147217396>>
- press the green button on the toolbar that looks like "pause" on a music player, next to the red "stop" button
- select Debug -> Windows -> Call stack from the menu
- screenshot the call stack window

It might be missing the .pdb files, but don't worry for now. We'll go through loading them if that info's not enough.
