### ISSUE TITLE
Nano + GY-85 via usb cable

### ISSUE THREAD

**Issue by lukaszgrochola** [opentrack/opentrack#626]
Hello!

I made setup for head tracking. Nano with usb interface and gy-85. So i've upload sketch(Razor-AHRS), tested in "Processing" and movement is rly good but... When i try use it in opentrack/facetrack no ir, selecting all of the options etc. I have no movement in this programms.(in section about i see numbers running in, so the programms are getting data).

Any ideas whats wrong?

**Comment by MrCapone** [comment]
https://github.com/opentrack/opentrack/issues/662#issuecomment-320503370
