### ISSUE TITLE
Mapping Properties Negative Curve build 2.3.7

### ISSUE THREAD

**Issue by Forsaken-Player** [opentrack/opentrack#628]
When the Mapping Properties "Curve goes negative", cursor doesn't stay at 0, y tries to follow the curve but with a positive sign.

![1](https://cloud.githubusercontent.com/assets/13246441/26802367/a84a2602-4a16-11e7-9d56-80d2e207e0ff.jpg)

**Comment by Len62** [comment]
Same here.

**Comment by sthalik** [comment]
Thank you @Forsaken-Player @Len62. I put up a build at http://opentrack.misaki.pl.

I'm thinking of replacing current Catmull-Rom splines with "monotonic cubic" splines that avoid these weirdnesses. But it's another bit of work.

Thought of catching some more Z's but Kropek was meowing incredibly loud this night.

**Comment by sthalik** [comment]
![image](https://cloud.githubusercontent.com/assets/1896811/26811214/a6bd40e4-4a70-11e7-9585-f635c1e26faa.png)

See that bulge around X=0.4. That's how Catmull-Rom often performs also. I hate that too.

**Comment by Len62** [comment]
The build you provided works fine. No more negative movement here.

**Comment by sthalik** [comment]
:+1: I'll leave the issue open to investigate monotonic splines.

**Comment by Forsaken-Player** [comment]
Same here, new build doesn't have the issue. I had no time to test it in games yet. I'm a bit busy at work this week, sorry on that.
Thank you for this great software!
