### ISSUE TITLE
No video problem

### ISSUE THREAD

**Issue by lowkeygit** [opentrack/opentrack#629]
I plan to use Opentrack with Android phone for head tracking. I followed the instruction to set up: https://github.com/opentrack/opentrack/wiki/Smartphone-Headtracking
However, when I click the button "start", it shows no video.

I'm sure that the phone and PC are well connected. I am using samsung gt i9100. I have tried up my thought but cannot find a solution. What potential problem might be?

Thanks,

**Comment by sthalik** [comment]
Not all trackers show any video. Android head tracking uses only inertial sensors and no camera.

**Comment by lowkeygit** [comment]
May I use this setup if I want to use the smartphone for tracking the head movement and then collect the data. I mean, even if I cannot see the video, can I still collect the data successfully?

https://github.com/opentrack/opentrack/wiki/Smartphone-Headtracking

Thanks,

**Comment by sthalik** [comment]
Yes. Use the .csv data logger in the options menu.

**Comment by lowkeygit** [comment]
Thank you very much. I will try it.
