### ISSUE TITLE
How to use opentrack on Virtual Machine

### ISSUE THREAD

**Issue by lowkeygit** [opentrack/opentrack#634]
I installed a virtualbox with Win10 on my Macbook. So, there are different IPv4 address in Mac OS and Win10. Now I can successfully use opentrack on the laptop with Windows system. However, the opentrack installed in virtualbox(Win10) cannot accept data from smartphone, no matter which IP address I use. 
I'm wondering if another setup might help? Thanks a lot!

**Comment by sthalik** [comment]
Set the VM to bridged mode.

**Comment by lowkeygit** [comment]
Thank you! Problem solved!
