### ISSUE TITLE
Feature request: Ability to track different colors and autochange!

### ISSUE THREAD

**Issue by Shadoware** [opentrack/opentrack#637]
I was thinking in a little different setup. Imagine Im using a 3 point clip(with red led's) and a standard webcam. Next to each red led I have put a second green led(total 6 leds). I would like to configure Opentrack to track just red leds, and if it lose one red point or get one more spurious point from some light interference, it could automatically change to track green leds and keep auto-changing track colors as needed to keep a good track.
 Is that possible?

**Comment by sthalik** [comment]
No, there's no support for this. You can use the aruco tracker for roll-invariant tracking...
