### ISSUE TITLE
Not able to build opentrack

### ISSUE THREAD

**Issue by babbott1000** [opentrack/opentrack#638]
When I try to run Cmake I get the error:
`Support for MSVC removed due to incomplete C++11 support`
Can't figure out what to do.  I have c++ installed with VS and I selected everything that was related to c++ in the installation modification section of the installer and modified the installation but that didn't do anything.

**Comment by sthalik** [comment]
Which branch/tag are you building?

**Comment by babbott1000** [comment]
Thanks, that was the issue but I ran into another(I fixed it though).  It just couldn't find Qt for some reason.
