### ISSUE TITLE
[Bug] Mapping curvature going negative

### ISSUE THREAD

**Issue by Qiler** [opentrack/opentrack#641]
It is possible for the mapping curvature to bend under the graph as show in screenshot:
[https://dl.dropboxusercontent.com/s/c4s1ttjqwg76oct/firefox_2017-06-23_19-14-38.png](url)
It is nearly impossible to make a deadzone with this bug.
Please make it so it clips to 0 when it goes under.

**Comment by sthalik** [comment]
Yes, it went over and under too. I don't remember when I fixed this, use the latest binary snapshot to be safe: <<http://opentrack.misaki.pl>>.

**Comment by sthalik** [comment]
I'm closing this since there's very little chance it's still broken. Please respond if it's still broken in the binary build.
