### ISSUE TITLE
Feature request: OpenTrack as standard for apps and games

### ISSUE THREAD

**Issue by r57zone** [opentrack/opentrack#642]
In order for developers to use OpenTrack as a standard in their applications and games, it is necessary to create a library (OpenTrack.dll) with export functions (how on "XInput.dll") and demonstration examples (import function from dll and show result).

For example, export functions.
> function SetProfile(path: PChar): DWORD; stdcall;

for read profile with settings. 

The developer can add basic functions to his program, for example, to change the sensitivity or change the filter in ini config. If someone needs advanced settings, he can use the full program and set up a profile that can be used.

> function GetData(dwIndex: DWORD; out myOpenTrack: TOpenTrack): DWORD; stdcall;

for get output data.

dwIndex is one of the constants (ARUCO = 0; FREEPIE_UDP_RECEIVER = 1; HATIRE_ARDUINO = 3; and etc)
TOpenTrack - structure (TOpenTrackPacket{double x; double y; double z; double yaw; double pitch; double roll;};)

> function GetQuat(dwIndex: DWORD; out myQuat: TQuat): DWORD; stdcall;

for get output quaternion

TQuat - structure (TOpenTrackPacket{double qW; double qX; double qY; double qZ;};)

quaternion calculated with yaw, pitch, roll.

> double DegToRad(double f){
> 	return f * (3.14159265358979323846 / 180);
> }

> double t0 = cos(DegToRad(Yaw) * 0.5);
> double t1 = sin(DegToRad(Yaw) * 0.5);
> double t2 = cos(DegToRad(Roll) * 0.5);
> double t3 = sin(DegToRad(Roll) * 0.5);
> double t4 = cos(DegToRad(Pitch) * 0.5);
> double t5 = sin(DegToRad(Pitch) * 0.5);
> 
> qW = t0 * t2 * t4 + t1 * t3 * t5;
> qX = t0 * t3 * t4 - t1 * t2 * t5;
> qY = t0 * t2 * t5 + t1 * t3 * t4;
> qZ = t1 * t2 * t4 - t0 * t3 * t5;

It this also allows you to combine devices. For example, Arduino tracker for rotation and Aruco paper marker for positioning.

> function SetCentering(dwIndex: DWORD): DWORD; stdcall;

for set centering.

**Comment by sthalik** [comment]
It's already been done. The user interface module is optional. It's enough to use the `opentrack-api` module. The `opentrack-logic` module exists if there's a need to implement a different user interface.
