### ISSUE TITLE
Not all keys on keyboard can be assign to functions

### ISSUE THREAD

**Issue by BA1-Templar** [opentrack/opentrack#646]
Hello,
I want to report bug:
I'm trying to assing key to _Zero while held_, and I can't assign a lot of keys, like alt, ctrl, tab, caps-lock etc,
Or maybe there is some other way, like writing key into profile ini?

**Comment by Len62** [comment]
alt and ctrl are just modifiers, you must press another key/joystick button while holding down alt or ctrl. I don't think tab and caps-lock work.

**Comment by sthalik** [comment]
It's a design decision that modifier keys can't be bound.  But you're right about the Tab and Caps Lock keys. They weren't included by accident.

**Comment by BA1-Templar** [comment]
Ok, thanks for info.
Pozdrawiam!

**Comment by sthalik** [comment]
@BA1-Templar ściągnij dzisiejszy z http://opentrack.misaki.pl. Może będziesz miał jeszcze jakieś uwagi.

**Comment by BA1-Templar** [comment]
Ok, pobrany i zainstalowany.
Pomęczę tą wersję i jak coś znajdę to dam znać.

**Comment by BA1-Templar** [comment]
Mam kolejny pomysł odnośnie klawiszy.
Chodzi o dodanie do możliwych klawiszy myszki. Jak i PPM oraz LPM jak i przycisków przód/tył na myszce.

**Comment by sthalik** [comment]
To trzeba by zrobić kod osobno od joysticka i klawiatury. Przemapuj sobie jakimś programem, tak będzie łatwiej.
