### ISSUE TITLE
Mapping issue - stuttering when in dead zones

### ISSUE THREAD

**Issue by unhappytroll** [opentrack/opentrack#651]
![mapping](https://user-images.githubusercontent.com/20564482/28088037-25a3dd7c-668d-11e7-9ac1-47be7f9ed372.jpg)
This is how my mapping window look like as of now - curves wasn't so broken in previous version. 
also I have a video of how this strange mapping now behaves:
https://youtu.be/kNZH770XoYk

this was not in previous version too. And if I remove dead zones this stuttering in them is not happens.
what is that and how I can avoid it (except rollbacking into previous version)?

**Comment by Len62** [comment]
Try this version: https://www.dropbox.com/sh/823dd4wyhixv5a7/AABIY7dkHAjCgkVsS6mrVQxEa/opentrack-test-20170622_01.7z?dl=0

It fixes the mapping issue.

**Comment by unhappytroll** [comment]
oh. ok, thanks. 
Yes, it fixed it. Thanks again.

**Comment by Len62** [comment]
You're welcome!

**Comment by sthalik** [comment]
I really need to release 2.3.8. I can't for the moment.

@Len62 Are there any new issues in the nightly build?

**Comment by Len62** [comment]
I haven't run into any issues with the 20170707-01 build. I've been using it since you posted it.
