### ISSUE TITLE
TrackHat opentrack

### ISSUE THREAD

**Issue by rockandrole18** [opentrack/opentrack#655]
Hey all, I have recently bought a TrackHat head-tracking kit with a hat and a camera from trackhat.org, and I noticed that in addition to the TrackHat opentrack that they recommend to use, there's the source version on here which is updated more regularly and seems to have more options than the TrackHat opentrack. Because I was having issues with setting up the TrackHat opentrack, maybe I should give a try to the source version? What do you think?
I think I'll be downloading it anyway when I get home, but should I configure anything differently than suggested in the quick start guide because I have a TrackHat, or is the procedure is pretty much the same?
Thank you very much in advance 👍

**Comment by Len62** [comment]
No harm in giving it a try. If you run into any problems  just ask for some help.

**Comment by sthalik** [comment]
@rockandrole18 the trackhat branch has defaults set up that you needn't change. In opentrack you need to input values such as clip/cap size, camera fps, etc.

**Comment by sthalik** [comment]
FWIW, here's the default clip measure:

![image](https://user-images.githubusercontent.com/1896811/28248221-257d56d6-6a41-11e7-8ff1-9a1de8910b18.png)

**Comment by rockandrole18** [comment]
@sthalik Any idea what the cap model dimensions are? (I bought a hat)

**Comment by sthalik** [comment]
@rockandrole18 see https://github.com/opentrack/opentrack/blob/trackhat/tracker-pt/point_tracker.h#L88

**Comment by sthalik** [comment]
And I don't know which is which, sorry.

**Comment by rockandrole18** [comment]
@stahlik Thanks, I think I figured it out. I'll let you know if I run into problems but for now, I think I'll close this thread.
