### ISSUE TITLE
trembling problems opentrack

### ISSUE THREAD

**Issue by xolights** [opentrack/opentrack#656]
Hi (excuse my english i'm french),

I have a big problems with open track :

I use windows 10 and a galaxy s8 plus

I have install apk and open track on my pc but i have this trembling effect all time : https://gyazo.com/0dae1317dc93d9fc36796282f8ec611a

You have any idea about my problems ?

Thx

**Comment by sthalik** [comment]
The phone has a gyro so it has to work. Try removing headphones, speakers, and other magnets from the room. I'm not saying they can't be in the room, but let's check the hypothesis that it's magnets breaking magnetometer readings.

**Comment by xolights** [comment]
Yeah i have remove all magnet all my sensor moving i dont hknow for what ...

**Comment by sthalik** [comment]
If you position the device relative to the headphones in a right way, magnetometer readings should be correct enough. Do you have speakers? What other magnets do you have?

Technically we could do AHRS with pure gyro+acc, disregarding magnetometer readings completely. Please try repositioning the device and if it doesn't help, I'll do something with AHRS.

Hint: you have headphones on your ears, so position the device on top of your head if possible,

**Comment by xolights** [comment]
yes i have positioning my smartphone on the top of my head but same problem :(

**Comment by sthalik** [comment]
Will you be able to test an .apk build this day?

**Comment by xolights** [comment]
accelerometer moving all time

**Comment by xolights** [comment]
yes i have resr apk

**Comment by xolights** [comment]
yes i can test apk

**Comment by sthalik** [comment]
What's up with the accelerometer? It should be affected by gravity when held stationary at a vector dependent upon the phone's own orientation.

**Comment by xolights** [comment]
i dont move move my phone but acceleromrometre moving all time

**Comment by sthalik** [comment]
Gravity moves it :)

**Comment by sthalik** [comment]
Now wait a minute, does it move in different directions if you don't move it?

**Comment by xolights** [comment]
ok so its normal for accelerometre, but why other sensor moving ?

**Comment by xolights** [comment]
yes is moving in different direction

**Comment by sthalik** [comment]
Something's very wrong here since with the phone lying on the table, you should get one of 3 accelerometer DOF pointing at -10 and others stationary.

**Comment by sthalik** [comment]
Are you able to verify with CPU-Z what acc is doing?

**Comment by xolights** [comment]
euh no sorry :(

**Comment by xolights** [comment]
all time same problems https://gyazo.com/10b38798f9f419a0ad23af672f7c5f47

**Comment by sthalik** [comment]
Does it behave like this without magnets in the room, also?

**Comment by xolights** [comment]
yes

**Comment by sthalik** [comment]
Also it's strange as hell that it's only the pitch DOF that gets any data. Rest is zeroes.

**Comment by sthalik** [comment]
Please install CPU-Z from Play Store and see what the sensors are doing.

**Comment by xolights** [comment]
ok

**Comment by xolights** [comment]
sensor page : 
![screenshot_2017-07-18-16-56-01](https://user-images.githubusercontent.com/30256699/28323878-4b5c8b02-6bda-11e7-97d5-f8a4c850a676.png)
![screenshot_2017-07-18-16-56-01 1](https://user-images.githubusercontent.com/30256699/28323885-5284804c-6bda-11e7-8651-aeada66cc9ee.png)

**Comment by sthalik** [comment]
If you rotate the phone continuously (can be slightly), do you get gyroscope readings? These are delta readings, hence the need fo rotate while taking readings.

**Comment by sthalik** [comment]
Also look at the "MPL Rotation Vector" readings and see if they're correct when keeping the phone on various orientations.

**Comment by xolights** [comment]
yes

**Comment by xolights** [comment]
nono gyrocope dont work

**Comment by xolights** [comment]
and rotation vector enable

**Comment by albertolg** [comment]
tried calibrating the sensors?

**Comment by sthalik** [comment]
@xolights I can't get anything to work without at least gyro and acc working.
