### ISSUE TITLE
Hatire Arduino plugin don't read data from serial. Bug?

### ISSUE THREAD

**Issue by r57zone** [opentrack/opentrack#662]
I flashed firmware [Razor AHRS](https://github.com/Razor-AHRS/razor-9dof-ahrs/tree/master/Arduino/Razor_AHRS) to Arduino + GY 85. I [changed the speed of 115200](http://i.imgur.com/QKRJmYL.jpg) in the plugin and sketch Arduino. I changed the com-port in the Hatire Arduino plugin. In OpenTrack [don't read data](http://i.imgur.com/B0mdaQh.jpg). Arduino sends [data to the com port "YPR ="](http://i.imgur.com/8wLGUh3.jpg). In the sketch, the Razor_AHRS_test for Processing [also works](http://i.imgur.com/Iqduumo.jpg).

From log file "HATDiagnostics.txt":
> 13:38:56.179: Starting Tracker
> 13:38:56.195: Setting serial port name
> 13:38:56.196: Opening serial port
> 13:38:56.206: Port Open
> 13:38:56.219: Port Parameters set
> 13:38:56.219: Raising DTR
> 13:38:56.224: Raising RTS
> 13:38:56.224: Couldn't set RTS
> 13:38:56.224: Waiting on init
> 13:38:56.224: Port setup, waiting for HAT frames to process

**Comment by r57zone** [comment]
It seems the latest firmware is not compatible with OpenTrack. I'll try the old firmware.

**Comment by MrCapone** [comment]
I use same tracker based on Arduino nano + GY85. Do you change output format to face track on Razor_AHRS?
Also try com port monitor on Arduino IDE, you should see something like that
![default](https://user-images.githubusercontent.com/5929042/29003159-ac932b96-7adb-11e7-8f2d-77a49c83f286.png)

**Comment by r57zone** [comment]
@MrCapone This is Binary output, yes I changed arduino sketch, but it does not work.  Could you upload your firmware somewhere?

**Comment by MrCapone** [comment]
@r57zone [link](https://mega.nz/#!oE4gzC5A!Ssnny6eX3Yb7y-CyjX4tKynobVMbXs9uRkRtlvwXrks)
On `Razor_AHRS.ino:192` change `int output_format` to `OUTPUT__FORMAT_FACETRACK`

**Comment by r57zone** [comment]
@MrCapone I replaced, I flashed you sketch, changed the speed, checked Com-port, but OpenTrack still does not see.

In addition, the latest version of Razor IMU does not support FACETRACK. Perhaps it is worth changing the Hatire Arduino plugin to read the text #ypr = ...

**Comment by MrCapone** [comment]
@r57zone Just tested same sketch from my link and everything works.
![default](https://user-images.githubusercontent.com/5929042/29017118-a8508a3e-7b7f-11e7-8dc4-f116e2eb2092.png)
Did you change `#define OUTPUT__BAUD_RATE` to 115200 on line 170?
Also you can try [this sketch](https://mega.nz/#!QAQFBYLY!8jLGcPLapgEF9XtkgwT-dA8-7jP3LmJfUjpKe2sB4Wg). It was made just for Hatire plugin.

**Comment by r57zone** [comment]
@MrCapone yes. i changed speed in sketch and in OpenTrack

**Comment by MrCapone** [comment]
@r57zone Dont know what your problem. But this is definitely not opentrack's bug or issue. Maybe some other soft use this com port at same time?

**Comment by r57zone** [comment]
No, the port is not busy.
![screenshot_1](https://user-images.githubusercontent.com/9499881/29019223-ff396138-7b6e-11e7-9082-1cf0d904fc9d.jpg)
![screenshot_2](https://user-images.githubusercontent.com/9499881/29019222-ff37efce-7b6e-11e7-89db-5b452976510f.jpg)
![screenshot_3](https://user-images.githubusercontent.com/9499881/29019221-ff3744de-7b6e-11e7-91ad-66837583f744.jpg)
![screenshot_4](https://user-images.githubusercontent.com/9499881/29019224-ff3bc856-7b6e-11e7-8af9-3a9c3ff349f8.jpg)
![screenshot_5](https://user-images.githubusercontent.com/9499881/29019219-ff344ea0-7b6e-11e7-9c4d-b80f145a1318.jpg)
![screenshot_6](https://user-images.githubusercontent.com/9499881/29019220-ff36169a-7b6e-11e7-8b59-f957d45fe546.jpg)

**Comment by MrCapone** [comment]
Arduino IDE can use com port. Did you close it before use opentrack? I also tried stable opentrack release on windows: 
![default](https://user-images.githubusercontent.com/5929042/29027650-c2422318-7bab-11e7-9b33-440aa40a7904.png)

**Comment by r57zone** [comment]
Yes, I closed Arduino Ide. I've checked many times.

**Comment by MrCapone** [comment]
I give up. I really dont know what your problem is, but id definitely not opentrack's bug. I can only give you my [opentrack build](https://mega.nz/#!Qdhhib7D!uCd6tX02xIymSKSo8Yp2MAe44EBdp8-37GCK2Zouyq8) and my [opentrack settings](https://mega.nz/#!UBgjgRRK!OEL3Yc-ZvNygSRprbs5v4GmUBoHCApZ4kW3wrKl0jf4) (place it on `Documents\opentrack-2.3`). Maybe it will help.

**Comment by sthalik** [comment]
Just to rule out the obvious, did you compile and upload the compiled firmware?

**Comment by r57zone** [comment]
@sthalik yes, after the changes, I saved, compiled and uploaded to arduino.

**Comment by sthalik** [comment]
Are you guys using the same GPIO port, sensor types, and wiring?

**Comment by r57zone** [comment]
I used GY-85 BMP085 (ITG3205 + ADXL345 + HMC5883L) + Arduino Nano V3 (CH340). 
Maybe can add output text support to the plugin? That someone has a [similar problem](https://github.com/opentrack/opentrack/issues/626), if there was a text, then the problem would not arise.

**Comment by sthalik** [comment]
Or use Python or minicom.

**Comment by sthalik** [comment]
@MrCapone can you comment on the hardware?

**Comment by sthalik** [comment]
Also as I saw the first firmware releases -- sadly they're badly written. It should be easy to make sending via wire, reading from sensors, pose estimation all modular. As I saw the original firmware, there were tons of static arrays but no use of the `struct` keyword.

I can help but with no ability to run the code, other than compile-testing.

**Comment by MrCapone** [comment]
@sthalik I use exactly same hardware. Arduino nano V3 based on Atmega 328 with CH340 USB chip: 
![nano30ch340-00](https://user-images.githubusercontent.com/5929042/29064317-c558e184-7c52-11e7-9252-a84ce16bc568.jpg)
and GY-85 
![gy-85-sch750x7502timesy2small](https://user-images.githubusercontent.com/5929042/29064345-d8123b7c-7c52-11e7-9643-4adfe5cd643c.jpg)
GPIO (GY-85 -> Arduino)
VCC_IN -> +5V
GND -> GND
SCL -> A5
SDA ->A4
G_INT -> D2

**Comment by r57zone** [comment]
If someone repeats a similar problem, then you can use the [vr proxy apps](https://github.com/r57zone/VR-tracking-apps) for SteamVR and GoPro VR Player.

**Comment by ki714** [comment]
Did you folks managed to get it working? If not, trying this solutions. It worked for me. 
https://sourceforge.net/p/facetracknoir/discussion/iht/thread/9cbb2f4c/

**Comment by fzxj520** [comment]
Try the following items:
https://sites.google.com/site/diyheadtracking/home/diy_ahrs_razor_20170701
I did not test!

**Comment by sthalik** [comment]
Does it work right now? @huliqan said it doesn't since 2.3.1.

**Comment by ki714** [comment]
I did managed to to get it working with the latest version of opentrack/facetracknoir with Pololu MinIMU V9, See my previous post  Sept 28 2017

**Comment by huliqan** [comment]
I testing

**Comment by sthalik** [comment]
@huliqan,

It should all work in the recent build (see 2.3.10 prerelease on http://opentrack.misaki.pl). There should be no need to use an old build.

Let's work on fixing the problem so you (and possibly others) don't need an old build.

**Comment by huliqan** [comment]
Ok! I Testing
Ok! I Testing

**Comment by huliqan** [comment]
hatire and Oculus runtime 1.4.0 works fine!

**Comment by sthalik** [comment]
@huliqan this is great news. Also the CPU usage workaround is now automatic.

**Comment by huliqan** [comment]
CPU usage 1-2%

**Comment by dieghito** [comment]
Salutations,
i also have problems with hatire plugin for arduino ... it does not read what is sent by arduino itself.
Maybe in the various updates the reading protocol has been changed ... may I ask how the arduino data should be sent?
In case I modify my Arduino sketch, so I make it compatible.

Thanks for any kind of support you can give me!

**Comment by ki714** [comment]
Did you read this post? I uploaded it in the Cliff of Dover forum as well.
Let me know if you need more help. It's been a while.
Regards
Ki714
.

**Comment by ki714** [comment]
https://theairtacticalassaultgroup.com/forum/showthread.php?t=29072

**Comment by ki714** [comment]
https://theairtacticalassaultgroup.com/forum/showthread.php?t=28730
