### ISSUE TITLE
Latest Accela 2.3.9

### ISSUE THREAD

**Issue by petsild** [opentrack/opentrack#665]
Hi,
I can't calm the tremor any value of the Accela filter in the last 2.3.9. Change the parameters of the deadzone yaw,pitch,X,Y,Z doesn't help against the original 2.3.7. there is a look of calm.
Thank you for solving.  Pet

**Comment by sthalik** [comment]
Temporarily, does increasing rotation nonlinearity help? It works better than the older version of itself.

**Comment by petsild** [comment]
The higher the parameter of nonlinearity causes a huge stuttering.

**Comment by sthalik** [comment]
@petsild see if today's second build helps any. Looks like contours weren't as precise as flood fill.

**Comment by Len62** [comment]
Ran today's prerelease 2 and did not encounter any problems.

**Comment by sthalik** [comment]
@Len62 it's fixed in pre3. Sadly the config you made will have sliders reset to default values again.

**Comment by petsild** [comment]
Now it behaves gracefully even at low values of the deadzone.

**Comment by sthalik** [comment]
Great! Drop by #664 if you need anything else.
