### ISSUE TITLE
Avira warning since 1.3.9

### ISSUE THREAD

**Issue by Maetharin** [opentrack/opentrack#678]
Hey there, just wanted to tell that I´ve been getting a warning by Avira about opentrack.exe. Something about HEUR/APC, more details here https://www.avira.com/de/support-threats-summary-product?tid=26757&threat=HEUR%252FAPC&track=1

Anyidea, what has caused this?

**Comment by sthalik** [comment]
Last time Avira detected opentrack as a virus, I looked it up and turned out many developers had the same problem. I don't recommend using the Avira antivirus.
