### ISSUE TITLE
Does not link with aruco: undefined symbol: MarkerDetector::setMinMaxSizeEff

### ISSUE THREAD

**Issue by Talkless** [opentrack/opentrack#680]
I'm building opentrack 2.3.9 on Kubuntu 16.04, with aruco 2.0.19. When I launch opentrack, I get this:
```
library "aruco" failed: "Cannot load library /home/vincas/code/opensource/opentrack/prefix/bin/../libexec/opentrack//libopentrack-tracker-aruco.so: (/home/vincas/code/opensource/opentrack/prefix/bin/../libexec/opentrack//libopentrack-tracker-aruco.so: undefined symbol: _ZN5aruco14MarkerDetector13setMinMaxSizeEff)"
```

**EDIT**: I guess it's something wrong with my linking.

**Comment by Talkless** [comment]
What should "-DSDK_ARUCO_LIBPATH" point to? Directly to .so, .a?

**Comment by Talkless** [comment]
I have tried with .a (had to add `-fPIC` for aruco to make `libopentrack-tracker-aruco.so` link), and with .so, same issue.

**Comment by Talkless** [comment]
It seems that `aruco-2.0.19/src/markerdetector.h` has this function defined inline, meanwhile there is a copy of headers in `tracker-aruco/include/markerdetector.h` and it has it declared out of line...

Why the headers are stored in `opentrack` repo anyway?

**Comment by sthalik** [comment]
Clone this with `--recurse-submodules`:  <<https://github.com/opentrack/opentrack-depends>>.

**Comment by Talkless** [comment]
Aruco from that repo worked, thanks.

It would be nice to have it documented more.. explicitly somehwere :) .

**Comment by sthalik** [comment]
I agree it should. For now please ask :)
