### ISSUE TITLE
headtracker.xml overrides Flightgear default offset

### ISSUE THREAD

**Issue by Talkless** [opentrack/opentrack#682]
It seems that I have to set individual x/y/z offset in Opentrack UI for each aircraft I launch in Flightgear, to match default pilot's head center position...

It would be nice if opentrack would _add_ offset to the Flightgear offset (offset for the offset? :) ) that is currently applied, so if Opentrack sets Y to "0,10", this means that camera position would be 10 cm up from original pilots position defined by the aircraft authors.

Although I am afraid that this is feature request for the Flightgear itself, to have some soft of offset-2, for secold-layer offsets as mentioned, or maybe it is implemetable by NASAL in Opentrack protocol plugin..?

**Comment by sthalik** [comment]
> Although I am afraid that this is feature request for the Flightgear itself, to have some soft of offset-2, for secold-layer offsets as mentioned, or maybe it is implemetable by NASAL in Opentrack protocol plugin..?

We're not using Nasal. We're binding the UDP data to fgfs's properties directly. I imagine Nasal would be more CPU-intensive here.

Also when I launched the default setup with and without connecting opentrack, the pilot's position was the same when centered.

**Comment by Talkless** [comment]
Here are reports on Flightgear forum:
https://forum.flightgear.org/viewtopic.php?f=36&t=31117&p=316143&hilit=opentrack#p316143

> With the default cessna c172 I'm positioned right in the center of the plane (thus not on the pilot seat).

**Comment by sthalik** [comment]
@Talkless if there's another property we can tie to, then sure. But saving the default property state and adding an offset is too brittle. It could be modified for an arbitrary reason. Also Nasal is overkill for this purpose.

**Comment by Talkless** [comment]
> It could be modified for an arbitrary reason.

Yes, true. I have created topic for this issue:
https://forum.flightgear.org/viewtopic.php?f=6&t=32821
I haven't got any developer comment yet though...

Although, _if_ it would be possible somehow to implement it in NASAL _correctly_, please have in mind that there are probably hundred times more "stuff" being calculated by all these gauges in instrument panel, Canvas displays, etc., so I believe adding a few numbers wouldn't be a huge problem, compared to what's already done.

**Comment by sthalik** [comment]
Please post here once there's a working solution.

Nasal can break if it's started after an offset's already established.

**Comment by sthalik** [comment]
Also you can use custom center pose in opentrack as an ugly workaround for the duration.

**Comment by Talkless** [comment]
Yes I am using Custom center pose. I put Opentrack window on top of FG and calibrate it accordingly for aircraft currently in use.

**Comment by sthalik** [comment]
I think aircraft models should have the pilot position at offset zero. Not a fgfs content developer but still.

**Comment by Talkless** [comment]
I have launched Cessna C172P, then open `View -> Adjust View Position`, and it shows -0.21m, 0.19m 0.36. 

A-10 has 0.00m, 1.50m and 3.20m.

This value is overridden by Opentrack when tracking is on.

**Comment by sthalik** [comment]
Can opentrack know the default value?

**Comment by Talkless** [comment]
I don't know that. That's more, pressing 'v' key changes view into "Model View", "Left Passenger View", etc, and these have their own different offsets...

**Comment by sthalik** [comment]
There should be a separate offset for external headtracking control. I'll implement it once that exists.

**Comment by sthalik** [comment]
Give me the name of stock aircraft with that issue please.

**Comment by Talkless** [comment]
c172p for example.

**Comment by Talkless** [comment]
I have started `flightgear-devel` thread, got one response, so I guess FG needs some changing:
https://sourceforge.net/p/flightgear/mailman/message/36024474/

**Comment by sthalik** [comment]
I'll write some code for direct freetrack support once a solution's in place.
