### ISSUE TITLE
No "GENERAL" in new release

### ISSUE THREAD

**Issue by JazzyManSerg** [opentrack/opentrack#683]
Good Day, It's not GENERAL page in opentrack option for Pointtracker 1.1. So I can't  enable/disable axis for this protocol.
Can you help me. I use FUSION for hatire/pointtrack

**Comment by sthalik** [comment]
Sorry, what are you talking about?

- First select each of both trackers as active and set them up
- Then, switch to Fusion and select these trackers
- Disable rotation along particular axis in the general "options" screen, see screnshot

![image](https://user-images.githubusercontent.com/1896811/29856436-0f1d5d8e-8d53-11e7-99b3-4211bf26107e.png)
