### ISSUE TITLE
GetUserPreferredUILanguages

### ISSUE THREAD

**Issue by sliva1979** [opentrack/opentrack#686]
Здравствуйте. На winxp sp3 не запускается
Hello. On winxp sp3 it isn't started
![opentrack](https://user-images.githubusercontent.com/31522284/29946376-b8cb3b2a-8ead-11e7-8e0e-303cca233c61.PNG)

**Comment by sthalik** [comment]
Hey,

Use this build: <<https://www.dropbox.com/s/0grn84pk5qvo5he/opentrack-xp-2.3.9.7z>>.

I'm not sure what to do yet. Qt discontinued XP support several versions ago. This one uses an obsolete version of Qt but it's not a permanent solution.

**Comment by sliva1979** [comment]
Большое спасибо, теперь работает.
Many thanks, works now.
