### ISSUE TITLE
Opentrack Preview FPS

### ISSUE THREAD

**Issue by rinsatomi** [opentrack/opentrack#692]
Hello, recently I installed the latest opentrack 2.3.9 with the PSEye camera and latest CL-Eye drivers. The problem is that even though I set it to 60fps the preview window is locked at ~15fps.

![image](https://user-images.githubusercontent.com/32850178/31628903-c9b78ad6-b290-11e7-98dd-0a35e56a7197.png)

Is this reason for concern since at the Camera Info screen it displays the proper amount of frames per second? Should I rely on the FPS info? Thanks in advance.

![image](https://user-images.githubusercontent.com/32850178/31628853-a83daf52-b290-11e7-93c1-e59edb0dc746.png)

Edit: I meant, the preview is actually showing me something around 15fps.

**Comment by sthalik** [comment]
You've got a good eye, it's *exactly* 15 fps.

It's limited on purpose. The purpose of the video feed is checking whether the capture works. It doesn't look too awfully choppy but displaying at full framerate would take unnecessary CPU cycles.

FWIW, use 640x480@60Hz, it need less filtering. At 320x240 you can use up to 120Hz without image distortion, but there's no benefit to it.

**Comment by sthalik** [comment]
I'm closing this issue since this has been discussed a lot.

**Comment by rinsatomi** [comment]
Good show. Thank you!
