### ISSUE TITLE
donation option -- comments?

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#693]
It appears that donations are tax-ignorable in Poland. They aren't meant to be shown on tax forms at all. Quite a few people asked for the ability to donate to the project.

I'd like to know what you feel about it. But first, some ground rules.

- opentrack **WILL NOT** be obnoxious, desperate, or annoying about the donations (user interface, web site, etc.).
- opentrack **WILL NOT** give preferential treatment to donators. all people's bugs and feature requests are equal, always.
- opentrack **WILL NOT** add new functionality to donators.
- opentrack **WILL NOT** ask for donations by default, only as an option to click when one feels like it. It won't be visible on the main window, and it won't be easy to click accidentally.

Finally, opentrack **WILL** continue to be developed in case of low donation amounts.

I'd like you to express your opinion, especially the against the functionality.

**Comment by Len62** [comment]
I think this is a good idea. If people are willing to donate in order to compensate you for providing such a great program, they should be able to do so. The ground rules you set are perfect.

**Comment by MathijsG** [comment]
I really like the idea of doing something back to programs I use, either to contribute with money, or with my time, or both. I think it's a sustainable thing helping programs potentially going on.

I think if you do it transparently and without nagging it's perfectly fine for many. So I hope you won't hide the donation button on the website, but just prominently put it somewhere, people still can decide whether they do it or not. I like the Paypal Donation button, because if it's ease of use. Maybe you should dive into that?

**Comment by Laserclip** [comment]
I agree. I wrote to sthalik to put the financial support from anyone who wanted to.

There are many people who produce and sell equipment based on their opentrack products and have great financial benefits. And many others who appreciate your work in improving the program.

I am from Poland and here Paypall is not popular so it is good to have other possibilities of donation. Transfer to your account or something else.

Of course, it is better not to focus on large amounts, but it is better to have the opportunity to donate than to not be.

I'm sorry for my English ;)

**Comment by 503Kento** [comment]
I agree, the ability to donate is a great idea.

**Comment by MarcinSzczecin** [comment]
And definitely DO NOT hide this button

**Comment by Emton** [comment]
I think it's a good idea opentrack is a great program and you've made some solid updates for it
