### ISSUE TITLE
[Idea] centering of inertial trackers in fusion tracker configuration

### ISSUE THREAD

**Issue by Maetharin** [opentrack/opentrack#694]
Hello there!
Thx for all the time you put into this and also how you patiently answer our questions.

I usually use the Fusion tracker with the Aruco Tracker for positioning and my EDTracker for more detailed rotation. But even though the Magnetometer inside the EDtracker is supposed to eliminate drifting, I still sometimes suffer from it if I play over a longer period of time. (Which is always)

Would it be possible to put a function into the next or any subsequent versions which recenters the rotation input from my EDTracker (or any other inertial tracker) whenever the position tracker rotates into the center position?

I don´t know anything about programming, so I don´t know how complicated this would be. Does Opentrack register the rotation of the position tracker and disregards it?

Thx in advance for your answer

**Comment by sthalik** [comment]
That's too complex and specialized to be exposed directly.

I'm halfway done with plugin support however. All the specialized functionality can be embedded in external plugins with their own dialogs.

**Comment by sthalik** [comment]
Does Fusion center correctly with the button press?

**Comment by Maetharin** [comment]
yes it does centre perfectly

**Comment by sthalik** [comment]
Actually it's doable. Which tracker (input method) do you use?

**Comment by Maetharin** [comment]
I am using my EDTracker as rotation source and Aruco as Position tracker in the Fusion Tracker. So inertial and camera.

Thank you for all this effort you put into this, this will greatly enhance my experience!

**Comment by sthalik** [comment]
The functionality is too complex by itself. I'm closing this until we have plugin support.
