### ISSUE TITLE
Would it be possible to limit relative translation to a certain angle?

### ISSUE THREAD

**Issue by Maetharin** [opentrack/opentrack#699]
Hello there!

I was just wondering if it were possible to limit relative translation only to working after you´ve turned your head ± 90°? F.e. add a toggle which switches RT on once the Octopus has turned 90° on the horizontal axis in any direction.  

Why you ask? Because I love the way I can move my head naturally with RT when looking backwards, but I also love how I can move my head naturally when looking forwards without it.

When I have RT off, I can move my head forwards in the cockpit and turn my head at the same spot. When I have it on, if I turn my head, it instantly translates the forward position of my head into a sidewards position, moving my POV, which feels completely unnatural.

But then again, when I have it turned off, I have to move my head counterintuitively when I´m looking backwards.

I hope I have in adequately described my dilemma, and hope you can help me.

**Comment by sthalik** [comment]
Hey,

Use the "neck" feature on the same tab as relative translation.
