### ISSUE TITLE
IL-2 Battle of Stalingrad 90 degree pitch axis lock?

### ISSUE THREAD

**Issue by NoelShourai** [opentrack/opentrack#701]
I don't know if this an opentrack exclusive issue or not, but in IL-2: Battle of Stalingrad, the pitch axis seems to be limited to 90 degrees upwards and 45 degrees downwards in the default cockpit view; however, in other view modes such as head-unlinked cockpit view (Alt + F1 by default), the full range of motion is accessible.

I am using opentrack 2.3.9. I've also spoken with others who are using different headtracking devices (TrackIR, etc.) and they don't seem to have this issue. I also don't have this issue in other games (Falcon BMS, etc.).

**Comment by Len62** [comment]
Make sure that in the mappings window you set max pitch to 180 degrees.

**Comment by NoelShourai** [comment]
Max pitch is set to 180 degrees, as stated it works correctly in other view modes in IL-2, including the head unlinked cockpit view; just not the default cockpit view.

![image](https://user-images.githubusercontent.com/19917103/33227277-9e2bd966-d16d-11e7-95e5-00d66d32bacb.png)

**Comment by Len62** [comment]
IIRC you have to set your pitch down to 180 also in order to get full movement. OT has always been like that.

**Comment by NoelShourai** [comment]
Pitch down to 90 degrees was done on purpose. Even so, using asymmetrical mapping doesn't change anything.

To clarify, the default cockpit view's pitch up is locked to 90 degrees, and downward pitch is locked to 45 degrees. The head-unlinked cockpit view (Alt + F1) as well as the external cameras have the full 180 degree range of motion, but does not allow for rotation or XYZ panning. I initially thought this was a restriction with the game, but I was told by people using other tracking devices (TrackIR) that this is not the case.

**Comment by Len62** [comment]
The issue may have been raised before, but I think it's a limitation of the view system in BoS. I can't comment on other trackers as I have only used OT.  In the freetrack protocol settings have you tried just enabling the TrackIR protocol, as opposed to the freetrack or both options?

**Comment by sthalik** [comment]
As long as your "game data" value is +-180, that's what is sent to the game. opentrack has no further control over how the game interprets that.

**Comment by NoelShourai** [comment]
Hi again,

I just tried switching between both protocols/FreeTrack/TrackIR and restarting the game every time I switch protocols, no difference from what I can tell.

I am inclined to believe the restriction is with IL-2 in particular, but I have heard from other people who own the game but use different tracking hardware (a TrackIR5, for example) that they do not have this issue even in the regular cockpit view. It's possible that I misunderstood them, I just wanted to confirm if the restriction actually is with IL-2 itself or if there is something OpenTrack may be missing or not accounting for.

**Comment by albertolg** [comment]
@NoelShourai the view is restricted in IL-2, you can easily test it just using the numeric keypad to move the view and you will see that vertical view is a little bit more than 90°

**Comment by sthalik** [comment]
@NoelShourai 
> but I have heard from other people who own the game but use different tracking hardware (a TrackIR5, for example) 

We use the exact same method for transmitting the data.
