### ISSUE TITLE
How to use OpenTrack - traking from usb cable(smartphone)?

### ISSUE THREAD

**Issue by GrandAlex96** [opentrack/opentrack#702]
i find "FreePIE UDP receiver" but it use only WIFI. I dont know where find settings for connection from usb cable smartphone. Help me please. this will give us minimum ping in connection witch phone)

**Comment by Forsaken-Player** [comment]
I guess ping will be virtually the same....

**Comment by sthalik** [comment]
Even a ping of 10 ms wouldn't be a problem. The head isn't a precise enough controller.

There's a solution but you're solving the wrong problem.

**Comment by GrandAlex96** [comment]
Ok:)
