### ISSUE TITLE
Multiplatform Client API?

### ISSUE THREAD

**Issue by akloster** [opentrack/opentrack#703]
I'd like to experiment with using Opentrack in Blender. For that, I would need a means to access the tracking information from Python. Inside Blender, it is virtually impossible or at least impractical to use compiled extensions. Best would be some kind of UDP/TCP or even http API.

It would also be nice if this works across platforms.

Any suggestions where to start?

**Comment by sthalik** [comment]
Yes, receive floating-point data using the UDP protocol. The format is 6 `double` values, for `x y z yaw pitch roll` respectively. Rotation unit is degree, not radian.
