### ISSUE TITLE
UI fails to launch when Moonlight is connected

### ISSUE THREAD

**Issue by ouoertheo** [opentrack/opentrack#708]
I found a bug where if I launch opentrack with Moonlight connected from my Android phone, the opentrack UI will not display at all. The process runs in the back, but nothing at all happens on launch.

I have Windows 10. Not sure what info you would like up front, but let me know and I can get it for you.

**Comment by sthalik** [comment]
Does the Moonlight app have a component running on the PC?

Download "sysinternals process explorer", run it, then:

- select the opentrack process in the colored list by a single-click (double-click will open properties, we don't need them)
- view -> show lower pane: enable
- view -> lower pane view: DLLs
- expand the lower pane view so it takes most of the screen
- sort the lower pane by "Path"
- screenshot its pages and post the screenshots. I need to see the entire content. Use Page Down to scroll the list by one page, then do another screenshot, etc.

Here's an example how it's gonna look like

![image](https://user-images.githubusercontent.com/1896811/34472326-efc439de-ef5f-11e7-914f-4e07d104c95c.png)

**Comment by ouoertheo** [comment]
I noticed that Nvidia injects their streaming libraries, which is what moonlight uses. Let me see if I can wrangle up all the variables on repro and get you some better information.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by ouoertheo** [comment]
![opentrack before moonlight 2](https://user-images.githubusercontent.com/5422109/35184003-f6e2e2e8-fdb4-11e7-8815-2404828d40ea.png)
![opentrack after moonlight 1](https://user-images.githubusercontent.com/5422109/35184004-f6f19ca2-fdb4-11e7-960d-186a971ade81.png)
![opentrack before moonlight 1](https://user-images.githubusercontent.com/5422109/35184005-f6fee6e6-fdb4-11e7-9821-0b49e32ffd08.png)
![opentrack after moonlight 2](https://user-images.githubusercontent.com/5422109/35184006-f70c1f50-fdb4-11e7-8f21-8a9c9709c9e2.png)

**Comment by sthalik** [comment]
It's that `nvgamepadinput.dll` thing that's breaking opentrack 99%.

**Comment by sthalik** [comment]
It's now in FAQ, see <<https://github.com/opentrack/opentrack/wiki/common-issues>>.
