### ISSUE TITLE
Assetto Corsa not working with OpenTrack

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#709]
Hi,

Today I was playing with Assetto Corsa, however I couldn't get it to work. How can I debug this the best way? Because none of the free programs do work (Opentrack, Trackhat, FacetrackNoIR)

And the game is incorrectly listed as Lock On: Modern Air Combat:
![image](https://user-images.githubusercontent.com/529552/34219674-435dc8f6-e5b2-11e7-92c3-c337ec8cc1cf.png)

**Comment by MathijsG** [comment]
Woops somehow the default camera wasn't the free looking in cockpit camera :'). Sorry

**Comment by sthalik** [comment]
Is it still showing with LOMAC as the game title?

**Comment by MathijsG** [comment]
Yup, the same for FaceTrack and Trackhat.

**Comment by sthalik** [comment]
I need `sgl.dat` and can't get it myself. Can you send me an email please?

sh

**Comment by MathijsG** [comment]
Hi, where can I get this file? I can't find any of this in Assetto Corsa folder.

**Comment by sthalik** [comment]
Send me an email, I'll explain.

**Comment by MathijsG** [comment]
I emailed you the definitions :-).
