### ISSUE TITLE
reset/toggle with joystick

### ISSUE THREAD

**Issue by Pretagonist** [opentrack/opentrack#71]
I might be going at this the wrong way but anyhow.

I have been using autohotkey to do some more advanced joystick scripting.
My goal is to have a button where a short press is a reset and a hold and release is a on off toggle.
i can get autohotkey to listen to the joystick; determine if long or short; and press a key. the problem is that opentrack apparently uses some special magical way of listening to my keyboard that AHK cant emulate. Is there a commandline message i can send to opentrack or is there any other channel for me to use?

**Comment by iamc** [comment]
I'm trying @Pretagonist solution and it does not work for me. I see the keypresses in keyboard testing utilities, but opentrack seems to ignore them and just gets the "Joy button" press. Any ideas?

This is on Windows10 64bit and opentrack 2.3.9.

**Comment by iamc** [comment]
Ups, sorry, it does work indeed. I had "SendMode Input" set in the script header and for @Pretagonist  solution to work Send has to be in the (default) "Event" mode. My fault!
