### ISSUE TITLE
tracking small dot sticker on head

### ISSUE THREAD

**Issue by fabeit** [opentrack/opentrack#710]
I would like to use opentracker as a mouse to reduce strain on my tendons. I had a single LED setup with free-track, it works great but I get up from my chair a lot, so the wire and the recalibration were not helpful.
I am trying to find a better setup, like SmartNav or Tobii but not so expensive.

I have noticed aruco marker tracker, is there a way to have a small dot or any small object to attach to forehead or to a headset but without any cable?

Thanks!

**Comment by sthalik** [comment]
Yes, aruco will work fine. Things to keep in mind:

- the marker must be a rigid planar square
- keep a bit of empty white space around the marker
- the marker must be placed at angle angle with regard the camera. see wiki's aruco page.

**Comment by fabeit** [comment]
How big does the square have to be? Keep in mind that I have to wear this on my face.

**Comment by sthalik** [comment]
That is, 7 cm PLUS white area around the marker. The camera needs to distinguish the white area.

**Comment by fabeit** [comment]
Thanks for the info, I don't think this will work, can you imagine putting that on your forehead?

**Comment by sthalik** [comment]
Definitely. I used a piece of cardboard put between my head and headphones, with the marker mounted on it. Am not kidding.
