### ISSUE TITLE
[feature request] 6DOF tracking using acceleration/position sensors

### ISSUE THREAD

**Issue by ST6Daniel** [opentrack/opentrack#715]
Is this possible or not? (Technically accurate)

**Comment by sthalik** [comment]
TL;DR No.

Long version: try running FreePIE .apk on a phone without a gyroscope, but only the accelerometer and the magnetometer. You'll see what kind of tracking "quality" we're talking about.

**Comment by ST6Daniel** [comment]
Thanks!!!
