### ISSUE TITLE
mapping: pitch and alt-pitch graph have different snap value steps in 2.3.9

### ISSUE THREAD

**Issue by sanpats** [opentrack/opentrack#722]
Pitch graph has snap value step of 1.8 on x and 1 on y, but alt-pitch has 1 on x and 2.5 on y. I haven’t test other axes as I only has pitch axis that is not mirrored. 

If possible, can you make the step of x on rotation axes has the incremental step of 0.5 or 1? 1.8 is too high to set for a minimal dead zone at the beginning.

**Comment by sthalik** [comment]
I'm setting it to X=0.5, Y=1. Having less for Y is overkill with my low mouse sensitivity.

**Comment by sthalik** [comment]
There won't be a stable prerelease build for a while sadly. Some heavy changes went in at the last minute.
