### ISSUE TITLE
Arma 3 occasionally stop tracking. 

### ISSUE THREAD

**Issue by sanpats** [opentrack/opentrack#723]
Occasionally opentrack stop tracking in Arma3. It is still tracking in OT, but it seems the game does not get the value. Reset controller setting in game does not help. Stop and restart tracking in OT doesn’t help. The only way to fix is too close and reopen OT.

**Comment by sthalik** [comment]
This is the first time I ever heard about this. Some people had troubles with "Game mode" in newer Windows. Could this be it?

**Comment by sanpats** [comment]
I believe it was my own mistake in setting keys in Arma 3 that accidentally turn on the zero mode in OT. Please close this issue.
