### ISSUE TITLE
OpenTrack writes head movement(Yaw, pitch and roll) incorrectly in the csv file

### ISSUE THREAD

**Issue by ddrmorais** [opentrack/opentrack#725]
Hi Guys,

	I am using 360 videos and I need to employ head movement to this kind of videos. 
So, I use openTrack 2.3.9 and FreePie IMU to create an interaction between the Virtual Glass and the PC. 
The virtual glass transmits the head movements (yaw, pitch and roll)  using the FreePie to the computer. 

Thus, the OpenTrack 2.3.9 (Desktop Software) receives this information, prints it in the screen and records it in a csv file. 
However, the data (yaw, pitch and roll)that is showed in the display is different from recorded data. 

Whereas, they should be the same. As you can see in the picture just for a simple example, the yaw is turned in 45 degrees and the opentrack measures it correctly. But when opentrack software writes this infomation in the csv file, the head movements are wrong.

      Does anybody have any idea how to solve this problem?

![img_20180116_102128329](https://user-images.githubusercontent.com/35492354/34990417-29be75b6-faad-11e7-8038-ae5edfee70ac.jpg)

**Comment by sthalik** [comment]
1. What is your opentrack version?
2. opentrack records the pose during various transformation. You'd want the first six values, they're exactly what the device sends.

**Comment by sthalik** [comment]
opentrack records the pose during various transformations. There are various labels here:

- `raw`: what freepie sent, "raw data" window
- `mapped`: what you see in the "game data" window.

**Comment by sthalik** [comment]
@ddrmorais how large are the discrepancies?

**Comment by ddrmorais** [comment]
The data does not match at all.

I attached 2 files : a Gif with the example of my test and its csv file .

This first simple example intends to verify if Game data (in the screen) and Mapped data(in the csv file) are matching.
[OpenTrackTest.zip](https://github.com/opentrack/opentrack/files/1642781/OpenTrackTest.zip)

**Comment by sthalik** [comment]
Here's what LibreOffice draws:

![image](https://user-images.githubusercontent.com/1896811/35117881-56347700-fc90-11e7-8077-55517dfd6cb8.png)

I see you centered after several seconds. From this point it's offsetted on the Y axis.

It's strange how the maximum yaw value is (-135) rather than close to (-180). Is this the issue?

**Comment by ddrmorais** [comment]
I have just found out the error.
I normally open the csv file in Excel, and I dont know what happens that It messes up the numbers. When I opened in the gedit editor I have had no problem with the data (mappedYaw, mappedPitch and ,mappedRoll).

**Comment by sthalik** [comment]
Delimiters?

**Comment by sthalik** [comment]
Looks like we're god.
