### ISSUE TITLE
BitDefender blocking Opentrack dlls

### ISSUE THREAD

**Issue by Wh00kiE** [opentrack/opentrack#734]
Hi,
I can not use Opentrack since tuesday, BitDefender Antivirus is blocking some dlls in program files folder. (for example: opentrack-tracker-udp.dll ; opentrack-tracker-freepie-udp.dll ; opentrack-proto-win32-mouse.dll ; opentrack-migration.dll ; opentrack-tracket-joystick.dll ; opentrack-tracker-s2bot.dll)
BitDefender says that the files are infected with Variant.Razy.246207

I tried to uninstall and reinstall the latest version but the result is the same.

**Comment by sthalik** [comment]
There's nothing I can do about it. Add an exception or uninstall BitDefender.
