### ISSUE TITLE
How can i send my HeadMovement data  to my udpClient from opentrack via udp?

### ISSUE THREAD

**Issue by fuxingyang** [opentrack/opentrack#736]
when i set the output at udp over network,library load error！
![image](https://user-images.githubusercontent.com/20569009/35429904-06886938-02b1-11e8-9dd6-31cb9572b9a2.png)

**Comment by fuxingyang** [comment]
when i set the output at udp over network,library load error！Can you give me some ideas?Thank you

**Comment by sthalik** [comment]
The development build has descriptive failure messages. 2.4.0 hasn't yet been released.

I recommend using today's build. Things are quiet right now and it should be as stable as 2.3.9, if not more.

The dev builds are always on <<http://opentrack.misaki.pl>>.

- - -

![image](https://user-images.githubusercontent.com/1896811/35431623-78b8d008-027d-11e8-9261-83cf7a3440b8.png)
