### ISSUE TITLE
udp protocol data format

### ISSUE THREAD

**Issue by fuxingyang** [opentrack/opentrack#747]
I can get x,y,z data from opentrack via udp,but I don't know the streaming structure and can't translate to xyz data or yaw,pitch,roll data.Could you please give me some ideas?Thank you.

**Comment by cpuwolf** [comment]
I think you could refer to
https://github.com/opentrack/opentrack/blob/unstable/tracker-udp/ftnoir_tracker_udp.cpp

`double last_recv_pose[6], last_recv_pose2[6];`

hope it will help

**Comment by fuxingyang** [comment]
Is it correct structure for opentrack data as shown in the following figure? The figure is from https://github.com/opentrack/opentrack/issues/48.
![image](https://user-images.githubusercontent.com/20569009/36091651-69339d0c-101f-11e8-8b46-a4f1eba8bcd5.png)

**Comment by sthalik** [comment]
This is for FreePIE input. It's more complex than opentrack's input. opentrack's input is six double-floats with Euler angles as rotation.

**Comment by sthalik** [comment]
Oh, and note that endianness doesn't matter. IEEE floats are always little-endian.

**Comment by fuxingyang** [comment]
Thank you for your reply!opentrack's input is six double-floats with Euler angles as rotation.What about opentrack's output? Is opentrack's output  six double-floats with Euler angles as rotation? @sthalik

**Comment by fuxingyang** [comment]
I used java to write an udp client to receive opentrack data, but java is big-endian and the opentrack data sender is little-endian. Now I can get data from opentrack,but I can't read the data correctly.What should I do?thank you!

**Comment by sthalik** [comment]
@fuxingyang that endianness thing only applies to integers. IEEE floats are what they are.

The output is also six double-precision floats with rotation as degrees.

**Comment by fuxingyang** [comment]
Thank you!Best wishes!@sthalik 
I used testing-sine wave as input,and UDP overnetwork as output.Then I receive data by java and read the data in six double-precision floats,but i doubt the result.
![image](https://user-images.githubusercontent.com/20569009/37308467-17e627d8-2679-11e8-9a7a-f537503082ab.png)
Here is my code.Can you give me some ideas?Thank you!
`package client.viewportPredictModule;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;

/**udp数据接收器:<br>
 * 接收opentrack的头部运动数据
 * @author YangFuxing
 *
 */
public class UdpConnection {
	
	public static void main(String[] args){
		new UdpConnection().connection(3001);;
	}

	
	protected void connection(int udpPort){
		byte[] recvBuf=new byte[1024];
		DatagramPacket dp=new DatagramPacket(recvBuf, recvBuf.length);
		try {
			DatagramSocket ds=new DatagramSocket(udpPort);
			ds.receive(dp);
		    byte[] data=dp.getData();
		       
	        for(int i=0;i<data.length/8;i++){
	        	if(i!=0&&i%6==0){
	        		 System.out.println();
	        	 }
	        	 System.out.print(getDouble(data,i*8)+",");	 
	        }
			ds.close();
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
    // 从byte数组的index处的连续8个字节获得一个double  
	protected  double getDouble(byte[] arr, int index) {  
        return Double.longBitsToDouble(getLong(arr, index));  
    }  
	
	 // 从byte数组的index处的连续8个字节获得一个long  
	protected  long getLong(byte[] arr, int index) {  
        return  (0xff00000000000000L    & ((long)arr[index+0] << 56))  |   
                (0x00ff000000000000L    & ((long)arr[index+1] << 48))  |   
                (0x0000ff0000000000L    & ((long)arr[index+2] << 40))  |   
                (0x000000ff00000000L    & ((long)arr[index+3] << 32))  |  
                (0x00000000ff000000L    & ((long)arr[index+4] << 24))  |   
                (0x0000000000ff0000L    & ((long)arr[index+5] << 16))  |   
                (0x000000000000ff00L    & ((long)arr[index+6] << 8))   |   
                (0x00000000000000ffL    &  (long)arr[index+7]);  
    }  
}
`

**Comment by sthalik** [comment]
```
    return  (0xff00000000000000L    & ((long)arr[index+0] << 56))  |   
            (0x00ff000000000000L    & ((long)arr[index+1] << 48))  |   
            (0x0000ff0000000000L    & ((long)arr[index+2] << 40))  |   
            (0x000000ff00000000L    & ((long)arr[index+3] << 32))  |  
            (0x00000000ff000000L    & ((long)arr[index+4] << 24))  |   
            (0x0000000000ff0000L    & ((long)arr[index+5] << 16))  |   
            (0x000000000000ff00L    & ((long)arr[index+6] << 8))   |   
            (0x00000000000000ffL    &  (long)arr[index+7]);  
```

Shift without the AND mask. Always use little-endian for doubles on all platforms.

**Comment by fuxingyang** [comment]
hi @sthalik,Why is the output data of opentrack 6 double types data instead of 3?I just want to get the Movement data of HMD.
Thank you, @sthalik .Best wishes!

**Comment by sthalik** [comment]
@fuxingyang it returns position and rotation data, in that order.

**Comment by fuxingyang** [comment]
@sthalik ,Thanks for your patience with me!
"it returns position and rotation data, in that order."Are they all degrees data ? Or [x,y,x,yaw,pitch,roll]?
The [yaw,pitch,roll] data is useful for me.
Now I don't know how to get it.I can get the data streaming in java, but the bytes to double is seemingly wrong.
I am so Depressed！

**Comment by sthalik** [comment]
XYZ are in centimeters. yaw, pitch, and roll are in degrees.

Convert bytes to long in a little-endian format (i.e. reverse the left shift order). As long as you see "raw data" and "game data" as sensible values, you'll also receive sensible values from the UDP socket.

**Comment by fuxingyang** [comment]
Thank you!
You mean that, the data i got first three are positional data, and the back three are the game data. They are all angle data. That is to say, for me, the first three data are useful.
