### ISSUE TITLE
opentrack now has lang RU and NL, can we add Chinese support?

### ISSUE THREAD

**Issue by cpuwolf** [opentrack/opentrack#748]
I would love to support Chinese related portion. I think I could do it from module to module, and tracker/wii is just a beginning.

#746

**Comment by sthalik** [comment]
Please see 6bb50c04e5c40a5e036e41dde11b1660c3b077f6. I fixed translation-related issues that we had.

I also added `zh_CN` to the language list in 31d9768413199f388c216d92d9db5158ce8785cf and then running `make install` created the `.ts` files automatically.

Finally, I fixed a bug where `make clean` deleted all translation files.

**Comment by sthalik** [comment]
You should be able to do translations from now on. To update based on code changes, run one of the `i18n`, `all` or `install` targets.

It's best to run `QObject::tr` as long as you're within some `QObject` subclass.  See also `_(str, ...)` for when necessary to translate outside `QObject`.

Does it work now?

**Comment by cpuwolf** [comment]
until latest commit: tracker/wii: silence #pragma deprecated

there is build error with target "INSTALL" in MSVC


1>------ Build started: Project: i18n, Configuration: Release Win32 ------
1>Building Custom Rule F:/works/GitHub/opentrack/CMakeLists.txt
1>CMake does not need to re-run because F:/works/GitHub/output/opentrack/CMakeFiles/generate.stamp is up-to-date.
1>Running lrelease for nl_NL
1>CUSTOMBUILD : lrelease error : Cannot open F:/works/GitHub/output/opentrack/variant/default/lang/nl_NL.ts: 系统找不到指定的路径。
1>Done building project "i18n.vcxproj" -- FAILED.

**Comment by sthalik** [comment]
What happens if you run the `i18n` target manually?

This is strange because `/variant/default/lang/nl_NL.ts` exists in the repository.

**Comment by sthalik** [comment]
I'm able to run:

```
dev/opentrack/build % find . -name '*.ts' -delete
dev/opentrack/build % msvc ninja install
```

While there are subtle differences between build systems, it should work after solution reload, `clean` or `mrproper`, then `install`. It should also work on following installs. Of course if you still have an issue it's unacceptable and I need to fix it.

**Comment by cpuwolf** [comment]
I created a new folder, and fetched latest commit. now same error with target "build"

1>------ Build started: Project: i18n, Configuration: Release Win32 ------
1>Building Custom Rule F:/works/GitHub/opentrack/CMakeLists.txt
1>CMake does not need to re-run because F:/works/GitHub/output/opentrack/CMakeFiles/generate.stamp is up-to-date.
1>Running lrelease for nl_NL
1>CUSTOMBUILD : lrelease error : Cannot open F:/works/GitHub/output/opentrack/variant/default/lang/nl_NL.ts: 系统找不到指定的路径。
1>Done building project "i18n.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 34 up-to-date, 0 skipped ==========

![zbmate_com_obs_addon02 2018-02-13](https://user-images.githubusercontent.com/1320329/36124949-0429f686-108d-11e8-85f7-37288593a2fc.jpg)

I checked the path

F:/works/GitHub/output/opentrack/variant/default/lang/nl_NL.ts

as I show above, there is no folder '''lang'''

**Comment by sthalik** [comment]
Does it work now? I was able to build from a `.sln`.

**Comment by cpuwolf** [comment]
it works now :+1: 

then what should I expect to see the final result. because what I can see is still English during runtime

**Comment by sthalik** [comment]
Works for me now.
