### ISSUE TITLE
experimental bild 20180216_11 crashes when starting before Il-2 Sturmovic Forgotten Battles

### ISSUE THREAD

**Issue by Seamas73** [opentrack/opentrack#752]
When I start opentrack testing build 20180216_11 and then start "Il-2 Sturmovik: Forgotten Battles" game shows error window with nearly this content: " program NPClient.dll not made to work in Windows or broken. Try to reinstall it". And then opentrack crashes. I solved this problem by replacing NPClient.dll with the dll from latest stable release.

**Comment by sthalik** [comment]
It's a 64-bit binary. Is it fully patched? Make sure to disable `old_trackir` in IL2 config.

**Comment by sthalik** [comment]
To explain -- it should be opening `NPClient64.dll`.

**Comment by Seamas73** [comment]
I told not about new "Il2Sturmovik: Battle over X" game, I told about "good old" "Il-2 Sturmovik 1946: Forgotten Battles" game. Old game is 32bit, with all last patches installed. And in it config file don't exist "old_trackir" parameter, there is only "TrackIRUse" parameter.
On stable releases of opentrack old "Il-2" didn't show errors with NPClient.dll and didn't cause crash of opentrack.

**Comment by sthalik** [comment]
I'll look into it. For now use today's 2.3.10-pre from the same site.

**Comment by Seamas73** [comment]
> For now use today's 2.3.10-pre from the same site.

It works fine

**Comment by sthalik** [comment]
With the old build, it can be Windows Defender or SmartScreen. Please check with antivirus disabled.
