### ISSUE TITLE
[TrackHat] New Clip dimensions are incorrect

### ISSUE THREAD

**Issue by sanpats** [opentrack/opentrack#755]
I just bought TrackHat Clip Plus Mini (the new clip in your code, trackhat branch). But my measurements are different than what you put in a recent commit. Mine are by = 62, bz = 35, ty = 43, tz = 14. You're better check with TrackHat.

**Comment by sthalik** [comment]
I elevated the issue.

Now, my own questions. The clip I own wasn't made by trackhat, I only provided the size for their manufacture.

1. What kind of measuring device did you use?
2. What size is a single trackhat LED?
3. Did you get the depth values by Pythagoras?

**Comment by sanpats** [comment]
1. A ruler and a square. Plus a sheet of paper to mark and out line the LEDs and the shape. 
2. I tried to measure from the center of the base as the height of the LEDs vary between the three LEDs +- 2mm (I think they were cut at the top and sanded down by hand). 
3. I drawed 3 parallel lines that pass through all the centerlines of all three LEDs, plotted the outline, and measured the distance between 3 LED bases.

**Comment by sanpats** [comment]
My measurement may be error 1-2mm but should not be more than that, but as the y axes are 43 and 62 the same as older clip, I think it is intentional.

**Comment by sanpats** [comment]
I read your reply amp n BMS forum that it is the old clip with z values cut in half. 
The track hat clip pros, both old and new, have the same y value, by = 62, ty = 43. 
The different are z values, the old one are bz = 75, tz = 27. 
The new one are bz = 35, tz = 14; which are approximately half of the old one. (The exact half of the old one would be 37.5 and 13.5 respectively.

**Comment by sthalik** [comment]
New values:

> by = 60, bz = 38.2, ty = 42.2, tz = 12.6;

I'm releasing a TEST build.

**Comment by sthalik** [comment]
Get it at http://opentrack.misaki.pl. You should know which file it is.

I'd expect trackhat to release an official version soon.

**Comment by sthalik** [comment]
Please confirm whether the damn thing works.

**Comment by sanpats** [comment]
I'll test the trackhat opentrack. What about normal opentrack? I cant input floating point, only integer. Will the nearest integer suffice?

**Comment by sthalik** [comment]
Nearest will suffice.

**Comment by sthalik** [comment]
I'm keeping this issue open until p6 comes out.

**Comment by sanpats** [comment]
New dimensions work fine with p5, but I didn’t test it very extensively as I normally use normal opentrack with my Trackhat clip plus mini.

**Comment by sthalik** [comment]
Use the test build or the new dimensions in opentrack. The issues manifest themselves in subtle ways. The algorithm is robust in face of incorrect values but there's some "residue". You'll also need less filtering with correct model.

**Comment by sanpats** [comment]
Sorry I meant test build not p5. I tested in normal opentrack as well. Both works fine.

**Comment by sthalik** [comment]
Complain loudly till it's fixed. I can only nag relevant people to a certain degree.

**Comment by sthalik** [comment]
FWIW, I sent p6 already but it hasn't been put on the site.

**Comment by sthalik** [comment]
They should release p7 soon. Thank you for reporting this.

**Comment by sthalik** [comment]
@sanpats looks like version p7 is now on trackhat's site. Sorry for the belated reply.
