### ISSUE TITLE
PS3 eye FPS down abruptly problem

### ISSUE THREAD

**Issue by jimidemian92** [opentrack/opentrack#763]
Hello! I hope you can help me. Some time ago when I used opentrack with ARMA3 or assettocorsa with other devices other than keyboard and mouse, for example, joystick saitek or logitech g 27, once the game was executed after a time fps down abruptly. This was solved by reinstalling the ps3eye camera drivers, but today it happened again and reinstalling the drivers did not solve it.
Interestingly if I use the keyboard and the mouse with opentrack in ARMA, for example, this does not happen, also using joystick or G 27 if the task manager is running the low fps does not happen either. (It is a solution but not the optimal one)
I'm going crazy with this.
Thank you!

PD: 100% google translator.

**Comment by sthalik** [comment]
What is your Windows version? Are you using "Game Mode" in Windows 10?
