### ISSUE TITLE
Yaw drift issue

### ISSUE THREAD

**Issue by Reaper6722** [opentrack/opentrack#766]
when i start tracking using udp over network as input and freetrack 2.0 as output, my yaw starts drifting and then switches to 180º instantly, it keeps doing the same thing over and over after i center, i tried adjusting deadzones and nothing happens, please help, im using TrinusVR and trying to play Assetto Corsa

**Comment by sthalik** [comment]
Look for raw data on the main window, it's the exact data "TrinusVR" sends.
