### ISSUE TITLE
Single Point Tracking [Request]

### ISSUE THREAD

**Issue by alnilamorion** [opentrack/opentrack#767]
I see this has been requested before but I want to bring it again.
I use PS3 Eye with TrackClip Pro. Personally, I use 2DOF tracking for Arma 3. My newest wireless headset has adjustable lights which are perfectly recognized by opentrack. But without the support of Single Point Tracking, I am bound to use TrackClip Pro. I tried making the whole thing wireless by installing a power bank but it bothers me to attach unnecessary things on my head when what I need is already there. I could just put on the headset and ready to go with 2DOF.

Yes... 6DOF and 2DOF is not even comparable when it comes to games like DCS World. But why not to add a very simple and elegant feature. Should it be supported, lots of people in developing countries who cannot get TrackClip Pro or similar DIY solutions easily, will start using at least 2DOF. Single Point Tracking is so easy to use that even a keychain light does the work. In fact this is how I started back when FreeTrack was working.

Thanks

**Comment by sthalik** [comment]
Not unless someone contributes the code.
