### ISSUE TITLE
Opentrack not working anymore

### ISSUE THREAD

**Issue by TommyLee42** [opentrack/opentrack#769]
I noticed this couple a days ago (not sure about exact moment) first in DCS it kinda moved momentarily once and then dies out. Same thin happened in ETS2 aswell as i tested it today. It was all working just fine with current settings and I see all three LED's in opentrack preview window.  For notice I am usind Opentrack 2.0 as output set on both. I wish I could write more data . Only thing I know it is working ok when i am testing it in opentrack preview window. it is just not connecting to DCS anymore . Nothing was changed in mean time. I am only thinking to reinstall opentrack...again...

**Comment by TommyLee42** [comment]
Update.
After reinstalling (dirty) it looks fine now. Well. Maybe someone else will have use of this information if nothing else.

**Comment by TommyLee42** [comment]
I did not checked and it died on me yet again..ill go check

**Comment by TommyLee42** [comment]
not sure who should recive this email but my opentrack is working just fine.

2018-05-22 18:06 GMT+02:00 Stanisław Halik <notifications@github.com>:

**Comment by sthalik** [comment]
@TommyLee42 for reference, each time you change opentrack's directory, you must start tracking with freetrack once before running any games. Otherwise the games won't work with freetrack output at all. This is because starting tracking sets up some registry entries (with freetrack output).

**Comment by TommyLee42** [comment]
Ok I will keep that in mind thank you.

2018-05-27 21:42 GMT+02:00 Stanisław Halik <notifications@github.com>:
