### ISSUE TITLE
Opentrack doesn't receive data from FreePIE IMU but receives from another app

### ISSUE THREAD

**Issue by StuDentBRz** [opentrack/opentrack#773]
I am trying to use opentrack with FreePie IMU, on my android smartphone with gyroscope and accelerometer , but i am having some trouble...
I can see on FreePIE IMU on Android that it is getting the acelerometer and gyroscope data, but opentrack won't receive any of this data. I've tried via wi-fi network and USB tether, i always configured the same IP and ports, and even disabled windows firewall and nothing worked.
It's not a problem on my network, because i've tested with another app on android (HeadTracker from play store) and also changed the input from FreePIE UDP receiver to UDP over network and then opentrack received the data as it should...

**Comment by sthalik** [comment]
I need to see the packet payload. Are you able to use Wireshark?

**Comment by sthalik** [comment]
First check if version from opentrack install directory's `doc/contrib/freepie-udp` works for you.

**Comment by sthalik** [comment]
Disable Windows firewall temporarily, start opentrack and see if it works. If it does, it's a firewall problem. Also check port and IP address.

**Comment by sthalik** [comment]
Oh, and also confirm that the phone has all of: accelerometer, gyroscope, magnetometer.

**Comment by StuDentBRz** [comment]
My smartphone is a Motorola moto G4 plus (Android 7.0), It has gyroscope and accelerometer but no magnetometer. As i Said in the first post i already tried to disable firewall and checked the ports, i even opened the 5555 port on firewall myself and didn't work.
I thought It was a because it didn't have magnetometer, but It Works Just as It should with the other app (headtracker).
Unfortunatelly i don't have a Phone with magnetometer to see If It Will work...

**Comment by sthalik** [comment]
In the Android app, select "send orientation", check "debug", and see if you get any rotation data after starting.

**Comment by StuDentBRz** [comment]
No i don't get any orietation data, i can only get data when RAW input is active and It is only gyroscope and acelerometer, no magnetometer or orietation.

**Comment by sthalik** [comment]
`opentrack` specifically asks for rotation data. If you select "send raw" on Android but debug shows no rotation data, the phone isn't supported.

**Comment by sthalik** [comment]
Just to be clear, please note that rotation data is extracted using Android's internal API. We don't implement the estimator.

**Comment by sthalik** [comment]
I forgot again, apologies. I've tried extracting data using only gyro+acc, it had serious problems and wasn't really usable.

Consider using the Aruco tracker (info on github's wiki) for a zero-cost solution.

**Comment by StuDentBRz** [comment]
It's really weird that you say that my Phone is not supported  by opentrack, because it Works Very well Just by using headtracker app(which i downloaded from Playstore), instead of FreePie IMU,  i am just going to keep using this way... It is Free with ads, but it doesn't really matter for me, because i won't be looking at the app for much longer... At least It is a option for people like me who has a Phone with gyroscope and acelerometer but no magnetometer, so i can have opentrack working without have to buy a New Phone... Did You try to use Headtracker to see what is the difference the data difference between Headtracker and FreePie IMU ?

**Comment by sthalik** [comment]
There's an AHRS method for using gyro+acc only but we don't implement any methods on our own in the .apk.

**Comment by diveyez** [comment]
The FREEPIE apk is not sending any data to windows at all, entirely broken UDP code

**Comment by sthalik** [comment]
@diveyez the code's not broken. The apk's been like that for a long time and hasn't had problems sending data. Did you check with Wireshark?

**Comment by dorianr666** [comment]
yep, its broken. looks like freepie imu doesnt send data. other apps communicating with opentrack from android work fine.

**Comment by sthalik** [comment]
What's the Android version?

**Comment by MABlosfeld** [comment]
freepie imu is working but when i turn on another app or game, freepie turns off by itself. i'm using opentrack/moonlight/reshade with my vr headset and android, just need freepie to transmit data from motion sensors to opentrack. I support paying a small amount to keep all these projects and developers motivated.

**Comment by sthalik** [comment]
There are several .apk versions in the contrib directory. One of them was known to work with Android 9.

**Comment by MABlosfeld** [comment]
I'm using "freepie_imu_android9.apk" apk and the app is working, the problem is that when I start moonlight or any game, freepie shuts down by itself. My android is on version 12, maybe this is the reason that makes freepie turn off by itself.

**Comment by MABlosfeld** [comment]
Moonlight and other games are added within the GAME LAUNCHER APP which has a priority mode, I disabled priority mode and now FREEPIE is not turned off when I start moonlight. Priority mode is important, it keeps the screen always on. Now I need to find a way to add FREEPIE inside the GAME LAUCHER app.

**Comment by MABlosfeld** [comment]
I disabled priority mode in game launcher, started freepie and then started moonlight. After 20 min everything was still up and running (freepie/moonlight/cell phone display).
