### ISSUE TITLE
Toggle while held (@Options>Shortcuts) does not stop the filter output (Accela at least).

### ISSUE THREAD

**Issue by r8d** [opentrack/opentrack#777]
Hey you talented Opentrack developer 

I testes & found (version 2.3.10) that the "Toggle while held" shortcut (@Options>Shortcuts) does not stop the filter output (for Accela filter at least).
I think this issue/future feature will make my gaming life much easier in a clickable cockpit (DCS for example).

Thank you so much for sharing your awesome software & keep it coming

P.S. Let me know if you need other info from me.

**Comment by sthalik** [comment]
It's fixed for the next build
