### ISSUE TITLE
[need option] No-Centering 

### ISSUE THREAD

**Issue by DrYuD** [opentrack/opentrack#780]
Hi! I found that ther is no option that can "stop" centering camera by Yaw.
Main idea- is to make VR, with small FullHD video Helmet (witch usually used by fpv pilots) like a monitor and  headtracker (arduino+gy-85. ) 

It's perfectly works like a similar VR with your programm, but I have one problem, camera always come back to center after rotating head by Yaw.  So i'm using "Hatire Arduino" with "mouse emulation protocol."  Could you add an option "no centering"?

In the end, users can find one more way to use this programm! And this will be cheep way to play games in VR.
I hope i explained  well what did i mean. If no, please contact me.

**Comment by sthalik** [comment]
What's exactly happening as per your problem? I don't understand the behavior yet.

**Comment by DrYuD** [comment]
Ok, I waht to make movement for Right and Left the same, as working Up an Down, without automatical coming back to center to main position. But there is no option, how to stop this centering. 
I will try to explain detaily in video below, link on gogole drive.
https://drive.google.com/open?id=1Djq7EA6uknGJJE4Mirvchm_Y09r_Ebin

**Comment by sthalik** [comment]
It'll have to go into a plugin given the feature is obscure. Plugin support is halfway done.

**Comment by DrYuD** [comment]
Hi, I'm sorry. I right understand, you will fix this feature in new version 2.4.0?

**Comment by sthalik** [comment]
Yes. It'll be fixed even sooner.

You have the same problem as #852. I'm closing this one and keeping the other one open.

**Comment by sthalik** [comment]
@DrYuD I think this can be a different issue.

Please look at raw yaw values on the program's main screen. Do they move toward the center on their own?

Some HMD models suffer from gyroscope drift, and firmware autocorrects it by centering by itself, with no user motion. This may or may not be the case.
