### ISSUE TITLE
[POLL] which Rift version are you using

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#781]
We don't have poll support so please answer in a post.

- [ ] Rift 0.2.5
- [ ] Rift 0.4.2
- [ ] Rift 0.8.0
- [ ] Rift 1.4.0

This is actually sort of important to Rift support.

**Comment by Animus777** [comment]
1.4.0

**Comment by senorprime** [comment]
1.4.0

**Comment by sthalik** [comment]
If you're using any of the older Rift trackers please post on this issue tracker or send an email to <<sthalik@misaki.pl>>. I'll be phasing them out first with a message on each start, ending with removal after few opentrack versions. So speak up if you need them for anything.

**Comment by sthalik** [comment]
Removed, thanks.
