### ISSUE TITLE
Rift 1.4.0 - erroneous roll while pitching

### ISSUE THREAD

**Issue by senorprime** [opentrack/opentrack#791]
Using opentrack 2.3.10.

Whenever I pitch up or down, I get significant roll, I can't figure out where it's coming from.

For instance at pitch -44, I have a roll of 50, and and about -60 roll when the pitch is 40.

**Comment by sthalik** [comment]
Do the other values (yaw and pitch) change when that roll happens?

**Comment by senorprime** [comment]
Yes, when I roll the HMD, the pitch significantly increases when rolling left, and decreases when rolling right. Essentially the inverse of what happens when it pitches.

**Comment by sthalik** [comment]
What is the raw roll value when you're centered?

**Comment by senorprime** [comment]
Very close to 0, it's broadly the same as the game data output, so if I just hold the headset in my hands and carefully roll it, the Raw roll value is pretty much 0, and it's just the pitch that increases/decreases.

**Comment by sthalik** [comment]
I'm going to implement a custom center function for Rift. Also Rift earlier to 1.4.0 is going away.

**Comment by sthalik** [comment]
What happens if you disable "center at startup" and don't center by yourself? Does it work then?

**Comment by sthalik** [comment]
Please head on to #820.
