### ISSUE TITLE
Windows Mixed Reality support.

### ISSUE THREAD

**Issue by Kieran43770** [opentrack/opentrack#793]
Was trying to get opentrack working on my WMR headset as it works through Steamvr but when I press start it isn't tracking on opentrack. The headset is being detected as it appears in the the device selection.
![vrsnap](https://user-images.githubusercontent.com/39784496/40757145-0308b1fc-647f-11e8-822e-bf3e9929cd92.png)

**Comment by Kieran43770** [comment]
Nevermind, got it working.

**Comment by sthalik** [comment]
@Kieran43770 how?
