### ISSUE TITLE
Please add 100 & 50 fps for countries with 50Hz electric signal. 

### ISSUE THREAD

**Issue by calico2** [opentrack/opentrack#794]
In my country we have 50 Hz signal and when artificial illumination is in use, it makes an awfull blink effect when captured at 30 60  75 or 120 fps. Ps3 eye toy driver can handle 50 or 100 fps smothly but the option list has not got these options. I am using aruco tracker.  1000 thanks in advance.

**Comment by sthalik** [comment]
Changing fps won't help. Only driver-side power line compensation will help. These are different things.

I'd like to see a video with the power line flicker visible and run some tests. Please upload one, just compress it first.

**Comment by calico2** [comment]
[prueba60.zip](https://github.com/opentrack/opentrack/files/2068843/prueba60.zip)

**Comment by calico2** [comment]
I am trying to make it lower than 10 MB  rename this one as z01

[prueba60.z01.zip](https://github.com/opentrack/opentrack/files/2068855/prueba60.z01.zip)

**Comment by calico2** [comment]
rename this as z02 
[prueba60.z02.zip](https://github.com/opentrack/opentrack/files/2068859/prueba60.z02.zip)

**Comment by calico2** [comment]
If i use point tracker 1.1  I can set capture to 50 Hz  and adjust in 1 Hz steps. The capture is perfect then. In aruco I am limited to fixed FPS.

**Comment by sthalik** [comment]
I'm unable to open it using 7zip or unzip from Unix. Please send something that extracts using either of these tools.

I recommend just splitting the data in half or hosting it on Dropbox.

**Comment by sthalik** [comment]
Do you get a bad capture in PointTracker if Hz isn't a multiple of the European 230V/50Hz AC rate?

**Comment by calico2** [comment]
[prueba60.7z.001.log](https://github.com/opentrack/opentrack/files/2071919/prueba60.7z.001.log)
[prueba60.7z.002.log](https://github.com/opentrack/opentrack/files/2071924/prueba60.7z.002.log)
[prueba60.7z.003.log](https://github.com/opentrack/opentrack/files/2071929/prueba60.7z.003.log)
[prueba60.7z.004.log](https://github.com/opentrack/opentrack/files/2071938/prueba60.7z.004.log)

**Comment by calico2** [comment]
Please rename the files without the .log for extracting.
