### ISSUE TITLE
Model position gets displaced after loosing 1 point momentarily

### ISSUE THREAD

**Issue by nuno-pc** [opentrack/opentrack#801]
Using: hat model; input pointracker 1.1; output freetrack 2.0 enhanced

If turning left/right it looses track of one point on left/right:
Then (when getting back to center and reacquiring point) all is mixed up; view is stuck,
and Model position is out of place.
Need to press re-center twice to get back to normal.

Attached pictures:

[IssueOT_Losing_Point_Displaces_Model_Center_20180612.pdf](https://github.com/opentrack/opentrack/files/2094785/IssueOT_Losing_Point_Displaces_Model_Center_20180612.pdf)

**Comment by Len62** [comment]
I would try increasing the minimum point size to 6 or 7, and max to 9 or so. With small point sizes some tracking is lost if it gets to low. Experiment with the point settings.

**Comment by sthalik** [comment]
- Look forward and center after this happens in worst-case scenario.
- Increase dynamic pose timeout.

**Comment by sthalik** [comment]
> Need to press re-center twice to get back to normal.

If you need to center **twice**, it's a bug.

**Comment by sthalik** [comment]
Pressing "center" once is now enough in the dev build.
