### ISSUE TITLE
Check permissions for your .ini directory

### ISSUE THREAD

**Issue by InsanelyOrange** [opentrack/opentrack#805]
After installing and launching open track for the first time, I was greeted with this error message.
![untitled](https://user-images.githubusercontent.com/40529959/41814716-16359012-7724-11e8-90bd-0367a37c0854.png)
As you can see, the folder exists and I (along with all other groups have full access to the file). 
Running Windows 10, not sure what's going on.

**Comment by sthalik** [comment]
See if you checked "Windows Defender -> Controlled folder access" (aka ransomware protection). It's off by default.

Did you create the directory by yourself or was it created on its own? The latter should happen. But in the same case, the missing `.ini` file should get created as well!

This logic can happen either before the main window shows up, or during program runtime. I retraced it and it's sound.  You're also the first person to report this.

**Comment by InsanelyOrange** [comment]
> See if you checked "Windows Defender -> Controlled folder access" (aka ransomware protection). It's off by default.

I'm running BitDefender as my antivirus and turned off ransomware protection but the error still persists. I tried uninstalling and reinstalling with ransomware protection off and no dice.

> Did you create the directory by yourself or was it created on its own? The latter should happen. But in the same case, the missing .ini file should get created as well!

The folder was created on it's own, strange the ini wasn't created.

> This logic can happen either before the main window shows up, or during program runtime. I retraced it and it's sound. You're also the first person to report this.

Never been able to get the program to open, so I guess I'm experiencing the former part of the logic.
I'm the lucky first, Saw another post about this on some Spanish or Portuguese flight sim board, that was it, haha. Thanks for taking the time to respond.

**Comment by sthalik** [comment]
But I'm not done! I intend to help you with the problem.

Antivirus software normally has an option to disable it for X minutes in the tray icon. Can you try with that first?

**Comment by InsanelyOrange** [comment]
> But I'm not done! I intend to help you with the problem.

Glad to hear it since you've helped me solve my problem. It seems Bitdefender was blocking opentracker from writing files to my Documents folder. I simply went to View Features -> Safe Files -> Application Access and added opentrack.exe as an exception. opentrack now launches successfully. 

Thanks a lot for your help sthalik, I probably should've looked at my anti virus software before bothering you!

**Comment by sthalik** [comment]
I'm glad this helped! Cheers.
