### ISSUE TITLE
Points are too big

### ISSUE THREAD

**Issue by spogatetz8386** [opentrack/opentrack#806]
I have a DIY LED rig that works quite well when it is dark but when there is some light in the room it detects the three points initially but then loses them because they are bigger than the 100px limit. Any ideas on how to fix this.
![capture](https://user-images.githubusercontent.com/21247362/42006985-d5d894e8-7a42-11e8-911c-ff7bf30a5b20.PNG)
I think it is reasonable to have it track these points.

If I turn down the resolution it picks up the points fine but the tracking does not work properly.

**Comment by sthalik** [comment]
These don't have 100px radius. It must detect something else as equally or more bright.
