### ISSUE TITLE
Raw tracker data and game data don't match up

### ISSUE THREAD

**Issue by quinn1005** [opentrack/opentrack#814]
I havent really screwed with anything to do with changing the output but for some reason the raw and game data are no where near each other. I am using a aruco tracker on my headset, it was working just fine until i tried to put my phone in via trinus. I tried turning off trinus but it's still doing it. I've tried centering it, calibrating it but nothing has worked so i figured i had nothing to lose posting here.
![opentrackscrewedup](https://user-images.githubusercontent.com/41151528/42629699-4d40f92a-85a2-11e8-9ec5-bafad861b1b2.png)

**Comment by sthalik** [comment]
Your marker is rotated. First make sure raw data roll is close to zero.

**Comment by quinn1005** [comment]
ok i'll try that

**Comment by quinn1005** [comment]
ok it works now thanks man. Just need to get a better webcam now, my kinda blurs if i move fast so it freezes then jerks to where im looking when it can recognize the qr code again lol

**Comment by sthalik** [comment]
Just so you know, PS3 Eye works worse with Aruco worse than a 30 Hz camera.
