### ISSUE TITLE
Added pages to the Wiki

### ISSUE THREAD

**Issue by DanTDBV** [opentrack/opentrack#815]
Based on you reply to Len62 here:
https://github.com/opentrack/opentrack/issues/810 
I have gone ahead and added the following pages to the Wiki:

https://github.com/opentrack/opentrack/wiki/opentrack-Shortcuts-descriptions

https://github.com/opentrack/opentrack/wiki/Manual-calibration-of-PointTracker-1.1-model

https://github.com/opentrack/opentrack/wiki/Loss-of-tracking-with-PointTracker-1.1-and-Cap-tip

I hope that they are helpful to some.

**Comment by Len62** [comment]
Thanks for adding info to the wiki! I don't have the time at present but eventually I hope to get around to updating some items. I know for sure that sthalik will appreciate your efforts.

**Comment by sthalik** [comment]
Thank you for the contributions!

I think credit for given page's principal author is ethical and in fact, a must. I'm leaving your attribution as-is. One thing I disliked about Wikipedia was being one of countless nameless editors who get no recognition.

I added some small elaborations on "Shortcuts" and "Loss of tracking" pages.
