### ISSUE TITLE
Not calibrating correctly in OT 2.3.10 when using PointTracker 1.1 and Cap.

### ISSUE THREAD

**Issue by DanTDBV** [opentrack/opentrack#816]
Not really an issue, as I have solved it by doing a manual calibration instead.
Whenever I use your calibration method or the Len Endy method, the center + is offset to one side, as if the calibration assumes, that I am using a Clip instead of the cap.

It is consistent, as in every time I try. It could very well be me doing it wrong.

Here are a couple of pictures showing what I mean.

sthalik calibration method
![sthalik calibration method](https://user-images.githubusercontent.com/28660962/42729051-131852d0-87cc-11e8-8ed6-998c4620b624.jpg)

Len Endy Calibration method 1
![len endy calibration method 1](https://user-images.githubusercontent.com/28660962/42729057-263e5968-87cc-11e8-8a7e-a46b8feadfb3.jpg)

Len Endy Calibration method 2
![len endy calibration method 2](https://user-images.githubusercontent.com/28660962/42729058-30e39cb6-87cc-11e8-8b96-76eac3daa86a.jpg)

I figured this out:
Directions are for moving the calibration marker (The +) in relation to you facing the screen, that is left is to your left and vice versa.

X 0 Y 0 Z 0 is the position of one of the LED’s (The LED with the + over it.)
(In my case, the top center LED of my cap.)
X + is to the right, - is to the left
Y + is above, - is below	
Z + is behind, - is in front

I set it up like this:
Manual Calibration
![manual calibration](https://user-images.githubusercontent.com/28660962/42729060-3cd915f0-87cc-11e8-8315-403ae79e9f46.jpg)

Now it works as a charm.

Once again, thank you so very much for this great software!

DanTDBV

**Comment by sthalik** [comment]
The calibrator isn't assuming anything. It's generic statistical code. You can read it and not find a single reference to what the clip actually is. There's something else at play here. I don't know what, need to know more about camera position, camera rotation, etc.

**Comment by sthalik** [comment]
As for the centering procedure I'd like you offer mine:

IMPORTANT: don't rotate too fast when calibrating. The calibrator only runs 30 times a second.

NOTE: don't roll on purpose. Just do natural movements as you'd do ingame. Roll calibration is a debug feature for users that can read and write code. 🐙 

NOTE: no need to yaw and pitch more than you'd do ingame.

- Pitch up as much as sensible
- `START`: yaw left/right
- Pitch up a bit lower (I do it with 3-5 pitch steps)
- If you're already pitched very low, go to `END`
- Pitch lower.
- Go to `START`
- `END`: Done, stop calibrating :octocat:
