### ISSUE TITLE
War Thunder on Linux

### ISSUE THREAD

**Issue by CJPilot** [opentrack/opentrack#819]
I was wondering if there was a way to get opentrack to work with the native version of War Thunder. I read in a old topic that there was no Freetrack support for native Linux games. Is that still true? I would prefer if I don't have to have a opentrack version for X-Plane and another opentrack for War Thunder.

**Comment by sthalik** [comment]
Maybe via a virtual joystick on Linux?

**Comment by CJPilot** [comment]
Do I have to udev something to make it work? I read that you need Read-Write permissions for the file /dev/input/uinput/ but when I start tracking, it say it can't find /dev/uinput/. I'm confused to what it's asking me to do.

**Comment by sthalik** [comment]
You might have `/dev/uinput`. Symlink it and add yourself group permissions.

**Comment by sthalik** [comment]
As long as `/dev/uinput` has a sensible group you can add yourself to the group and relog.

**Comment by CJPilot** [comment]
I don't have a /dev/uinput folder. Should I create one?

**Comment by sthalik** [comment]
# find /dev -name uinput

**Comment by CJPilot** [comment]
I got it to see the "joystick" in X-Plane. Thank you so much @sthalik!
