### ISSUE TITLE
No video with debian testing

### ISSUE THREAD

**Issue by Attigliuzzo** [opentrack/opentrack#821]
The 2.3.10 version under win10 works perfectly. I've just compiled the latest unstable version in my debian testing box, fixed the uinput permission. But now i don't know which input i can choose, there isn't a freetrack plugin like in windows. 
The s2bot gives no video, i tested my Ps3 eye cam with V4L2 and i get a video.

**Comment by sthalik** [comment]
Which tracker are you using again?

**Comment by Attigliuzzo** [comment]
A cap with 3 IR leds.

**Comment by sthalik** [comment]
And which tracker do you have selected?

**Comment by sthalik** [comment]
Install some `libopencv-dev`, then `cmake .` in opentrack's build directory should pick up `OpenCV_DIR`. In any case make sure it does.

**Comment by sthalik** [comment]
Glad to hear it's all working now.

You can get it working for Wine games as well. The process is somewhat harder on multilib `amd64` installations but `winegcc` is the key.

sh
