### ISSUE TITLE
aruco build abi.h missing

### ISSUE THREAD

**Issue by DanielKinsman** [opentrack/opentrack#823]
The unstable branch seems to want [<aruco/abi.h>](https://github.com/opentrack/opentrack/blob/unstable/tracker-aruco/compile-test/abi.cpp#L1), but opentrack's aruco fork [doesn't have an abi.h](https://github.com/opentrack/aruco/tree/master/src). I'm probably just missing something, any tips?

**Comment by sthalik** [comment]
You were right all along, thanks for noticing it.

**Comment by DanielKinsman** [comment]
thanks, fixed so quickly!
