### ISSUE TITLE
Opentrack CSV data logging transform to image(vedio frames) position 

### ISSUE THREAD

**Issue by tjinjin95** [opentrack/opentrack#824]
I want to relate head movement data with image(vedio frames) position, I have head movement data per frame like this , how to find the position in image? or on spherical surface?
![position](https://user-images.githubusercontent.com/30750867/44645636-e1d49380-aa0a-11e8-99f7-69d6bf797696.png)
thanks

**Comment by tjinjin95** [comment]
my expression not clearly before, I want use coordinate(yaw , pitch, roll) to find the position in video fram,  I made a figure in follow, maybe their some error. the field of view will change with coordinate(yaw , pitch, roll), where yaw in range of [-180,180], pitch in range of [-90,90]. I want know the relation between coordinate(yaw , pitch, roll) with field of view.
![orien](https://user-images.githubusercontent.com/30750867/44705697-f2037600-aad1-11e8-8dbd-c8a25798da14.png)
thanks  @sthalik

**Comment by sthalik** [comment]
There will be rotation value differences if the physical FOV changes. The same odd behavior manifests when you move without rotating with regard to the camera plane.

As for changing the FOV setting without affecting the physical lenses, there shouldn't be any effect. The code is robust for vastly incorrect FOV settings.
