### ISSUE TITLE
Brightness control

### ISSUE THREAD

**Issue by Pluscrafter** [opentrack/opentrack#826]
I have a HD 5000 as Trackcam and the selected brightness will reset it automatically after a certain time. Is there any solution, that the brightness stay in the selected setting ?

**Comment by sthalik** [comment]
It's not opentrack's decision what happens to the brightness setting. You may want to set your camera driver to "UVC Video Class" if it's listed in Device Manager for that device.

**Comment by Pluscrafter** [comment]
Thanks that had helped.
