### ISSUE TITLE
mouse tracking not working for some games

### ISSUE THREAD

**Issue by MrNobodyX3** [opentrack/opentrack#828]
Games don't seem to react to Opentrack. It does show a output, but nothing actually "moves". Do I need to do something?

**Comment by MathijsG** [comment]
Which games did you use? And what Output protocol did you use? Please we need more info :).

**Comment by MrNobodyX3** [comment]
Any / all games I have like MC, Eco, Overwatch, R6

and I'm use the input of Steam VR and output of mouse emulation

**Comment by sthalik** [comment]
Are you running opentrack as administrator? Either run both the games and opentrack as administrator, or nothing at all.

Also, opentrack doesn't require admin privileges.

**Comment by MrNobodyX3** [comment]
Yes I've tried both, admin and not admin

**Comment by MathijsG** [comment]
And the games DID work earlier with this? Many games don't use the direct Mouse input. I needed it to change to direct in GTA V to work. But I rather play real supported games with this :).

**Comment by sthalik** [comment]
In theory it should work everywhere. Can you give an example of any game where it doesn't work so I can do further research?

**Comment by MathijsG** [comment]
In GTA5 I needed to explicitly enable something like: Mouse Input: Direct

Will look up the name of it. The mouse input mode that was default didn't work with Opentrack

**Comment by sthalik** [comment]
@MathijsG I understand, and have bought GTA5 a while ago.

**Comment by sthalik** [comment]
I added a legacy input mode. It works but drifts away from center constantly.
