### ISSUE TITLE
Access raw output over UDP

### ISSUE THREAD

**Issue by ctbrahmstedt** [opentrack/opentrack#829]
Is there a way to access the absolute coordinates/pose instead of relative over UDP? I'm using this for object tracking in Processing and the relative coordinate system is incredibly difficult to use in this case. Even just a tick box to output raw vs game data would be amazing. 

Thanks!

**Comment by sthalik** [comment]
You can create a profile with no filter and all mappings set to 0->180.

**Comment by ctbrahmstedt** [comment]
That works fine for roll, pitch, yaw, but my game data, specifically the translation of X, Y, Z is still offset from my raw data. That is, wherever my marker is on startup is considered 0,0,0 in the game data, but the raw data will show it's absolute coordinates relative to the camera. I am trying to access the latter.

**Comment by sthalik** [comment]
With "Center on startup" disabled it should output raw translation data. Is that not the case?

**Comment by ctbrahmstedt** [comment]
Ah, it was having to also disable "translation compensation." (using MacOS build 2.3-rc20p1)
Thanks for the help! This is incredible work.

**Comment by sthalik** [comment]
Glad it works for you!

**Comment by sthalik** [comment]
Only preprocessed data is transmitted over UDP. You'd have to disable relative translation, neck displacement, set mappings to 1:1, and disable center on startup in order to get the same output as raw data.

**Comment by RasmusEklund** [comment]
I have tried that, but it still doesn't match with the raw tracker data. I have just been testing using the aruco paper marker tracker for testing. 
![arucopaper](https://user-images.githubusercontent.com/11421431/53880741-1193d200-4012-11e9-8cb3-37a91f6bf85d.png)

Pitch, yaw and roll looks fine, but XYZ doesn't.

**Comment by ghdalsrl326** [comment]
I recommend set mappings to 1:1 in 'Mapping' -> check 'Asymmetric mapping below' by manual way.
