### ISSUE TITLE
Cant get opentrack to work with my smartphone

### ISSUE THREAD

**Issue by rodrigoxm49** [opentrack/opentrack#830]
The connection is fine, but it just don't work properly. Looks like Opentrack doesn't receive data from my phone the way it should, but it moves by itself. A example. I don't move my phone, but Opentrack show movements for every direction on it. If I move the phone, it keeps the same way.

It is a Zenfone 3 (Android 8). I think the smart is compatible with opentrack, since it have gyro, acc mag and orientation working fine on debug mode.

Things that I noticed with debug mode on on FreePIE:

+ When SEND RAW is ticked, ACC, GYRO, MAG and ORIENTATION registered movements perfectly, but this way there's no connection with OpenTrack on PC. Simply there's no movement registered even with FreePIE showing it there.

+ When I ticked off RAW DATA, letting only SEND ORIENTATION on, ACC, GYRO and MAG are gone and only ORIENTATION register movements. Now I can connect with OpenTrack, but happens what I say above in the first place.

**Comment by sthalik** [comment]
What happens if you remove any magnets (headphones, speakers) from the room?

**Comment by rodrigoxm49** [comment]
Thanks, but the problem was a old apk

**Comment by sthalik** [comment]
So it works now?

**Comment by rodrigoxm49** [comment]
Yes! It's working. Just need to use apk inside on opentrack instead using Google
