### ISSUE TITLE
Not detecting aruco paper?

### ISSUE THREAD

**Issue by Shawek** [opentrack/opentrack#832]
I've mounted my aruco paper onto my headset, and drawn my aruco paper perfectly (printer not working), but it wont detect/track my aruco paper at all. (Apart from once for a split second.) I feel the quality of my aruco paper that i drew is of high standards but it does not seem to be working. (Pics Included.)
I've tried the tracking 3-4 times with the lights on and off but it doesn't seem to work either way, no matter how many different starting positions ect i try.. Please help.. x.x

![pr1](https://user-images.githubusercontent.com/44080459/46849351-da424000-ce3a-11e8-8c26-73a0965eda00.png)
![pr2](https://user-images.githubusercontent.com/44080459/46849353-da424000-ce3a-11e8-8bf5-6a69becd3674.png)

Things to note:
I am wearing a white shirt, (dunno if this confuses the software or something?)
The light causes glare, (Duh)
The software seems to be tracking something else in the full picture, i cant tell what it could bt trying to track though

Important: The linked pictures are not the whole screen/area that is being tracked, just a bit of it.
Also i followed this guide " https://steamcommunity.com/sharedfiles/filedetails/?id=923596825 "
The one thing i changed is I'm using my phone as a camera instead, linked to my pc via an app called "iVCam"

**Comment by sthalik** [comment]
If you don't have a printer, visit the local copy/print shop and do few printouts. It's recommended that you use marker id "1". I tried to manually make a marker like that too with a reflective material for the white color. It didn't work either.

I don't think you can keep the level of precision necessary even if done on graph paper, black background and a ruler for cutting the tape right. Start with something done right (laser-printed) and maybe play with the material reflectivity later, if at all.
