### ISSUE TITLE
Windows Hello IR camera support

### ISSUE THREAD

**Issue by lrq3000** [opentrack/opentrack#835]
Dear developers,

Some computers like the HP Spectre x360 are now shipped with (near-)infrared cameras and support of the Windows Hello IR login.

Maybe it would be possible to add support of these cameras in OpenTrack (if the infrared is of enough quality)?

Here are some useful resources:
* https://www.reddit.com/r/Surface/comments/6gp4am/developer_has_someone_tried_accessing_the_ir/
* https://docs.microsoft.com/en-us/uwp/api/windows.devices.perception.perceptioninfraredframesource
* https://www.npmjs.com/search?q=keywords:PerceptionInfraredFrameSource

**Comment by sthalik** [comment]
If it's implemented then please send a pull request.
