### ISSUE TITLE
Haitre with Arduino Leo MPU 6050

### ISSUE THREAD

**Issue by Zulfiqarib** [opentrack/opentrack#836]
Hi,
 
 I am trying to use the Haitre Arduino , have already uploaded the MPU6050 sketch to the Arduino Leo and during test in the Arduino IDE it shows the Gyro + Accel is working fine.

But when i try it under Opentrack with the Input as Haitre Arduino and Output as Freetrack 2.0 , it does not do anything , under the log file it shows the com port is open and ready but i get 0 input.

If i set RTS / CTS ON in opentrack then i get an error "Couldn't set RTS"

Thought the Arduino Leo and the MPU could be an issue but it works with EDTracker.

Any help will be appreciated , let me know if more info is needed.

Rgds.

**Comment by sthalik** [comment]
Ask in #139, that's where Arduino users hang out. I'm closing this issue.

Unfortunately I'm unable to personally offer any assistance with the devices and connectors.
