### ISSUE TITLE
The version "opentrack-test-20181020_01" does not work Jaw, Pitch, Roll. 

### ISSUE THREAD

**Issue by olegiy** [opentrack/opentrack#837]
(((

**Comment by Len62** [comment]
@sthalik  Seeing the same issue as olegiy.

**Comment by sthalik** [comment]
Is that in-game or also on the user interface? Sorry, I'm barely available at the moment.

**Comment by olegiy** [comment]
user interface

**Comment by Len62** [comment]
Tried in game and no movement there either. x, y, and z movement is fine. You can see in the mapping window that there is no yaw, pitch, or roll movement.

**Comment by sthalik** [comment]
Can you see yesterday's build? Thanks.

**Comment by Len62** [comment]
Getting a virus threat warning: Win32/Unwaders.C!ml.  I've never before had a threat warning with any versions of OT.

**Comment by sthalik** [comment]
Which antivirus is it?

**Comment by Len62** [comment]
Windows Defender. Malwarebytes does not detect it.

**Comment by sthalik** [comment]
Virustotal shows clean for:

```
opentrack-test-20181102_01.7z
5f4e1902d9af4ce2119c3247aa4e0d23a114fddc44c7b24d84e0808bf1f7799a
25.68 MB
```

**Comment by Len62** [comment]
Ok. Probably just a Windows mistake.

**Comment by Len62** [comment]
Ok, deleted the extracted folder, re-extracted it again, set-up my short cut, ran fine w/no threat warning this time, strange, to say the least. Did a quick test, everything working as it should, both in OT and game.

**Comment by sthalik** [comment]
Thanks for checking it out! Let's wait a few days and see if there's anything still broken.

**Comment by Len62** [comment]
Ok. I'll use this version for the next couple of days and report if I find anything.
