### ISSUE TITLE
2.2-stable20141112 to 2.3.10

### ISSUE THREAD

**Issue by helmchenlord** [opentrack/opentrack#838]
Hello, 

I am using opentrack with edtracker, filter is Accela.
When moving to the newer version the deadzones are not working anymore.
Rotation deadband and translation are set to 2,300 in 2.2-stable20141112.

Using the slider for both deadzones in 2.3.10 doesn't work for me no matter the value I set.

Old config is:
[Accela]
exponent=4.25
rotation-alpha=60
rotation-deadband=2.3
second-order-alpha=100
third-order-alpha=180
translation-alpha=40
translation-deadband=2.3

[Curves-rx]
point-0-x=70.1485748291016
point-0-y=180
point-count=1

[Curves-rx_alt]
point-count=0

[Curves-ry]
point-0-x=23.1428565979004
point-0-y=90
point-count=1

[Curves-ry_alt]
point-0-x=15.4285717010498
point-0-y=90
point-count=1

[Curves-rz]
point-0-x=180
point-0-y=180
point-count=1

[Curves-rz_alt]
point-count=0

[Curves-tx]
point-count=1
point-0-x=99.5428571428571
point-0-y=100

[Curves-tx_alt]
point-count=0

[Curves-ty]
point-count=0

[Curves-ty_alt]
point-count=0

[Curves-tz]
point-count=0

[Curves-tz_alt]
point-count=0

[opentrack-ui]
compensate-translation=true
compensate-translation-disable-z-axis=false
ding=true
filter-dll=Accela Filter Mk4
key-alt-center=false
key-alt-toggle=false
key-ctrl-center=false
key-ctrl-toggle=false
key-index-center=28
key-index-toggle=43
key-shift-center=false
key-shift-toggle=false
pitch-alt-axis-sign=true
pitch-invert-axis=true
pitch-source-index=4
pitch-zero-pos=0
protocol-dll=FreeTrack 2.0
roll-alt-axis-sign=false
roll-invert-axis=true
roll-source-index=5
roll-zero-pos=0
tracker-dll=Joystick
tracker2-dll=
x-alt-axis-sign=false
x-invert-axis=false
x-source-index=0
x-zero-pos=0
y-alt-axis-sign=false
y-invert-axis=false
y-source-index=1
y-zero-pos=0
yaw-alt-axis-sign=false
yaw-invert-axis=true
yaw-source-index=3
yaw-zero-pos=0
z-alt-axis-sign=false
z-invert-axis=false
z-source-index=2
z-zero-pos=0

[proto-freetrack]
ezca-mode=false
use-memory-hacks=false
used-interfaces=0

[tracker-joystick]
joy-id=EDTracker EDTracker2

Thank you

**Comment by sthalik** [comment]
Remove the "Accela" section from the .ini and set it again.
