### ISSUE TITLE
FSX simconnect sdk error

### ISSUE THREAD

**Issue by thewoolysheep08** [opentrack/opentrack#840]
I have installed the latest version of simconnect and i keep getting and error like this:
![yt](https://user-images.githubusercontent.com/44717734/47947578-82978000-df73-11e8-83b9-5b44f9e713bc.PNG)
What can i do to fix this?

**Comment by sthalik** [comment]
https://github.com/opentrack/opentrack/issues/804#issuecomment-399209519
