### ISSUE TITLE
Still cant get simconnect to work.

### ISSUE THREAD

**Issue by thewoolysheep08** [opentrack/opentrack#841]
I still cant get simconnect to work, im confused with the instructions and i wish you wouldnt close my issue without asking if i could get it working...

**Comment by sthalik** [comment]
You can respond in the original issue. I can reopen it. Just copy the file and name it like the original but without "lib" up front. Don't change the extension.

**Comment by sthalik** [comment]
Go to the "modules" directory where you installed opentrack. Don't rename, __copy__ it.

Copy `libopentrack-proto-simconnect.dll` to `opentrack-proto-simconnect.dll`. Notice the lack of the "lib" prefix on the copied file.

**Comment by thewoolysheep08** [comment]
rename libopentrack to just opentrack?

**Comment by sthalik** [comment]
DO NOT RENAME BUT COPY! 👍 

Do that for that simconnect dll file. Leave rest as-is.

**Comment by thewoolysheep08** [comment]
right, i got it! thanks so much, i apologize  for how long it took when it comes to stuff like this I'm a complete noob
