### ISSUE TITLE
Need a simple freepie scripts for gyro the mouse on pc

### ISSUE THREAD

**Issue by Tonymazzz** [opentrack/opentrack#844]
Guys i need to emulate mouse with the gyro of my phone for play GTA V, tried lots of config and no one works straight, its like all of them finish on curves... Help me please.

**Comment by sthalik** [comment]
That's outside the scope of this project.

**Comment by Tonymazzz** [comment]
I only need to know why the oficial scripts for freepie finish always doing a curves on my screen...

**Comment by sthalik** [comment]
There ought to be a FAQ on this problem.

Next time please don't post in unrelated issues.

- See whether your phone model has all of gyro, mag, and acc. You can use the CPU-Z app and uninstall it afterward.
- When mounting on headphones, position as far away from each magnet as possible. Try different configurations.
- The rotation is received through the system's API for position. The only room for improvement is phone hardware's sensor precision.
- There's a working freepie app as `.apk` inside opentrack's `contrib` directory.

**Comment by sthalik** [comment]
There ought to be a FAQ on this problem.

Next time please don't post in unrelated issues.

- See whether your phone model has all of gyro, mag, and acc. You can use the CPU-Z app and uninstall it afterward.
- When mounting on headphones, position as far away from each magnet as possible. Try different configurations.
- The rotation is received through the system's API for position. The only room for improvement is phone hardware's sensor precision.
- There's a working freepie app as `.apk` inside opentrack's `contrib` directory.

**Comment by sthalik** [comment]
And what's that?
