### ISSUE TITLE
Are you this person?

### ISSUE THREAD

**Issue by Forsaken-Player** [opentrack/opentrack#846]
![image](https://user-images.githubusercontent.com/13246441/48877925-2b533580-ede4-11e8-9127-699a299bf1ac.png)

**Comment by sthalik** [comment]
No. Why?

**Comment by Forsaken-Player** [comment]
Because it's selling opentrack in Steam with a different application name.

**Comment by sthalik** [comment]
It's allowed as long as they keep copyright notices.

**Comment by Forsaken-Player** [comment]
Wow. Ok sorry for the misunderstanding.
