### ISSUE TITLE
[Suggestion]Use TrackIR output as Opentrack Input

### ISSUE THREAD

**Issue by Maetharin** [opentrack/opentrack#848]
Hi there, I´ve been using TrackIR for the last few months, and I´m really happy with the consistency it provides me when compared to my earlier EDTracker/Aruco combo.

The one thing I really miss from Opentrack was the neck displacement feature, which TrackIRs TrueView is completely missing.

Would it be possible to use TrackIR output as an Input option in Opentrack? This way I could use Trueview with your neck displacement, by putting TrackIR acceleration of the xyz axes on 1:1 and increasing it again in opentrack.

**Comment by sthalik** [comment]
These two data streams would conflict when using the freetrack protocol.

**Comment by Maetharin** [comment]
still thx for answering
