### ISSUE TITLE
OpenTrack "Profile" shortcut key 

### ISSUE THREAD

**Issue by mbr2xgd** [opentrack/opentrack#849]
Hi. 

Is possible to create a shortcut key for "profile". I have two Combat Simulation Games. 
I always need to change my profile option. It's hard to alternate between Fullscreen mode
to Desktop mode. Is possible to create a shortcut key to alternate within profiles?

![opentrack_switch_profile](https://user-images.githubusercontent.com/10035783/49324723-e6817a00-f51a-11e8-9c19-ccca0d05534a.jpg)

**Comment by sthalik** [comment]
Hey,

You may find "game detection" in the options menu useful.

For now there's no such functionality unfortunately. It's planned.

**Comment by sthalik** [comment]
There are multiple requests to implement this. Please discuss this in #609.
