### ISSUE TITLE
Real Linux support?

### ISSUE THREAD

**Issue by atoms118** [opentrack/opentrack#850]
I know this probably isn't the best place to ask but I'm doing it anyways. By "supports Linux", do you mean it the Windows version runs in WINE, or is there actual native Linux support.

**Comment by sthalik** [comment]
There's "real" input in form of a virtual joystick device, and a working X-Plane plugin. I'd like to support more protocols on Linux but there are none. The virtual joystick protocol is known to work with Euro Truck Simulator at least.
