### ISSUE TITLE
Wiimote LED

### ISSUE THREAD

**Issue by DJPlaya** [opentrack/opentrack#851]
Its pretty simple, when the Wiimote is connected to Opentrack, none of the Player Leds light up.
This can get pretty confusing since you never know if the Wiimote is active or not.

**Comment by sthalik** [comment]
@cpuwolf is the only one that can fix it, in case he's still active.

**Comment by sthalik** [comment]
I also believe that there are multiple images signifying the state Wii pairing is in.

**Comment by sthalik** [comment]
I think we should reject this feature request then.
