### ISSUE TITLE
don't move mouse on center

### ISSUE THREAD

**Issue by uborapnik** [opentrack/opentrack#852]
Sorry, I'm not sure if solution exist for my problem but I tried nearly everything...

I would like my mouse cursor to stay in place where I left it in-between toggling.
As it is now, if toggle OFF and move head, the mouse will jump and start moving from the point where my head is when I toggle ON.

I hope I explained issue clearly and you know what I mean. Am I missing something, is this possible or ?

**Comment by sthalik** [comment]
Hey,

This makes sense. I'm introducing an option to disable the center behavior.

**Comment by uborapnik** [comment]
Thats really good to hear! I hope it's not too hard to implement and happy holidays!

**Comment by sthalik** [comment]
Bind the same button the centering and toggling. It should be enough.

**Comment by uborapnik** [comment]
Tried that. Does not work.

**Comment by sthalik** [comment]
I think centering with mouse output shouldn't result in any movement. Do you agree?

**Comment by sthalik** [comment]
What if you used "center" instead of "toggle" completely? The center button functions while held and only stops working when it's depressed.

**Comment by sthalik** [comment]
I need the game title where this is happening.

**Comment by uborapnik** [comment]
It's already like this in windows. I wanna use it with gta:san andreas (multiplayer) though.

**Comment by sthalik** [comment]
See the legacy mouse control mode in the latest snapshot at http://opentrack.misaki.pl. It's badly drifting though.

**Comment by uborapnik** [comment]
Still the same issue, I recorded a video to give you better idea: https://youtu.be/oMphloijbWE

Let me know if there's anything else I can do to help.

**Comment by uborapnik** [comment]
any updates ?

**Comment by sthalik** [comment]
Is your ingame resolution at least 1920x1080? There's a bad interaction between low resolution and mouse speed.

**Comment by uborapnik** [comment]
2560x1440, same as windows

**Comment by sthalik** [comment]
Please see if centering works in today's build. There was a bug with the cursor going out of bounds vertically.
