### ISSUE TITLE
Suggestion: Track by color!

### ISSUE THREAD

**Issue by Shadoware** [opentrack/opentrack#853]
I dont use github frequently so Im novice here.

The software pointtracker works good but is generally hard to get a good hardware set to track infra red with quality, without interference and other camera/filter problems.

I would be a lot easier if its possible to use a clip with normal red led's for example and track it just by color like some kind of chromakey effect. This way anyone could use the ps3-cam without any modifications.

Is there a way to do it?

**Comment by sthalik** [comment]
Yes, it's right there in PT tracker options.

**Comment by MathijsG** [comment]
@Shadoware 

See:

![image](https://user-images.githubusercontent.com/529552/51438889-683b8b80-1cb2-11e9-962c-b617def9509b.png)

Did it work out for you that way?
