### ISSUE TITLE
[FEATURE] keybinding to profiles

### ISSUE THREAD

**Issue by VadimVolynkin** [opentrack/opentrack#859]
I ask you to add in the new versions of the program profiles of curved lines and the possibility of switching them with a hot key. I play Arma 3. I think it will be convenient to use different profiles for infantry and for flying.

**Comment by sthalik** [comment]
Definitely. There are a couple of issues here, though.

- We're overloaded with options as it is right now.
- The software isn't prepared for switching *trackers* while tracking is enabled. Even if there's another tracker/filter/output combo enabled for the second profile, it has to be overwritten when switching while tracking. It's also easier for the programmer if the filter or output can't be changed (but can have its options changed, of course).
- You need to keep these profiles in sync, e.g. when switching camera resolution or model.

I'm closing this duplicate issue in favor of #609, which has been accepted a long time ago. Please discuss this in #609.
