### ISSUE TITLE
vjoystick not been detected

### ISSUE THREAD

**Issue by yuk27** [opentrack/opentrack#860]
I have tried installing vjoystick multiple times, but even if vjoystick works correclty and I can use it by the vjoy feeder. OpenTrack doesn't recognize it. 

![image](https://user-images.githubusercontent.com/12703285/51504765-95159e80-1d97-11e9-8343-9514f17b6a4f.png)

(I'm on windows 8.1 BTW)

It's there something I'm doing wrong?

**Comment by sthalik** [comment]
Add another vjoystick, so that you have two in total. Does this work for you?

**Comment by sthalik** [comment]
Fixed. See wiki for experimental builds.
