### ISSUE TITLE
How are you guys building your release?

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#864]
Say opentrack 2.3.11 BETA2, was it build with cygwin or VS, and does it matter?
Will it be able to load a tracker I built using VS for instance?

**Comment by sthalik** [comment]
Closing in favor of #861. Please don't open many issues relating to a single question.

**Comment by sthalik** [comment]
#861 should answer this question as well.

**Comment by Slion** [comment]
Sorry about that, I thought this one was a bit more specific. I'm happy to have a single issue where we can discuss all that though.
