### ISSUE TITLE
Kinect V2 SDK EULA

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#868]
Microsoft Kinect for Windows v2 Software Development Kit (SDK) 

These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. It also applies to any Microsoft
·	updates,
·	supplements,
·	documentation, and
·	support services
for this software, unless other terms accompany those items. If so, those terms apply.
The software is licensed, not sold. By downloading, installing, accessing, or using the software, you accept all terms in this agreement. If you do not accept them, do not download, install, access, or use the software. “You” or “you” means the individual who downloads, installs, accesses, or uses the software (and, if you represent a legal entity, it also means that entity, and you represent and warrant that you are authorized to enter into this agreement for that entity). 
If you comply with these license terms, you have the rights below.
1. INSTALLATION AND USE RIGHTS.
a.	Installation and Use. You may (i) install and use any number of copies of the software (only when installed using the accompanying software installer package) on your computer to design, develop, and test your programs that run specifically on a Microsoft Windows operating system, and that are intended for use solely in connection with the Microsoft Kinect for Windows v2 sensor (“Kinect v2 Sensor”), and its associated drivers and runtime software, and no other sensor unless such sensor is supported by Microsoft (collectively, the “Kinect V2 Applications”), and (ii) distribute your Kinect v2 Applications, subject to the terms in this agreement.
b.	 Telemetry Data Collection. When in use by you, the software will provide Microsoft with telemetry data (e.g. operating system, number of processors, graphic chipset, memory, device type, locale, time) regarding your installation and use. The data will not be used to identify specific individuals.   Microsoft will use the Telemetry Data for product and service improvements.    
c.	Included Microsoft Programs.  The software includes other Microsoft programs.  The license terms with those programs apply to your use of them.
d.	No High Risk Use.  WARNING: The Kinect v2 Sensor and the software are not fault-tolerant. The Kinect v2 Sensor and the software are not designed or intended for use with any program where failure or fault of any kind of the Kinect v2 Sensor or software could lead to death or serious bodily injury of any person, or to severe physical or environmental damage (“High Risk Use”). You are not licensed to, and you agree not to, use, distribute or sublicense the use of the Kinect v2 Sensor and/or software in, or in conjunction with, High Risk Use.  High Risk Use is STRICTLY PROHIBITED.  High Risk Use includes, for example, the following: aircraft navigation and control of other modes of human mass transportation, nuclear or chemical facilities. 
2. ADDITIONAL LICENSING REQUIREMENTS AND/OR USE RIGHTS 
a.	 Distributable Code.  The software contains code that you are permitted to distribute solely in Kinect v2 Applications if you comply with the terms below.  
i.	Right to Use and Distribute.  The code and text files listed below are “Distributable Code.”
·	REDIST.TXT Files. You may copy and distribute the object code form of code listed in REDIST.TXT files as part of your Kinect v2 Application.
·	Sample Code.  You may modify, copy and distribute the source and object code form of code in the Samples subdirectory as part of your Kinect v2 Application.
·	Third Party Distribution. You may permit distributors of your Kinect v2 Applications to copy and distribute the Distributable Code as part of those Kinect v2 Applications.
⦁	Third Party Programs.  This software may contain certain third-party programs. You agree that your use of them is governed by the license terms provided with those programs.

ii.  Distribution Requirements. For any Distributable Code you distribute, you must: 
§	add significant primary functionality to it in your Kinect v2 Applications;
§	distribute Distributable Code included in a setup program only as part of that setup program without modification;
⦁	clearly state in your Kinect V2 Application (as well as require your licensees to do so) a privacy statement regarding the collection and use of customer data as well as the following statement regarding Microsoft’s collection and use of customer data:  “Note:  When using the _________________(insert name of Your Kinect v2 Application) with a Kinect for Windows v2 Sensor, Microsoft will collect telemetry data (e.g. operating system, number of processors, graphic chipset, memory, device type, locale, time) in order to improve Microsoft products and services.  The data will not be used to identify specific individuals.”    
§	clearly state in marketing materials, documentation and other materials related to the Kinect v2 Application (e.g. on the webpages on which the Kinect V2 Application is described or from which the Kinect V2 Application may be downloaded or otherwise obtained), that it is intended for use only with the Kinect V2 Sensor;
§	require licensees, distributors and external end users to agree to license terms that are as protective of Microsoft’s rights and interests in the Distributable Code as stated in this agreement; and 
§	display your valid copyright notice on your Kinect v2 Applications.
iii.	Distribution Restrictions.  You may not:
·	alter any copyright, trademark or patent notice in the Distributable Code;
⦁	License the Microsoft Distributable Code in a manner inconsistent with the terms of this License. 
·	use Microsoft’s trademarks, including but not limited to Microsoft, Kinect and Windows, in your Kinect v2 Applications’ names or in a way that suggests your Kinect for v2 Applications come from or are endorsed by Microsoft;
·	distribute Distributable Code to run on a platform other than a Microsoft Windows operating system;
·	include Distributable Code in malicious, obscene, deceptive or unlawful programs;
·	include Distributable Code for any programs designed or intended for High Risk Use; or
·	modify or distribute the source code of any Distributable Code so that any part of it becomes subject to an Excluded License. An Excluded License is one that requires, as a condition of use, modification or distribution, that
·	the code be disclosed or distributed in source code form; or
·	others have the right to modify it.
3. SCOPE OF LICENSE. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. Unless applicable law gives you more rights despite this limitation, you may use the software only as expressly permitted in this agreement. In doing so, you must comply with any technical limitations in the software that only allow you to use it in certain ways. You may not:
·	access or use, or attempt to access or use, features of the Kinect v2 Sensor that are not exposed or enabled by the software;
·	distribute Kinect v2 Applications for use with any sensor other than the Kinect v2 Sensor or its associated drivers and runtime software; 
·	use the software or any Kinect v2 Applications in any High Risk Use; 
·	work around any technical limitations in the software;
·	reverse engineer, decompile, or disassemble any part of the software not provided in source code form, except and only to the extent that applicable law expressly permits, despite this limitation;
·	publish the software for others to copy;
·	rent, lease, or lend the software;
·	transfer the software or this agreement to any third party; or
·	use the software for commercial software hosting services.
4. REGULATORY COMPLIANCE.  You agree that your development, marketing, sales, and distribution of Kinect v2 Applications shall be in compliance with all applicable legal requirements, including compliance with the medical device regulatory requirements of the U.S. Federal Food, Drug, and Cosmetic Act and any associated requirements, or similar laws, regulations, or policies in other countries or territories.  To the extent required by law, you are solely responsible for obtaining or filing any approval, clearance, registration, permit, or other regulatory authorization and shall comply with the requirements of such authorization.

5. ACKNOWLEDGEMENT AND WAIVER.  You acknowledge the software may allow you to control the Kinect v2 Sensor, which are mechanical hardware devices that include motors to move the device, a fan to cool it, and other mechanical components. Depending on how you elect to use the software, you could harm persons or damage or destroy the Kinect v2 Sensor, products incorporating the Kinect v2 Sensor, or other property. In using the software, you must take steps to design and test your Kinect v2 Applications to ensure that your applications do not present unreasonable risks of personal injury or death, property damage, or other losses. Kinect v2 Sensors utilize complex hardware and software technology that may not always function as intended. You must design your application so that any failure of a Kinect v2 Sensor and/or the software does not cause personal injury or death, property damage, or other losses. If you choose to use the software, you assume all risk that your use of the Kinect v2 Sensors and/or the software causes any harm or loss, including to the end users of your Kinect v2 Applications, and you agree to waive all claims against Microsoft and its affiliates related to such use (including but not limited to any claim that a Kinect v2 Sensor or the software is defective) and to hold Microsoft and its affiliates harmless from such claims. 
6. INDEMNIFICATION.  You agree to indemnify, defend, and hold harmless Microsoft and its affiliates from any claims, including attorneys’ fees, related to the distribution or use of your Kinect v2 Applications.
7. BACKUP COPY. You may make one backup copy of the software. You may use it only to reinstall the software. 
8. DOCUMENTATION. Any person who has valid access to your computer or internal network may copy and use the documentation for your internal, reference purposes.  
9. SUPPORT SERVICES. Because this software is “as is,” we may not provide support services for it.
10. EXPORT RESTRICTIONS. The software is subject to United States export laws and regulations. You must comply with all domestic and international export laws and regulations that apply to the software. These laws include restrictions on destinations, end users, and end use. For additional information, see www.microsoft.com/exporting.
11. ENTIRE AGREEMENT. This agreement, and the terms for supplements, updates, Internet-based services and support services that you use, are the entire agreement for the software and support services.
12. APPLICABLE LAW.
a. United States. If you acquired the software in the United States, Washington state law governs the interpretation of this agreement and applies to claims for breach of it, regardless of conflict of laws principles. The laws of the state where you live govern all other claims, including claims under state consumer protection laws, unfair competition laws, and in tort.
b. Outside the United States. If you acquired the software in any other country, the laws of that country apply.
13. LEGAL EFFECT. This agreement describes certain legal rights. You may have other rights under the laws of your state, province or country. This agreement does not change your rights under the laws of your state, province or country if the laws of your state, province or country do not permit it to do so.
14. DISCLAIMER OF WARRANTY. The software is licensed “as-is.” You bear all risk of using it. Microsoft gives no express warranties, guarantees or conditions. You may have additional consumer rights under your local laws that this agreement cannot change. To the extent permitted under your local laws, Microsoft excludes the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
15. LIMITATION ON AND EXCLUSION OF REMEDIES AND DAMAGES. You can recover from Microsoft and its suppliers only direct damages up to U.S. $5.00. You cannot recover any other damages, including consequential, lost profits, special, indirect or incidental damages.
This limitation applies to
a. anything related to the software, services, content (including code) on third party Internet sites, or third party programs; and
b. claims for breach of contract; breach of warranty, guarantee, or condition; strict liability, negligence, or other tort, to the extent permitted by applicable law.
It also applies even if Microsoft knew or should have known about the possibility of the damages. The above limitation or exclusion may not apply to you because your state, province or country may not allow the exclusion or limitation of incidental, consequential, or other damages.

**Comment by sthalik** [comment]
This is great news.
