### ISSUE TITLE
Kinect video preview is broken

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#874]
Possibly since the dependency on OpenCV was removed.

**Comment by Slion** [comment]
The issue is with the code in `video_widget::paintEvent` which keeps deleting the bitmap that was provided replacing it with one filled with grey. I'm not sure what's the proper fix.

**Comment by sthalik** [comment]
It's unfortunate that the preview isn't of the right size to begin with. With opencv it's `malloc`-free and efficient, but `QImage::scaled` allocates.

**Comment by sthalik** [comment]
@Slion please add the copyright statement in the header. It can't go into a binary release until you do.

**Comment by sthalik** [comment]
I removed this entire block since `texture` can be guaranteed consistent at this point.

**Comment by Slion** [comment]
> It's unfortunate that the preview isn't of the right size to begin with. With opencv it's malloc-free and efficient, but QImage::scaled allocates.

I agree, idealy our render loop should be free of allocations too. Though I'm not sure why a larger texture could not be scaled in smaller one for rendering without allocation, surely Qt can do that one way or another.
