### ISSUE TITLE
Camera jumps back to starting Position

### ISSUE THREAD

**Issue by Jannik03** [opentrack/opentrack#877]
Ingame the camera constantly jumps to starting position and back (like this: https://youtu.be/59p90krHJzw) but in the preview its perfectly fine. I used an Oculus Rift as input, freetrack 2.0 enhanced only TrackIr output and default Accela filter. Everything else is on default.

**Comment by Jannik03** [comment]
Another program caused the issue so no bug from opentrack just two programs that dont like each other.

**Comment by sthalik** [comment]
Thanks for reporting back.
