### ISSUE TITLE
Opentrack software won't open

### ISSUE THREAD

**Issue by spicyborland** [opentrack/opentrack#878]
I'm totally unable to start the opentrack software. I've tried installing/running it as admin, adding exceptions to my security, etc but when I double click on the software it does nothing, although the program does appear in my task manager. I'm on win 10 64bit. Any ideas?

**Comment by sthalik** [comment]
Make sure you're not using GIGABYTE OC GURU or Moonlight software. They're known to interfere with all running processes, and affect opentrack in a wrong way.

I have more ways to diagnose this with other tools but let's try the most common issue first.

**Comment by spicyborland** [comment]
hey there, just fixed it - was a conflict with an old version of some magnification software that another user had installed. Thanks though
