### ISSUE TITLE
Opentrack stopped working

### ISSUE THREAD

**Issue by famellad** [opentrack/opentrack#879]
OS: `Windows 10 Pro (v. 1809)`
Versions affected: `2.3.10, 2.3.11 beta 1, 2.3.11 beta 2`

I looked through the open and closed issues and couldn't find anything similar (and reasonably recent), if I missed some archaic old thread that happens to be this very problem, I apologise in advance :(

**Problem description**
Tonight I turned on my computer and Opentrack wasn't communicating with my games anymore, prior to restarting it worked flawlessly on both Euro Truck Simulator 2 and Elite: Dangerous, yet now it doesn't work on neither.

**How to reproduce**
I honestly have no idea how to reproduce this problem, the one thing I remember doing differently last time was saving my profile because I wanted to try different values on the filter. I was using 2.3.11 beta 1 when this problem first appeared, I have since tried other versions (including 2.3.10, which I also had working some months ago)

**Things I've tried**
- Running as administrator
- Rebooting
- Uninstalling and reinstalling
- Uninstalling, deleting references from registry and reinstalling
- Uninstalling, deleting references from registry, rebooting and reinstalling

I've tried these things with all three versions mentioned above.

**Additional info**
The tracker seems to be working fine, it seems to be just the output that's failing.
On 2.3.11 it says "Unknown Game" in the title bar at all times, even when a supported game is running.

Feel free to ask for any further information regarding my setup, right now I'm gonna go catch some sleep, and many thanks in advance!

**Comment by Len62** [comment]
What are you using for your output settings?

**Comment by famellad** [comment]
Freetrack 2.0 enhanced, with TrackIR hidden

**Comment by Len62** [comment]
Try enabling both.

**Comment by famellad** [comment]
Doesn't work 😢

**Comment by famellad** [comment]
Okay I got it to work by downloading someone else's profile off the internet, but I can't, for the life of me, figure out what's different on this one

**Comment by sthalik** [comment]
Send it as attachment here, please.

**Comment by Len62** [comment]
@famellad Glad you got it sorted out. Strange issue, make sure you send the faulty ini as sthalik requested.

**Comment by lukiluk100** [comment]
Sorry for digging up the topic, but i have the same problem. I see "Unknown Game" and nothing else.
Can anyone give me Opentrack profile?

**Comment by cromsan** [comment]
Resuelto el anterior problema al desistalar e instalar, 
Nuevo problema: el Opentrack ya no se comunica  con mi juego Xplane 11.
He desistalado opentrack y vuelto a instalar la versión 2.3.10, pero  el problema continua. Uso el freetrack 2.0.
 No sé cómo mandarles el ini?

**Comment by cromsan** [comment]
Les mando el log. Si necesitan algo más, pidanmelo.
[Log.txt](https://github.com/opentrack/opentrack/files/3609825/Log.txt)

**Comment by sthalik** [comment]
That file's not an opentrack profile. Please use English exclusively.

**Comment by cromsan** [comment]
Sorry; where is the opentrack profile so I can send.

**Comment by Len62** [comment]
On Windows 10 it's in the documents/opentrack folder.

**Comment by cromsan** [comment]
I send what I found in documents/ opentrack, on file type ZIP (It was a file type RAR)



[opentrack-2.3.zip](https://github.com/opentrack/opentrack/files/3613209/opentrack-2.3.zip)

**Comment by cromsan** [comment]
Enviado desde Correo para Windows 10

De: Len62
Enviado: sábado, 14 de septiembre de 2019 22:31
Para: opentrack/opentrack
CC: cromsan; Comment
Asunto: Re: [opentrack/opentrack] Opentrack stopped working (#879)

On Windows 10 it's in the documents/opentrack folder.

**Comment by Len62** [comment]
Does OT work ok with some games but not others, or does it just not start due to the startup error? Is OT not finding the camera? If it does not start at all try deleting all of the ini files except the default ini.

**Comment by cromsan** [comment]
I only play xplane 11. Opentrack do not open now. I have put opentrack on disk D. ¿where is the ini files, I do not find them?

 

De: Len62 <notifications@github.com> 
Enviado el: martes, 17 de septiembre de 2019 0:41
Para: opentrack/opentrack <opentrack@noreply.github.com>
CC: cromsan <c.romerosanzdemadrid@gmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [opentrack/opentrack] Opentrack stopped working (#879)

 

Does OT work ok with some games but not others, or does it just not start due to the startup error? Is OT not finding the camera? If it does not start at all try deleting all of the ini files except the default ini.

**Comment by Len62** [comment]
The ini files are located in the documents/opentrack folder. What is the exact error message you get when you run OT? What drive do you have Windows installed on?

**Comment by cromsan** [comment]
In the opentrack, doc, I have: 3rdparty-notices
                                                contrib
                                                settings
                                                README.md
I do not get any error message, because now OT does not open.
I do not understand "what drive do you have Windows intalled". I have not installed any driver.

**Comment by Len62** [comment]
They are not in opentrack/doc folder. See this pic: 
![OT ini file location](https://user-images.githubusercontent.com/10486813/65066836-2c48eb00-d953-11e9-92ad-902df40c73ba.jpg)

Next, are you using windows 10 operating system, or any other OS, what hard drive is it installed on?

**Comment by cromsan** [comment]
![image](https://user-images.githubusercontent.com/36861973/65068323-be1f1b00-d988-11e9-939e-bcf61f7bf074.png)

**Comment by cromsan** [comment]
![image](https://user-images.githubusercontent.com/36861973/65112692-da4ea680-d9e0-11e9-926a-fb65930a8d59.png)
![image](https://user-images.githubusercontent.com/36861973/65112694-dae73d00-d9e0-11e9-960d-494766da1207.png)
![image](https://user-images.githubusercontent.com/36861973/65112696-dae73d00-d9e0-11e9-8ccc-4b6ac5c8ee5e.png)
![image](https://user-images.githubusercontent.com/36861973/65112697-dae73d00-d9e0-11e9-9b19-48be35d2b47d.png)
![image](https://user-images.githubusercontent.com/36861973/65112698-db7fd380-d9e0-11e9-8c7f-d1e8739d9be0.png)
![image](https://user-images.githubusercontent.com/36861973/65112700-db7fd380-d9e0-11e9-9e35-154267c92a15.png)
![image](https://user-images.githubusercontent.com/36861973/65112701-db7fd380-d9e0-11e9-9e50-400655f12826.png)
![image](https://user-images.githubusercontent.com/36861973/65112702-db7fd380-d9e0-11e9-8b7a-8c4f6a43e386.png)
![image](https://user-images.githubusercontent.com/36861973/65112704-dc186a00-d9e0-11e9-9d59-3899c4fb1114.png)
![image](https://user-images.githubusercontent.com/36861973/65112706-dc186a00-d9e0-11e9-8e95-117ba8194233.png)
![image](https://user-images.githubusercontent.com/36861973/65112707-dc186a00-d9e0-11e9-8ac2-e35d275184c1.png)
![image](https://user-images.githubusercontent.com/36861973/65112708-dcb10080-d9e0-11e9-93d6-df05f58fee75.png)
![image](https://user-images.githubusercontent.com/36861973/65112709-dcb10080-d9e0-11e9-90c5-02ad6b9a56cc.png)

**Comment by cromsan** [comment]
Sorry for making the same 11 times.

**Comment by cromsan** [comment]
I have to put this files of opentrack 2.3.10 into the opentrack on disk D I send before?
![image](https://user-images.githubusercontent.com/36861973/65115128-cb1f2700-d9e7-11e9-99fc-1c76824aaf28.png)

**Comment by Len62** [comment]
At this point I think it would be best to just delete everything you have installed for OT. Then I would make sure that your camera is working properly. Once you've done that I would re-install OT, but install it on your C: drive. Once you have done that see if OT will at least run without crashing. What type of tracking device are you using?

**Comment by cromsan** [comment]
Thank you, Len62. I will do what you say when I want to come back to opentrack.  For the moment, i am going to rest of opentrack.

**Comment by Len62** [comment]
Ok. You can probably close this thread then.

**Comment by cromsan** [comment]
Yes, I close this thread.

**Comment by pilpo** [comment]
> 
> 
> Once you've done that I would re-install OT, but install it on your C: drive (Disco local (C:)). 

That did the trick for me! Thanks!
