### ISSUE TITLE
Receiving data via UDP in Max/Msp

### ISSUE THREAD

**Issue by RasmusEklund** [opentrack/opentrack#881]
Hi,

I have been able to receive tracking data via UDP in Max/Msp from Opentrack. However, I am not sure how to interpret the data I am receiving. I.e. what does the yaw, pitch and roll and xyz represent for each message I am receiving? 

![udpreceive](https://user-images.githubusercontent.com/11421431/53412838-c272ef00-39ca-11e9-982e-3269f1c0d6d2.png)

**Comment by RasmusEklund** [comment]
I figured out after some indepth testing and research. I will upload a Max patch here that receive the UDP messages from Opentrack and converts them to xyz and pitch yaw and roll. In case others have the same problem and want a solution :) 
[OrientationExtractor.zip](https://github.com/opentrack/opentrack/files/2930657/OrientationExtractor.zip)

**Comment by sthalik** [comment]
> I have been able to receive tracking data via UDP in Max/Msp from Opentrack. However, I am not sure how to interpret the data I am receiving.

These are yaw, pitch, roll, x, y, and z as double-precision floats. The floats are always transmitted little-endian so on embedded arches you may have to flip the bytes around. Rotation in degrees, position change in centimeters.

**Comment by RasmusEklund** [comment]
I didn't flip the bytes around to begin with, so that's why it didn't make sense in the beginning. It works great now. Thanks!
