### ISSUE TITLE
X-plane plugin links provided in #202 are not available anymore.

### ISSUE THREAD

**Issue by colmoschin94** [opentrack/opentrack#906]
Hi, 
after failing in compiling the latest release of opentrack in Ubuntu 18.04 I saw that in the issue #202 a link to the compiled XPlane plugin was provided, however the link is not alive anymore.
Could you please upload it again?

Thanks.

**Comment by sthalik** [comment]
I agree about the Wine multilib setup. It could be easier. Compile Wine on your own since both Ubuntu and WineHQ packages are missing essentials for 32-bit `winegcc`.
