### ISSUE TITLE
idea: mapping in full coordinate system

### ISSUE THREAD

**Issue by DukeNewman** [opentrack/opentrack#909]
Hi, me again.

another idea regarding the mapping:

All mapping is done in only one or two quadrants of the coordinate system. And for the second option (asymmetric mapping) it means that the mapping can be done in the first and third quadrant. Therefore pos. input equals pos. output and vice versa.

My suggestion is to replace the two separated partial coordinate systems with one full system (all four quadrants). -- You may ask why ... here is one example:

I'm using an head tracking system with 3 axis rotation only. To compensate the lack of translation I assign the input of Pitch and Roll also to x, y and z (pseudo 6dof). And for some situations I would like to map pitching forward AND backward to y up. Currently one can only map pitching forth and back to y up and down.

**Comment by sthalik** [comment]
No, people have enough trouble understanding mappings as it is.
