### ISSUE TITLE
Issue when going from positive to negative 180 yaw

### ISSUE THREAD

**Issue by UnknownEvil** [opentrack/opentrack#912]
Instead taking the quickest path from 180 to -180 (which is not moving) it makes a full rotation. Really unpleasant

**Comment by sthalik** [comment]
What output is it?

**Comment by sthalik** [comment]
I'm not sure if the problem is located in the filter. Can you please see if disabling the filter fixes the issue? I'd know which component has the issue at least.

**Comment by UnknownEvil** [comment]
Accela causes the full rotation. No filter causes the yaw to lock to +/-180 once I pass +/-180, respectively. Kalman seems to almost work but it appears to face the opposite direction for a few frames before returning to the correct direction. EWMA does something like the no filter and the Kalman combined.

**Comment by sthalik** [comment]
Let me get this clear, does disabling filtering result in proper behavior?

**Comment by UnknownEvil** [comment]
No. 

> No filter causes the yaw to lock to +/-180 once I pass +/-180, respectively. 

With the filter disabled if I rotate my phone to -180 yaw (to the left), the output yaw will lock to -180. If I rotate it to 180 yaw (the right) the output will lock to 180.

If I look left and it locks to -180, I can look right and it will still work until locking to 180. |
I don't know if it's intended behavior for yaw to max out at 180 and -180?

**Comment by sthalik** [comment]
@UnknownEvil please see if it works at least with no filter in the current build. Once it works with no filter I can fix Accela.

Builds as usual at <<http://opentrack.misaki.pl>>.

**Comment by UnknownEvil** [comment]
Same thing as the thing I said. No filter causes the yaw to lock to +/-180 once I pass +/-180, respectively.

**Comment by sthalik** [comment]
I see the issue's caused by centering. Please see today's build.
