### ISSUE TITLE
Freepie IMU doesn't work on newer Android versions

### ISSUE THREAD

**Issue by simbake** [opentrack/opentrack#913]
Hi,
Opentrack tracking pauses after running freepie imu in the background. The only way to resume tracking is to open freepie imu. This happens on Samsung s10e android 9.
Please help.

**Comment by sthalik** [comment]
Disable battery saving mode for this application.

**Comment by simbake** [comment]
Is it under optimize battery usage? Please guide me on how to disable. Thanks

**Comment by simbake** [comment]
I turned off battery optimization for the app but the issue still occurs.

**Comment by sthalik** [comment]
I haven't had any Samsung phones in a while and can't help, sorry. Maybe somebody else knows.

**Comment by quietbug** [comment]
I got exactly the same issue after flashing Android 9. `dumpsys deviceidle disable` also not resolve it. Redmi 5+.

**Comment by sthalik** [comment]
I think this is related to general optimizations in newer Android versions.

**Comment by simbake** [comment]
It would be nice to see and update of the IMU.

**Comment by diego123456789** [comment]
same problem here with Motorola -> Android 9

**Comment by Ardemon96** [comment]
Me too - redmi note 7, android 9

**Comment by sthalik** [comment]
Unless there's a way to disable all battery life optimizations the freepie tracker has to be discontinued unfortunately. :(

**Comment by siriux** [comment]
I ported the freepie imu to newer android versions for an app I'm playing with and it works without pauses even on the background and I think I remember even with the screen locked.

It has a different name (WishIMU) and it's on a different package because I've use it as a base for something different, but I still keep the first copy of the code that was a straight port and compatible with freepie imu.

Keep in mind this is old code, not very well tested, and it might contain plenty of bugs, but it seemed to work.

I attach the code and a debug apk I have. You can use WishIMU and the code under the original MIT license (I added my name, it would be nice if you keep it) as a replacement for freepie imu, or move it to the old package, or just backport the changes (not straight forward, everything is really old, that's why I created a new package in the first place).

[WishIMU Compatible With FreePIE.zip](https://github.com/opentrack/opentrack/files/3645831/WishIMU.Compatible.With.FreePIE.zip)

[com.wishsalad.wishimu-debug.apk.zip](https://github.com/opentrack/opentrack/files/3645835/com.wishsalad.wishimu-debug.apk.zip)

Let me know if it works for you.

**Comment by simbake** [comment]
Hi Siriux, thanks for the update. Unfortunately it doesn't work for me, it seems to not be able to detect my sensors as when I click on 'Debug' there are no values and Opentrack doesn't receive any values. I have tested with the old version also and this sends values and detects the sensors.

**Comment by Morblax** [comment]
Thank you Siriux, I merged your sources with original ones and now my Galaxy Note 8 send data to FreePIE ! I don't test it on Opentrack, it's dirty, but it works.

The builded APK :
[FreePIE_IMU_Android9.zip](https://github.com/opentrack/opentrack/files/3649638/FreePIE_IMU_Android9.zip)

**Comment by siriux** [comment]
@simbake The debug doesn't work in my code (I didn't need it, so I didn't port the code) I forgot to mention it. You can try with FreePIE, to see if it works.

@Morblax Good to know that it works for you. I tried with opentrack some time ago and it worked for me, but as I said, this code is something old I didn't test too much.

**Comment by simbake** [comment]
@Morblax Thanks for sharing. Your version works for me.
@siriux Thanks for sharing and updating the tool, Morblax version works on Opentrack haven't tried FREEPIE as I dont use it.

**Comment by sthalik** [comment]
@siriux can I bundle it with opentrack?

**Comment by siriux** [comment]
@sthalik Sure, you can bundle it, port it, or do whatever you want with it. 

It would be nice if you keep the MIT license file with my name (along the original authors).

**Comment by sthalik** [comment]
Added to the stable version. Thanks!

**Comment by MABlosfeld** [comment]
I'm using RESHADE/MOONLIGHT/FREEPIE IMU/OPENTRACK apps to play with VR HEADSET on SMARTPHONE. I did several tests and found that every time I turn on moonlight, it turns freepie off. Is there any chance that moonlight will allow other apps to run in the background?

**Comment by r57zone** [comment]
MABlosfeld, have you tried the new FreePie IMU version?

**Comment by MABlosfeld** [comment]
I looked over the version installed on my phone and it says VERSION 1.0 and the file name description is FREEPIE_IMU_ANDROID9.APK
I did other tests and every time I turn on an app inside GAME LAUNCHER SAMSUNG, the freepie turns off by itself.

**Comment by MABlosfeld** [comment]
Perhaps the solution is to include all the FREEPIE source code within the MOONLIGHT source code, this way, when turning on MOONLIGHT it will automatically transmit data from the motion sensors to OPENTRACK or any other application.

**Comment by MABlosfeld** [comment]
Perhaps a small financial contribution is needed for the development of updates and new projects. OPENTRACK/FREEPIE/MOONLIGHT/RESHADE are 4 excellent projects and each one has its due value. I support the idea of ​​creating a way to contribute.

**Comment by communitytranslations** [comment]
Sorry for necro-posting, but this is the first result when searching for the FreePIE Android app and I think it deserves an update.

Thanks to @siriux for the original app — I've published a modernized fork targeting Android 9–16 (Material 3 UI, no deprecated APIs, foreground service with Stop button, connection lost detection when used with ps3pie, IP validation). It also adds mouse button support: two on-screen click buttons, and optionally the physical volume keys as left/right click — including while the screen is locked.

 WishIMU (source + APK): https://github.com/communitytranslations/ps3pie/releases/tag/wishmiu-v1.0

The app is also compatible with ps3pie, a FreePIE-inspired programmable input emulator for Linux (Node.js, no Windows required):
https://github.com/communitytranslations/ps3pie
