### ISSUE TITLE
Call to `cv::putText` broken when using OpenCV DLLs

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#921]
When using OpenCV DLLs a call to `cv::putText` fails to pass the `const std::string&` parameter properly corrupting the variable and causing a crash.
CMake generator `Visual Studio 15 2017 Win64`, debug build.

**Comment by sthalik** [comment]
What if you use `std::string::constData()`?

**Comment by sthalik** [comment]
Just a side note, don't build 64-bit Windows builds. The common PS3 Eye payware driver only has a 32-bit filter. There's no benefit whatsoever to 64-bit.
