### ISSUE TITLE
Yaw Value only going one way.

### ISSUE THREAD

**Issue by ghost** [opentrack/opentrack#925]
I'm Using the Vive headset as my input. When i rotate my head left or right its only going negative or just one direction.

output: freetrack
Filter: Accela

**Comment by sthalik** [comment]
See whether the nightly build fixes the problem. It's the same problem as #912.

**Comment by sthalik** [comment]
@ghost in particular, please check the newest build on <<http://opentrack.misaki.pl>> and see if this fixes the problem. Thanks!
