### ISSUE TITLE
Single point tracking - Two instances

### ISSUE THREAD

**Issue by Lucas24865** [opentrack/opentrack#927]
With two cameras, one above and other in the left or right, and a single led on top of the vr it will be posible to have track in the X,Y and Z axes. My problem is the program not support single led tracker and i don't know if it is possible to open two opentrack at the same time one with the X and Z(the above webcam) and the another with Y(with the side webcam). Freetrack support single led track but don't support two instances.

**Comment by sthalik** [comment]
Save yourself the trouble and use three LEDs. opentrack won't support tracking one or two LEDs.
