### ISSUE TITLE
Best model for Easy Tracker OpenCV P3P solver

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#936]
With Easy Tracker and Kinect V2 hardware it looks like I'm getting a lot less noise when using my custom 3 vertices model instead of the default TrackerIR cap. Even though the coordinates of my custom model are certainly not as precise as the ones from the TrackerIR cap. It's so much better that the custom model signal, it could almost be used without filtering.

The picture below shows the TrackIR cap on the left and my custom model on the right.

![20190427_103402](https://user-images.githubusercontent.com/6508892/56847388-5b928900-68da-11e9-8d37-2c6b44964a1e.jpg)

Custom model specs:
![image](https://user-images.githubusercontent.com/6508892/56847402-8f6dae80-68da-11e9-86fc-3e11f4a18feb.png)

Default TrackIR specs:
![image](https://user-images.githubusercontent.com/6508892/56847413-c2b03d80-68da-11e9-9b69-2fc418ac3903.png)

I'm guessing the specs are responsible for the difference in accuracy though the shape of the markers could play a role too.

**Comment by Slion** [comment]
I had a go at Elite Dangerous with another custom hat much like the one shown above and the experience is now much the same than with the TrackIR camera, just awesome 😄 Since the signal is a lot more stable I could lower the Accela setting to Smoothing 2.5 and Deadzone 0.5. I wonder if they could be lowered some more.

**Comment by sthalik** [comment]
This isn't an issue when using a non-Kinect webcam. People using caps report excellent tracking and stability.

**Comment by Slion** [comment]
> This isn't an issue when using a non-Kinect webcam. People using caps report excellent tracking and stability.

Of course this is something I observed on Kinect. Those guys do not use the same solver and they also are most likely using active markers and custom cap rather than the default TrackIR passive one.
