### ISSUE TITLE
Build error in set_curthread_name_old on Windows

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#940]
`error C2712:  Cannot use __try in functions that require object unwinding`

**Comment by sthalik** [comment]
Is it okay now?

**Comment by Slion** [comment]
Should we setup a build machine to catch those issues?

**Comment by sthalik** [comment]
I have AppVeyor set up but not yet multi-platform. Do you have experience with AppVeyor?

**Comment by Slion** [comment]
> Do you have experience with AppVeyor?

Nope, I usually use Visual Studio Online/Azure whatever they call it this days.
