### ISSUE TITLE
should there be unit tests?

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#943]
It's actually feasible to write unit tests for opentrack, at least for a decent subset of the implementation. Most of the code, including the modules, `compat` and `logic` libraries don't include any UI dependencies.

Should we go on writing tests (for AppVeyor) or should the attention be diverted elsewhere?

**Comment by sthalik** [comment]
Paging @Slion.

**Comment by Slion** [comment]
> Should we go on writing tests (for AppVeyor) or should the attention be diverted elsewhere?

It's your call mate. I think a simple build machine for every supported platform should come first.
