### ISSUE TITLE
Document Kinect usage in Wiki

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#950]
Kinect usage needs to be [documented in Wiki](https://github.com/opentrack/opentrack/wiki/Using-Microsoft-Kinect-V2).

Also using this issue so that GitHub will host images used in Wiki without having to add them to OpenTrack repository. For some reason GitHub's Wiki does not support image upload like issues do. 

![Kinect Monitor Mount](https://user-images.githubusercontent.com/6508892/57972597-0a3b5e00-799d-11e9-89a3-2aabcc90738a.jpg)

![Tripod](https://user-images.githubusercontent.com/6508892/57972625-8b92f080-799d-11e9-85a4-978e77468566.jpg)

![Kinect Arm Mount](https://user-images.githubusercontent.com/6508892/57972774-58e9f780-799f-11e9-8584-7ea7880d3a27.jpg)

![Tripod with extension](https://user-images.githubusercontent.com/6508892/57972787-88006900-799f-11e9-978d-ffa80f51fa6c.jpg)

![Kinect Arm Mount detail](https://user-images.githubusercontent.com/6508892/57972917-f0037f00-79a0-11e9-8196-69cbaa23b7f4.jpg)

![Kinect Elite](https://user-images.githubusercontent.com/6508892/57973876-e3d2ee00-79af-11e9-9866-be1cb6207a7b.jpg)

![kinect-face](https://user-images.githubusercontent.com/6508892/57974353-1af8cd80-79b7-11e9-8127-3b48553ef690.png)

![Hats](https://user-images.githubusercontent.com/6508892/57974369-454a8b00-79b7-11e9-8fb2-bef5ea441e67.jpg)

![Custom-Hats](https://user-images.githubusercontent.com/6508892/57974380-585d5b00-79b7-11e9-8883-6723663a2d27.jpg)

![Easy Tracker](https://user-images.githubusercontent.com/6508892/57974362-306df780-79b7-11e9-8282-652ba1d80ea1.png)

**Comment by Slion** [comment]
Trash:
![20190421_140939](https://user-images.githubusercontent.com/6508892/57972629-9b123980-799d-11e9-92b7-cba2070c2bba.jpg)

![20190428_074937](https://user-images.githubusercontent.com/6508892/57972627-9057a480-799d-11e9-9a7d-dde4ad6f09f2.jpg)

**Comment by sthalik** [comment]
@Slion if you clone the wiki's `opentrack.wiki.git` repository then there's no problem with images.

**Comment by Slion** [comment]
I see, I should have put them in the wiki repository, I guess. Though it worked well like that too.

**Comment by Slion** [comment]
Wiki page is done:
https://github.com/opentrack/opentrack/wiki/Using-Microsoft-Kinect-V2

**Comment by StoryLabTAMU** [comment]
Hi Slion, I can't see Easy Tracker option appear in my input option, what should I do?

**Comment by Slion** [comment]
Make sure you use one of the latest build.
