### ISSUE TITLE
Slion to add himself to README.md, AUTHORS.md and OPENTRACK-LICENSING.txt

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#954]
Apparently I need to add myself to those files.

**Comment by Slion** [comment]
@sthalik I'm not sure what I should put in OPENTRACK-LICENSING.txt
that's not already in `3rdparty-notices`. I'm fine with the default licensing.

**Comment by sthalik** [comment]
@Slion `OPENTRACK-LICENSING.txt` gets installed to the `doc/` directory.

In that particular file, go for something like,

```
Kinect camera input and Easy-Tracker

Your copyright statement

Your licensing terms

(optional warranty statement)
```

For `AUTHORS.md`, make a new section named `Video input` and later I'm gonna add myself for opencv input.
