### ISSUE TITLE
Output Data

### ISSUE THREAD

**Issue by gomeslucasm** [opentrack/opentrack#959]
what is the better way to catch the output data (X,Y,Z)  for use in other software, like puredata, matlab or python?

**Comment by sthalik** [comment]
Either a [shared memory mapping](https://github.com/opentrack/opentrack/blob/unstable/freetrackclient/fttypes.h) or the UDP protocol. The former has less overhead.

**Comment by billyjo2002** [comment]
Hi, I am something of a Luddite when it comes to new tricks and still an avid Visual Basic programmer (of sorts). Can you give me any simple explanation of how I can grab the X, Y, Z coordinates generated by Opentrack so I can use them in my VB application? I'd be grateful for any help.

**Comment by sthalik** [comment]
Listen on a UDP socket and get the data.
