### ISSUE TITLE
Feedback OpenTrack 2.3

### ISSUE THREAD

**Issue by FlyingCircus-** [opentrack/opentrack#96]
Pros:
- Every major problem you encountered in the way from 2.2 to 2.3 seem to be solved. As long as I've tested this release is perfectly usable.
- Former issues, such as the axis inversion I had to apply to yaw and pitch in 2.2, are gone.
- Fewer settings in the UI which I don't miss (I mean: focal length of the sensor for what? Geometric model gives us a completely deterministic system)

Issues:
- Profile Save as-button resets PointTracker settings and keyboard shortcuts.
- R label in clip model description is missing.
- I’m experiencing some jitter that I didn't have in 2.2, but I still have to tweak the new settings to reach the same sweet spot. I'll start using this new version for now on so I can be more specific or just dismiss my first impression as not meaningful. Don't expect immediate feedback though, I play flight simulators once a week or less.

**Comment by sthalik** [comment]
And you have right SimConnect SDK for that version as well? Opentrack is known to work with FSX, and it's hard to say anything meaningful without performing voodoo on the target computer.

**Comment by lama33** [comment]
Yes, that was the problem. I fixed it by reinstaling simconnect from 
FSX\SDK\Core Utilities Kit\SimConnect SDK\LegacyInterfaces\
I had to reinstall all versions, RTM, SP1 and XPACK, in that order, when I instaled only XPACK, the error was still there. 
However, the system (Win7) was reinstalled before instaling FSX from steam, there was not any other install of FSX or P3D.
Thank you for this great app.

**Comment by amigastar** [comment]
Hello,
i have a question regarding opentrack 2.3 rc8 and basically every unstable release.
now i know they are beta or even alpha but i'm wondering why the curveadjusting makes always this mistake, basically a zigzag. is there a way to prevent it, or something?
![curves](https://cloud.githubusercontent.com/assets/8751716/5672269/5484a16e-978f-11e4-9320-af326734ad4c.jpg)
otherwise no compaint, opentrack is awesome.

**Comment by exirous** [comment]
"" - PT tracker dynamic pose resolution removal, it never worked right"
Thats Really,Really bad =( Cant use OpenTrack Anymore, because now if i look forward-right-down, or back-left-down - the tracker suddenly goes into some weird angles. (3 point cap configuration)
And earlier versions did not have 180 degrees.. i dont know what to do anymore =(

**Comment by FlyingCircus-** [comment]
@exirous Known issue, discussed in #112. My impression is dynamic pose resolution code traces were all around and were cleaned up for maintenance reasons. I trust @sthalik will get a fix for this on its due time. In the meanwhile you might use the older versions.

**Comment by sthalik** [comment]
@amigastar add another point for a minimum of four. The code requires as much and we're just fooling it if there are less than four.

@exirous the response for dynamic pose removal was so negative I'll put it back on before final release.

**Comment by Trooph** [comment]
Hello. RC9 is great :) But I noticed that when using X and Y axis in game movemets stutter a bit. Meaning they are not fluid. 
Also when doing rapid head turns it can cause a bit of a lag in traslating software to game head movements

**Comment by sthalik** [comment]
@Trooph is there nothing filter configuration can do about it?

**Comment by Trooph** [comment]
@sthalik 
I have to set it to extreme to keep "frame jumping" to a minimum. ALso lowering the sliders helps but does not eliminate this. Its most visible with slow movements X and Y axis

**Comment by sthalik** [comment]
@Trooph then of course you're gonna have extreme lag. In fact the options above 'normal' should be removed since they're exaggerated. There's something wrong with the tracker if it doesn't work on lower settings. Dropbox to low/high and messing with the slider is the way to go.

**Comment by PatayTayoJen** [comment]
Hi Sthalik, First off, let me say that Opentrack with my Android device works like a charm in DCS and EuroTruck sim2! You sir a genius. No need to buy the expensive TrackIR. :)

That said, I wonder if you know of any other problems that might cause the setup I have to not work in FSX SE. lama33 above got it to work but after doing what he did i.e. installing all the simconnect.msi files, I still can't get it to work.

I even tried EZdok and moving Opentrack to C: to no avail.

Appreciate the help! :)

**Comment by sthalik** [comment]
@PatayTayoJen install the FSX SDK, and update the SDK version for any FSX expansions you have.

**Comment by PatayTayoJen** [comment]
Wow. I'm impressed by the quick response! Thanks! :)

By "FSX SDK," do you mean the FSX-RTM, FSX-SP1 and FSX-XPACK SimConnect
files in the *C:\Program Files (x86)\Steam\steamapps\common\FSX\SDK\Core
Utilities Kit\SimConnect SDK\LegacyInterfaces* folder?

If so, I've installed those already. I even installed the Simconnect.msi in
the *lib* folder



How do I update the "SDK version" of FSX Steam?

Sorry for the questions. I just don't believe that your Opentrack is the
issue and that it's FSX Steam. Opentrack rules! ;)



Thanks!



On Tue, Jan 12, 2016 at 9:16 PM, Stanisław Halik <notifications@github.com>
wrote:

> @PatayTayoJen <https://github.com/PatayTayoJen> install the FSX SDK, and
> update the SDK version for any FSX expansions you have.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentrack/opentrack/issues/96#issuecomment-170908258>.
>



-- 
"Love your calling with passion. It is the meaning of your life." - Rodin

**Comment by sniperwolfpk5** [comment]
You have to select simconnect instead of freetrack for fsx in opentrack

**Comment by PatayTayoJen** [comment]
Got it to work! Thanks a bunch!

You sir are awesome! :)

On Wed, Jan 13, 2016 at 11:51 AM, sniperwolfpk5 <notifications@github.com>
wrote:

> You have to select simconnect instead of freetrack for fsx in opentrack
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentrack/opentrack/issues/96#issuecomment-171153938>.
>



-- 
"Love your calling with passion. It is the meaning of your life." - Rodin

**Comment by amigastar** [comment]
Hello, 
got a question, how can i make the curve handling idk how you call it but my guess would be "Linear"?
for now the newest build of opentrack has the snap to background grid and not free and smooth like in 2.2 stable. can i move the points on the curves without snap somwhow.

thx.

**Comment by sthalik** [comment]
@amigastar snap isn't possible to disable, and once more than 1 point exists it's no longer linear interpolation.

**Comment by amigastar** [comment]
ok, thank you for the info sthalik.
