### ISSUE TITLE
Not returning to center

### ISSUE THREAD

**Issue by Geronimo553** [opentrack/opentrack#960]
So I have been running build 2.3.9 for awhile now. I noticed that 2.3.11 beta recently released and updated. Now it seems that the tracking does not return to center if the trackir goes out of range. Instead of the view angle returning to center/default. It now gets stuck looking backwards or looking backwards upside down. At this current time I consider 2.3.11 unusable because of this problem and have switched back to 2.3.9.

Here are two images of the "not returning to center" issue of the latest build.

looking out of bounds
https://i.imgur.com/PJqMuao.png

not returned to center
https://i.imgur.com/iGZZBNI.png

Secondary issues
-Vertical movement up and down has never worked correctly for me so I have to disable it. Any time I look left or right the camera will move up/down and forward/back. A total headache...
-The filter setting in 2.3.11 defaults to blank after restarting the program sometimes. Note that I use Accela filter and the filter tab was blank in the images from just restarting/opening the program.

**Comment by sthalik** [comment]
Use the latest build from <<http://opentrack.misaki.pl>> and see if this is already fixed.

Also, set auto threshold (or pixel value) in the PT tracker so that point sizes correspond to what they actually are. Your point sizes are more of around 11 pixels and not twenty. Having them too big introduces false detections.

**Comment by Geronimo553** [comment]
The problem with the point sizes is that anything under 18 pixel is not detected.

**Comment by sthalik** [comment]
Can you adjust camera gain so the points are brighter than just few pixels above black? It's also going to help detection due to larger dynamic range.
