### ISSUE TITLE
Software Setup

### ISSUE THREAD

**Issue by carolynasan** [opentrack/opentrack#964]
I don't know whether this is the appropriate way to approach the issue but here I am.
I know nothing about coding, I know nothing about how this program works. I am researching for a friend.
He has downloaded the software via the link and installed the 32 bit exe file. We don't know how to set up the input/output settings. He has a webcam set up which is working on other apps.
In the youtube video we watched there was a ht setting, we couldn't see this option under input.

So, if anyone has any tips or links to setup guides, it would be much appreciated.

I apologise if this issue has already been raised, I could not find any helpful links

**Comment by Slion** [comment]
See if that helps:
https://github.com/opentrack/opentrack/wiki
