### ISSUE TITLE
Support multiple Wii Remotes for improved tracking coverage.

### ISSUE THREAD

**Issue by altimumdelta** [opentrack/opentrack#969]
Wii Remotes have a kind of narrow FOV, I'm building my setup as we speak but I'm not sure how well is this going to perform on a 32inch 1440p screen inside DCS World where I would be trying to lean down and to the back around the cockpit, which is the main point, to be able to get up close to the gauges, and it looks like I won't be able to do that with Wii Tracking, but we'll see, perhaps some good settings and adjustments are possible so I could have Wii Remote placed up in an angle looking down so it can track when I'm looking closer at the screen, or well I think the way this is done now is probably using some high sensetivity for the forward-back axis, and the rest, but it may not be optimal.

However I do realize now that moving 1:1 is probably not practical because you can't look at the screen unless the monitor rotates with your head around you so a higher multiplier/sensetivity is probably needed.

It could also be helpful to use one from the side-ways for better forward-back axis coverage. Infact that would actually fit better for this kind of usecase, having 120-160 degrees of movement is good but this is budget, I think having a Wii Remote installed at one of the sides further away so the coverage is increased, coupled with enough power on the IRLEDs, it would do the trick of being able to get close to the gauges in an aircraft cockpit and have some rotation and leaning in a 30deg space would kinda be enough for starters.

**Comment by HugoSandell** [comment]
I agree. In fact, I was considering opening an issue to see you've beaten me by about an hour.  
I've been trying to do it myself, but it's a headache to set up on my computer.

**Comment by sthalik** [comment]
No way. This is too specialized to ever be viable.
