### ISSUE TITLE
Voice controlled tracking?

### ISSUE THREAD

**Issue by altimumdelta** [opentrack/opentrack#970]
So I had an idea it could be fun to do it as simple as making certain tone with voice and it would move you forward/up/down etc depending on the tone, it would definitely be wonky as you can only produce one sound at a time with mouth but it could at least be just one more way this great program can do it, if nothing else just for the challenge and legacy of it.

Has anyone tried anything similar or some kind of translation program exists for UDP?

You would produce sounds basically like, aaaaa ,iiiii ,ooooo, uuuu, iiiiiii, aaaaa, oooo, iiiii aaaaa oooo (_iiiiiao .... fiiaaoo fiiigaro fiiigaro figaro figaro ... ehm_) which would correspond to some frequency-or-such pattern which would p, you would have to ofcourse sample your own voice but only like what minimum of 6 voices for 3D, and additional leaning etc but it gets more complicated to remember ofcourse and then to train and practically use it.

For the difficulty of coding, I think due to the nature of just monotone and just extrapolating some base pattern out of that which could just be "this voice is this close to AB frequency" so all the software that would be needed is a constant check of the probability weight (%) of your voice being to that freq-or-such-pattern which you're trying to hit, so it wouldn't be any kind of serious voice recognition at all, it's all monotone, shouldn't be that hard on programming the core, it could also be built upon maybe adding volume as a modifier and ofcourse it can be made a lot more complicated if one wishes but this is enough.

Would need some program that converts the sounds to the UDP stuff perhaps, I heard something about voice mentioned in the issue referenced below.
https://github.com/opentrack/opentrack/issues/576

It may not be useful as much in a real-time gaming/simulator but what about slower stuff such as presentations or tutorials where you can pause and you're not bound by time to move quickly.

**Comment by sthalik** [comment]
Are you able to at least whistle out the DTMF codes?

**Comment by altimumdelta** [comment]
Heh, I've updated the OP to mention that IMO *all* the software would need to do with the voice data is just calculate probability weight of that voice signal "matching" the user-set pattern/frequency (I say pattern just cause I don't have a better word now, it's not a pattern it's just one tone but you know there's tiny variations even in that from person to person, to notify it's something user-set, but I think the term "tone" should be more appropriate going forward). And it doesn't need to match, just how close it is, then whichever is the highest at any given point it'll apply the command tied to that frequency/tone.

I'm kinda new to head tracking and what I'm doing right now is emulating TrackIR so maybe there's better use of this in other kinds of "tracking".
