### ISSUE TITLE
Kinect-easy tracker: Please explain vertices setup?

### ISSUE THREAD

**Issue by wostg** [opentrack/opentrack#971]
Hi, I'm a long time pointtracker user, now with a Kinect V2. I have had success with the facetracker, but am spending this Saturday night, like many, with an array of balls in my face.
May I ask for some support on the Easy Tracker vertices setup?  I assume the following is mostly correct for a cap setup close to default but it would be great to be sure before I look at issues with input/output/mapping. 

![image](https://user-images.githubusercontent.com/19717394/61177408-e11a0100-a5cc-11e9-8e84-8cf19ee3aea5.png)

Many thanks for all the excellent work!

**Comment by wostg** [comment]
eh seems fine

**Comment by Slion** [comment]
Glad you got it working.

See wiki: https://github.com/opentrack/opentrack/wiki/Using-Microsoft-Kinect-V2

Though to be fair I should really rewrite the Easy Tracker page:
https://github.com/opentrack/opentrack/wiki/Easy-Tracker

**Comment by wostg** [comment]
Thanks for reply :) I am using kinect facetracking in daylight hours and easy tracker when it gets dark now. The vertices were logical enough once tested, but I don't think I've seen that layout within opentrack before so took me a minute.

May I ask what the benefit of 4/5/6 markers would realistically be?

Also I don't know if this is any use but thought I'd share the ritual I need to get easy tracker working: (possibly because I have MyDocs in Onedrive?) I need to start kinect up in the latest main Opentrack release (no easy tracker option) then close that down and load up the test build, run kinect, and then easy tracker.

**Comment by Slion** [comment]
> May I ask what the benefit of 4/5/6 markers would realistically be?

Only three four or five vertices are supported. Just stick to three vertices unless you know what you are doing.

It was developed to try out various algorithms OpenCV is providing to solve the PNP problem. However testing with four and five vertices proved rather disappointing.

If I recall well four is notably bad since it often provides the wrong solution.

Five was alright but you get a lot more chances of vertices merging with one another thus breaking the solver.

**Comment by wostg** [comment]
That's interesting to know, thank you!

**Comment by StoryLabTAMU** [comment]
Thank you Slion:) When I went to Easy Tracker page, I don't know how to make a self-custom hat, can you send me a link or add some more explanation in there?

**Comment by wostg** [comment]
Hey here is my hat, using the above numbers. It is made of
1 x black cap
3 x bouncy rubber balls covered with reflective cyclists tape
velcro dots to hold them on
![hat](https://user-images.githubusercontent.com/19717394/61985178-f432c500-afff-11e9-933e-d2b92f8e0843.jpg)

**Comment by StoryLabTAMU** [comment]
> Hey here is my hat, using the above numbers. It is made of
> 1 x black cap
> 3 x bouncy rubber balls covered with reflective cyclists tape
> velcro dots to hold them on
> ![hat](https://user-images.githubusercontent.com/19717394/61985178-f432c500-afff-11e9-933e-d2b92f8e0843.jpg)

Thank you wostg:)

**Comment by sthalik** [comment]
> If I recall well four is notably bad since it often provides the wrong solution.

It's alright if it's not planar.

**Comment by JimmyRaoUF** [comment]
> Hey here is my hat, using the above numbers. It is made of
> 1 x black cap
> 3 x bouncy rubber balls covered with reflective cyclists tape
> velcro dots to hold them on
> ![hat](https://user-images.githubusercontent.com/19717394/61985178-f432c500-afff-11e9-933e-d2b92f8e0843.jpg)

@wostg Hi,
can you share a screenshot of your settings?
I am having a problem with this:
https://github.com/opentrack/opentrack/issues/861#issuecomment-539760256

Can you switch between the IR source?


Thanks!

**Comment by wostg** [comment]
Hi I think the below is everything. I think the numbers are probably reversed so inverted in the output settings. I put away the ps3eye once I got this working so not sure about switching sources!

![image](https://user-images.githubusercontent.com/19717394/66707747-95970080-ed3d-11e9-8aee-07892226ca75.png)

**Comment by Slion** [comment]
I wonder if I should fix that reverse problem in the code somehow.

**Comment by Slion** [comment]
@wostg Your screenshots are showing Kinect V2 Video Sensor is selected. I seriously doubt that's working. It should be Kinect V2 IR Sensor.

**Comment by wostg** [comment]
![cammy](https://user-images.githubusercontent.com/19717394/66713603-b21a5380-eda4-11e9-986b-873a9d14522b.gif)
That's me now. I'm using whatever ms drivers and the regedit needed to use the kinect as a webcam if that helps.
To get it working I load up 2.3.11-beta3, run face 0.1, close that off, load up the beta above, run face 0.1 and then easy tracker 1.0. Assumed that was just the cost of running test versions.

**Comment by Slion** [comment]
We ought to do a proper release.

**Comment by JimmyRaoUF** [comment]
> To get it working I load up 2.3.11-beta3, run face 0.1, close that off, load up the beta above, run face 0.1 and then easy tracker 1.0. Assumed that was just the cost of running test versions.

@wostg Wow, I followed your instruction and it worked this time!
Big thanks to you!

@Slion Thank you for this wonderful work!

**Comment by sthalik** [comment]
@Slion regarding the release, see #778. Can you fix waiting for the camera frame in the Kinect camera provider before that?
