### ISSUE TITLE
First actual attempt with a DIY IR Cap setup with WiiRemote and DCS World

### ISSUE THREAD

**Issue by altimumdelta** [opentrack/opentrack#973]
PointTracker 2.0 settings don't seem to to have indication which type IR setup is used or any way of actually selecting.

That was just running, this is actually using my own IR LEDs, I didn't test enough and made assumptions and used too many LEDs apparently, 5 + 3 + 3. (the top 5 were angled 1left 1right 1up 1down 1center, and the two were 1left 1right 1center) trying to cover more angles, but the software doesn't register that it's actually multiple IR LEDs for what is meant to be a single point. I got too quick and impatient and didn't mess with the software enough, I think I forgot the filters (but I already got it set to max) before deciding to redo it.

So I already destroyed the first setup and will just go with simple 3 LEDs for the Cap type, I hope I didn't miss some kind of setting which blends the multiple IR signatures closer together to one single logical point, anyway it got worse I as tried to block the IR light from the view as the IR light went through the blockages and bounced all over the place making it unusable.

**Comment by sthalik** [comment]
I'd like to see an image (in full resolution) where the software detects multiple LEDs as one.

**Comment by altimumdelta** [comment]
@sthalik IDK what you mean with full resolution but in the camera view I can see multiple dots combining into one bigger dot once I zoom out far enough, only in those cases where LEDs are very close to each other.

**Comment by cpuwolf** [comment]
@altimumdelta  exactly, it supports only 3 LEDs, and FOV of WIIRemote is a great pain I have to admit
