### ISSUE TITLE
raw data always zero in the FreeTrack structure

### ISSUE THREAD

**Issue by gb2111** [opentrack/opentrack#975]
i am trying to read raw data using either FTGetData or shared memory directly.
the result is always zero. game data is working fine.
is there way to acquire raw data from opentrack?
thank you.

**Comment by sthalik** [comment]
You can set the game pose to be equal to raw pose. Is that satisfactory?

**Comment by gb2111** [comment]
yes. but how can I do this? it always works with some relative position related to re-center point.

**Comment by sthalik** [comment]
For now, you can disable initial centering in the options menu. I'm going to enable raw data output for the next opentrack release.

**Comment by gb2111** [comment]
thank you !

**Comment by sthalik** [comment]
Fixed in stable release.
