### ISSUE TITLE
initial model centre

### ISSUE THREAD

**Issue by dylanmenzies** [opentrack/opentrack#976]
I have an application where I would like the initial position centre to be fixed, eg 0 at the camera position. Currently the centre resets to the first captured reading. I imagine this requires some code modifications - can anyone give some pointers? Thanks.

**Comment by sthalik** [comment]
You can disable initial center in the options dialog.

**Comment by dylanmenzies** [comment]
@sthalik Thanks. When I disable 'centre at startup'  the z value is fixed at 75, so I can't track position. Can this be fixed?

**Comment by sthalik** [comment]
That's the uncentered position.

**Comment by sthalik** [comment]
That's the uncentered position. What is it that you're trying to accomplish exactly? Why is it that you can't use centering?

**Comment by dylanmenzies** [comment]
I want to have the position relative to the cam, this is useful information in my application. Seems strange just the z value is fixed.

**Comment by sthalik** [comment]
For the latest beta, raw values for the freetrack protocol are now filled. Get it from <<http://opentrack.misaki.pl>>.

**Comment by dylanmenzies** [comment]
Thanks!
Dylan

**Comment by sthalik** [comment]
@dylanmenzies can you confirm whether this works? Thanks!

**Comment by Slion** [comment]
I had a similar request not so long ago, see #917. I worked around it but I'm still convinced that's the right thing to do.

**Comment by dylanmenzies** [comment]
I just tried the beta. The z value is no linger flixed, but it reaches a value of 75 when the target is short distance from the cam then stays at that value as the target moves further away.

**Comment by sthalik** [comment]
The raw values are only exposed through the in-memory mapping. See https://github.com/opentrack/opentrack/blob/unstable/freetrackclient/freetrackclient.c
