### ISSUE TITLE
WMR controllers

### ISSUE THREAD

**Issue by point1024** [opentrack/opentrack#978]
Will it be possible to track WMR controllers using point tracker and Bluetooth. Without using a mixed reality portal. Without a headset.

**Comment by sthalik** [comment]
No idea whether you'd be able to mount a clip on that particular VR headset.

**Comment by point1024** [comment]
no need to make a clip. controllers themselves have an LED circuit. the question is in tracking it.

**Comment by sthalik** [comment]
I'd need to know the LED layout.

**Comment by point1024** [comment]
https://docs.microsoft.com/en-us/windows/mixed-reality/motion-controllers.

if necessary I can measure the location directly on the controllers

**Comment by point1024** [comment]
14 LED on the inside and 16 LED on the outside.

**Comment by sthalik** [comment]
All trackers require the same point count. That's the biggest obstacle since it's non-trivial to implement. You may find the Aruco tracker interesting though. There's a page dedicated on the wiki.

**Comment by point1024** [comment]
The device itself monitors the position of the controllers well, but as soon as they leave the field of view of the cameras, they cease to be normally tracked. and tracking only happens with the help of gyroscopes. It was thought to use an additional camera for tracking. but I feel the implementation will not be easy.

**Comment by point1024** [comment]
http://freepascal.ru/forum/viewtopic.php?t=25002&view=unread#unread
Человек ковыряет в wmr уже есть доступ к данным wmr контроллеров.

**Comment by sthalik** [comment]
Send a pull request with working code.
