### ISSUE TITLE
CFS3 not supported?

### ISSUE THREAD

**Issue by NoelShourai** [opentrack/opentrack#980]
Is Microsoft Combat Flight Simulator 3 supported? Because I have not been able to get it to work with opentrack, even through moving the TIRViews.dll into the opentrack folder and/or into CFS3's folder. I've also tried mouse emulation but CFS3 manages to ignore its input entirely.

**Comment by Len62** [comment]
I have never used OT with CFS3, however, doing a little searching showed no one reporting they got it to work. Maybe someone else with some more CFS3 experience will comment.

**Comment by sthalik** [comment]
TIRViews isn't supported for legal and technical reasons. Sorry.

**Comment by sthalik** [comment]
If facetracknoir 1.7 works then it can technically work.
