### ISSUE TITLE
wiimote + game data output crawl out of zero

### ISSUE THREAD

**Issue by Nasty76** [opentrack/opentrack#981]
I get stupid problem which start it self no changing anythink
if imake head still and raw data show my head is position +-1 unit , output game data crawl or jumping over 15 units.

**Comment by Nasty76** [comment]
i find reason for this , cos open track not have impelemnt camera treshold , some times open track not see dots , and when u open freetrack , treshold come on and then open track see dots clearly.
So if that hard job to make treshold slider in wiicamera too

**Comment by cpuwolf** [comment]
impossible wiicamera is not working as you thought, wiiimote directly reports dots position

**Comment by Nasty76** [comment]
well i know wii mote report only dots position BUT , my open track not see any dots , ok see if i go realy close my wiimote , and when i open freetrack and adjust treshold wiimote camera dadaaa open track see dots clearly :| so allways when i start play i need open opentrack then open freetrack and close freetrack.

**Comment by Nasty76** [comment]
here is video https://youtu.be/L4rm8u-82Fk

**Comment by sthalik** [comment]
Are you able to use the Wii sensor as a webcam in the freetrack example?

**Comment by Nasty76** [comment]
No , freetrack has build in support for wiimote like opentrack but there IS Slider where you can adjudt treshold.and that report battery level too

**Comment by sthalik** [comment]
@cpuwolf can you comment on that please?
