### ISSUE TITLE
TrackIR support broken

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#983]
I'm on the tip of master f17f1a5910987654f64bdf2209ea2a8ad96f7e1e and can't get FreeTrack to work with ED nor MWO.
This was never a problem before. Did we change something?

**Comment by Slion** [comment]
Rolling back to 1579a97c480578dcd14691cd3e40f56fd508204e fixes the issue.
TrackIR support was broken somewhere between those two commits.

**Comment by Slion** [comment]
e9b5cd0e9dff9897b7f6c3e12c9563e3a40bf915 is working too.

**Comment by sthalik** [comment]
Is this specific to that particular output method?

**Comment by sthalik** [comment]
Can you see if 38d466a972d4455b02aee2b55674f3b29ece24d7 works please?

**Comment by Slion** [comment]
66c2373014fc107d918b8549d554420d63405cc7 is working too and is more recent than the one you mentioned.

**Comment by Slion** [comment]
Can't reproduce the issue anymore. Tip of master is working fine now, weird stuff.

**Comment by Slion** [comment]
My bad, there is definitely something broken since 66c2373014fc107d918b8549d554420d63405cc7 .

**Comment by Slion** [comment]
8fbcdf775660a0cc1857e8bedee7ac2351292aa6 is working too.

**Comment by Slion** [comment]
7d898e638abad8267420f8c0d827d21f716b8977 is working.
03236ba81d6c85a26695968e5e4e266a18991362 is broken.

**Comment by Slion** [comment]
9a308f07242d6ad996afdcd07c79abfe30293c8b is working.
Therefore 03236ba81d6c85a26695968e5e4e266a18991362 broke TrackIR support somehow.

**Comment by sthalik** [comment]
Thanks for bisecting this. Does it work for you now? I'm not on Windows unfortunately.

**Comment by Slion** [comment]
It's working now, thanks.

**Comment by sthalik** [comment]
I wrote a test program, it's in the contrib directory.
