### ISSUE TITLE
Azure CI pipeline creation error

### ISSUE THREAD

**Issue by Slion** [opentrack/opentrack#985]
I was getting the following error while trying to setup an Azure CI pipeline:

> Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository.

@sthalik  Any chance you could give me the necessary permissions?
I also sent you a request to install azure pipelines.

**Comment by sthalik** [comment]
I gave you admin privileges.

**Comment by Slion** [comment]
Thanks, that worked.
Though I can't find a way to install that GitHub application.
Is this working for you?
https://github.com/organizations/opentrack/settings/installations

**Comment by sthalik** [comment]
It seems to be installed right now. What problem are you having?

**Comment by sthalik** [comment]
Can you connect CI for this repository?

**Comment by Slion** [comment]
Ok, fair enough, it looked like the request was still pending.

**Comment by sthalik** [comment]
Looks like CMake configuration isn't setup yet. How much problem is it for you to enable all supported plugins from opentrack-depends and the like?

**Comment by Slion** [comment]
Nothing is setup really. It's just an empty CI job at this point. I was hoping to setup a shared account but got stuck trying to resolve dependencies without providing a credit card number :)
