### ISSUE TITLE
Possible to account for non-vertical IR LED mounting methods?

### ISSUE THREAD

**Issue by dsrtfx** [opentrack/opentrack#987]
The problem that I'm running into is this:
- I have a DelanClip Fusion, the rechargeable battery-powered IR LED product. It isn't light, and requires a secure and rigid mount for acceptable-quality headtracking.
- My headphones don't have a flat surface on their earcups to mount the DelanClip Fusion, so I zip-tied it to the "45 degree" mark, if you will, along the headphones' headband.
- **Even with calibration (PointTracker 1.1), Opentrack thinks that, when I move my head side-to-side, I'm also moving my head up/down (the direction depends on left/right real-life head movement).**

I want to keep this 45 degree mounting location because I record webcam video along with gameplay footage, and the DelanClip Fusion looks best here. It doesn't look like antlers (if I was to mount it horizontally at my head's 12 o'clock position), and I haven't found a way to securely mount at the 3 or 9 o'clock positions with my two particular pairs of headphones.

Maybe add a "mounting angle" field to proportionally average the input X and Y to create the output X and Y?

**Comment by sthalik** [comment]
I have a clip from [feelcustom](https://vk.com/feelcustom) with a gimbal that allows for arbitrary rotation. Consider one of these.
