### ISSUE TITLE
toggle perfomance

### ISSUE THREAD

**Issue by Verc0rs** [opentrack/opentrack#990]
Hello,
When using the shortcut toggle key, there is always a little movement before the view get freeze. It's a little problematic when i want to use keyboard of a cockpit plane with my mouse.
Thanks for your job.
Verc0rs

**Comment by sthalik** [comment]
I don't understand. Please explain it better.

**Comment by Verc0rs** [comment]
Sorry for my english.
In the "Global shortcut" view, I use the "toggle" shortcut to freeze the view in my plane. When I use it the view isn't frozen immediatly, there is always a short delay before it.
Hope it is more clear...

**Comment by Verc0rs** [comment]
I have test the beta version, it works great now.
thank you for your job !
