### ISSUE TITLE
Relative translation without Z input

### ISSUE THREAD

**Issue by FlyMakerBR** [opentrack/opentrack#992]
https://github.com/opentrack/opentrack/issues/765

I would like to use this option without the need to zoom. I only use YAW and PITCH

Before any YAW values ​​exceeding 180 were applied to X, this no longer occurs.
I don't have the Z axis to apply the translation

Many users dont have too. Any option to use only YAW in relative translation?

**Comment by sthalik** [comment]
Reopening #765.
