### ISSUE TITLE
Slow start and wont work with P3D

### ISSUE THREAD

**Issue by Torkil80** [opentrack/opentrack#993]
Hello.
Very often my OT is really slow to start. 
It also can be very slow to starting when i have pushed Start. 
Anyone know why? 

I also get a Error when i try to start it with P3D. 
I choose Joystick Input and Microsoft FSX Simconnect, but then it says: Error occured while loading protocol Micrs FSX SC. Cant load SDK-check selected simconnect version.

**Comment by sthalik** [comment]
First off, see if using the development version from <<http://opentrack.misaki.pl>> helps with the slow start issue. Regarding the SDK issue, you need to install the SDK bundled with FSX/P3D. It should be included in either the game's installation directory or installation media.
